<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForBC extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (5, "","Agas", NOW(), NOW()),
            (5, "","Ardeoani", NOW(), NOW()),
            (5, "","Asau", NOW(), NOW()),
            (5, "","Bacau", NOW(), NOW()),
            (5, "","Balcani", NOW(), NOW()),
            (5, "","Beresti-Bistrita", NOW(), NOW()),
            (5, "","Beresti-Tazlau", NOW(), NOW()),
            (5, "","Berzunti", NOW(), NOW()),
            (5, "","Blagesti", NOW(), NOW()),
            (5, "","Bogdanesti", NOW(), NOW()),
            (5, "","Brusturoasa", NOW(), NOW()),
            (5, "","Buhoci", NOW(), NOW()),
            (5, "","Buhusi", NOW(), NOW()),
            (5, "","Barsanesti", NOW(), NOW()),
            (5, "","Casin", NOW(), NOW()),
            (5, "","Cleja", NOW(), NOW()),
            (5, "","Colonesti", NOW(), NOW()),
            (5, "","Comanesti", NOW(), NOW()),
            (5, "","Corbasca", NOW(), NOW()),
            (5, "","Cotofanesti", NOW(), NOW()),
            (5, "","Caiuti", NOW(), NOW()),
            (5, "","Dealu Morii", NOW(), NOW()),
            (5, "","Dofteana", NOW(), NOW()),
            (5, "","Damienesti", NOW(), NOW()),
            (5, "","Darmanesti", NOW(), NOW()),
            (5, "","Faraoani", NOW(), NOW()),
            (5, "","Filipeni", NOW(), NOW()),
            (5, "","Filipesti", NOW(), NOW()),
            (5, "","Glavanesti", NOW(), NOW()),
            (5, "","Gura Vaii", NOW(), NOW()),
            (5, "","Garleni", NOW(), NOW()),
            (5, "","Gaiceana", NOW(), NOW()),
            (5, "","Helegiu", NOW(), NOW()),
            (5, "","Hemeius", NOW(), NOW()),
            (5, "","Horgesti", NOW(), NOW()),
            (5, "","Huruiesti", NOW(), NOW()),
            (5, "","Izvoru Berheciului", NOW(), NOW()),
            (5, "","Letea Veche", NOW(), NOW()),
            (5, "","Lipova", NOW(), NOW()),
            (5, "","Livezi", NOW(), NOW()),
            (5, "","Luizi-Calugara", NOW(), NOW()),
            (5, "","Moinesti", NOW(), NOW()),
            (5, "","Motoseni", NOW(), NOW()),
            (5, "","Magiresti", NOW(), NOW()),
            (5, "","Magura", NOW(), NOW()),
            (5, "","Manastirea Casin", NOW(), NOW()),
            (5, "","Margineni", NOW(), NOW()),
            (5, "","Negri", NOW(), NOW()),
            (5, "","Nicolae Balcescu", NOW(), NOW()),
            (5, "","Oituz", NOW(), NOW()),
            (5, "","Oncesti", NOW(), NOW()),
            (5, "","Onesti", NOW(), NOW()),
            (5, "","Orbeni", NOW(), NOW()),
            (5, "","Palanca", NOW(), NOW()),
            (5, "","Parava", NOW(), NOW()),
            (5, "","Parincea", NOW(), NOW()),
            (5, "","Plopana", NOW(), NOW()),
            (5, "","Podu Turcului", NOW(), NOW()),
            (5, "","Poduri", NOW(), NOW()),
            (5, "","Pancesti", NOW(), NOW()),
            (5, "","Pargaresti", NOW(), NOW()),
            (5, "","Parjol", NOW(), NOW()),
            (5, "","Racova", NOW(), NOW()),
            (5, "","Rosiori", NOW(), NOW()),
            (5, "","Rachitoasa", NOW(), NOW()),
            (5, "","Racaciuni", NOW(), NOW()),
            (5, "","Sascut", NOW(), NOW()),
            (5, "","Scorteni", NOW(), NOW()),
            (5, "","Secuieni", NOW(), NOW()),
            (5, "","Solont", NOW(), NOW()),
            (5, "","Strugari", NOW(), NOW()),
            (5, "","Stanisesti", NOW(), NOW()),
            (5, "","Sanduleni", NOW(), NOW()),
            (5, "","Saucesti", NOW(), NOW()),
            (5, "","Tamasi", NOW(), NOW()),
            (5, "","Traian", NOW(), NOW()),
            (5, "","Targu Ocna", NOW(), NOW()),
            (5, "","Targu Trotus", NOW(), NOW()),
            (5, "","Tatarasti", NOW(), NOW()),
            (5, "","Ungureni", NOW(), NOW()),
            (5, "","Urechesti", NOW(), NOW()),
            (5, "","Valea Seaca", NOW(), NOW()),
            (5, "","Vultureni", NOW(), NOW()),
            (5, "","Zemes", NOW(), NOW()),
            (5, "","Stefan cel Mare", NOW(), NOW()),
            (5, "Agas","Beleghet", NOW(), NOW()),
            (5, "Agas","Cotumba", NOW(), NOW()),
            (5, "Agas","Cosnea", NOW(), NOW()),
            (5, "Agas","Diaconesti", NOW(), NOW()),
            (5, "Agas","Goioasa", NOW(), NOW()),
            (5, "Agas","Preluci", NOW(), NOW()),
            (5, "Agas","Sulta", NOW(), NOW()),
            (5, "Ardeoani","Leontinesti", NOW(), NOW()),
            (5, "Asau","Apa Asau", NOW(), NOW()),
            (5, "Asau","Ciobanus", NOW(), NOW()),
            (5, "Asau","Lunca Asau", NOW(), NOW()),
            (5, "Asau","Paltinis", NOW(), NOW()),
            (5, "Asau","Straja", NOW(), NOW()),
            (5, "Balcani","Frumoasa", NOW(), NOW()),
            (5, "Balcani","Ludasi", NOW(), NOW()),
            (5, "Balcani","Schitu Frumoasa", NOW(), NOW()),
            (5, "Barsanesti","Albele", NOW(), NOW()),
            (5, "Barsanesti","Bratesti", NOW(), NOW()),
            (5, "Barsanesti","Caraclau", NOW(), NOW()),
            (5, "Beresti-Bistrita","Brad", NOW(), NOW()),
            (5, "Beresti-Bistrita","Ciumasi", NOW(), NOW()),
            (5, "Beresti-Bistrita","Climesti", NOW(), NOW()),
            (5, "Beresti-Bistrita","Dumbrava", NOW(), NOW()),
            (5, "Beresti-Bistrita","Fagetel", NOW(), NOW()),
            (5, "Beresti-Bistrita","Itesti", NOW(), NOW()),
            (5, "Beresti-Bistrita","Padureni", NOW(), NOW()),
            (5, "Beresti-Tazlau","Bosoteni", NOW(), NOW()),
            (5, "Beresti-Tazlau","Enachesti", NOW(), NOW()),
            (5, "Beresti-Tazlau","Prisaca", NOW(), NOW()),
            (5, "Beresti-Tazlau","Romanesti", NOW(), NOW()),
            (5, "Beresti-Tazlau","Tescani", NOW(), NOW()),
            (5, "Beresti-Tazlau","Turluianu", NOW(), NOW()),
            (5, "Berzunti","Buda", NOW(), NOW()),
            (5, "Berzunti","Dragomir", NOW(), NOW()),
            (5, "Blagesti","Buda", NOW(), NOW()),
            (5, "Blagesti","Poiana Negustorului", NOW(), NOW()),
            (5, "Blagesti","Valea lui Ion", NOW(), NOW()),
            (5, "Blagesti","Tardenii Mari", NOW(), NOW()),
            (5, "Bogdanesti","Filipesti", NOW(), NOW()),
            (5, "Brusturoasa","Buruienis", NOW(), NOW()),
            (5, "Brusturoasa","Buruienisu de Sus", NOW(), NOW()),
            (5, "Brusturoasa","Camenca", NOW(), NOW()),
            (5, "Brusturoasa","Cuchinis", NOW(), NOW()),
            (5, "Brusturoasa","Hanganesti", NOW(), NOW()),
            (5, "Buhoci","Bijghir", NOW(), NOW()),
            (5, "Buhoci","Buhocel", NOW(), NOW()),
            (5, "Buhoci","Coteni", NOW(), NOW()),
            (5, "Buhoci","Dospinesti", NOW(), NOW()),
            (5, "Buhusi","Marginea", NOW(), NOW()),
            (5, "Buhusi","Runcu", NOW(), NOW()),
            (5, "Caiuti","Blidari", NOW(), NOW()),
            (5, "Caiuti","Boistea", NOW(), NOW()),
            (5, "Caiuti","Floresti", NOW(), NOW()),
            (5, "Caiuti","Heltiu", NOW(), NOW()),
            (5, "Caiuti","Marcesti", NOW(), NOW()),
            (5, "Caiuti","Popeni", NOW(), NOW()),
            (5, "Caiuti","Pralea", NOW(), NOW()),
            (5, "Caiuti","Vranceni", NOW(), NOW()),
            (5, "Casin","Curita", NOW(), NOW()),
            (5, "Cleja","Somusca", NOW(), NOW()),
            (5, "Cleja","Valea Mica", NOW(), NOW()),
            (5, "Colonesti","Calini", NOW(), NOW()),
            (5, "Colonesti","Poiana", NOW(), NOW()),
            (5, "Colonesti","Satu Nou", NOW(), NOW()),
            (5, "Colonesti","Spria", NOW(), NOW()),
            (5, "Colonesti","Valea Mare", NOW(), NOW()),
            (5, "Colonesti","Zapodia", NOW(), NOW()),
            (5, "Comanesti","Podei", NOW(), NOW()),
            (5, "Comanesti","Vermesti", NOW(), NOW()),
            (5, "Corbasca","Bacioiu", NOW(), NOW()),
            (5, "Corbasca","Marvila", NOW(), NOW()),
            (5, "Corbasca","Poglet", NOW(), NOW()),
            (5, "Corbasca","Rogoaza", NOW(), NOW()),
            (5, "Corbasca","Scarisoara", NOW(), NOW()),
            (5, "Corbasca","Valcele", NOW(), NOW()),
            (5, "Cotofanesti","Boistea de Jos", NOW(), NOW()),
            (5, "Cotofanesti","Borsani", NOW(), NOW()),
            (5, "Cotofanesti","Balca", NOW(), NOW()),
            (5, "Cotofanesti","Tamasoaia", NOW(), NOW()),
            (5, "Damienesti","Calugareni", NOW(), NOW()),
            (5, "Damienesti","Dragesti", NOW(), NOW()),
            (5, "Damienesti","Padureni", NOW(), NOW()),
            (5, "Darmanesti","Darmaneasca", NOW(), NOW()),
            (5, "Darmanesti","Lapos", NOW(), NOW()),
            (5, "Darmanesti","Plopu", NOW(), NOW()),
            (5, "Darmanesti","Pagubeni", NOW(), NOW()),
            (5, "Darmanesti","Salatruc", NOW(), NOW()),
            (5, "Dealu Morii","Banca", NOW(), NOW()),
            (5, "Dealu Morii","Blaga", NOW(), NOW()),
            (5, "Dealu Morii","Bobos", NOW(), NOW()),
            (5, "Dealu Morii","Bodeasa", NOW(), NOW()),
            (5, "Dealu Morii","Bostanesti", NOW(), NOW()),
            (5, "Dealu Morii","Balanesti", NOW(), NOW()),
            (5, "Dealu Morii","Calapodesti", NOW(), NOW()),
            (5, "Dealu Morii","Cauia", NOW(), NOW()),
            (5, "Dealu Morii","Dorofei", NOW(), NOW()),
            (5, "Dealu Morii","Ghionoaia", NOW(), NOW()),
            (5, "Dealu Morii","Gradesti", NOW(), NOW()),
            (5, "Dealu Morii","Negulesti", NOW(), NOW()),
            (5, "Dealu Morii","Tavadaresti", NOW(), NOW()),
            (5, "Dofteana","Bogata", NOW(), NOW()),
            (5, "Dofteana","Cucuieti", NOW(), NOW()),
            (5, "Dofteana","Haghiac", NOW(), NOW()),
            (5, "Dofteana","Larga", NOW(), NOW()),
            (5, "Dofteana","Seaca", NOW(), NOW()),
            (5, "Dofteana","Stefan Voda", NOW(), NOW()),
            (5, "Filipeni","Brad", NOW(), NOW()),
            (5, "Filipeni","Balaia", NOW(), NOW()),
            (5, "Filipeni","Fruntesti", NOW(), NOW()),
            (5, "Filipeni","Marasti", NOW(), NOW()),
            (5, "Filipeni","Padureni", NOW(), NOW()),
            (5, "Filipeni","Slobozia", NOW(), NOW()),
            (5, "Filipeni","Valea Botului", NOW(), NOW()),
            (5, "Filipesti","Boanta", NOW(), NOW()),
            (5, "Filipesti","Cornesti", NOW(), NOW()),
            (5, "Filipesti","Cotu Grosului", NOW(), NOW()),
            (5, "Filipesti","Carligi", NOW(), NOW()),
            (5, "Filipesti","Galbeni", NOW(), NOW()),
            (5, "Filipesti","Harlesti", NOW(), NOW()),
            (5, "Filipesti","Oniscani", NOW(), NOW()),
            (5, "Gaiceana","Arini", NOW(), NOW()),
            (5, "Gaiceana","Hutu", NOW(), NOW()),
            (5, "Gaiceana","Popesti", NOW(), NOW()),
            (5, "Garleni","Garlenii de Sus", NOW(), NOW()),
            (5, "Garleni","Lespezi", NOW(), NOW()),
            (5, "Garleni","Surina", NOW(), NOW()),
            (5, "Ghimes-Faget","Bolovanis", NOW(), NOW()),
            (5, "Ghimes-Faget","Faget", NOW(), NOW()),
            (5, "Ghimes-Faget","Fagetu de Sus", NOW(), NOW()),
            (5, "Ghimes-Faget","Ghimes", NOW(), NOW()),
            (5, "Ghimes-Faget","Rachitis", NOW(), NOW()),
            (5, "Ghimes-Faget","Tarhausi", NOW(), NOW()),
            (5, "Glavanesti","Frumuselu", NOW(), NOW()),
            (5, "Glavanesti","Muncelu", NOW(), NOW()),
            (5, "Glavanesti","Putredeni", NOW(), NOW()),
            (5, "Glavanesti","Razesu", NOW(), NOW()),
            (5, "Gura Vaii","Capata", NOW(), NOW()),
            (5, "Gura Vaii","Dumbrava", NOW(), NOW()),
            (5, "Gura Vaii","Motocesti", NOW(), NOW()),
            (5, "Gura Vaii","Paltinata", NOW(), NOW()),
            (5, "Gura Vaii","Temelia", NOW(), NOW()),
            (5, "Helegiu","Bratila", NOW(), NOW()),
            (5, "Helegiu","Deleni", NOW(), NOW()),
            (5, "Helegiu","Dragugesti", NOW(), NOW()),
            (5, "Hemeius","Fantanele", NOW(), NOW()),
            (5, "Hemeius","Lilieci", NOW(), NOW()),
            (5, "Horgesti","Bazga", NOW(), NOW()),
            (5, "Horgesti","Galeri", NOW(), NOW()),
            (5, "Horgesti","Marascu", NOW(), NOW()),
            (5, "Horgesti","Recea", NOW(), NOW()),
            (5, "Horgesti","Racatau de Jos", NOW(), NOW()),
            (5, "Horgesti","Racatau-Razesi", NOW(), NOW()),
            (5, "Horgesti","Sohodor", NOW(), NOW()),
            (5, "Huruiesti","Capotesti", NOW(), NOW()),
            (5, "Huruiesti","Floresti", NOW(), NOW()),
            (5, "Huruiesti","Fundoaia", NOW(), NOW()),
            (5, "Huruiesti","Ocheni", NOW(), NOW()),
            (5, "Huruiesti","Perchiu", NOW(), NOW()),
            (5, "Huruiesti","Pradais", NOW(), NOW()),
            (5, "Izvoru Berheciului","Antohesti", NOW(), NOW()),
            (5, "Izvoru Berheciului","Baimac", NOW(), NOW()),
            (5, "Izvoru Berheciului","Faghieni", NOW(), NOW()),
            (5, "Izvoru Berheciului","Obarsia", NOW(), NOW()),
            (5, "Izvoru Berheciului","Otelesti", NOW(), NOW()),
            (5, "Izvoru Berheciului","Padureni", NOW(), NOW()),
            (5, "Letea Veche","Holt", NOW(), NOW()),
            (5, "Letea Veche","Radomiresti", NOW(), NOW()),
            (5, "Letea Veche","Rusi-Ciutea", NOW(), NOW()),
            (5, "Letea Veche","Siretu", NOW(), NOW()),
            (5, "Lipova","Malosu", NOW(), NOW()),
            (5, "Lipova","Satu Nou", NOW(), NOW()),
            (5, "Lipova","Valea Caselor", NOW(), NOW()),
            (5, "Lipova","Valea Hogei", NOW(), NOW()),
            (5, "Lipova","Valea Mosneagului", NOW(), NOW()),
            (5, "Lipova","Valea Marului", NOW(), NOW()),
            (5, "Livezi","Balaneasa", NOW(), NOW()),
            (5, "Livezi","Orasa", NOW(), NOW()),
            (5, "Livezi","Poiana", NOW(), NOW()),
            (5, "Livezi","Prajoaia", NOW(), NOW()),
            (5, "Livezi","Scariga", NOW(), NOW()),
            (5, "Luizi-Calugara","Osebiti", NOW(), NOW()),
            (5, "Magiresti","Prajesti", NOW(), NOW()),
            (5, "Magiresti","Stanesti", NOW(), NOW()),
            (5, "Magiresti","Valea Arinilor", NOW(), NOW()),
            (5, "Magiresti","Sesuri", NOW(), NOW()),
            (5, "Magura","Crihan", NOW(), NOW()),
            (5, "Magura","Dealu-Mare", NOW(), NOW()),
            (5, "Magura","Sohodol", NOW(), NOW()),
            (5, "Manastirea Casin","Lupesti", NOW(), NOW()),
            (5, "Manastirea Casin","Parvulesti", NOW(), NOW()),
            (5, "Manastirea Casin","Scutaru", NOW(), NOW()),
            (5, "Margineni","Barati", NOW(), NOW()),
            (5, "Margineni","Luncani", NOW(), NOW()),
            (5, "Margineni","Podis", NOW(), NOW()),
            (5, "Margineni","Poiana", NOW(), NOW()),
            (5, "Margineni","Padureni", NOW(), NOW()),
            (5, "Margineni","Trebes", NOW(), NOW()),
            (5, "Margineni","Valea Budului", NOW(), NOW()),
            (5, "Moinesti","Gazarie", NOW(), NOW()),
            (5, "Motoseni","Baclesti", NOW(), NOW()),
            (5, "Motoseni","Chetreni", NOW(), NOW()),
            (5, "Motoseni","Chicerea", NOW(), NOW()),
            (5, "Motoseni","Cociu", NOW(), NOW()),
            (5, "Motoseni","Cornatelu", NOW(), NOW()),
            (5, "Motoseni","Fundatura", NOW(), NOW()),
            (5, "Motoseni","Fantanele", NOW(), NOW()),
            (5, "Motoseni","Gura Craiesti", NOW(), NOW()),
            (5, "Motoseni","Poiana", NOW(), NOW()),
            (5, "Motoseni","Praja", NOW(), NOW()),
            (5, "Motoseni","Rotaria", NOW(), NOW()),
            (5, "Motoseni","Sendresti", NOW(), NOW()),
            (5, "Motoseni","Tepoaia", NOW(), NOW()),
            (5, "Negri","Brad", NOW(), NOW()),
            (5, "Negri","Calinesti", NOW(), NOW()),
            (5, "Negri","Magla", NOW(), NOW()),
            (5, "Negri","Poiana", NOW(), NOW()),
            (5, "Negri","Ursoaia", NOW(), NOW()),
            (5, "Nicolae Balcescu","Buchila", NOW(), NOW()),
            (5, "Nicolae Balcescu","Baltata", NOW(), NOW()),
            (5, "Nicolae Balcescu","Galbeni", NOW(), NOW()),
            (5, "Nicolae Balcescu","Larguta", NOW(), NOW()),
            (5, "Nicolae Balcescu","Sarata", NOW(), NOW()),
            (5, "Nicolae Balcescu","Valea Seaca", NOW(), NOW()),
            (5, "Oituz","Calcai", NOW(), NOW()),
            (5, "Oituz","Ferestrau-Oituz", NOW(), NOW()),
            (5, "Oituz","Harja", NOW(), NOW()),
            (5, "Oituz","Marginea", NOW(), NOW()),
            (5, "Oituz","Poiana Sarata", NOW(), NOW()),
            (5, "Oncesti","Barboasa", NOW(), NOW()),
            (5, "Oncesti","Dealu Perjului", NOW(), NOW()),
            (5, "Oncesti","Oncestii Vechi", NOW(), NOW()),
            (5, "Oncesti","Satu Nou", NOW(), NOW()),
            (5, "Oncesti","Tarnita", NOW(), NOW()),
            (5, "Oncesti","Taula", NOW(), NOW()),
            (5, "Onesti","Borzesti", NOW(), NOW()),
            (5, "Onesti","Slobozia", NOW(), NOW()),
            (5, "Orbeni","Scurta", NOW(), NOW()),
            (5, "Palanca","Ciughes", NOW(), NOW()),
            (5, "Palanca","Cadaresti", NOW(), NOW()),
            (5, "Palanca","Pajistea", NOW(), NOW()),
            (5, "Palanca","Popoiu", NOW(), NOW()),
            (5, "Pancesti","Chilia Benei", NOW(), NOW()),
            (5, "Pancesti","Dienet", NOW(), NOW()),
            (5, "Pancesti","Fulgeris", NOW(), NOW()),
            (5, "Pancesti","Fundu Vaii", NOW(), NOW()),
            (5, "Pancesti","Motoc", NOW(), NOW()),
            (5, "Pancesti","Petresti", NOW(), NOW()),
            (5, "Pancesti","Soci", NOW(), NOW()),
            (5, "Parava","Dragusani", NOW(), NOW()),
            (5, "Parava","Radoaia", NOW(), NOW()),
            (5, "Parava","Teius", NOW(), NOW()),
            (5, "Pargaresti","Bahna", NOW(), NOW()),
            (5, "Pargaresti","Nicoresti", NOW(), NOW()),
            (5, "Pargaresti","Parau Boghii", NOW(), NOW()),
            (5, "Pargaresti","Satu Nou", NOW(), NOW()),
            (5, "Parincea","Barna", NOW(), NOW()),
            (5, "Parincea","Milestii de Jos", NOW(), NOW()),
            (5, "Parincea","Milestii de Sus", NOW(), NOW()),
            (5, "Parincea","Nanesti", NOW(), NOW()),
            (5, "Parincea","Nastaseni", NOW(), NOW()),
            (5, "Parincea","Poieni", NOW(), NOW()),
            (5, "Parincea","Satu Nou", NOW(), NOW()),
            (5, "Parincea","Vladnic", NOW(), NOW()),
            (5, "Parincea","Valeni", NOW(), NOW()),
            (5, "Parjol","Bahnaseni", NOW(), NOW()),
            (5, "Parjol","Barnesti", NOW(), NOW()),
            (5, "Parjol","Basasti", NOW(), NOW()),
            (5, "Parjol","Campeni", NOW(), NOW()),
            (5, "Parjol","Hemieni", NOW(), NOW()),
            (5, "Parjol","Haineala", NOW(), NOW()),
            (5, "Parjol","Pustiana", NOW(), NOW()),
            (5, "Parjol","Tarata", NOW(), NOW()),
            (5, "Plopana","Budesti", NOW(), NOW()),
            (5, "Plopana","Dorneni", NOW(), NOW()),
            (5, "Plopana","Fundu Tutovei", NOW(), NOW()),
            (5, "Plopana","Itcani", NOW(), NOW()),
            (5, "Plopana","Rusenii Razesi", NOW(), NOW()),
            (5, "Plopana","Rusenii de Sus", NOW(), NOW()),
            (5, "Plopana","Straminoasa", NOW(), NOW()),
            (5, "Plopana","Tagara", NOW(), NOW()),
            (5, "Podu Turcului","Balanesti", NOW(), NOW()),
            (5, "Podu Turcului","Cabesti", NOW(), NOW()),
            (5, "Podu Turcului","Fichitesti", NOW(), NOW()),
            (5, "Podu Turcului","Giurgioana", NOW(), NOW()),
            (5, "Podu Turcului","Hanta", NOW(), NOW()),
            (5, "Podu Turcului","Lehancea", NOW(), NOW()),
            (5, "Podu Turcului","Plopu", NOW(), NOW()),
            (5, "Podu Turcului","Racusana", NOW(), NOW()),
            (5, "Podu Turcului","Sarbi", NOW(), NOW()),
            (5, "Poduri","Bucsesti", NOW(), NOW()),
            (5, "Poduri","Cernu", NOW(), NOW()),
            (5, "Poduri","Cornet", NOW(), NOW()),
            (5, "Poduri","Negreni", NOW(), NOW()),
            (5, "Poduri","Prohozesti", NOW(), NOW()),
            (5, "Poduri","Valea Sosii", NOW(), NOW()),
            (5, "Racaciuni","Ciucani", NOW(), NOW()),
            (5, "Racaciuni","Fundu Racaciuni", NOW(), NOW()),
            (5, "Racaciuni","Gheorghe Doja", NOW(), NOW()),
            (5, "Racaciuni","Gasteni", NOW(), NOW()),
            (5, "Racaciuni","Rastoaca", NOW(), NOW()),
            (5, "Rachitoasa","Barcana", NOW(), NOW()),
            (5, "Rachitoasa","Bucsa", NOW(), NOW()),
            (5, "Rachitoasa","Buda", NOW(), NOW()),
            (5, "Rachitoasa","Burdusaci", NOW(), NOW()),
            (5, "Rachitoasa","Dumbrava", NOW(), NOW()),
            (5, "Rachitoasa","Danaila", NOW(), NOW()),
            (5, "Rachitoasa","Farcasa", NOW(), NOW()),
            (5, "Rachitoasa","Fundatura Rachitoasa", NOW(), NOW()),
            (5, "Rachitoasa","Haghiac", NOW(), NOW()),
            (5, "Rachitoasa","Magazia", NOW(), NOW()),
            (5, "Rachitoasa","Movilita", NOW(), NOW()),
            (5, "Rachitoasa","Oprisesti", NOW(), NOW()),
            (5, "Rachitoasa","Putini", NOW(), NOW()),
            (5, "Rachitoasa","Tochilea", NOW(), NOW()),
            (5, "Racova","Gura Vaii", NOW(), NOW()),
            (5, "Racova","Halmacioaia", NOW(), NOW()),
            (5, "Racova","Iliesi", NOW(), NOW()),
            (5, "Rosiori","Misihanesti", NOW(), NOW()),
            (5, "Rosiori","Neguseni", NOW(), NOW()),
            (5, "Rosiori","Poieni", NOW(), NOW()),
            (5, "Rosiori","Valea Mare", NOW(), NOW()),
            (5, "Rosiori","Valea Mica", NOW(), NOW()),
            (5, "Sanduleni","Barzulesti", NOW(), NOW()),
            (5, "Sanduleni","Coman", NOW(), NOW()),
            (5, "Sanduleni","Mateiesti", NOW(), NOW()),
            (5, "Sanduleni","Stufu", NOW(), NOW()),
            (5, "Sanduleni","Tisa", NOW(), NOW()),
            (5, "Sanduleni","Versesti", NOW(), NOW()),
            (5, "Sascut","Beresti", NOW(), NOW()),
            (5, "Sascut","Contesti", NOW(), NOW()),
            (5, "Sascut","Pancesti", NOW(), NOW()),
            (5, "Sascut","Sascut-Sat", NOW(), NOW()),
            (5, "Sascut","Schineni", NOW(), NOW()),
            (5, "Sascut","Valea Nacului", NOW(), NOW()),
            (5, "Saucesti","Bogdan Voda", NOW(), NOW()),
            (5, "Saucesti","Costei", NOW(), NOW()),
            (5, "Saucesti","Schineni", NOW(), NOW()),
            (5, "Saucesti","Siretu", NOW(), NOW()),
            (5, "Saucesti","Serbesti", NOW(), NOW()),
            (5, "Scorteni","Bogdanesti", NOW(), NOW()),
            (5, "Scorteni","Floresti", NOW(), NOW()),
            (5, "Scorteni","Grigoreni", NOW(), NOW()),
            (5, "Scorteni","Stejaru", NOW(), NOW()),
            (5, "Scorteni","Serpeni", NOW(), NOW()),
            (5, "Secuieni","Berbinceni", NOW(), NOW()),
            (5, "Secuieni","Balusa", NOW(), NOW()),
            (5, "Secuieni","Chiticeni", NOW(), NOW()),
            (5, "Secuieni","Ciuturesti", NOW(), NOW()),
            (5, "Secuieni","Fundeni", NOW(), NOW()),
            (5, "Secuieni","Glodisoarele", NOW(), NOW()),
            (5, "Secuieni","Odobesti", NOW(), NOW()),
            (5, "Secuieni","Tisa-Silvestri", NOW(), NOW()),
            (5, "Secuieni","Valea Fanatului", NOW(), NOW()),
            (5, "Secuieni","Valeni", NOW(), NOW()),
            (5, "Slanic Moldova","Cerdac", NOW(), NOW()),
            (5, "Slanic Moldova","Ciresoaia", NOW(), NOW()),
            (5, "Slanic Moldova","Slanic-Moldova", NOW(), NOW()),
            (5, "Solont","Cucuieti", NOW(), NOW()),
            (5, "Solont","Sarata", NOW(), NOW()),
            (5, "Stanisesti","Balotesti", NOW(), NOW()),
            (5, "Stanisesti","Belciuneasa", NOW(), NOW()),
            (5, "Stanisesti","Benesti", NOW(), NOW()),
            (5, "Stanisesti","Craiesti", NOW(), NOW()),
            (5, "Stanisesti","Gorghesti", NOW(), NOW()),
            (5, "Stanisesti","Slobozia", NOW(), NOW()),
            (5, "Stanisesti","Slobozia Noua", NOW(), NOW()),
            (5, "Stanisesti","Valeni", NOW(), NOW()),
            (5, "Stefan Cel Mare","Bogdana", NOW(), NOW()),
            (5, "Stefan Cel Mare","Buciumi", NOW(), NOW()),
            (5, "Stefan Cel Mare","Gutinas", NOW(), NOW()),
            (5, "Stefan Cel Mare","Negoiesti", NOW(), NOW()),
            (5, "Stefan Cel Mare","Racauti", NOW(), NOW()),
            (5, "Stefan Cel Mare","Radeana", NOW(), NOW()),
            (5, "Stefan Cel Mare","Viisoara", NOW(), NOW()),
            (5, "Strugari","Cetatuia", NOW(), NOW()),
            (5, "Strugari","Iaz", NOW(), NOW()),
            (5, "Strugari","Nadisa", NOW(), NOW()),
            (5, "Strugari","Petricica", NOW(), NOW()),
            (5, "Strugari","Rachitisu", NOW(), NOW()),
            (5, "Tamasi","Chetris", NOW(), NOW()),
            (5, "Tamasi","Furnicari", NOW(), NOW()),
            (5, "Tamasi","Gioseni", NOW(), NOW()),
            (5, "Targu Ocna","Poieni", NOW(), NOW()),
            (5, "Targu Ocna","Valcele", NOW(), NOW()),
            (5, "Targu Trotus","Tuta", NOW(), NOW()),
            (5, "Targu Trotus","Viisoara", NOW(), NOW()),
            (5, "Tatarasti","Cornii de Jos", NOW(), NOW()),
            (5, "Tatarasti","Cornii de Sus", NOW(), NOW()),
            (5, "Tatarasti","Dragesti", NOW(), NOW()),
            (5, "Tatarasti","Gherdana", NOW(), NOW()),
            (5, "Tatarasti","Giurgeni", NOW(), NOW()),
            (5, "Tatarasti","Ungureni", NOW(), NOW()),
            (5, "Traian","Bogdanesti", NOW(), NOW()),
            (5, "Traian","Hertioana de Jos", NOW(), NOW()),
            (5, "Traian","Hertioana-Razesi", NOW(), NOW()),
            (5, "Traian","Prajesti", NOW(), NOW()),
            (5, "Traian","Zapodia", NOW(), NOW()),
            (5, "Ungureni","Bibiresti", NOW(), NOW()),
            (5, "Ungureni","Bota", NOW(), NOW()),
            (5, "Ungureni","Botesti", NOW(), NOW()),
            (5, "Ungureni","Bartasesti", NOW(), NOW()),
            (5, "Ungureni","Garla Anei", NOW(), NOW()),
            (5, "Ungureni","Viforeni", NOW(), NOW()),
            (5, "Ungureni","Zlatari", NOW(), NOW()),
            (5, "Urechesti","Cornatel", NOW(), NOW()),
            (5, "Urechesti","Lunca Dochiei", NOW(), NOW()),
            (5, "Urechesti","Satu Nou", NOW(), NOW()),
            (5, "Urechesti","Slobozia", NOW(), NOW()),
            (5, "Valea Seaca","Cucova", NOW(), NOW()),
            (5, "Vultureni","Bosia", NOW(), NOW()),
            (5, "Vultureni","Dorneni", NOW(), NOW()),
            (5, "Vultureni","Dadesti", NOW(), NOW()),
            (5, "Vultureni","Ghilavesti", NOW(), NOW()),
            (5, "Vultureni","Godinestii de Jos", NOW(), NOW()),
            (5, "Vultureni","Godinestii de Sus", NOW(), NOW()),
            (5, "Vultureni","Lichitiseni", NOW(), NOW()),
            (5, "Vultureni","Medeleni", NOW(), NOW()),
            (5, "Vultureni","Nazarioaia", NOW(), NOW()),
            (5, "Vultureni","Reprivat", NOW(), NOW()),
            (5, "Vultureni","Tomozia", NOW(), NOW()),
            (5, "Vultureni","Valea Lupului", NOW(), NOW()),
            (5, "Vultureni","Valea Merilor", NOW(), NOW()),
            (5, "Vultureni","Valea Salciei", NOW(), NOW()),
            (5, "Vultureni","Tiganesti", NOW(), NOW()),
            (5, "Zemes","Bolatau", NOW(), NOW())
        ;';
        if (config('app.env') !== 'testing') {
            DB::connection()->getPdo()->exec($sql);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=5;';
        DB::connection()->getPdo()->exec($sql);
    }
}
