<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForGR extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
          (25, "","Adunatii-Copaceni", NOW(), NOW()),
          (25, "","Bolintin-Deal", NOW(), NOW()),
          (25, "","Bolintin-Vale", NOW(), NOW()),
          (25, "","Bucsani", NOW(), NOW()),
          (25, "","Bulbucata", NOW(), NOW()),
          (25, "","Buturugeni", NOW(), NOW()),
          (25, "","Baneasa", NOW(), NOW()),
          (25, "","Clejani", NOW(), NOW()),
          (25, "","Colibasi", NOW(), NOW()),
          (25, "","Comana", NOW(), NOW()),
          (25, "","Crevedia Mare", NOW(), NOW()),
          (25, "","Calugareni", NOW(), NOW()),
          (25, "","Daia", NOW(), NOW()),
          (25, "","Fratesti", NOW(), NOW()),
          (25, "","Ghimpati", NOW(), NOW()),
          (25, "","Giurgiu", NOW(), NOW()),
          (25, "","Gogosari", NOW(), NOW()),
          (25, "","Gostinari", NOW(), NOW()),
          (25, "","Gostinu", NOW(), NOW()),
          (25, "","Greaca", NOW(), NOW()),
          (25, "","Gradinari", NOW(), NOW()),
          (25, "","Gaiseni", NOW(), NOW()),
          (25, "","Gaujani", NOW(), NOW()),
          (25, "","Hotarele", NOW(), NOW()),
          (25, "","Iepuresti", NOW(), NOW()),
          (25, "","Izvoarele", NOW(), NOW()),
          (25, "","Joita", NOW(), NOW()),
          (25, "","Letca Noua", NOW(), NOW()),
          (25, "","Malu", NOW(), NOW()),
          (25, "","Mihai Bravu", NOW(), NOW()),
          (25, "","Mihailesti", NOW(), NOW()),
          (25, "","Marsa", NOW(), NOW()),
          (25, "","Ogrezeni", NOW(), NOW()),
          (25, "","Oinacu", NOW(), NOW()),
          (25, "","Prundu", NOW(), NOW()),
          (25, "","Putineiu", NOW(), NOW()),
          (25, "","Roata de Jos", NOW(), NOW()),
          (25, "","Rasuceni", NOW(), NOW()),
          (25, "","Schitu", NOW(), NOW()),
          (25, "","Singureni", NOW(), NOW()),
          (25, "","Slobozia", NOW(), NOW()),
          (25, "","Stoenesti", NOW(), NOW()),
          (25, "","Stanesti", NOW(), NOW()),
          (25, "","Toporu", NOW(), NOW()),
          (25, "","Ulmi", NOW(), NOW()),
          (25, "","Valea Dragului", NOW(), NOW()),
          (25, "","Vedea", NOW(), NOW()),
          (25, "","Vanatorii Mici", NOW(), NOW()),
          (25, "","Varasti", NOW(), NOW()),
          (25, "Adunatii-Copaceni","Darasti-Vlasca", NOW(), NOW()),
          (25, "Adunatii-Copaceni","Mogosesti", NOW(), NOW()),
          (25, "Adunatii-Copaceni","Varlaam", NOW(), NOW()),
          (25, "Baneasa","Frasinu", NOW(), NOW()),
          (25, "Baneasa","Pietrele", NOW(), NOW()),
          (25, "Baneasa","Sfantu Gheorghe", NOW(), NOW()),
          (25, "Bolintin-Deal","Mihai Voda", NOW(), NOW()),
          (25, "Bolintin-Vale","Crivina", NOW(), NOW()),
          (25, "Bolintin-Vale","Malu Spart", NOW(), NOW()),
          (25, "Bolintin-Vale","Suseni", NOW(), NOW()),
          (25, "Bucsani","Anghelesti", NOW(), NOW()),
          (25, "Bucsani","Goleasca", NOW(), NOW()),
          (25, "Bucsani","Obedeni", NOW(), NOW()),
          (25, "Bucsani","Podisor", NOW(), NOW()),
          (25, "Bucsani","Uiesti", NOW(), NOW()),
          (25, "Bucsani","Vadu Lat", NOW(), NOW()),
          (25, "Bulbucata","Coteni", NOW(), NOW()),
          (25, "Bulbucata","Facau", NOW(), NOW()),
          (25, "Bulbucata","Teisori", NOW(), NOW()),
          (25, "Buturugeni","Podu Ilfovatului", NOW(), NOW()),
          (25, "Buturugeni","Posta", NOW(), NOW()),
          (25, "Buturugeni","Padureni", NOW(), NOW()),
          (25, "Calugareni","Branistari", NOW(), NOW()),
          (25, "Calugareni","Crucea de Piatra", NOW(), NOW()),
          (25, "Calugareni","Hulubesti", NOW(), NOW()),
          (25, "Calugareni","Uzunu", NOW(), NOW()),
          (25, "Clejani","Neajlov", NOW(), NOW()),
          (25, "Clejani","Podu Doamnei", NOW(), NOW()),
          (25, "Clejani","Sterea", NOW(), NOW()),
          (25, "Colibasi","Campurelu", NOW(), NOW()),
          (25, "Comana","Budeni", NOW(), NOW()),
          (25, "Comana","Falastoaca", NOW(), NOW()),
          (25, "Comana","Gradistea", NOW(), NOW()),
          (25, "Comana","Vlad Tepes", NOW(), NOW()),
          (25, "Crevedia Mare","Crevedia Mica", NOW(), NOW()),
          (25, "Crevedia Mare","Dealu", NOW(), NOW()),
          (25, "Crevedia Mare","Gaiseanca", NOW(), NOW()),
          (25, "Crevedia Mare","Priboiu", NOW(), NOW()),
          (25, "Crevedia Mare","Sfantu Gheorghe", NOW(), NOW()),
          (25, "Daia","Plopsoru", NOW(), NOW()),
          (25, "Floresti-Stoenesti","Floresti", NOW(), NOW()),
          (25, "Floresti-Stoenesti","Palanca", NOW(), NOW()),
          (25, "Floresti-Stoenesti","Stoenesti", NOW(), NOW()),
          (25, "Fratesti","Cetatea", NOW(), NOW()),
          (25, "Fratesti","Remus", NOW(), NOW()),
          (25, "Gaiseni","Carpenisu", NOW(), NOW()),
          (25, "Gaiseni","Cascioarele", NOW(), NOW()),
          (25, "Gaiseni","Podu Popa Nae", NOW(), NOW()),
          (25, "Gaujani","Cetatuia", NOW(), NOW()),
          (25, "Gaujani","Pietrisu", NOW(), NOW()),
          (25, "Ghimpati","Copaciu", NOW(), NOW()),
          (25, "Ghimpati","Naipu", NOW(), NOW()),
          (25, "Ghimpati","Valea Plopilor", NOW(), NOW()),
          (25, "Gogosari","Draghiceanu", NOW(), NOW()),
          (25, "Gogosari","Izvoru", NOW(), NOW()),
          (25, "Gogosari","Ralesti", NOW(), NOW()),
          (25, "Gostinari","Mironesti", NOW(), NOW()),
          (25, "Gradinari","Tantava", NOW(), NOW()),
          (25, "Gradinari","Zorile", NOW(), NOW()),
          (25, "Greaca","Putu Greci", NOW(), NOW()),
          (25, "Greaca","Zboiu", NOW(), NOW()),
          (25, "Hotarele","Herasti", NOW(), NOW()),
          (25, "Hotarele","Isvoarele", NOW(), NOW()),
          (25, "Hotarele","Milosesti", NOW(), NOW()),
          (25, "Hotarele","Teiusu", NOW(), NOW()),
          (25, "Iepuresti","Banesti", NOW(), NOW()),
          (25, "Iepuresti","Chirculesti", NOW(), NOW()),
          (25, "Iepuresti","Gorneni", NOW(), NOW()),
          (25, "Iepuresti","Stalpu", NOW(), NOW()),
          (25, "Iepuresti","Valter Maracineanu", NOW(), NOW()),
          (25, "Izvoarele","Chiriacu", NOW(), NOW()),
          (25, "Izvoarele","Dimitrie Cantemir", NOW(), NOW()),
          (25, "Izvoarele","Petru Rares", NOW(), NOW()),
          (25, "Izvoarele","Radu Voda", NOW(), NOW()),
          (25, "Izvoarele","Valea Bujorului", NOW(), NOW()),
          (25, "Joita","Bacu", NOW(), NOW()),
          (25, "Joita","Cosoba", NOW(), NOW()),
          (25, "Joita","Sabareni", NOW(), NOW()),
          (25, "Letca Noua","Letca Veche", NOW(), NOW()),
          (25, "Letca Noua","Milcovatu", NOW(), NOW()),
          (25, "Mihailesti","Draganescu", NOW(), NOW()),
          (25, "Mihailesti","Novaci", NOW(), NOW()),
          (25, "Mihailesti","Popesti", NOW(), NOW()),
          (25, "Ogrezeni","Hobaia", NOW(), NOW()),
          (25, "Oinacu","Branistea", NOW(), NOW()),
          (25, "Oinacu","Comasca", NOW(), NOW()),
          (25, "Prundu","Puieni", NOW(), NOW()),
          (25, "Putineiu","Hodivoaia", NOW(), NOW()),
          (25, "Putineiu","Vieru", NOW(), NOW()),
          (25, "Rasuceni","Carapancea", NOW(), NOW()),
          (25, "Rasuceni","Cucuruzu", NOW(), NOW()),
          (25, "Rasuceni","Satu Nou", NOW(), NOW()),
          (25, "Roata De Jos","Cartojani", NOW(), NOW()),
          (25, "Roata De Jos","Roata Mica", NOW(), NOW()),
          (25, "Roata De Jos","Sadina", NOW(), NOW()),
          (25, "Schitu","Bila", NOW(), NOW()),
          (25, "Schitu","Camineasca", NOW(), NOW()),
          (25, "Schitu","Vlasin", NOW(), NOW()),
          (25, "Singureni","Cranguri", NOW(), NOW()),
          (25, "Singureni","Stejaru", NOW(), NOW()),
          (25, "Stanesti","Balanu", NOW(), NOW()),
          (25, "Stanesti","Ghizdaru", NOW(), NOW()),
          (25, "Stanesti","Oncesti", NOW(), NOW()),
          (25, "Stoenesti","Ianculesti", NOW(), NOW()),
          (25, "Stoenesti","Mirau", NOW(), NOW()),
          (25, "Toporu","Tomulesti", NOW(), NOW()),
          (25, "Ulmi","Cascioarele", NOW(), NOW()),
          (25, "Ulmi","Draganeasca", NOW(), NOW()),
          (25, "Ulmi","Ghionea", NOW(), NOW()),
          (25, "Ulmi","Icoana", NOW(), NOW()),
          (25, "Ulmi","Mosteni", NOW(), NOW()),
          (25, "Ulmi","Poenari", NOW(), NOW()),
          (25, "Ulmi","Trestieni", NOW(), NOW()),
          (25, "Vanatorii Mici","Corbeanca", NOW(), NOW()),
          (25, "Vanatorii Mici","Cupele", NOW(), NOW()),
          (25, "Vanatorii Mici","Izvoru", NOW(), NOW()),
          (25, "Vanatorii Mici","Poiana lui Stanga", NOW(), NOW()),
          (25, "Vanatorii Mici","Valcele", NOW(), NOW()),
          (25, "Vanatorii Mici","Vanatorii Mari", NOW(), NOW()),
          (25, "Vanatorii Mici","Zadariciu", NOW(), NOW()),
          (25, "Varasti","Dobreni", NOW(), NOW())
        ;';
        DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=25;';
        DB::connection()->getPdo()->exec($sql);
    }
}
