<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForMH extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (28, "","Baia de Arama", NOW(), NOW()),
            (28, "","Bala", NOW(), NOW()),
            (28, "","Balta", NOW(), NOW()),
            (28, "","Breznita-Motru", NOW(), NOW()),
            (28, "","Breznita-Ocol", NOW(), NOW()),
            (28, "","Brosteni", NOW(), NOW()),
            (28, "","Burila Mare", NOW(), NOW()),
            (28, "","Butoiesti", NOW(), NOW()),
            (28, "","Bacles", NOW(), NOW()),
            (28, "","Balvanesti", NOW(), NOW()),
            (28, "","Balacita", NOW(), NOW()),
            (28, "","Ciresu", NOW(), NOW()),
            (28, "","Corcova", NOW(), NOW()),
            (28, "","Corlatel", NOW(), NOW()),
            (28, "","Cujmir", NOW(), NOW()),
            (28, "","Cazanesti", NOW(), NOW()),
            (28, "","Devesel", NOW(), NOW()),
            (28, "","Drobeta-Turnu Severin", NOW(), NOW()),
            (28, "","Dubova", NOW(), NOW()),
            (28, "","Darvari", NOW(), NOW()),
            (28, "","Eselnita", NOW(), NOW()),
            (28, "","Floresti", NOW(), NOW()),
            (28, "","Godeanu", NOW(), NOW()),
            (28, "","Gogosu", NOW(), NOW()),
            (28, "","Greci", NOW(), NOW()),
            (28, "","Grozesti", NOW(), NOW()),
            (28, "","Gruia", NOW(), NOW()),
            (28, "","Garla Mare", NOW(), NOW()),
            (28, "","Hinova", NOW(), NOW()),
            (28, "","Husnicioara", NOW(), NOW()),
            (28, "","Ilovita", NOW(), NOW()),
            (28, "","Ilovat", NOW(), NOW()),
            (28, "","Isverna", NOW(), NOW()),
            (28, "","Izvoru Barzii", NOW(), NOW()),
            (28, "","Jiana", NOW(), NOW()),
            (28, "","Livezile", NOW(), NOW()),
            (28, "","Malovat", NOW(), NOW()),
            (28, "","Obarsia de Camp", NOW(), NOW()),
            (28, "","Obarsia-Closani", NOW(), NOW()),
            (28, "","Oprisor", NOW(), NOW()),
            (28, "","Orsova", NOW(), NOW()),
            (28, "","Podeni", NOW(), NOW()),
            (28, "","Ponoarele", NOW(), NOW()),
            (28, "","Poroina Mare", NOW(), NOW()),
            (28, "","Pristol", NOW(), NOW()),
            (28, "","Prunisor", NOW(), NOW()),
            (28, "","Punghina", NOW(), NOW()),
            (28, "","Patulele", NOW(), NOW()),
            (28, "","Rogova", NOW(), NOW()),
            (28, "","Salcia", NOW(), NOW()),
            (28, "","Strehaia", NOW(), NOW()),
            (28, "","Stangaceaua", NOW(), NOW()),
            (28, "","Svinita", NOW(), NOW()),
            (28, "","Tamna", NOW(), NOW()),
            (28, "","Vladaia", NOW(), NOW()),
            (28, "","Voloiac", NOW(), NOW()),
            (28, "","Vanju Mare", NOW(), NOW()),
            (28, "","Vanjulet", NOW(), NOW()),
            (28, "","Vanatori", NOW(), NOW()),
            (28, "","Simian", NOW(), NOW()),
            (28, "","Sisesti", NOW(), NOW()),
            (28, "","Sovarna", NOW(), NOW()),
            (28, "Bacles","Corzu", NOW(), NOW()),
            (28, "Bacles","Giura", NOW(), NOW()),
            (28, "Bacles","Petra", NOW(), NOW()),
            (28, "Bacles","Podu Grosului", NOW(), NOW()),
            (28, "Bacles","Selistiuta", NOW(), NOW()),
            (28, "Bacles","Smadovita", NOW(), NOW()),
            (28, "Baia De Arama","Bratilovu", NOW(), NOW()),
            (28, "Baia De Arama","Brebina", NOW(), NOW()),
            (28, "Baia De Arama","Dealu Mare", NOW(), NOW()),
            (28, "Baia De Arama","Marasesti", NOW(), NOW()),
            (28, "Baia De Arama","Negoesti", NOW(), NOW()),
            (28, "Baia De Arama","Pistrita", NOW(), NOW()),
            (28, "Baia De Arama","Stanesti", NOW(), NOW()),
            (28, "Baia De Arama","Titerlesti", NOW(), NOW()),
            (28, "Bala","Bala de Sus", NOW(), NOW()),
            (28, "Bala","Bratesul", NOW(), NOW()),
            (28, "Bala","Brativoesti", NOW(), NOW()),
            (28, "Bala","Comanesti", NOW(), NOW()),
            (28, "Bala","Crainici", NOW(), NOW()),
            (28, "Bala","Campu Mare", NOW(), NOW()),
            (28, "Bala","Carsu", NOW(), NOW()),
            (28, "Bala","Dalma", NOW(), NOW()),
            (28, "Bala","Iupca", NOW(), NOW()),
            (28, "Bala","Molani", NOW(), NOW()),
            (28, "Bala","Rudina", NOW(), NOW()),
            (28, "Bala","Runcusoru", NOW(), NOW()),
            (28, "Bala","Sardanesti", NOW(), NOW()),
            (28, "Bala","Vidimiresti", NOW(), NOW()),
            (28, "Balacita","Dobra", NOW(), NOW()),
            (28, "Balacita","Gvardinita", NOW(), NOW()),
            (28, "Balta","Coada Cornetului", NOW(), NOW()),
            (28, "Balta","Costesti", NOW(), NOW()),
            (28, "Balta","Gornovita", NOW(), NOW()),
            (28, "Balta","Nevatu", NOW(), NOW()),
            (28, "Balta","Prejna", NOW(), NOW()),
            (28, "Balta","Sfodea", NOW(), NOW()),
            (28, "Balvanesti","Balvanestii de Jos", NOW(), NOW()),
            (28, "Balvanesti","Calinestii de Jos", NOW(), NOW()),
            (28, "Balvanesti","Calinestii de Sus", NOW(), NOW()),
            (28, "Balvanesti","Parlagele", NOW(), NOW()),
            (28, "Breznita-Motru","Cosovat", NOW(), NOW()),
            (28, "Breznita-Motru","Deleni", NOW(), NOW()),
            (28, "Breznita-Motru","Fauroaia", NOW(), NOW()),
            (28, "Breznita-Motru","Plai", NOW(), NOW()),
            (28, "Breznita-Motru","Talapanu", NOW(), NOW()),
            (28, "Breznita-Motru","Valea Teiului", NOW(), NOW()),
            (28, "Breznita-Ocol","Jidostita", NOW(), NOW()),
            (28, "Breznita-Ocol","Magheru", NOW(), NOW()),
            (28, "Breznita-Ocol","Susita", NOW(), NOW()),
            (28, "Brosteni","Capatanesti", NOW(), NOW()),
            (28, "Brosteni","Luncsoara", NOW(), NOW()),
            (28, "Brosteni","Lupsa de Jos", NOW(), NOW()),
            (28, "Brosteni","Lupsa de Sus", NOW(), NOW()),
            (28, "Brosteni","Meris", NOW(), NOW()),
            (28, "Burila Mare","Crivina", NOW(), NOW()),
            (28, "Burila Mare","Izvoru Frumos", NOW(), NOW()),
            (28, "Burila Mare","Vrancea", NOW(), NOW()),
            (28, "Burila Mare","Tiganasi", NOW(), NOW()),
            (28, "Butoiesti","Arginesti", NOW(), NOW()),
            (28, "Butoiesti","Buicesti", NOW(), NOW()),
            (28, "Butoiesti","Gura Motrului", NOW(), NOW()),
            (28, "Butoiesti","Jugastru", NOW(), NOW()),
            (28, "Butoiesti","Pluta", NOW(), NOW()),
            (28, "Butoiesti","Radutesti", NOW(), NOW()),
            (28, "Butoiesti","Tantaru", NOW(), NOW()),
            (28, "Cazanesti","Ercea", NOW(), NOW()),
            (28, "Cazanesti","Govodarva", NOW(), NOW()),
            (28, "Cazanesti","Garbovatu de Sus", NOW(), NOW()),
            (28, "Cazanesti","Ilovu", NOW(), NOW()),
            (28, "Cazanesti","Jignita", NOW(), NOW()),
            (28, "Cazanesti","Poiana", NOW(), NOW()),
            (28, "Cazanesti","Paltinisu", NOW(), NOW()),
            (28, "Cazanesti","Rosia", NOW(), NOW()),
            (28, "Cazanesti","Severinesti", NOW(), NOW()),
            (28, "Cazanesti","Suharu", NOW(), NOW()),
            (28, "Cazanesti","Valea Cosustei", NOW(), NOW()),
            (28, "Ciresu","Bunoaica", NOW(), NOW()),
            (28, "Ciresu","Jupanesti", NOW(), NOW()),
            (28, "Ciresu","Negrusa", NOW(), NOW()),
            (28, "Corcova","Breta", NOW(), NOW()),
            (28, "Corcova","Cernaia", NOW(), NOW()),
            (28, "Corcova","Cordun", NOW(), NOW()),
            (28, "Corcova","Croica", NOW(), NOW()),
            (28, "Corcova","Garbovatu de Jos", NOW(), NOW()),
            (28, "Corcova","Imoasa", NOW(), NOW()),
            (28, "Corcova","Jirov", NOW(), NOW()),
            (28, "Corcova","Maru Rosu", NOW(), NOW()),
            (28, "Corcova","Puscasu", NOW(), NOW()),
            (28, "Corcova","Parvulesti", NOW(), NOW()),
            (28, "Corcova","Stejaru", NOW(), NOW()),
            (28, "Corcova","Vladasesti", NOW(), NOW()),
            (28, "Corlatel","Valea Anilor", NOW(), NOW()),
            (28, "Cujmir","Aurora", NOW(), NOW()),
            (28, "Cujmir","Cujmiru Mic", NOW(), NOW()),
            (28, "Darvari","Gemeni", NOW(), NOW()),
            (28, "Devesel","Batoti", NOW(), NOW()),
            (28, "Devesel","Bistretu", NOW(), NOW()),
            (28, "Devesel","Dunarea Mica", NOW(), NOW()),
            (28, "Devesel","Scapau", NOW(), NOW()),
            (28, "Devesel","Tismana", NOW(), NOW()),
            (28, "Drobeta-Turnu Severin","Dudasu Schelei", NOW(), NOW()),
            (28, "Drobeta-Turnu Severin","Gura Vaii", NOW(), NOW()),
            (28, "Drobeta-Turnu Severin","Schela Cladovei", NOW(), NOW()),
            (28, "Dubova","Baia Noua", NOW(), NOW()),
            (28, "Dubova","Eibenthal", NOW(), NOW()),
            (28, "Dumbrava","Albulesti", NOW(), NOW()),
            (28, "Dumbrava","Bragleasa", NOW(), NOW()),
            (28, "Dumbrava","Dumbrava de Jos", NOW(), NOW()),
            (28, "Dumbrava","Dumbrava de Mijloc", NOW(), NOW()),
            (28, "Dumbrava","Dumbrava de Sus", NOW(), NOW()),
            (28, "Dumbrava","Golineasa", NOW(), NOW()),
            (28, "Dumbrava","Higiu", NOW(), NOW()),
            (28, "Dumbrava","Rocsoreni", NOW(), NOW()),
            (28, "Dumbrava","Valea Marcului", NOW(), NOW()),
            (28, "Dumbrava","Varodia", NOW(), NOW()),
            (28, "Dumbrava","Vladica", NOW(), NOW()),
            (28, "Floresti","Copacioasa", NOW(), NOW()),
            (28, "Floresti","Gardoaia", NOW(), NOW()),
            (28, "Floresti","Livezi", NOW(), NOW()),
            (28, "Floresti","Mosneni", NOW(), NOW()),
            (28, "Floresti","Pesteana", NOW(), NOW()),
            (28, "Floresti","Pestenuta", NOW(), NOW()),
            (28, "Floresti","Stroesti", NOW(), NOW()),
            (28, "Floresti","Zegujani", NOW(), NOW()),
            (28, "Garla Mare","Vrata", NOW(), NOW()),
            (28, "Godeanu","Marga", NOW(), NOW()),
            (28, "Godeanu","Paunesti", NOW(), NOW()),
            (28, "Godeanu","Siroca", NOW(), NOW()),
            (28, "Gogosu","Balta Verde", NOW(), NOW()),
            (28, "Gogosu","Burila Mica", NOW(), NOW()),
            (28, "Gogosu","Ostrovu Mare", NOW(), NOW()),
            (28, "Greci","Blidaru", NOW(), NOW()),
            (28, "Greci","Baltanele", NOW(), NOW()),
            (28, "Greci","Salatruc", NOW(), NOW()),
            (28, "Greci","Valea Petrii", NOW(), NOW()),
            (28, "Greci","Visina", NOW(), NOW()),
            (28, "Grozesti","Carceni", NOW(), NOW()),
            (28, "Grozesti","Pasarani", NOW(), NOW()),
            (28, "Grozesti","Susita", NOW(), NOW()),
            (28, "Gruia","Izvoarele", NOW(), NOW()),
            (28, "Gruia","Poiana Gruii", NOW(), NOW()),
            (28, "Hinova","Bistrita", NOW(), NOW()),
            (28, "Hinova","Carjei", NOW(), NOW()),
            (28, "Hinova","Ostrovu Corbului", NOW(), NOW()),
            (28, "Husnicioara","Alunisul", NOW(), NOW()),
            (28, "Husnicioara","Borogea", NOW(), NOW()),
            (28, "Husnicioara","Baditesti", NOW(), NOW()),
            (28, "Husnicioara","Celnata", NOW(), NOW()),
            (28, "Husnicioara","Dumbravita", NOW(), NOW()),
            (28, "Husnicioara","Marmanu", NOW(), NOW()),
            (28, "Husnicioara","Opranesti", NOW(), NOW()),
            (28, "Husnicioara","Peri", NOW(), NOW()),
            (28, "Husnicioara","Priboiesti", NOW(), NOW()),
            (28, "Husnicioara","Selisteni", NOW(), NOW()),
            (28, "Ilovat","Budanesti", NOW(), NOW()),
            (28, "Ilovat","Cracu Lung", NOW(), NOW()),
            (28, "Ilovat","Dalbocita", NOW(), NOW()),
            (28, "Ilovat","Firizu", NOW(), NOW()),
            (28, "Ilovat","Racova", NOW(), NOW()),
            (28, "Ilovita","Bahna", NOW(), NOW()),
            (28, "Ilovita","Moisesti", NOW(), NOW()),
            (28, "Isverna","Busesti", NOW(), NOW()),
            (28, "Isverna","Cerna-Varf", NOW(), NOW()),
            (28, "Isverna","Draghesti", NOW(), NOW()),
            (28, "Isverna","Giurgiani", NOW(), NOW()),
            (28, "Isverna","Nadanova", NOW(), NOW()),
            (28, "Isverna","Selistea", NOW(), NOW()),
            (28, "Isverna","Turtaba", NOW(), NOW()),
            (28, "Izvoru Barzii","Balotesti", NOW(), NOW()),
            (28, "Izvoru Barzii","Halanga", NOW(), NOW()),
            (28, "Izvoru Barzii","Putinei", NOW(), NOW()),
            (28, "Izvoru Barzii","Rascolesti", NOW(), NOW()),
            (28, "Izvoru Barzii","Schinteiesti", NOW(), NOW()),
            (28, "Izvoru Barzii","Schitu Topolnitei", NOW(), NOW()),
            (28, "Jiana","Cioroboreni", NOW(), NOW()),
            (28, "Jiana","Danceu", NOW(), NOW()),
            (28, "Jiana","Jiana Mare", NOW(), NOW()),
            (28, "Jiana","Jiana Veche", NOW(), NOW()),
            (28, "Livezile","Izvoru Anestilor", NOW(), NOW()),
            (28, "Livezile","Izvoralu de Jos", NOW(), NOW()),
            (28, "Livezile","Petris", NOW(), NOW()),
            (28, "Livezile","Stefan Odobleja", NOW(), NOW()),
            (28, "Malovat","23 August", NOW(), NOW()),
            (28, "Malovat","Bobaita", NOW(), NOW()),
            (28, "Malovat","Barda", NOW(), NOW()),
            (28, "Malovat","Colibasi", NOW(), NOW()),
            (28, "Malovat","Lazu", NOW(), NOW()),
            (28, "Malovat","Negresti", NOW(), NOW()),
            (28, "Obarsia De Camp","Izimsa", NOW(), NOW()),
            (28, "Obarsia-Closani","Godeanu", NOW(), NOW()),
            (28, "Oprisor","Prisaceaua", NOW(), NOW()),
            (28, "Padina","Biban", NOW(), NOW()),
            (28, "Padina","Iablanita", NOW(), NOW()),
            (28, "Padina","Olteanca", NOW(), NOW()),
            (28, "Padina","Padina Mare", NOW(), NOW()),
            (28, "Padina","Padina Mica", NOW(), NOW()),
            (28, "Padina","Slasoma", NOW(), NOW()),
            (28, "Patulele","Viasu", NOW(), NOW()),
            (28, "Podeni","Gornenti", NOW(), NOW()),
            (28, "Podeni","Malarisca", NOW(), NOW()),
            (28, "Ponoarele","Branzeni", NOW(), NOW()),
            (28, "Ponoarele","Buicani", NOW(), NOW()),
            (28, "Ponoarele","Baraiacu", NOW(), NOW()),
            (28, "Ponoarele","Baluta", NOW(), NOW()),
            (28, "Ponoarele","Ceptureni", NOW(), NOW()),
            (28, "Ponoarele","Cracu Muntelui", NOW(), NOW()),
            (28, "Ponoarele","Delureni", NOW(), NOW()),
            (28, "Ponoarele","Gheorghesti", NOW(), NOW()),
            (28, "Ponoarele","Gardaneasa", NOW(), NOW()),
            (28, "Ponoarele","Ludu", NOW(), NOW()),
            (28, "Ponoarele","Proitesti", NOW(), NOW()),
            (28, "Ponoarele","Raiculesti", NOW(), NOW()),
            (28, "Ponoarele","Valea Ursului", NOW(), NOW()),
            (28, "Ponoarele","Sipotu", NOW(), NOW()),
            (28, "Poroina Mare","Fantanile Negre", NOW(), NOW()),
            (28, "Poroina Mare","Stignita", NOW(), NOW()),
            (28, "Poroina Mare","Sipotu", NOW(), NOW()),
            (28, "Pristol","Cozia", NOW(), NOW()),
            (28, "Prunisor","Arvatesti", NOW(), NOW()),
            (28, "Prunisor","Balota", NOW(), NOW()),
            (28, "Prunisor","Baltanele", NOW(), NOW()),
            (28, "Prunisor","Cervenita", NOW(), NOW()),
            (28, "Prunisor","Dragotesti", NOW(), NOW()),
            (28, "Prunisor","Fantana Domneasca", NOW(), NOW()),
            (28, "Prunisor","Ghelmegioaia", NOW(), NOW()),
            (28, "Prunisor","Gutu", NOW(), NOW()),
            (28, "Prunisor","Garnita", NOW(), NOW()),
            (28, "Prunisor","Igiroasa", NOW(), NOW()),
            (28, "Prunisor","Lumnic", NOW(), NOW()),
            (28, "Prunisor","Mijarca", NOW(), NOW()),
            (28, "Prunisor","Prunaru", NOW(), NOW()),
            (28, "Prunisor","Zegaia", NOW(), NOW()),
            (28, "Punghina","Cearangu", NOW(), NOW()),
            (28, "Punghina","Drincea", NOW(), NOW()),
            (28, "Punghina","Magurele", NOW(), NOW()),
            (28, "Punghina","Recea", NOW(), NOW()),
            (28, "Punghina","Satu Nou", NOW(), NOW()),
            (28, "Rogova","Poroinita", NOW(), NOW()),
            (28, "Simian","Cerneti", NOW(), NOW()),
            (28, "Simian","Dedovita Noua", NOW(), NOW()),
            (28, "Simian","Dedovita Veche", NOW(), NOW()),
            (28, "Simian","Dudasu", NOW(), NOW()),
            (28, "Simian","Erghevita", NOW(), NOW()),
            (28, "Simian","Poroina", NOW(), NOW()),
            (28, "Simian","Valea Copcii", NOW(), NOW()),
            (28, "Sisesti","Ciovarnasani", NOW(), NOW()),
            (28, "Sisesti","Cocorova", NOW(), NOW()),
            (28, "Sisesti","Craguesti", NOW(), NOW()),
            (28, "Sisesti","Caramidaru", NOW(), NOW()),
            (28, "Sisesti","Noaptesa", NOW(), NOW()),
            (28, "Sovarna","Ohaba", NOW(), NOW()),
            (28, "Sovarna","Studina", NOW(), NOW()),
            (28, "Stangaceaua","Breznicioara", NOW(), NOW()),
            (28, "Stangaceaua","Barlogeni", NOW(), NOW()),
            (28, "Stangaceaua","Ceranganul", NOW(), NOW()),
            (28, "Stangaceaua","Fata Motrului", NOW(), NOW()),
            (28, "Stangaceaua","Posta Veche", NOW(), NOW()),
            (28, "Stangaceaua","Satu Mare", NOW(), NOW()),
            (28, "Stangaceaua","Tarsa", NOW(), NOW()),
            (28, "Strehaia","Ciochiuta", NOW(), NOW()),
            (28, "Strehaia","Comanda", NOW(), NOW()),
            (28, "Strehaia","Hurducesti", NOW(), NOW()),
            (28, "Strehaia","Lunca Banului", NOW(), NOW()),
            (28, "Strehaia","Menti", NOW(), NOW()),
            (28, "Strehaia","Motruleni", NOW(), NOW()),
            (28, "Strehaia","Slatinicu Mare", NOW(), NOW()),
            (28, "Strehaia","Slatinicu Mic", NOW(), NOW()),
            (28, "Strehaia","Stancesti", NOW(), NOW()),
            (28, "Tamna","Adunatii Teiului", NOW(), NOW()),
            (28, "Tamna","Boceni", NOW(), NOW()),
            (28, "Tamna","Colaret", NOW(), NOW()),
            (28, "Tamna","Cremenea", NOW(), NOW()),
            (28, "Tamna","Fata Cremenii", NOW(), NOW()),
            (28, "Tamna","Izvoralu", NOW(), NOW()),
            (28, "Tamna","Manu", NOW(), NOW()),
            (28, "Tamna","Pavat", NOW(), NOW()),
            (28, "Tamna","Plopi", NOW(), NOW()),
            (28, "Tamna","Valea Ursului", NOW(), NOW()),
            (28, "Vanatori","Branistea", NOW(), NOW()),
            (28, "Vanatori","Goanta", NOW(), NOW()),
            (28, "Vanatori","Rosiori", NOW(), NOW()),
            (28, "Vanju Mare","Bucura", NOW(), NOW()),
            (28, "Vanju Mare","Nicolae Balcescu", NOW(), NOW()),
            (28, "Vanju Mare","Orevita Mare", NOW(), NOW()),
            (28, "Vanju Mare","Traian", NOW(), NOW()),
            (28, "Vanjulet","Hotarani", NOW(), NOW()),
            (28, "Vladaia","Almajel", NOW(), NOW()),
            (28, "Vladaia","Scorila", NOW(), NOW()),
            (28, "Vladaia","Stircovita", NOW(), NOW()),
            (28, "Voloiac","Cotoroaia", NOW(), NOW()),
            (28, "Voloiac","Lac", NOW(), NOW()),
            (28, "Voloiac","Ruptura", NOW(), NOW()),
            (28, "Voloiac","Sperlesti", NOW(), NOW()),
            (28, "Voloiac","Valea Buna", NOW(), NOW()),
            (28, "Voloiac","Voloicel", NOW(), NOW()),
            (28, "Voloiac","Titirigi", NOW(), NOW())
        ;';
        DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=28;';
        DB::connection()->getPdo()->exec($sql);
    }
}
