<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForDJ extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (17, "","Afumati", NOW(), NOW()),
            (17, "","Almaj", NOW(), NOW()),
            (17, "","Amarastii de Jos", NOW(), NOW()),
            (17, "","Amarastii de Sus", NOW(), NOW()),
            (17, "","Apele Vii", NOW(), NOW()),
            (17, "","Argetoaia", NOW(), NOW()),
            (17, "","Bechet", NOW(), NOW()),
            (17, "","Bistret", NOW(), NOW()),
            (17, "","Botosesti-Paia", NOW(), NOW()),
            (17, "","Brabova", NOW(), NOW()),
            (17, "","Bralostita", NOW(), NOW()),
            (17, "","Bratovoesti", NOW(), NOW()),
            (17, "","Breasta", NOW(), NOW()),
            (17, "","Bradesti", NOW(), NOW()),
            (17, "","Bucovat", NOW(), NOW()),
            (17, "","Bulzesti", NOW(), NOW()),
            (17, "","Bailesti", NOW(), NOW()),
            (17, "","Calafat", NOW(), NOW()),
            (17, "","Calopar", NOW(), NOW()),
            (17, "","Caraula", NOW(), NOW()),
            (17, "","Carpen", NOW(), NOW()),
            (17, "","Castranova", NOW(), NOW()),
            (17, "","Celaru", NOW(), NOW()),
            (17, "","Cernatesti", NOW(), NOW()),
            (17, "","Cerat", NOW(), NOW()),
            (17, "","Cetate", NOW(), NOW()),
            (17, "","Cioroiasi", NOW(), NOW()),
            (17, "","Ciupercenii Noi", NOW(), NOW()),
            (17, "","Cosoveni", NOW(), NOW()),
            (17, "","Cotofenii din Dos", NOW(), NOW()),
            (17, "","Craiova", NOW(), NOW()),
            (17, "","Calarasi", NOW(), NOW()),
            (17, "","Daneti", NOW(), NOW()),
            (17, "","Desa", NOW(), NOW()),
            (17, "","Diosti", NOW(), NOW()),
            (17, "","Dobresti", NOW(), NOW()),
            (17, "","Dragotesti", NOW(), NOW()),
            (17, "","Dranic", NOW(), NOW()),
            (17, "","Dabuleni", NOW(), NOW()),
            (17, "","Filiasi", NOW(), NOW()),
            (17, "","Farcas", NOW(), NOW()),
            (17, "","Galicea Mare", NOW(), NOW()),
            (17, "","Ghercesti", NOW(), NOW()),
            (17, "","Gighera", NOW(), NOW()),
            (17, "","Giubega", NOW(), NOW()),
            (17, "","Giurgita", NOW(), NOW()),
            (17, "","Gogosu", NOW(), NOW()),
            (17, "","Goicea", NOW(), NOW()),
            (17, "","Goiesti", NOW(), NOW()),
            (17, "","Grecesti", NOW(), NOW()),
            (17, "","Izvoare", NOW(), NOW()),
            (17, "","Isalnita", NOW(), NOW()),
            (17, "","Leu", NOW(), NOW()),
            (17, "","Lipovu", NOW(), NOW()),
            (17, "","Maglavit", NOW(), NOW()),
            (17, "","Malu Mare", NOW(), NOW()),
            (17, "","Melinesti", NOW(), NOW()),
            (17, "","Mischii", NOW(), NOW()),
            (17, "","Motatei", NOW(), NOW()),
            (17, "","Murgasi", NOW(), NOW()),
            (17, "","Marsani", NOW(), NOW()),
            (17, "","Macesu de Jos", NOW(), NOW()),
            (17, "","Macesu de Sus", NOW(), NOW()),
            (17, "","Negoi", NOW(), NOW()),
            (17, "","Orodel", NOW(), NOW()),
            (17, "","Ostroveni", NOW(), NOW()),
            (17, "","Perisor", NOW(), NOW()),
            (17, "","Pielesti", NOW(), NOW()),
            (17, "","Piscu Vechi", NOW(), NOW()),
            (17, "","Plenita", NOW(), NOW()),
            (17, "","Podari", NOW(), NOW()),
            (17, "","Poiana Mare", NOW(), NOW()),
            (17, "","Predesti", NOW(), NOW()),
            (17, "","Radovan", NOW(), NOW()),
            (17, "","Rast", NOW(), NOW()),
            (17, "","Sadova", NOW(), NOW()),
            (17, "","Scaesti", NOW(), NOW()),
            (17, "","Seaca de Camp", NOW(), NOW()),
            (17, "","Seaca de Padure", NOW(), NOW()),
            (17, "","Secu", NOW(), NOW()),
            (17, "","Segarcea", NOW(), NOW()),
            (17, "","Silistea Crucii", NOW(), NOW()),
            (17, "","Sopot", NOW(), NOW()),
            (17, "","Salcuta", NOW(), NOW()),
            (17, "","Teasc", NOW(), NOW()),
            (17, "","Terpezita", NOW(), NOW()),
            (17, "","Teslui", NOW(), NOW()),
            (17, "","Unirea", NOW(), NOW()),
            (17, "","Urzicuta", NOW(), NOW()),
            (17, "","Valea Stanciului", NOW(), NOW()),
            (17, "","Vela", NOW(), NOW()),
            (17, "","Verbita", NOW(), NOW()),
            (17, "","Vartop", NOW(), NOW()),
            (17, "","Varvoru de Jos", NOW(), NOW()),
            (17, "","Simnicu de Sus", NOW(), NOW()),
            (17, "","Tuglui", NOW(), NOW()),
            (17, "Afumati","Boureni", NOW(), NOW()),
            (17, "Afumati","Covei", NOW(), NOW()),
            (17, "Almaj","Beharca", NOW(), NOW()),
            (17, "Almaj","Bogea", NOW(), NOW()),
            (17, "Almaj","Cotofenii din Fata", NOW(), NOW()),
            (17, "Almaj","Mosneni", NOW(), NOW()),
            (17, "Almaj","Sitoaia", NOW(), NOW()),
            (17, "Amarastii De Jos","Ocolna", NOW(), NOW()),
            (17, "Amarastii De Jos","Prapor", NOW(), NOW()),
            (17, "Amarastii De Sus","Dobrotesti", NOW(), NOW()),
            (17, "Amarastii De Sus","Nisipuri", NOW(), NOW()),
            (17, "Amarastii De Sus","Zvorsca", NOW(), NOW()),
            (17, "Argetoaia","Berbesu", NOW(), NOW()),
            (17, "Argetoaia","Baranu", NOW(), NOW()),
            (17, "Argetoaia","Iordachesti", NOW(), NOW()),
            (17, "Argetoaia","Leordoasa", NOW(), NOW()),
            (17, "Argetoaia","Malumnic", NOW(), NOW()),
            (17, "Argetoaia","Novac", NOW(), NOW()),
            (17, "Argetoaia","Piria", NOW(), NOW()),
            (17, "Argetoaia","Poiana Fantanii", NOW(), NOW()),
            (17, "Argetoaia","Salcia", NOW(), NOW()),
            (17, "Argetoaia","Teascu din Deal", NOW(), NOW()),
            (17, "Argetoaia","Ursoaia", NOW(), NOW()),
            (17, "Bailesti","Balasan", NOW(), NOW()),
            (17, "Birca","Barca", NOW(), NOW()),
            (17, "Bistret","Bistretu Nou", NOW(), NOW()),
            (17, "Bistret","Brandusa", NOW(), NOW()),
            (17, "Bistret","Plosca", NOW(), NOW()),
            (17, "Brabova","Caraiman", NOW(), NOW()),
            (17, "Brabova","Mosna", NOW(), NOW()),
            (17, "Brabova","Rachita de Jos", NOW(), NOW()),
            (17, "Brabova","Urdinita", NOW(), NOW()),
            (17, "Brabova","Voita", NOW(), NOW()),
            (17, "Bradesti","Bradestii Batrani", NOW(), NOW()),
            (17, "Bradesti","Meteu", NOW(), NOW()),
            (17, "Bradesti","Piscani", NOW(), NOW()),
            (17, "Bradesti","Racarii de Jos", NOW(), NOW()),
            (17, "Bradesti","Tatomiresti", NOW(), NOW()),
            (17, "Bralostita","Ciocanele", NOW(), NOW()),
            (17, "Bralostita","Racovita", NOW(), NOW()),
            (17, "Bralostita","Schitu", NOW(), NOW()),
            (17, "Bralostita","Sfarcea", NOW(), NOW()),
            (17, "Bralostita","Valea Fantanilor", NOW(), NOW()),
            (17, "Bratovoesti","Badosi", NOW(), NOW()),
            (17, "Bratovoesti","Georocu Mare", NOW(), NOW()),
            (17, "Bratovoesti","Prunet", NOW(), NOW()),
            (17, "Bratovoesti","Rojiste", NOW(), NOW()),
            (17, "Bratovoesti","Tamburesti", NOW(), NOW()),
            (17, "Breasta","Cotu", NOW(), NOW()),
            (17, "Breasta","Crovna", NOW(), NOW()),
            (17, "Breasta","Faget", NOW(), NOW()),
            (17, "Breasta","Obedin", NOW(), NOW()),
            (17, "Breasta","Rosieni", NOW(), NOW()),
            (17, "Breasta","Valea Lungului", NOW(), NOW()),
            (17, "Bucovat","Carligei", NOW(), NOW()),
            (17, "Bucovat","Italieni", NOW(), NOW()),
            (17, "Bucovat","Leamna de Jos", NOW(), NOW()),
            (17, "Bucovat","Leamna de Sus", NOW(), NOW()),
            (17, "Bucovat","Palilula", NOW(), NOW()),
            (17, "Bucovat","Sarbatoarea", NOW(), NOW()),
            (17, "Bulzesti","Fratila", NOW(), NOW()),
            (17, "Bulzesti","Gura Racului", NOW(), NOW()),
            (17, "Bulzesti","Piscu Lung", NOW(), NOW()),
            (17, "Bulzesti","Poienile", NOW(), NOW()),
            (17, "Bulzesti","Prejoi", NOW(), NOW()),
            (17, "Bulzesti","Seculesti", NOW(), NOW()),
            (17, "Bulzesti","Stoicesti", NOW(), NOW()),
            (17, "Bulzesti","Saliste", NOW(), NOW()),
            (17, "Bulzesti","Infratirea", NOW(), NOW()),
            (17, "Calafat","Basarabi", NOW(), NOW()),
            (17, "Calafat","Ciupercenii Vechi", NOW(), NOW()),
            (17, "Calafat","Golenti", NOW(), NOW()),
            (17, "Calarasi","Sarata", NOW(), NOW()),
            (17, "Calopar","Belcinu", NOW(), NOW()),
            (17, "Calopar","Bazdana", NOW(), NOW()),
            (17, "Calopar","Panaghia", NOW(), NOW()),
            (17, "Calopar","Salcuta", NOW(), NOW()),
            (17, "Carpen","Cleanov", NOW(), NOW()),
            (17, "Carpen","Geblesti", NOW(), NOW()),
            (17, "Castranova","Puturi", NOW(), NOW()),
            (17, "Celaru","Ghizdavesti", NOW(), NOW()),
            (17, "Celaru","Marotinu de Jos", NOW(), NOW()),
            (17, "Celaru","Marotinu de Sus", NOW(), NOW()),
            (17, "Celaru","Soreni", NOW(), NOW()),
            (17, "Cerat","Malaica", NOW(), NOW()),
            (17, "Cernatesti","Cornita", NOW(), NOW()),
            (17, "Cernatesti","Rasnicu Batran", NOW(), NOW()),
            (17, "Cernatesti","Rasnicu Oghian", NOW(), NOW()),
            (17, "Cernatesti","Tiu", NOW(), NOW()),
            (17, "Cetate","Moreni", NOW(), NOW()),
            (17, "Cioroiasi","Cetatuia", NOW(), NOW()),
            (17, "Cioroiasi","Cioroiu Nou", NOW(), NOW()),
            (17, "Ciupercenii Noi","Smardan", NOW(), NOW()),
            (17, "Cosoveni","Carcea", NOW(), NOW()),
            (17, "Cotofenii Din Dos","Mihaita", NOW(), NOW()),
            (17, "Cotofenii Din Dos","Potmeltu", NOW(), NOW()),
            (17, "Craiova","Cernele", NOW(), NOW()),
            (17, "Craiova","Cernelele de Sus", NOW(), NOW()),
            (17, "Craiova","Facai", NOW(), NOW()),
            (17, "Craiova","Izvorul Rece", NOW(), NOW()),
            (17, "Craiova","Mofleni", NOW(), NOW()),
            (17, "Craiova","Popoveni", NOW(), NOW()),
            (17, "Craiova","Rovine", NOW(), NOW()),
            (17, "Craiova","Simnicu de Jos", NOW(), NOW()),
            (17, "Dabuleni","Chiasu", NOW(), NOW()),
            (17, "Daneti","Brabeti", NOW(), NOW()),
            (17, "Daneti","Braniste", NOW(), NOW()),
            (17, "Daneti","Locusteni", NOW(), NOW()),
            (17, "Diosti","Ciocanesti", NOW(), NOW()),
            (17, "Diosti","Radomir", NOW(), NOW()),
            (17, "Dobresti","Caciulatesti", NOW(), NOW()),
            (17, "Dobresti","Georocel", NOW(), NOW()),
            (17, "Dobresti","Murta", NOW(), NOW()),
            (17, "Dobresti","Toceni", NOW(), NOW()),
            (17, "Dragotesti","Benesti", NOW(), NOW()),
            (17, "Dragotesti","Bobeanu", NOW(), NOW()),
            (17, "Dragotesti","Buzduc", NOW(), NOW()),
            (17, "Dragotesti","Popanzalesti", NOW(), NOW()),
            (17, "Dragotesti","Viisoara", NOW(), NOW()),
            (17, "Dranic","Booveni", NOW(), NOW()),
            (17, "Dranic","Foisor", NOW(), NOW()),
            (17, "Dranic","Padea", NOW(), NOW()),
            (17, "Farcas","Amarasti", NOW(), NOW()),
            (17, "Farcas","Golumbelu", NOW(), NOW()),
            (17, "Farcas","Golumbu", NOW(), NOW()),
            (17, "Farcas","Moflesti", NOW(), NOW()),
            (17, "Farcas","Nistoi", NOW(), NOW()),
            (17, "Farcas","Plopu Amarasti", NOW(), NOW()),
            (17, "Farcas","Putinei", NOW(), NOW()),
            (17, "Farcas","Soceni", NOW(), NOW()),
            (17, "Farcas","Talpas", NOW(), NOW()),
            (17, "Filiasi","Almajel", NOW(), NOW()),
            (17, "Filiasi","Braniste", NOW(), NOW()),
            (17, "Filiasi","Balta", NOW(), NOW()),
            (17, "Filiasi","Fratostita", NOW(), NOW()),
            (17, "Filiasi","Racarii de Sus", NOW(), NOW()),
            (17, "Filiasi","Uscaci", NOW(), NOW()),
            (17, "Ghercesti","Garlesti", NOW(), NOW()),
            (17, "Ghercesti","Luncsoru", NOW(), NOW()),
            (17, "Ghercesti","Ungureni", NOW(), NOW()),
            (17, "Ghercesti","Ungurenii Mici", NOW(), NOW()),
            (17, "Gighera","Nedeia", NOW(), NOW()),
            (17, "Gighera","Zaval", NOW(), NOW()),
            (17, "Gingiova","Comosteni", NOW(), NOW()),
            (17, "Gingiova","Gangiova", NOW(), NOW()),
            (17, "Giubega","Galiciuica", NOW(), NOW()),
            (17, "Giurgita","Curmatura", NOW(), NOW()),
            (17, "Giurgita","Filaret", NOW(), NOW()),
            (17, "Gogosu","Gogosita", NOW(), NOW()),
            (17, "Gogosu","Stefanel", NOW(), NOW()),
            (17, "Goicea","Carna", NOW(), NOW()),
            (17, "Goiesti","Adancata", NOW(), NOW()),
            (17, "Goiesti","Fantani", NOW(), NOW()),
            (17, "Goiesti","Gruita", NOW(), NOW()),
            (17, "Goiesti","Mogosesti", NOW(), NOW()),
            (17, "Goiesti","Muereni", NOW(), NOW()),
            (17, "Goiesti","Malaesti", NOW(), NOW()),
            (17, "Goiesti","Pioresti", NOW(), NOW()),
            (17, "Goiesti","Pometesti", NOW(), NOW()),
            (17, "Goiesti","Popeasa", NOW(), NOW()),
            (17, "Goiesti","Vladimir", NOW(), NOW()),
            (17, "Goiesti","Zlatari", NOW(), NOW()),
            (17, "Goiesti","Tandara", NOW(), NOW()),
            (17, "Grecesti","Busu", NOW(), NOW()),
            (17, "Grecesti","Busuletu", NOW(), NOW()),
            (17, "Grecesti","Barboi", NOW(), NOW()),
            (17, "Grecesti","Gropanele", NOW(), NOW()),
            (17, "Grecesti","Gradistea", NOW(), NOW()),
            (17, "Izvoare","Corlate", NOW(), NOW()),
            (17, "Izvoare","Domnu Tudor", NOW(), NOW()),
            (17, "Leu","Zanoaga", NOW(), NOW()),
            (17, "Lipovu","Lipovu de Sus", NOW(), NOW()),
            (17, "Macesu De Jos","Sapata", NOW(), NOW()),
            (17, "Maglavit","Hunia", NOW(), NOW()),
            (17, "Malu Mare","Ghindeni", NOW(), NOW()),
            (17, "Malu Mare","Preajba", NOW(), NOW()),
            (17, "Melinesti","Bodaiesti", NOW(), NOW()),
            (17, "Melinesti","Bodaiestii de Sus", NOW(), NOW()),
            (17, "Melinesti","Godeni", NOW(), NOW()),
            (17, "Melinesti","Muierusu", NOW(), NOW()),
            (17, "Melinesti","Negoiesti", NOW(), NOW()),
            (17, "Melinesti","Odoleni", NOW(), NOW()),
            (17, "Melinesti","Ohaba", NOW(), NOW()),
            (17, "Melinesti","Plostina", NOW(), NOW()),
            (17, "Melinesti","Popesti", NOW(), NOW()),
            (17, "Melinesti","Spineni", NOW(), NOW()),
            (17, "Melinesti","Valea Mare", NOW(), NOW()),
            (17, "Melinesti","Valea Muierii de Jos", NOW(), NOW()),
            (17, "Mischii","Calinesti", NOW(), NOW()),
            (17, "Mischii","Gogosesti", NOW(), NOW()),
            (17, "Mischii","Mlecanesti", NOW(), NOW()),
            (17, "Mischii","Motoci", NOW(), NOW()),
            (17, "Mischii","Urechesti", NOW(), NOW()),
            (17, "Motatei","Dobridor", NOW(), NOW()),
            (17, "Motatei","Motatei Gara", NOW(), NOW()),
            (17, "Murgasi","Balota de Jos", NOW(), NOW()),
            (17, "Murgasi","Balota de Sus", NOW(), NOW()),
            (17, "Murgasi","Busteni", NOW(), NOW()),
            (17, "Murgasi","Gaia", NOW(), NOW()),
            (17, "Murgasi","Picaturile", NOW(), NOW()),
            (17, "Murgasi","Rupturile", NOW(), NOW()),
            (17, "Murgasi","Velesti", NOW(), NOW()),
            (17, "Negoi","Catane", NOW(), NOW()),
            (17, "Negoi","Catanele Noi", NOW(), NOW()),
            (17, "Orodel","Bechet", NOW(), NOW()),
            (17, "Orodel","Cornu", NOW(), NOW()),
            (17, "Orodel","Calugarei", NOW(), NOW()),
            (17, "Orodel","Teiu", NOW(), NOW()),
            (17, "Ostroveni","Listeava", NOW(), NOW()),
            (17, "Perisor","Maracinele", NOW(), NOW()),
            (17, "Pielesti","Campeni", NOW(), NOW()),
            (17, "Pielesti","Langa", NOW(), NOW()),
            (17, "Piscu Vechi","Ghidici", NOW(), NOW()),
            (17, "Piscu Vechi","Pisculet", NOW(), NOW()),
            (17, "Plenita","Castrele Traiane", NOW(), NOW()),
            (17, "Podari","Balta Verde", NOW(), NOW()),
            (17, "Podari","Braniste", NOW(), NOW()),
            (17, "Podari","Gura Vaii", NOW(), NOW()),
            (17, "Podari","Livezi", NOW(), NOW()),
            (17, "Poiana Mare","Tunarii Noi", NOW(), NOW()),
            (17, "Poiana Mare","Tunarii Vechi", NOW(), NOW()),
            (17, "Predesti","Bucicani", NOW(), NOW()),
            (17, "Predesti","Carstovani", NOW(), NOW()),
            (17, "Predesti","Frasin", NOW(), NOW()),
            (17, "Predesti","Milovan", NOW(), NOW()),
            (17, "Predesti","Plesoi", NOW(), NOW()),
            (17, "Predesti","Predestii Mici", NOW(), NOW()),
            (17, "Radovan","Fantanele", NOW(), NOW()),
            (17, "Radovan","Tarnava", NOW(), NOW()),
            (17, "Radovan","Intorsura", NOW(), NOW()),
            (17, "Robanesti","Bojoiu", NOW(), NOW()),
            (17, "Robanesti","Golfin", NOW(), NOW()),
            (17, "Robanesti","Lacrita Mare", NOW(), NOW()),
            (17, "Robanesti","Lacrita Mica", NOW(), NOW()),
            (17, "Robanesti","Robanestii de Jos", NOW(), NOW()),
            (17, "Robanesti","Robanestii de Sus", NOW(), NOW()),
            (17, "Sadova","Piscu Sadovei", NOW(), NOW()),
            (17, "Salcuta","Marza", NOW(), NOW()),
            (17, "Salcuta","Plopsor", NOW(), NOW()),
            (17, "Salcuta","Tencanau", NOW(), NOW()),
            (17, "Scaesti","Valea lui Patru", NOW(), NOW()),
            (17, "Seaca De Camp","Piscu Nou", NOW(), NOW()),
            (17, "Seaca De Padure","Rachita de Sus", NOW(), NOW()),
            (17, "Seaca De Padure","Veleni", NOW(), NOW()),
            (17, "Secu","Comanicea", NOW(), NOW()),
            (17, "Secu","Smadovicioara de Secu", NOW(), NOW()),
            (17, "Secu","Sumandra", NOW(), NOW()),
            (17, "Simnicu De Sus","Albesti", NOW(), NOW()),
            (17, "Simnicu De Sus","Cornetu", NOW(), NOW()),
            (17, "Simnicu De Sus","Deleni", NOW(), NOW()),
            (17, "Simnicu De Sus","Dudovicesti", NOW(), NOW()),
            (17, "Simnicu De Sus","Dutulesti", NOW(), NOW()),
            (17, "Simnicu De Sus","Floresti", NOW(), NOW()),
            (17, "Simnicu De Sus","Izvor", NOW(), NOW()),
            (17, "Simnicu De Sus","Jieni", NOW(), NOW()),
            (17, "Simnicu De Sus","Lesile", NOW(), NOW()),
            (17, "Simnicu De Sus","Milesti", NOW(), NOW()),
            (17, "Simnicu De Sus","Romanesti", NOW(), NOW()),
            (17, "Sopot","Bascov", NOW(), NOW()),
            (17, "Sopot","Belot", NOW(), NOW()),
            (17, "Sopot","Cernat", NOW(), NOW()),
            (17, "Sopot","Pereni", NOW(), NOW()),
            (17, "Sopot","Pietroaia", NOW(), NOW()),
            (17, "Sopot","Sarsca", NOW(), NOW()),
            (17, "Teasc","Secui", NOW(), NOW()),
            (17, "Terpezita","Caciulatu", NOW(), NOW()),
            (17, "Terpezita","Caruia", NOW(), NOW()),
            (17, "Terpezita","Floran", NOW(), NOW()),
            (17, "Terpezita","Lazu", NOW(), NOW()),
            (17, "Teslui","Cosereni", NOW(), NOW()),
            (17, "Teslui","Fantanele", NOW(), NOW()),
            (17, "Teslui","Preajba de Jos", NOW(), NOW()),
            (17, "Teslui","Preajba de Padure", NOW(), NOW()),
            (17, "Teslui","Urieni", NOW(), NOW()),
            (17, "Teslui","Viisoara Mosneni", NOW(), NOW()),
            (17, "Teslui","Tartal", NOW(), NOW()),
            (17, "Tuglui","Jiul", NOW(), NOW()),
            (17, "Urzicuta","Urzica Mare", NOW(), NOW()),
            (17, "Valea Stanciului","Horezu Poenari", NOW(), NOW()),
            (17, "Varvoru De Jos","Bujor", NOW(), NOW()),
            (17, "Varvoru De Jos","Ciutura", NOW(), NOW()),
            (17, "Varvoru De Jos","Criva", NOW(), NOW()),
            (17, "Varvoru De Jos","Dobromira", NOW(), NOW()),
            (17, "Varvoru De Jos","Dragoaia", NOW(), NOW()),
            (17, "Varvoru De Jos","Gabru", NOW(), NOW()),
            (17, "Varvoru De Jos","Varvor", NOW(), NOW()),
            (17, "Vela","Bucovicior", NOW(), NOW()),
            (17, "Vela","Cetatuia", NOW(), NOW()),
            (17, "Vela","Desnatui", NOW(), NOW()),
            (17, "Vela","Gubaucea", NOW(), NOW()),
            (17, "Vela","Seglet", NOW(), NOW()),
            (17, "Vela","Suharu", NOW(), NOW()),
            (17, "Vela","Stiubei", NOW(), NOW()),
            (17, "Verbita","Verbicioara", NOW(), NOW())
        ;';
        if (config('app.env') !== 'testing') {
            DB::connection()->getPdo()->exec($sql);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=17;';
        DB::connection()->getPdo()->exec($sql);
    }
}
