<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForOT extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (31, "","Baldovinesti", NOW(), NOW()),
            (31, "","Bals", NOW(), NOW()),
            (31, "","Bobicesti", NOW(), NOW()),
            (31, "","Brastavatu", NOW(), NOW()),
            (31, "","Brebeni", NOW(), NOW()),
            (31, "","Brancoveni", NOW(), NOW()),
            (31, "","Bucinisu", NOW(), NOW()),
            (31, "","Barza", NOW(), NOW()),
            (31, "","Babiciu", NOW(), NOW()),
            (31, "","Caracal", NOW(), NOW()),
            (31, "","Cezieni", NOW(), NOW()),
            (31, "","Cilieni", NOW(), NOW()),
            (31, "","Colonesti", NOW(), NOW()),
            (31, "","Corabia", NOW(), NOW()),
            (31, "","Corbu", NOW(), NOW()),
            (31, "","Coteana", NOW(), NOW()),
            (31, "","Crampoia", NOW(), NOW()),
            (31, "","Cungrea", NOW(), NOW()),
            (31, "","Curtisoara", NOW(), NOW()),
            (31, "","Carlogani", NOW(), NOW()),
            (31, "","Deveselu", NOW(), NOW()),
            (31, "","Dobretu", NOW(), NOW()),
            (31, "","Dobrosloveni", NOW(), NOW()),
            (31, "","Dobroteasa", NOW(), NOW()),
            (31, "","Dobrun", NOW(), NOW()),
            (31, "","Draghiceni", NOW(), NOW()),
            (31, "","Draganesti-Olt", NOW(), NOW()),
            (31, "","Daneasa", NOW(), NOW()),
            (31, "","Fagetelu", NOW(), NOW()),
            (31, "","Falcoiu", NOW(), NOW()),
            (31, "","Farcasele", NOW(), NOW()),
            (31, "","Giuvarasti", NOW(), NOW()),
            (31, "","Gostavatu", NOW(), NOW()),
            (31, "","Grojdibodu", NOW(), NOW()),
            (31, "","Gradinari", NOW(), NOW()),
            (31, "","Garcov", NOW(), NOW()),
            (31, "","Ganeasa", NOW(), NOW()),
            (31, "","Ianca", NOW(), NOW()),
            (31, "","Iancu Jianu", NOW(), NOW()),
            (31, "","Icoana", NOW(), NOW()),
            (31, "","Izbiceni", NOW(), NOW()),
            (31, "","Izvoarele", NOW(), NOW()),
            (31, "","Leleasca", NOW(), NOW()),
            (31, "","Mihaesti", NOW(), NOW()),
            (31, "","Morunglav", NOW(), NOW()),
            (31, "","Movileni", NOW(), NOW()),
            (31, "","Maruntei", NOW(), NOW()),
            (31, "","Nicolae Titulescu", NOW(), NOW()),
            (31, "","Oboga", NOW(), NOW()),
            (31, "","Obarsia", NOW(), NOW()),
            (31, "","Oporelu", NOW(), NOW()),
            (31, "","Orlea", NOW(), NOW()),
            (31, "","Osica de Sus", NOW(), NOW()),
            (31, "","Perieti", NOW(), NOW()),
            (31, "","Piatra-Olt", NOW(), NOW()),
            (31, "","Plesoiu", NOW(), NOW()),
            (31, "","Poboru", NOW(), NOW()),
            (31, "","Potcoava", NOW(), NOW()),
            (31, "","Priseaca", NOW(), NOW()),
            (31, "","Radomiresti", NOW(), NOW()),
            (31, "","Redea", NOW(), NOW()),
            (31, "","Rotunda", NOW(), NOW()),
            (31, "","Rusanesti", NOW(), NOW()),
            (31, "","Schitu", NOW(), NOW()),
            (31, "","Scornicesti", NOW(), NOW()),
            (31, "","Scarisoara", NOW(), NOW()),
            (31, "","Seaca", NOW(), NOW()),
            (31, "","Slatina", NOW(), NOW()),
            (31, "","Slatioara", NOW(), NOW()),
            (31, "","Spineni", NOW(), NOW()),
            (31, "","Sprancenata", NOW(), NOW()),
            (31, "","Stoenesti", NOW(), NOW()),
            (31, "","Stoicanesti", NOW(), NOW()),
            (31, "","Strejesti", NOW(), NOW()),
            (31, "","Studina", NOW(), NOW()),
            (31, "","Samburesti", NOW(), NOW()),
            (31, "","Teslui", NOW(), NOW()),
            (31, "","Tia Mare", NOW(), NOW()),
            (31, "","Topana", NOW(), NOW()),
            (31, "","Traian", NOW(), NOW()),
            (31, "","Tufeni", NOW(), NOW()),
            (31, "","Tatulesti", NOW(), NOW()),
            (31, "","Urzica", NOW(), NOW()),
            (31, "","Valea Mare", NOW(), NOW()),
            (31, "","Verguleasa", NOW(), NOW()),
            (31, "","Vitomiresti", NOW(), NOW()),
            (31, "","Visina", NOW(), NOW()),
            (31, "","Vladila", NOW(), NOW()),
            (31, "","Voineasa", NOW(), NOW()),
            (31, "","Vulpeni", NOW(), NOW()),
            (31, "","Vulturesti", NOW(), NOW()),
            (31, "","Valcele", NOW(), NOW()),
            (31, "","Vadastra", NOW(), NOW()),
            (31, "","Vadastrita", NOW(), NOW()),
            (31, "","Valeni", NOW(), NOW()),
            (31, "","Serbanesti", NOW(), NOW()),
            (31, "","Stefan cel Mare", NOW(), NOW()),
            (31, "Baldovinesti","Brosteni", NOW(), NOW()),
            (31, "Baldovinesti","Baleasa", NOW(), NOW()),
            (31, "Baldovinesti","Damburile", NOW(), NOW()),
            (31, "Baldovinesti","Gubandru", NOW(), NOW()),
            (31, "Baldovinesti","Gavanesti", NOW(), NOW()),
            (31, "Baldovinesti","Pietris", NOW(), NOW()),
            (31, "Bals","Corbeni", NOW(), NOW()),
            (31, "Bals","Romana", NOW(), NOW()),
            (31, "Bals","Teis", NOW(), NOW()),
            (31, "Barasti","Boroesti", NOW(), NOW()),
            (31, "Barasti","Barastii de Cepturi", NOW(), NOW()),
            (31, "Barasti","Barastii de Vede", NOW(), NOW()),
            (31, "Barasti","Ciocanesti", NOW(), NOW()),
            (31, "Barasti","Lazaresti", NOW(), NOW()),
            (31, "Barasti","Mereni", NOW(), NOW()),
            (31, "Barasti","Motoesti", NOW(), NOW()),
            (31, "Barasti","Popesti", NOW(), NOW()),
            (31, "Barza","Branet", NOW(), NOW()),
            (31, "Bobicesti","Bechet", NOW(), NOW()),
            (31, "Bobicesti","Belgun", NOW(), NOW()),
            (31, "Bobicesti","Chintesti", NOW(), NOW()),
            (31, "Bobicesti","Comanesti", NOW(), NOW()),
            (31, "Bobicesti","Govora", NOW(), NOW()),
            (31, "Bobicesti","Leotesti", NOW(), NOW()),
            (31, "Bobicesti","Mirila", NOW(), NOW()),
            (31, "Brancoveni","Margheni", NOW(), NOW()),
            (31, "Brancoveni","Ociogi", NOW(), NOW()),
            (31, "Brancoveni","Valeni", NOW(), NOW()),
            (31, "Brastavatu","Crusovu", NOW(), NOW()),
            (31, "Brebeni","Teiusu", NOW(), NOW()),
            (31, "Bucinisu","Bucinisu Mic", NOW(), NOW()),
            (31, "Carlogani","Beculesti", NOW(), NOW()),
            (31, "Carlogani","Cepari", NOW(), NOW()),
            (31, "Carlogani","Scorbura", NOW(), NOW()),
            (31, "Carlogani","Stupina", NOW(), NOW()),
            (31, "Cezieni","Bondrea", NOW(), NOW()),
            (31, "Cezieni","Corlatesti", NOW(), NOW()),
            (31, "Colonesti","Barasti", NOW(), NOW()),
            (31, "Colonesti","Batareni", NOW(), NOW()),
            (31, "Colonesti","Chelbesti", NOW(), NOW()),
            (31, "Colonesti","Carstani", NOW(), NOW()),
            (31, "Colonesti","Guesti", NOW(), NOW()),
            (31, "Colonesti","Maruntei", NOW(), NOW()),
            (31, "Colonesti","Navargeni", NOW(), NOW()),
            (31, "Colonesti","Vlaici", NOW(), NOW()),
            (31, "Corabia","Tudor Vladimirescu", NOW(), NOW()),
            (31, "Corabia","Vartopu", NOW(), NOW()),
            (31, "Corbu","Burdulesti", NOW(), NOW()),
            (31, "Corbu","Buzesti", NOW(), NOW()),
            (31, "Corbu","Ciuresti", NOW(), NOW()),
            (31, "Corbu","Milcoveni", NOW(), NOW()),
            (31, "Crampoia","Buta", NOW(), NOW()),
            (31, "Cungrea","Cepesti", NOW(), NOW()),
            (31, "Cungrea","Ibanesti", NOW(), NOW()),
            (31, "Cungrea","Miesti", NOW(), NOW()),
            (31, "Cungrea","Otestii de Jos", NOW(), NOW()),
            (31, "Cungrea","Otestii de Sus", NOW(), NOW()),
            (31, "Cungrea","Spataru", NOW(), NOW()),
            (31, "Curtisoara","Dobrotinet", NOW(), NOW()),
            (31, "Curtisoara","Linia din Vale", NOW(), NOW()),
            (31, "Curtisoara","Pietrisu", NOW(), NOW()),
            (31, "Curtisoara","Proaspeti", NOW(), NOW()),
            (31, "Curtisoara","Raitiu", NOW(), NOW()),
            (31, "Daneasa","Berindei", NOW(), NOW()),
            (31, "Daneasa","Cioflanu", NOW(), NOW()),
            (31, "Daneasa","Pestra", NOW(), NOW()),
            (31, "Daneasa","Zanoaga", NOW(), NOW()),
            (31, "Deveselu","Comanca", NOW(), NOW()),
            (31, "Dobretu","Curtisoara", NOW(), NOW()),
            (31, "Dobretu","Horezu", NOW(), NOW()),
            (31, "Dobrosloveni","Frasinetu", NOW(), NOW()),
            (31, "Dobrosloveni","Potopinu", NOW(), NOW()),
            (31, "Dobrosloveni","Resca", NOW(), NOW()),
            (31, "Dobrosloveni","Rescuta", NOW(), NOW()),
            (31, "Dobroteasa","Batia", NOW(), NOW()),
            (31, "Dobroteasa","Campu Mare", NOW(), NOW()),
            (31, "Dobroteasa","Vulpesti", NOW(), NOW()),
            (31, "Dobrun","Bobu", NOW(), NOW()),
            (31, "Dobrun","Chilii", NOW(), NOW()),
            (31, "Dobrun","Osica de Jos", NOW(), NOW()),
            (31, "Dobrun","Rosienii Mari", NOW(), NOW()),
            (31, "Dobrun","Rosienii Mici", NOW(), NOW()),
            (31, "Dobrun","Ulmet", NOW(), NOW()),
            (31, "Draganesti-Olt","Comani", NOW(), NOW()),
            (31, "Draghiceni","Grozavesti", NOW(), NOW()),
            (31, "Draghiceni","Liiceni", NOW(), NOW()),
            (31, "Fagetelu","Bagesti", NOW(), NOW()),
            (31, "Fagetelu","Chilia", NOW(), NOW()),
            (31, "Fagetelu","Gruiu", NOW(), NOW()),
            (31, "Fagetelu","Isaci", NOW(), NOW()),
            (31, "Fagetelu","Pielcani", NOW(), NOW()),
            (31, "Falcoiu","Cioroiasu", NOW(), NOW()),
            (31, "Falcoiu","Cioroiu", NOW(), NOW()),
            (31, "Farcasele","Farcasu de Jos", NOW(), NOW()),
            (31, "Farcasele","Ghimpati", NOW(), NOW()),
            (31, "Farcasele","Hotarani", NOW(), NOW()),
            (31, "Ganeasa","Dranovatu", NOW(), NOW()),
            (31, "Ganeasa","Gradistea", NOW(), NOW()),
            (31, "Ganeasa","Izvoru", NOW(), NOW()),
            (31, "Ganeasa","Oltisoru", NOW(), NOW()),
            (31, "Garcov","Ursa", NOW(), NOW()),
            (31, "Gostavatu","Slaveni", NOW(), NOW()),
            (31, "Gradinari","Petculesti", NOW(), NOW()),
            (31, "Gradinari","Runcu Mare", NOW(), NOW()),
            (31, "Gradinari","Satu Nou", NOW(), NOW()),
            (31, "Grojdibodu","Hotaru", NOW(), NOW()),
            (31, "Ianca","Potelu", NOW(), NOW()),
            (31, "Iancu Jianu","Dobriceni", NOW(), NOW()),
            (31, "Iancu Jianu","Preotesti", NOW(), NOW()),
            (31, "Icoana","Floru", NOW(), NOW()),
            (31, "Icoana","Ursoaia", NOW(), NOW()),
            (31, "Izvoarele","Alimanesti", NOW(), NOW()),
            (31, "Leleasca","Afumati", NOW(), NOW()),
            (31, "Leleasca","Greeresti", NOW(), NOW()),
            (31, "Leleasca","Mierlicesti", NOW(), NOW()),
            (31, "Leleasca","Tonesti", NOW(), NOW()),
            (31, "Leleasca","Tufaru", NOW(), NOW()),
            (31, "Leleasca","Ursi", NOW(), NOW()),
            (31, "Maruntei","Balanesti", NOW(), NOW()),
            (31, "Maruntei","Malu Rosu", NOW(), NOW()),
            (31, "Mihaesti","Busca", NOW(), NOW()),
            (31, "Milcov","Ipotesti", NOW(), NOW()),
            (31, "Milcov","Milcovu din Deal", NOW(), NOW()),
            (31, "Milcov","Milcovu din Vale", NOW(), NOW()),
            (31, "Milcov","Stejaru", NOW(), NOW()),
            (31, "Milcov","Ulmi", NOW(), NOW()),
            (31, "Morunglav","Barasti", NOW(), NOW()),
            (31, "Morunglav","Ghiosani", NOW(), NOW()),
            (31, "Morunglav","Morunesti", NOW(), NOW()),
            (31, "Morunglav","Poiana Mare", NOW(), NOW()),
            (31, "Movileni","Bacea", NOW(), NOW()),
            (31, "Nicolae Titulescu","Ghimpeteni", NOW(), NOW()),
            (31, "Nicolae Titulescu","Ghimpetenii Noi", NOW(), NOW()),
            (31, "Obarsia","Coteni", NOW(), NOW()),
            (31, "Obarsia","Campu Parului", NOW(), NOW()),
            (31, "Obarsia","Obarsia Noua", NOW(), NOW()),
            (31, "Obarsia","Tabonu", NOW(), NOW()),
            (31, "Oboga","Calui", NOW(), NOW()),
            (31, "Oboga","Gura Caluiu", NOW(), NOW()),
            (31, "Oporelu","Beria de Jos", NOW(), NOW()),
            (31, "Oporelu","Beria de Sus", NOW(), NOW()),
            (31, "Oporelu","Radesti", NOW(), NOW()),
            (31, "Optasi-Magura","Optasi", NOW(), NOW()),
            (31, "Optasi-Magura","Vitanesti", NOW(), NOW()),
            (31, "Orlea","Gura Padinii", NOW(), NOW()),
            (31, "Orlea","Orlea Noua", NOW(), NOW()),
            (31, "Orlea","Satu Nou", NOW(), NOW()),
            (31, "Osica De Sus","Greci", NOW(), NOW()),
            (31, "Osica De Sus","Ostrov", NOW(), NOW()),
            (31, "Osica De Sus","Peretu", NOW(), NOW()),
            (31, "Osica De Sus","Tomeni", NOW(), NOW()),
            (31, "Osica De Sus","Vladuleni", NOW(), NOW()),
            (31, "Parscoveni","Butoi", NOW(), NOW()),
            (31, "Parscoveni","Olari", NOW(), NOW()),
            (31, "Parscoveni","Parscoveni", NOW(), NOW()),
            (31, "Parscoveni","Soparlita", NOW(), NOW()),
            (31, "Perieti","Balteni", NOW(), NOW()),
            (31, "Perieti","Mierlestii de Sus", NOW(), NOW()),
            (31, "Perieti","Magura", NOW(), NOW()),
            (31, "Piatra-Olt","Bistrita Noua", NOW(), NOW()),
            (31, "Piatra-Olt","Criva de Jos", NOW(), NOW()),
            (31, "Piatra-Olt","Criva de Sus", NOW(), NOW()),
            (31, "Piatra-Olt","Enosesti", NOW(), NOW()),
            (31, "Piatra-Olt","Piatra", NOW(), NOW()),
            (31, "Plesoiu","Arcesti", NOW(), NOW()),
            (31, "Plesoiu","Arcesti Cot", NOW(), NOW()),
            (31, "Plesoiu","Cocorasti", NOW(), NOW()),
            (31, "Plesoiu","Doba", NOW(), NOW()),
            (31, "Plesoiu","Schitu din Deal", NOW(), NOW()),
            (31, "Plesoiu","Schitu din Vale", NOW(), NOW()),
            (31, "Poboru","Albesti", NOW(), NOW()),
            (31, "Poboru","Cornatelu", NOW(), NOW()),
            (31, "Poboru","Creti", NOW(), NOW()),
            (31, "Poboru","Seaca", NOW(), NOW()),
            (31, "Poboru","Surpeni", NOW(), NOW()),
            (31, "Potcoava","Potcoava Falcoeni", NOW(), NOW()),
            (31, "Potcoava","Sinesti", NOW(), NOW()),
            (31, "Potcoava","Trufinesti", NOW(), NOW()),
            (31, "Potcoava","Valea Merilor", NOW(), NOW()),
            (31, "Priseaca","Buicesti", NOW(), NOW()),
            (31, "Priseaca","Saltanesti", NOW(), NOW()),
            (31, "Radomiresti","Craciunei", NOW(), NOW()),
            (31, "Radomiresti","Calinesti", NOW(), NOW()),
            (31, "Radomiresti","Poiana", NOW(), NOW()),
            (31, "Redea","Redisoara", NOW(), NOW()),
            (31, "Redea","Valea Soarelui", NOW(), NOW()),
            (31, "Rusanesti","Jieni", NOW(), NOW()),
            (31, "Samburesti","Cerbeni", NOW(), NOW()),
            (31, "Samburesti","Ionicesti", NOW(), NOW()),
            (31, "Samburesti","Launele", NOW(), NOW()),
            (31, "Samburesti","Manulesti", NOW(), NOW()),
            (31, "Samburesti","Stanuleasa", NOW(), NOW()),
            (31, "Samburesti","Tonesti", NOW(), NOW()),
            (31, "Scarisoara","Plaviceni", NOW(), NOW()),
            (31, "Scarisoara","Rudari", NOW(), NOW()),
            (31, "Schitu","Catanele", NOW(), NOW()),
            (31, "Schitu","Greci", NOW(), NOW()),
            (31, "Schitu","Lisa", NOW(), NOW()),
            (31, "Schitu","Mosteni", NOW(), NOW()),
            (31, "Scornicesti","Bircii", NOW(), NOW()),
            (31, "Scornicesti","Baltati", NOW(), NOW()),
            (31, "Scornicesti","Chiteasca", NOW(), NOW()),
            (31, "Scornicesti","Constantinesti", NOW(), NOW()),
            (31, "Scornicesti","Jitaru", NOW(), NOW()),
            (31, "Scornicesti","Mihailesti Popesti", NOW(), NOW()),
            (31, "Scornicesti","Mogosesti", NOW(), NOW()),
            (31, "Scornicesti","Margineni Slobozia", NOW(), NOW()),
            (31, "Scornicesti","Negreni", NOW(), NOW()),
            (31, "Scornicesti","Piscani", NOW(), NOW()),
            (31, "Scornicesti","Rusciori", NOW(), NOW()),
            (31, "Scornicesti","Teius", NOW(), NOW()),
            (31, "Scornicesti","Suica", NOW(), NOW()),
            (31, "Serbanesti","Strugurelu", NOW(), NOW()),
            (31, "Serbanesti","Serbanestii de Sus", NOW(), NOW()),
            (31, "Slatina","Cireasov", NOW(), NOW()),
            (31, "Slatioara","Salcia", NOW(), NOW()),
            (31, "Spineni","Alunisu", NOW(), NOW()),
            (31, "Spineni","Cuza Voda", NOW(), NOW()),
            (31, "Spineni","Davidesti", NOW(), NOW()),
            (31, "Spineni","Optasani", NOW(), NOW()),
            (31, "Spineni","Profa", NOW(), NOW()),
            (31, "Spineni","Vineti", NOW(), NOW()),
            (31, "Sprancenata","Barsestii de Sus", NOW(), NOW()),
            (31, "Sprancenata","Frunzaru", NOW(), NOW()),
            (31, "Sprancenata","Uria", NOW(), NOW()),
            (31, "Stefan Cel Mare","Ianca Noua", NOW(), NOW()),
            (31, "Strejesti","Colibasi", NOW(), NOW()),
            (31, "Strejesti","Mamura", NOW(), NOW()),
            (31, "Strejesti","Strejestii de Sus", NOW(), NOW()),
            (31, "Studina","Arvateasca", NOW(), NOW()),
            (31, "Studina","Gradinile", NOW(), NOW()),
            (31, "Studina","Plaviceanca", NOW(), NOW()),
            (31, "Studina","Studinita", NOW(), NOW()),
            (31, "Tatulesti","Barbalai", NOW(), NOW()),
            (31, "Tatulesti","Lunca", NOW(), NOW()),
            (31, "Tatulesti","Mircesti", NOW(), NOW()),
            (31, "Tatulesti","Momaiu", NOW(), NOW()),
            (31, "Tatulesti","Magura", NOW(), NOW()),
            (31, "Teslui","Cherlestii Mosteni", NOW(), NOW()),
            (31, "Teslui","Cherlestii din Deal", NOW(), NOW()),
            (31, "Teslui","Comanita", NOW(), NOW()),
            (31, "Teslui","Corbu", NOW(), NOW()),
            (31, "Teslui","Deleni", NOW(), NOW()),
            (31, "Teslui","Schitu Deleni", NOW(), NOW()),
            (31, "Tia Mare","Doanca", NOW(), NOW()),
            (31, "Tia Mare","Potlogeni", NOW(), NOW()),
            (31, "Topana","Cioraca", NOW(), NOW()),
            (31, "Topana","Cojgarei", NOW(), NOW()),
            (31, "Topana","Candelesti", NOW(), NOW()),
            (31, "Topana","Ungureni", NOW(), NOW()),
            (31, "Tufeni","Barza", NOW(), NOW()),
            (31, "Tufeni","Stoborasti", NOW(), NOW()),
            (31, "Urzica","Stavaru", NOW(), NOW()),
            (31, "Vadastra","Visina Noua", NOW(), NOW()),
            (31, "Valcele","Barcanesti", NOW(), NOW()),
            (31, "Valcele","Valcelele de Sus", NOW(), NOW()),
            (31, "Valea Mare","Barca", NOW(), NOW()),
            (31, "Valea Mare","Recea", NOW(), NOW()),
            (31, "Valea Mare","Turia", NOW(), NOW()),
            (31, "Valea Mare","Zorleasca", NOW(), NOW()),
            (31, "Valeni","Mandra", NOW(), NOW()),
            (31, "Valeni","Popesti", NOW(), NOW()),
            (31, "Valeni","Tirisneag", NOW(), NOW()),
            (31, "Verguleasa","Cucueti", NOW(), NOW()),
            (31, "Verguleasa","Cazanesti", NOW(), NOW()),
            (31, "Verguleasa","Dumitresti", NOW(), NOW()),
            (31, "Verguleasa","Poganu", NOW(), NOW()),
            (31, "Verguleasa","Valea Fetei", NOW(), NOW()),
            (31, "Verguleasa","Vanesti", NOW(), NOW()),
            (31, "Vitomiresti","Bulimanu", NOW(), NOW()),
            (31, "Vitomiresti","Dejesti", NOW(), NOW()),
            (31, "Vitomiresti","Donesti", NOW(), NOW()),
            (31, "Vitomiresti","Stanuleasa", NOW(), NOW()),
            (31, "Vitomiresti","Trepteni", NOW(), NOW()),
            (31, "Vladila","Frasinet Gara", NOW(), NOW()),
            (31, "Vladila","Vladila Noua", NOW(), NOW()),
            (31, "Voineasa","Blaj", NOW(), NOW()),
            (31, "Voineasa","Margaritesti", NOW(), NOW()),
            (31, "Voineasa","Racovita", NOW(), NOW()),
            (31, "Voineasa","Rusanestii de Sus", NOW(), NOW()),
            (31, "Vulpeni","Cotorbesti", NOW(), NOW()),
            (31, "Vulpeni","Gropsani", NOW(), NOW()),
            (31, "Vulpeni","Mardale", NOW(), NOW()),
            (31, "Vulpeni","Pescaresti", NOW(), NOW()),
            (31, "Vulpeni","Plopsorelu", NOW(), NOW()),
            (31, "Vulpeni","Prisaca", NOW(), NOW()),
            (31, "Vulpeni","Simniceni", NOW(), NOW()),
            (31, "Vulpeni","Tabaci", NOW(), NOW()),
            (31, "Vulpeni","Valea Satului", NOW(), NOW()),
            (31, "Vulturesti","Dienci", NOW(), NOW()),
            (31, "Vulturesti","Valea lui Alb", NOW(), NOW()),
            (31, "Vulturesti","Vlangaresti", NOW(), NOW())
        ;';
        DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = "DELETE FROM localities WHERE county_id=31;";
        DB::connection()->getPdo()->exec($sql);
    }
}