<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForDB extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (16, "","Aninoasa", NOW(), NOW()),
            (16, "","Bezdead", NOW(), NOW()),
            (16, "","Bilciuresti", NOW(), NOW()),
            (16, "","Branistea", NOW(), NOW()),
            (16, "","Brezoaele", NOW(), NOW()),
            (16, "","Branesti", NOW(), NOW()),
            (16, "","Buciumeni", NOW(), NOW()),
            (16, "","Bucsani", NOW(), NOW()),
            (16, "","Butimanu", NOW(), NOW()),
            (16, "","Barbuletu", NOW(), NOW()),
            (16, "","Ciocanesti", NOW(), NOW()),
            (16, "","Cojasca", NOW(), NOW()),
            (16, "","Comisani", NOW(), NOW()),
            (16, "","Contesti", NOW(), NOW()),
            (16, "","Corbii Mari", NOW(), NOW()),
            (16, "","Cornesti", NOW(), NOW()),
            (16, "","Cornatelu", NOW(), NOW()),
            (16, "","Costestii din Vale", NOW(), NOW()),
            (16, "","Crevedia", NOW(), NOW()),
            (16, "","Dobra", NOW(), NOW()),
            (16, "","Doicesti", NOW(), NOW()),
            (16, "","Dragodana", NOW(), NOW()),
            (16, "","Dragomiresti", NOW(), NOW()),
            (16, "","Darmanesti", NOW(), NOW()),
            (16, "","Fieni", NOW(), NOW()),
            (16, "","Glodeni", NOW(), NOW()),
            (16, "","Gura Foii", NOW(), NOW()),
            (16, "","Gura Ocnitei", NOW(), NOW()),
            (16, "","Gura Sutii", NOW(), NOW()),
            (16, "","Gaesti", NOW(), NOW()),
            (16, "","Hulubesti", NOW(), NOW()),
            (16, "","I. L. Caragiale", NOW(), NOW()),
            (16, "","Lucieni", NOW(), NOW()),
            (16, "","Ludesti", NOW(), NOW()),
            (16, "","Lunguletu", NOW(), NOW()),
            (16, "","Malu cu Flori", NOW(), NOW()),
            (16, "","Mogosani", NOW(), NOW()),
            (16, "","Moreni", NOW(), NOW()),
            (16, "","Moroeni", NOW(), NOW()),
            (16, "","Morteni", NOW(), NOW()),
            (16, "","Motaieni", NOW(), NOW()),
            (16, "","Manesti", NOW(), NOW()),
            (16, "","Matasaru", NOW(), NOW()),
            (16, "","Niculesti", NOW(), NOW()),
            (16, "","Nucet", NOW(), NOW()),
            (16, "","Ocnita", NOW(), NOW()),
            (16, "","Odobesti", NOW(), NOW()),
            (16, "","Petresti", NOW(), NOW()),
            (16, "","Pietrosita", NOW(), NOW()),
            (16, "","Poiana", NOW(), NOW()),
            (16, "","Potlogi", NOW(), NOW()),
            (16, "","Produlesti", NOW(), NOW()),
            (16, "","Pucheni", NOW(), NOW()),
            (16, "","Pucioasa", NOW(), NOW()),
            (16, "","Runcu", NOW(), NOW()),
            (16, "","Racari", NOW(), NOW()),
            (16, "","Razvad", NOW(), NOW()),
            (16, "","Slobozia Moara", NOW(), NOW()),
            (16, "","Salcioara", NOW(), NOW()),
            (16, "","Titu", NOW(), NOW()),
            (16, "","Targoviste", NOW(), NOW()),
            (16, "","Tartasesti", NOW(), NOW()),
            (16, "","Tatarani", NOW(), NOW()),
            (16, "","Uliesti", NOW(), NOW()),
            (16, "","Ulmi", NOW(), NOW()),
            (16, "","Valea Mare", NOW(), NOW()),
            (16, "","Visina", NOW(), NOW()),
            (16, "","Visinesti", NOW(), NOW()),
            (16, "","Vladeni", NOW(), NOW()),
            (16, "","Voinesti", NOW(), NOW()),
            (16, "","Vulcana-Bai", NOW(), NOW()),
            (16, "","Vulcana-Pandele", NOW(), NOW()),
            (16, "","Vacaresti", NOW(), NOW()),
            (16, "","Selaru", NOW(), NOW()),
            (16, "","Sotanga", NOW(), NOW()),
            (16, "Aninoasa","Sateni", NOW(), NOW()),
            (16, "Aninoasa","Viforata", NOW(), NOW()),
            (16, "Baleni","Baleni-Romani", NOW(), NOW()),
            (16, "Baleni","Baleni-Sarbi", NOW(), NOW()),
            (16, "Barbuletu","Alunis", NOW(), NOW()),
            (16, "Barbuletu","Cetatuia", NOW(), NOW()),
            (16, "Barbuletu","Dupa Deal", NOW(), NOW()),
            (16, "Barbuletu","Gura Barbuletului", NOW(), NOW()),
            (16, "Barbuletu","Pietrari", NOW(), NOW()),
            (16, "Barbuletu","Rau Alb de Jos", NOW(), NOW()),
            (16, "Barbuletu","Rau Alb de Sus", NOW(), NOW()),
            (16, "Barbuletu","Valea", NOW(), NOW()),
            (16, "Barbuletu","Sipot", NOW(), NOW()),
            (16, "Bezdead","Brosteni", NOW(), NOW()),
            (16, "Bezdead","Costisata", NOW(), NOW()),
            (16, "Bezdead","Magura", NOW(), NOW()),
            (16, "Bezdead","Tunari", NOW(), NOW()),
            (16, "Bezdead","Valea Morii", NOW(), NOW()),
            (16, "Bilciuresti","Suseni Socetu", NOW(), NOW()),
            (16, "Branesti","Priboiu", NOW(), NOW()),
            (16, "Branistea","Dambovicioara", NOW(), NOW()),
            (16, "Branistea","Savesti", NOW(), NOW()),
            (16, "Brezoaele","Brezoaia", NOW(), NOW()),
            (16, "Buciumeni","Dealu Mare", NOW(), NOW()),
            (16, "Buciumeni","Valea Leurzii", NOW(), NOW()),
            (16, "Bucsani","Habeni", NOW(), NOW()),
            (16, "Bucsani","Racovita", NOW(), NOW()),
            (16, "Bucsani","Ratoaia", NOW(), NOW()),
            (16, "Butimanu","Barbuceanu", NOW(), NOW()),
            (16, "Butimanu","Lucianca", NOW(), NOW()),
            (16, "Butimanu","Ungureni", NOW(), NOW()),
            (16, "Candesti","Aninosani", NOW(), NOW()),
            (16, "Candesti","Candesti Deal", NOW(), NOW()),
            (16, "Candesti","Candesti-Vale", NOW(), NOW()),
            (16, "Candesti","Dragodanesti", NOW(), NOW()),
            (16, "Candesti","Valea Mare", NOW(), NOW()),
            (16, "Ciocanesti","Cretu", NOW(), NOW()),
            (16, "Ciocanesti","Decindea", NOW(), NOW()),
            (16, "Ciocanesti","Urziceanca", NOW(), NOW()),
            (16, "Ciocanesti","Vizuresti", NOW(), NOW()),
            (16, "Cobia","Blidari", NOW(), NOW()),
            (16, "Cobia","Cobiuta", NOW(), NOW()),
            (16, "Cobia","Craciunesti", NOW(), NOW()),
            (16, "Cobia","Calugareni", NOW(), NOW()),
            (16, "Cobia","Capsuna", NOW(), NOW()),
            (16, "Cobia","Frasin Deal", NOW(), NOW()),
            (16, "Cobia","Frasin Vale", NOW(), NOW()),
            (16, "Cobia","Gherghitesti", NOW(), NOW()),
            (16, "Cobia","Mislea", NOW(), NOW()),
            (16, "Cobia","Manastirea", NOW(), NOW()),
            (16, "Cojasca","Fantanele", NOW(), NOW()),
            (16, "Cojasca","Iazu", NOW(), NOW()),
            (16, "Comisani","Lazuri", NOW(), NOW()),
            (16, "Contesti","Boteni", NOW(), NOW()),
            (16, "Contesti","Balteni", NOW(), NOW()),
            (16, "Contesti","Crangasi", NOW(), NOW()),
            (16, "Contesti","Calugareni", NOW(), NOW()),
            (16, "Contesti","Gamanesti", NOW(), NOW()),
            (16, "Contesti","Helesteu", NOW(), NOW()),
            (16, "Contesti","Mereni", NOW(), NOW()),
            (16, "Corbii Mari","Baraceni", NOW(), NOW()),
            (16, "Corbii Mari","Grozavesti", NOW(), NOW()),
            (16, "Corbii Mari","Moara din Groapa", NOW(), NOW()),
            (16, "Corbii Mari","Petresti", NOW(), NOW()),
            (16, "Corbii Mari","Podu Corbencii", NOW(), NOW()),
            (16, "Corbii Mari","Satu Nou", NOW(), NOW()),
            (16, "Corbii Mari","Ungureni", NOW(), NOW()),
            (16, "Corbii Mari","Vadu Stanchii", NOW(), NOW()),
            (16, "Cornatelu","Alunisu", NOW(), NOW()),
            (16, "Cornatelu","Bolovani", NOW(), NOW()),
            (16, "Cornatelu","Corni", NOW(), NOW()),
            (16, "Cornatelu","Slobozia", NOW(), NOW()),
            (16, "Cornesti","Bujoreanca", NOW(), NOW()),
            (16, "Cornesti","Cristeasca", NOW(), NOW()),
            (16, "Cornesti","Crivatu", NOW(), NOW()),
            (16, "Cornesti","Catunu", NOW(), NOW()),
            (16, "Cornesti","Frasinu", NOW(), NOW()),
            (16, "Cornesti","Hodarasti", NOW(), NOW()),
            (16, "Cornesti","Ibrianu", NOW(), NOW()),
            (16, "Cornesti","Postarnacu", NOW(), NOW()),
            (16, "Cornesti","Ungureni", NOW(), NOW()),
            (16, "Costestii Din Vale","Maruntisu", NOW(), NOW()),
            (16, "Costestii Din Vale","Tomsani", NOW(), NOW()),
            (16, "Crangurile","Badulesti", NOW(), NOW()),
            (16, "Crangurile","Crangurile de Jos", NOW(), NOW()),
            (16, "Crangurile","Crangurile de Sus", NOW(), NOW()),
            (16, "Crangurile","Potlogeni Vale", NOW(), NOW()),
            (16, "Crangurile","Patroaia Deal", NOW(), NOW()),
            (16, "Crangurile","Patroaia Vale", NOW(), NOW()),
            (16, "Crangurile","Ratesti", NOW(), NOW()),
            (16, "Crangurile","Voia", NOW(), NOW()),
            (16, "Crevedia","Cocani", NOW(), NOW()),
            (16, "Crevedia","Darza", NOW(), NOW()),
            (16, "Crevedia","Manastirea", NOW(), NOW()),
            (16, "Crevedia","Samurcasi", NOW(), NOW()),
            (16, "Darmanesti","Marginenii de Sus", NOW(), NOW()),
            (16, "Dobra","Marcesti", NOW(), NOW()),
            (16, "Dragodana","Boboci", NOW(), NOW()),
            (16, "Dragodana","Burduca", NOW(), NOW()),
            (16, "Dragodana","Cuparu", NOW(), NOW()),
            (16, "Dragodana","Picior de Munte", NOW(), NOW()),
            (16, "Dragodana","Padureni", NOW(), NOW()),
            (16, "Dragodana","Straosti", NOW(), NOW()),
            (16, "Dragomiresti","Decindeni", NOW(), NOW()),
            (16, "Dragomiresti","Geangoesti", NOW(), NOW()),
            (16, "Dragomiresti","Mogosesti", NOW(), NOW()),
            (16, "Dragomiresti","Rancaciov", NOW(), NOW()),
            (16, "Dragomiresti","Ungureni", NOW(), NOW()),
            (16, "Fieni","Berevoesti", NOW(), NOW()),
            (16, "Fieni","Costesti", NOW(), NOW()),
            (16, "Finta","Bechinesti", NOW(), NOW()),
            (16, "Finta","Finta Mare", NOW(), NOW()),
            (16, "Finta","Finta Veche", NOW(), NOW()),
            (16, "Finta","Gheboaia", NOW(), NOW()),
            (16, "Glodeni","Gusoiu", NOW(), NOW()),
            (16, "Glodeni","Livezile", NOW(), NOW()),
            (16, "Glodeni","Laculete", NOW(), NOW()),
            (16, "Glodeni","Malu Mierii", NOW(), NOW()),
            (16, "Glodeni","Schela", NOW(), NOW()),
            (16, "Gura Foii","Bumbuia", NOW(), NOW()),
            (16, "Gura Foii","Catanele", NOW(), NOW()),
            (16, "Gura Foii","Fagetu", NOW(), NOW()),
            (16, "Gura Ocnitei","Adanca", NOW(), NOW()),
            (16, "Gura Ocnitei","Ochiuri", NOW(), NOW()),
            (16, "Gura Ocnitei","Sacueni", NOW(), NOW()),
            (16, "Gura Sutii","Sperieteni", NOW(), NOW()),
            (16, "Hulubesti","Butoiu de Jos", NOW(), NOW()),
            (16, "Hulubesti","Butoiu de Sus", NOW(), NOW()),
            (16, "Hulubesti","Magura", NOW(), NOW()),
            (16, "Hulubesti","Valea Dadei", NOW(), NOW()),
            (16, "I. L. Caragiale","Ghirdoveni", NOW(), NOW()),
            (16, "I. L. Caragiale","Mija", NOW(), NOW()),
            (16, "Iedera","Colibasi", NOW(), NOW()),
            (16, "Iedera","Cricovu Dulce", NOW(), NOW()),
            (16, "Iedera","Iedera de Jos", NOW(), NOW()),
            (16, "Iedera","Iedera de Sus", NOW(), NOW()),
            (16, "Lucieni","Olteni", NOW(), NOW()),
            (16, "Lucieni","Raciu", NOW(), NOW()),
            (16, "Lucieni","Silistea", NOW(), NOW()),
            (16, "Lucieni","Suta Seaca", NOW(), NOW()),
            (16, "Ludesti","Milosari", NOW(), NOW()),
            (16, "Ludesti","Potocelu", NOW(), NOW()),
            (16, "Ludesti","Scheiu de Jos", NOW(), NOW()),
            (16, "Ludesti","Scheiu de Sus", NOW(), NOW()),
            (16, "Ludesti","Telesti", NOW(), NOW()),
            (16, "Lunguletu","Oreasca", NOW(), NOW()),
            (16, "Lunguletu","Serdanu", NOW(), NOW()),
            (16, "Malu Cu Flori","Capu Coastei", NOW(), NOW()),
            (16, "Malu Cu Flori","Copaceni", NOW(), NOW()),
            (16, "Malu Cu Flori","Miclosanii Mari", NOW(), NOW()),
            (16, "Malu Cu Flori","Miclosanii Mici", NOW(), NOW()),
            (16, "Manesti","Dragaesti Pamanteni", NOW(), NOW()),
            (16, "Manesti","Dragaesti Ungureni", NOW(), NOW()),
            (16, "Matasaru","Cretulesti", NOW(), NOW()),
            (16, "Matasaru","Odaia Turcului", NOW(), NOW()),
            (16, "Matasaru","Poroinica", NOW(), NOW()),
            (16, "Matasaru","Putu cu Salcie", NOW(), NOW()),
            (16, "Matasaru","Salcioara", NOW(), NOW()),
            (16, "Matasaru","Tetcoiu", NOW(), NOW()),
            (16, "Mogosani","Chirca", NOW(), NOW()),
            (16, "Mogosani","Cojocaru", NOW(), NOW()),
            (16, "Mogosani","Merii", NOW(), NOW()),
            (16, "Mogosani","Zavoiu", NOW(), NOW()),
            (16, "Moroeni","Dobresti", NOW(), NOW()),
            (16, "Moroeni","Glod", NOW(), NOW()),
            (16, "Moroeni","Lunca", NOW(), NOW()),
            (16, "Moroeni","Muscel", NOW(), NOW()),
            (16, "Moroeni","Pucheni", NOW(), NOW()),
            (16, "Morteni","Neajlovu", NOW(), NOW()),
            (16, "Motaieni","Cucuteni", NOW(), NOW()),
            (16, "Niculesti","Ciocanari", NOW(), NOW()),
            (16, "Niculesti","Movila", NOW(), NOW()),
            (16, "Nucet","Cazaci", NOW(), NOW()),
            (16, "Nucet","Ilfoveni", NOW(), NOW()),
            (16, "Odobesti","Brancoveanu", NOW(), NOW()),
            (16, "Odobesti","Crovu", NOW(), NOW()),
            (16, "Odobesti","Miulesti", NOW(), NOW()),
            (16, "Odobesti","Zidurile", NOW(), NOW()),
            (16, "Petresti","Coada Izvorului", NOW(), NOW()),
            (16, "Petresti","Gherghesti", NOW(), NOW()),
            (16, "Petresti","Greci", NOW(), NOW()),
            (16, "Petresti","Ionesti", NOW(), NOW()),
            (16, "Petresti","Potlogeni-Deal", NOW(), NOW()),
            (16, "Petresti","Puntea de Greci", NOW(), NOW()),
            (16, "Pietrosita","Dealu Frumos", NOW(), NOW()),
            (16, "Poiana","Poienita", NOW(), NOW()),
            (16, "Potlogi","Pitaru", NOW(), NOW()),
            (16, "Potlogi","Podu Cristinii", NOW(), NOW()),
            (16, "Potlogi","Romanesti", NOW(), NOW()),
            (16, "Potlogi","Vlasceni", NOW(), NOW()),
            (16, "Produlesti","Brosteni", NOW(), NOW()),
            (16, "Produlesti","Costestii din Deal", NOW(), NOW()),
            (16, "Pucheni","Bradatel", NOW(), NOW()),
            (16, "Pucheni","Meisoare", NOW(), NOW()),
            (16, "Pucheni","Valea Larga", NOW(), NOW()),
            (16, "Pucheni","Varfureni", NOW(), NOW()),
            (16, "Pucioasa","Bela", NOW(), NOW()),
            (16, "Pucioasa","Diaconesti", NOW(), NOW()),
            (16, "Pucioasa","Glodeni", NOW(), NOW()),
            (16, "Pucioasa","Malurile", NOW(), NOW()),
            (16, "Pucioasa","Miculesti", NOW(), NOW()),
            (16, "Pucioasa","Pucioasa-Sat", NOW(), NOW()),
            (16, "Racari","Balanesti", NOW(), NOW()),
            (16, "Racari","Colacu", NOW(), NOW()),
            (16, "Racari","Ghergani", NOW(), NOW()),
            (16, "Racari","Ghimpati", NOW(), NOW()),
            (16, "Racari","Mavrodin", NOW(), NOW()),
            (16, "Racari","Stanesti", NOW(), NOW()),
            (16, "Racari","Sabiesti", NOW(), NOW()),
            (16, "Razvad","Gorgota", NOW(), NOW()),
            (16, "Razvad","Valea Voivozilor", NOW(), NOW()),
            (16, "Runcu","Brebu", NOW(), NOW()),
            (16, "Runcu","Badeni", NOW(), NOW()),
            (16, "Runcu","Ferestre", NOW(), NOW()),
            (16, "Runcu","Piatra", NOW(), NOW()),
            (16, "Runcu","Silistea", NOW(), NOW()),
            (16, "Salcioara","Banesti", NOW(), NOW()),
            (16, "Salcioara","Cuza Voda", NOW(), NOW()),
            (16, "Salcioara","Catunu", NOW(), NOW()),
            (16, "Salcioara","Ghinesti", NOW(), NOW()),
            (16, "Salcioara","Mircea Voda", NOW(), NOW()),
            (16, "Salcioara","Moara Noua", NOW(), NOW()),
            (16, "Salcioara","Movila", NOW(), NOW()),
            (16, "Salcioara","Podu Rizii", NOW(), NOW()),
            (16, "Selaru","Fierbinti", NOW(), NOW()),
            (16, "Selaru","Glogoveanu", NOW(), NOW()),
            (16, "Sotanga","Teis", NOW(), NOW()),
            (16, "Targoviste","Priseaca", NOW(), NOW()),
            (16, "Tartasesti","Baldana", NOW(), NOW()),
            (16, "Tartasesti","Gulia", NOW(), NOW()),
            (16, "Tatarani","Caprioru", NOW(), NOW()),
            (16, "Tatarani","Gheboieni", NOW(), NOW()),
            (16, "Tatarani","Priboiu", NOW(), NOW()),
            (16, "Titu","Fusea", NOW(), NOW()),
            (16, "Titu","Hagioaica", NOW(), NOW()),
            (16, "Titu","Mereni", NOW(), NOW()),
            (16, "Titu","Plopu", NOW(), NOW()),
            (16, "Titu","Salcuta", NOW(), NOW()),
            (16, "Uliesti","Croitori", NOW(), NOW()),
            (16, "Uliesti","Hanu lui Pala", NOW(), NOW()),
            (16, "Uliesti","Jugureni", NOW(), NOW()),
            (16, "Uliesti","Manastioara", NOW(), NOW()),
            (16, "Uliesti","Olteni", NOW(), NOW()),
            (16, "Uliesti","Ragu", NOW(), NOW()),
            (16, "Uliesti","Stavropolia", NOW(), NOW()),
            (16, "Ulmi","Colanu", NOW(), NOW()),
            (16, "Ulmi","Dimoiu", NOW(), NOW()),
            (16, "Ulmi","Dumbrava", NOW(), NOW()),
            (16, "Ulmi","Matraca", NOW(), NOW()),
            (16, "Ulmi","Nisipurile", NOW(), NOW()),
            (16, "Ulmi","Udresti", NOW(), NOW()),
            (16, "Ulmi","Viisoara", NOW(), NOW()),
            (16, "Vacaresti","Bratestii de Jos", NOW(), NOW()),
            (16, "Vacaresti","Bungetu", NOW(), NOW()),
            (16, "Vacaresti","Persinari", NOW(), NOW()),
            (16, "Valea Lunga","Bacesti", NOW(), NOW()),
            (16, "Valea Lunga","Izvoru", NOW(), NOW()),
            (16, "Valea Lunga","Mosia Mica", NOW(), NOW()),
            (16, "Valea Lunga","Valea Lunga Gorgota", NOW(), NOW()),
            (16, "Valea Lunga","Valea Lunga Ogrea", NOW(), NOW()),
            (16, "Valea Lunga","Valea Lunga-Cricov", NOW(), NOW()),
            (16, "Valea Lunga","Valea Mare", NOW(), NOW()),
            (16, "Valea Lunga","Valea lui Dan", NOW(), NOW()),
            (16, "Valea Lunga","Serbaneasa", NOW(), NOW()),
            (16, "Valea Lunga","Stubeie Tisa", NOW(), NOW()),
            (16, "Valea Mare","Feteni", NOW(), NOW()),
            (16, "Valea Mare","Garleni", NOW(), NOW()),
            (16, "Valea Mare","Livezile", NOW(), NOW()),
            (16, "Valea Mare","Saru", NOW(), NOW()),
            (16, "Valea Mare","Stratonesti", NOW(), NOW()),
            (16, "Valea Mare","Valea Caselor", NOW(), NOW()),
            (16, "Valeni-Dimbovita","Mesteacan", NOW(), NOW()),
            (16, "Valeni-Dimbovita","Valeni-Dambovita", NOW(), NOW()),
            (16, "Virfuri","Cojoiu", NOW(), NOW()),
            (16, "Virfuri","Carlanesti", NOW(), NOW()),
            (16, "Virfuri","Merisoru", NOW(), NOW()),
            (16, "Virfuri","Statesti", NOW(), NOW()),
            (16, "Virfuri","Ulmetu", NOW(), NOW()),
            (16, "Virfuri","Varfuri", NOW(), NOW()),
            (16, "Virfuri","Suvita", NOW(), NOW()),
            (16, "Visina","Brosteni", NOW(), NOW()),
            (16, "Visina","Izvoru", NOW(), NOW()),
            (16, "Visina","Rascaeti", NOW(), NOW()),
            (16, "Visina","Vultureanca", NOW(), NOW()),
            (16, "Visinesti","Dospinesti", NOW(), NOW()),
            (16, "Visinesti","Sultanu", NOW(), NOW()),
            (16, "Visinesti","Urseiu", NOW(), NOW()),
            (16, "Voinesti","Gemenea Bratulesti", NOW(), NOW()),
            (16, "Voinesti","Izvoarele", NOW(), NOW()),
            (16, "Voinesti","Lunca", NOW(), NOW()),
            (16, "Voinesti","Manga", NOW(), NOW()),
            (16, "Voinesti","Manjina", NOW(), NOW()),
            (16, "Voinesti","Oncesti", NOW(), NOW()),
            (16, "Voinesti","Suduleni", NOW(), NOW()),
            (16, "Vulcana-Bai","Nicolaesti", NOW(), NOW()),
            (16, "Vulcana-Bai","Vulcana de Sus", NOW(), NOW()),
            (16, "Vulcana-Pandele","Gura Vulcanei", NOW(), NOW()),
            (16, "Vulcana-Pandele","Laculete-Gara", NOW(), NOW()),
            (16, "Vulcana-Pandele","Toculesti", NOW(), NOW())
        ;';
        DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {

        $sql = "DELETE FROM localities WHERE county_id=16;";
        DB::connection()->getPdo()->exec($sql);
    }
}
