<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForVS extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (40, "","Albesti", NOW(), NOW()),
            (40, "","Alexandru Vlahuta", NOW(), NOW()),
            (40, "","Arsura", NOW(), NOW()),
            (40, "","Banca", NOW(), NOW()),
            (40, "","Berezeni", NOW(), NOW()),
            (40, "","Blagesti", NOW(), NOW()),
            (40, "","Bogdana", NOW(), NOW()),
            (40, "","Bogdanesti", NOW(), NOW()),
            (40, "","Bogdanita", NOW(), NOW()),
            (40, "","Botesti", NOW(), NOW()),
            (40, "","Bacani", NOW(), NOW()),
            (40, "","Bacesti", NOW(), NOW()),
            (40, "","Balteni", NOW(), NOW()),
            (40, "","Codaesti", NOW(), NOW()),
            (40, "","Coroiesti", NOW(), NOW()),
            (40, "","Costesti", NOW(), NOW()),
            (40, "","Cretesti", NOW(), NOW()),
            (40, "","Deleni", NOW(), NOW()),
            (40, "","Delesti", NOW(), NOW()),
            (40, "","Dragomiresti", NOW(), NOW()),
            (40, "","Dranceni", NOW(), NOW()),
            (40, "","Dumesti", NOW(), NOW()),
            (40, "","Danesti", NOW(), NOW()),
            (40, "","Epureni", NOW(), NOW()),
            (40, "","Falciu", NOW(), NOW()),
            (40, "","Gherghesti", NOW(), NOW()),
            (40, "","Grivita", NOW(), NOW()),
            (40, "","Garceni", NOW(), NOW()),
            (40, "","Gagesti", NOW(), NOW()),
            (40, "","Hoceni", NOW(), NOW()),
            (40, "","Husi", NOW(), NOW()),
            (40, "","Iana", NOW(), NOW()),
            (40, "","Ibanesti", NOW(), NOW()),
            (40, "","Ivesti", NOW(), NOW()),
            (40, "","Ivanesti", NOW(), NOW()),
            (40, "","Laza", NOW(), NOW()),
            (40, "","Lipovat", NOW(), NOW()),
            (40, "","Lunca Banului", NOW(), NOW()),
            (40, "","Miclesti", NOW(), NOW()),
            (40, "","Muntenii de Jos", NOW(), NOW()),
            (40, "","Murgeni", NOW(), NOW()),
            (40, "","Malusteni", NOW(), NOW()),
            (40, "","Negresti", NOW(), NOW()),
            (40, "","Oltenesti", NOW(), NOW()),
            (40, "","Osesti", NOW(), NOW()),
            (40, "","Perieni", NOW(), NOW()),
            (40, "","Pogana", NOW(), NOW()),
            (40, "","Poienesti", NOW(), NOW()),
            (40, "","Puiesti", NOW(), NOW()),
            (40, "","Pungesti", NOW(), NOW()),
            (40, "","Padureni", NOW(), NOW()),
            (40, "","Rebricea", NOW(), NOW()),
            (40, "","Rosiesti", NOW(), NOW()),
            (40, "","Solesti", NOW(), NOW()),
            (40, "","Stanilesti", NOW(), NOW()),
            (40, "","Tanacu", NOW(), NOW()),
            (40, "","Todiresti", NOW(), NOW()),
            (40, "","Tutova", NOW(), NOW()),
            (40, "","Tacuta", NOW(), NOW()),
            (40, "","Tatarani", NOW(), NOW()),
            (40, "","Vaslui", NOW(), NOW()),
            (40, "","Vetrisoaia", NOW(), NOW()),
            (40, "","Viisoara", NOW(), NOW()),
            (40, "","Vinderei", NOW(), NOW()),
            (40, "","Voinesti", NOW(), NOW()),
            (40, "","Vulturesti", NOW(), NOW()),
            (40, "","Vutcani", NOW(), NOW()),
            (40, "","Valeni", NOW(), NOW()),
            (40, "","Zorleni", NOW(), NOW()),
            (40, "","Zapodeni", NOW(), NOW()),
            (40, "","Stefan cel Mare", NOW(), NOW()),
            (40, "","Suletea", NOW(), NOW()),
            (40, "Albesti","Corni-Albesti", NOW(), NOW()),
            (40, "Albesti","Crasna", NOW(), NOW()),
            (40, "Albesti","Gura Albesti", NOW(), NOW()),
            (40, "Alexandru Vlahuta","Buda", NOW(), NOW()),
            (40, "Alexandru Vlahuta","Ghicani", NOW(), NOW()),
            (40, "Alexandru Vlahuta","Morareni", NOW(), NOW()),
            (40, "Arsura","Fundatura", NOW(), NOW()),
            (40, "Arsura","Mihail Kogalniceanu", NOW(), NOW()),
            (40, "Arsura","Pahnesti", NOW(), NOW()),
            (40, "Bacani","Baltateni", NOW(), NOW()),
            (40, "Bacani","Drujesti", NOW(), NOW()),
            (40, "Bacani","Suseni", NOW(), NOW()),
            (40, "Bacani","Vulpaseni", NOW(), NOW()),
            (40, "Bacesti","Armaseni", NOW(), NOW()),
            (40, "Bacesti","Babusa", NOW(), NOW()),
            (40, "Bacesti","Paltinis", NOW(), NOW()),
            (40, "Bacesti","Vovriesti", NOW(), NOW()),
            (40, "Bacesti","Tibanestii Buhlii", NOW(), NOW()),
            (40, "Balteni","Balteni-Deal", NOW(), NOW()),
            (40, "Balteni","Chetresti", NOW(), NOW()),
            (40, "Banca","1 Decembrie", NOW(), NOW()),
            (40, "Banca","Gara Banca", NOW(), NOW()),
            (40, "Banca","Ghermanesti", NOW(), NOW()),
            (40, "Banca","Miclesti", NOW(), NOW()),
            (40, "Banca","Mitoc", NOW(), NOW()),
            (40, "Banca","Satu Nou", NOW(), NOW()),
            (40, "Banca","Stoisesti", NOW(), NOW()),
            (40, "Banca","Stramtura-Mitoc", NOW(), NOW()),
            (40, "Banca","Sarbi", NOW(), NOW()),
            (40, "Banca","Salcioara", NOW(), NOW()),
            (40, "Banca","Tifu", NOW(), NOW()),
            (40, "Berezeni","Musata", NOW(), NOW()),
            (40, "Berezeni","Ranceni", NOW(), NOW()),
            (40, "Berezeni","Satu Nou", NOW(), NOW()),
            (40, "Berezeni","Stuhulet", NOW(), NOW()),
            (40, "Birlad","Barlad", NOW(), NOW()),
            (40, "Blagesti","Igesti", NOW(), NOW()),
            (40, "Blagesti","Sipeni", NOW(), NOW()),
            (40, "Bogdana","Arsita", NOW(), NOW()),
            (40, "Bogdana","Fantana Blanarului", NOW(), NOW()),
            (40, "Bogdana","Gavanu", NOW(), NOW()),
            (40, "Bogdana","Lacu Babei", NOW(), NOW()),
            (40, "Bogdana","Plopeni", NOW(), NOW()),
            (40, "Bogdana","Similisoara", NOW(), NOW()),
            (40, "Bogdana","Suceveni", NOW(), NOW()),
            (40, "Bogdana","Verdes", NOW(), NOW()),
            (40, "Bogdanesti","Buda", NOW(), NOW()),
            (40, "Bogdanesti","Horoiata", NOW(), NOW()),
            (40, "Bogdanesti","Hupca", NOW(), NOW()),
            (40, "Bogdanesti","Orgoiesti", NOW(), NOW()),
            (40, "Bogdanesti","Ulea", NOW(), NOW()),
            (40, "Bogdanesti","Untesti", NOW(), NOW()),
            (40, "Bogdanesti","Visinari", NOW(), NOW()),
            (40, "Bogdanesti","Vladesti", NOW(), NOW()),
            (40, "Bogdanita","Cepesti", NOW(), NOW()),
            (40, "Bogdanita","Coroiesti", NOW(), NOW()),
            (40, "Bogdanita","Cartibasi", NOW(), NOW()),
            (40, "Bogdanita","Radaesti", NOW(), NOW()),
            (40, "Bogdanita","Schitu", NOW(), NOW()),
            (40, "Bogdanita","Tunsesti", NOW(), NOW()),
            (40, "Botesti","Gugesti", NOW(), NOW()),
            (40, "Botesti","Ganesti", NOW(), NOW()),
            (40, "Botesti","Talpigeni", NOW(), NOW()),
            (40, "Bunesti-Averesti","Armaseni", NOW(), NOW()),
            (40, "Bunesti-Averesti","Averesti", NOW(), NOW()),
            (40, "Bunesti-Averesti","Bunesti", NOW(), NOW()),
            (40, "Bunesti-Averesti","Plopi", NOW(), NOW()),
            (40, "Bunesti-Averesti","Podu Oprii", NOW(), NOW()),
            (40, "Bunesti-Averesti","Rosiori", NOW(), NOW()),
            (40, "Bunesti-Averesti","Tabalaesti", NOW(), NOW()),
            (40, "Codaesti","Ghergheleu", NOW(), NOW()),
            (40, "Codaesti","Pribesti", NOW(), NOW()),
            (40, "Codaesti","Rediu Galian", NOW(), NOW()),
            (40, "Coroiesti","Chilieni", NOW(), NOW()),
            (40, "Coroiesti","Coroiestii de Sus", NOW(), NOW()),
            (40, "Coroiesti","Hreasca", NOW(), NOW()),
            (40, "Coroiesti","Mireni", NOW(), NOW()),
            (40, "Coroiesti","Movileni", NOW(), NOW()),
            (40, "Coroiesti","Pacuraresti", NOW(), NOW()),
            (40, "Costesti","Chitcani", NOW(), NOW()),
            (40, "Costesti","Dinga", NOW(), NOW()),
            (40, "Costesti","Puntiseni", NOW(), NOW()),
            (40, "Costesti","Parvesti", NOW(), NOW()),
            (40, "Costesti","Radesti", NOW(), NOW()),
            (40, "Cretesti","Budesti", NOW(), NOW()),
            (40, "Cretesti","Cretestii de Sus", NOW(), NOW()),
            (40, "Cretesti","Satu Nou", NOW(), NOW()),
            (40, "Danesti","Bereasa", NOW(), NOW()),
            (40, "Danesti","Botoaia", NOW(), NOW()),
            (40, "Danesti","Emil Racovita", NOW(), NOW()),
            (40, "Danesti","Rascani", NOW(), NOW()),
            (40, "Danesti","Tatarani", NOW(), NOW()),
            (40, "Deleni","Bulboaca", NOW(), NOW()),
            (40, "Deleni","Moreni", NOW(), NOW()),
            (40, "Deleni","Zizinca", NOW(), NOW()),
            (40, "Delesti","Albesti", NOW(), NOW()),
            (40, "Delesti","Balesti", NOW(), NOW()),
            (40, "Delesti","Cozmesti", NOW(), NOW()),
            (40, "Delesti","Fundatura", NOW(), NOW()),
            (40, "Delesti","Fastaci", NOW(), NOW()),
            (40, "Delesti","Hordilesti", NOW(), NOW()),
            (40, "Delesti","Harsova", NOW(), NOW()),
            (40, "Delesti","Manastirea", NOW(), NOW()),
            (40, "Delesti","Raduiesti", NOW(), NOW()),
            (40, "Dimitrie Cantemir","Grumezoaia", NOW(), NOW()),
            (40, "Dimitrie Cantemir","Gusitei", NOW(), NOW()),
            (40, "Dimitrie Cantemir","Hurdugi", NOW(), NOW()),
            (40, "Dimitrie Cantemir","Plotonesti", NOW(), NOW()),
            (40, "Dimitrie Cantemir","Urlati", NOW(), NOW()),
            (40, "Dragomiresti","Belzeni", NOW(), NOW()),
            (40, "Dragomiresti","Botoi", NOW(), NOW()),
            (40, "Dragomiresti","Babuta", NOW(), NOW()),
            (40, "Dragomiresti","Ciuperca", NOW(), NOW()),
            (40, "Dragomiresti","Doagele", NOW(), NOW()),
            (40, "Dragomiresti","Poiana Pietrei", NOW(), NOW()),
            (40, "Dragomiresti","Popesti", NOW(), NOW()),
            (40, "Dragomiresti","Radeni", NOW(), NOW()),
            (40, "Dragomiresti","Semenea", NOW(), NOW()),
            (40, "Dragomiresti","Tulesti", NOW(), NOW()),
            (40, "Dragomiresti","Vladia", NOW(), NOW()),
            (40, "Dranceni","Albita", NOW(), NOW()),
            (40, "Dranceni","Baile Dranceni", NOW(), NOW()),
            (40, "Dranceni","Ghermanesti", NOW(), NOW()),
            (40, "Dranceni","Rasesti", NOW(), NOW()),
            (40, "Dranceni","Soparleni", NOW(), NOW()),
            (40, "Duda-Epureni","Bobesti", NOW(), NOW()),
            (40, "Duda-Epureni","Duda", NOW(), NOW()),
            (40, "Duda-Epureni","Epureni", NOW(), NOW()),
            (40, "Duda-Epureni","Valea Grecului", NOW(), NOW()),
            (40, "Dumesti","Dumestii Vechi", NOW(), NOW()),
            (40, "Dumesti","Schinetea", NOW(), NOW()),
            (40, "Dumesti","Valea Mare", NOW(), NOW()),
            (40, "Epureni","Bursuci", NOW(), NOW()),
            (40, "Epureni","Barlalesti", NOW(), NOW()),
            (40, "Epureni","Horga", NOW(), NOW()),
            (40, "Falciu","Bogdanesti", NOW(), NOW()),
            (40, "Falciu","Bozia", NOW(), NOW()),
            (40, "Falciu","Copaceana", NOW(), NOW()),
            (40, "Falciu","Odaia Bogdana", NOW(), NOW()),
            (40, "Falciu","Ranzesti", NOW(), NOW()),
            (40, "Gagesti","Giurcani", NOW(), NOW()),
            (40, "Gagesti","Peicani", NOW(), NOW()),
            (40, "Gagesti","Popeni", NOW(), NOW()),
            (40, "Gagesti","Tupilati", NOW(), NOW()),
            (40, "Garceni","Dumbraveni", NOW(), NOW()),
            (40, "Garceni","Racova", NOW(), NOW()),
            (40, "Garceni","Racovita", NOW(), NOW()),
            (40, "Garceni","Slobozia", NOW(), NOW()),
            (40, "Garceni","Trohan", NOW(), NOW()),
            (40, "Gherghesti","Chetrosu", NOW(), NOW()),
            (40, "Gherghesti","Corodesti", NOW(), NOW()),
            (40, "Gherghesti","Dragomanesti", NOW(), NOW()),
            (40, "Gherghesti","Draxeni", NOW(), NOW()),
            (40, "Gherghesti","Lazu", NOW(), NOW()),
            (40, "Gherghesti","Lunca", NOW(), NOW()),
            (40, "Gherghesti","Soci", NOW(), NOW()),
            (40, "Gherghesti","Valea Lupului", NOW(), NOW()),
            (40, "Grivita","Fruntiseni", NOW(), NOW()),
            (40, "Grivita","Grajdeni", NOW(), NOW()),
            (40, "Grivita","Odaia Bursucani", NOW(), NOW()),
            (40, "Grivita","Trestiana", NOW(), NOW()),
            (40, "Hoceni","Barbosi", NOW(), NOW()),
            (40, "Hoceni","Deleni", NOW(), NOW()),
            (40, "Hoceni","Oteleni", NOW(), NOW()),
            (40, "Hoceni","Rediu", NOW(), NOW()),
            (40, "Hoceni","Tomsa", NOW(), NOW()),
            (40, "Hoceni","Siscani", NOW(), NOW()),
            (40, "Iana","Halaresti", NOW(), NOW()),
            (40, "Iana","Recea", NOW(), NOW()),
            (40, "Iana","Silistea", NOW(), NOW()),
            (40, "Iana","Vadurile", NOW(), NOW()),
            (40, "Ibanesti","Manzati", NOW(), NOW()),
            (40, "Ibanesti","Putu Olarului", NOW(), NOW()),
            (40, "Ivanesti","Albina", NOW(), NOW()),
            (40, "Ivanesti","Blesca", NOW(), NOW()),
            (40, "Ivanesti","Brosteni", NOW(), NOW()),
            (40, "Ivanesti","Buscata", NOW(), NOW()),
            (40, "Ivanesti","Cosca", NOW(), NOW()),
            (40, "Ivanesti","Cosesti", NOW(), NOW()),
            (40, "Ivanesti","Fundatura Mare", NOW(), NOW()),
            (40, "Ivanesti","Fundatura Mica", NOW(), NOW()),
            (40, "Ivanesti","Harsoveni", NOW(), NOW()),
            (40, "Ivanesti","Iezerel", NOW(), NOW()),
            (40, "Ivanesti","Ursoaia", NOW(), NOW()),
            (40, "Ivanesti","Valea Mare", NOW(), NOW()),
            (40, "Ivanesti","Valea Oanei", NOW(), NOW()),
            (40, "Ivesti","Belcesti", NOW(), NOW()),
            (40, "Ivesti","Pogonesti", NOW(), NOW()),
            (40, "Ivesti","Polocin", NOW(), NOW()),
            (40, "Laza","Bejenesti", NOW(), NOW()),
            (40, "Laza","Poiana lui Alexa", NOW(), NOW()),
            (40, "Laza","Puscasi", NOW(), NOW()),
            (40, "Laza","Rasnita", NOW(), NOW()),
            (40, "Laza","Sauca", NOW(), NOW()),
            (40, "Laza","Teisoru", NOW(), NOW()),
            (40, "Laza","Valea Targului", NOW(), NOW()),
            (40, "Lipovat","Chitoc", NOW(), NOW()),
            (40, "Lipovat","Corbu", NOW(), NOW()),
            (40, "Lipovat","Capusneni", NOW(), NOW()),
            (40, "Lipovat","Fundu Vaii", NOW(), NOW()),
            (40, "Lunca Banului","Broscosesti", NOW(), NOW()),
            (40, "Lunca Banului","Condrea", NOW(), NOW()),
            (40, "Lunca Banului","Focsa", NOW(), NOW()),
            (40, "Lunca Banului","Lunca Veche", NOW(), NOW()),
            (40, "Lunca Banului","Otetoaia", NOW(), NOW()),
            (40, "Lunca Banului","Raducani", NOW(), NOW()),
            (40, "Malusteni","Ghireasca", NOW(), NOW()),
            (40, "Malusteni","Lupesti", NOW(), NOW()),
            (40, "Malusteni","Manzatesti", NOW(), NOW()),
            (40, "Malusteni","Manastirea", NOW(), NOW()),
            (40, "Malusteni","Tutcani", NOW(), NOW()),
            (40, "Miclesti","Chircesti", NOW(), NOW()),
            (40, "Miclesti","Popesti", NOW(), NOW()),
            (40, "Muntenii De Jos","Bacaoani", NOW(), NOW()),
            (40, "Muntenii De Jos","Manjesti", NOW(), NOW()),
            (40, "Muntenii De Jos","Secuia", NOW(), NOW()),
            (40, "Murgeni","Carja", NOW(), NOW()),
            (40, "Murgeni","Floreni", NOW(), NOW()),
            (40, "Murgeni","Latesti", NOW(), NOW()),
            (40, "Murgeni","Raiu", NOW(), NOW()),
            (40, "Murgeni","Schineni", NOW(), NOW()),
            (40, "Murgeni","Sarateni", NOW(), NOW()),
            (40, "Negresti","Cioatele", NOW(), NOW()),
            (40, "Negresti","Cazanesti", NOW(), NOW()),
            (40, "Negresti","Glodeni", NOW(), NOW()),
            (40, "Negresti","Parpanita", NOW(), NOW()),
            (40, "Negresti","Poiana", NOW(), NOW()),
            (40, "Negresti","Valea Mare", NOW(), NOW()),
            (40, "Oltenesti","Curteni", NOW(), NOW()),
            (40, "Oltenesti","Pahna", NOW(), NOW()),
            (40, "Oltenesti","Tarzii", NOW(), NOW()),
            (40, "Oltenesti","Vinetesti", NOW(), NOW()),
            (40, "Oltenesti","Zgura", NOW(), NOW()),
            (40, "Osesti","Buda", NOW(), NOW()),
            (40, "Osesti","Padureni", NOW(), NOW()),
            (40, "Osesti","Valcele", NOW(), NOW()),
            (40, "Padureni","Capotesti", NOW(), NOW()),
            (40, "Padureni","Davidesti", NOW(), NOW()),
            (40, "Padureni","Ivanesti", NOW(), NOW()),
            (40, "Padureni","Leosti", NOW(), NOW()),
            (40, "Padureni","Rusca", NOW(), NOW()),
            (40, "Padureni","Todireni", NOW(), NOW()),
            (40, "Padureni","Valeni", NOW(), NOW()),
            (40, "Perieni","Ciocani", NOW(), NOW()),
            (40, "Perieni","Crang", NOW(), NOW()),
            (40, "Perieni","Crangu Nou", NOW(), NOW()),
            (40, "Perieni","Podu Petris", NOW(), NOW()),
            (40, "Pogana","Bogesti", NOW(), NOW()),
            (40, "Pogana","Carjoani", NOW(), NOW()),
            (40, "Pogana","Mascurei", NOW(), NOW()),
            (40, "Pogana","Tomesti", NOW(), NOW()),
            (40, "Poienesti","Dealu Secarii", NOW(), NOW()),
            (40, "Poienesti","Floresti", NOW(), NOW()),
            (40, "Poienesti","Frasinu", NOW(), NOW()),
            (40, "Poienesti","Fundu Vaii", NOW(), NOW()),
            (40, "Poienesti","Oprisita", NOW(), NOW()),
            (40, "Poienesti","Poienesti-Deal", NOW(), NOW()),
            (40, "Puiesti","Bartalus-Mocani", NOW(), NOW()),
            (40, "Puiesti","Bartalus-Razesi", NOW(), NOW()),
            (40, "Puiesti","Cetatuia", NOW(), NOW()),
            (40, "Puiesti","Cristesti", NOW(), NOW()),
            (40, "Puiesti","Calimanesti", NOW(), NOW()),
            (40, "Puiesti","Fulgu", NOW(), NOW()),
            (40, "Puiesti","Fantanele", NOW(), NOW()),
            (40, "Puiesti","Galtesti", NOW(), NOW()),
            (40, "Puiesti","Iezer", NOW(), NOW()),
            (40, "Puiesti","Lalesti", NOW(), NOW()),
            (40, "Puiesti","Rotari", NOW(), NOW()),
            (40, "Puiesti","Rusi", NOW(), NOW()),
            (40, "Pungesti","Armasoaia", NOW(), NOW()),
            (40, "Pungesti","Cursesti-Deal", NOW(), NOW()),
            (40, "Pungesti","Cursesti-Vale", NOW(), NOW()),
            (40, "Pungesti","Hordila", NOW(), NOW()),
            (40, "Pungesti","Rapsa", NOW(), NOW()),
            (40, "Pungesti","Silistea", NOW(), NOW()),
            (40, "Pungesti","Stejaru", NOW(), NOW()),
            (40, "Pungesti","Toporasti", NOW(), NOW()),
            (40, "Rebricea","Bolati", NOW(), NOW()),
            (40, "Rebricea","Craciunesti", NOW(), NOW()),
            (40, "Rebricea","Draxeni", NOW(), NOW()),
            (40, "Rebricea","Macresti", NOW(), NOW()),
            (40, "Rebricea","Ratesu Cuzei", NOW(), NOW()),
            (40, "Rebricea","Sasova", NOW(), NOW()),
            (40, "Rebricea","Tatomiresti", NOW(), NOW()),
            (40, "Rebricea","Tufestii de Jos", NOW(), NOW()),
            (40, "Rosiesti","Codreni", NOW(), NOW()),
            (40, "Rosiesti","Gara Rosiesti", NOW(), NOW()),
            (40, "Rosiesti","Gura Idrici", NOW(), NOW()),
            (40, "Rosiesti","Idrici", NOW(), NOW()),
            (40, "Rosiesti","Rediu", NOW(), NOW()),
            (40, "Rosiesti","Valea lui Darie", NOW(), NOW()),
            (40, "Solesti","Bousori", NOW(), NOW()),
            (40, "Solesti","Iaz", NOW(), NOW()),
            (40, "Solesti","Satu Nou", NOW(), NOW()),
            (40, "Solesti","Valea Silistei", NOW(), NOW()),
            (40, "Solesti","Serbotesti", NOW(), NOW()),
            (40, "Solesti","Stioborani", NOW(), NOW()),
            (40, "Stanilesti","Bogdana-Voloseni", NOW(), NOW()),
            (40, "Stanilesti","Budu Cantemir", NOW(), NOW()),
            (40, "Stanilesti","Chersacosu", NOW(), NOW()),
            (40, "Stanilesti","Gura Vaii", NOW(), NOW()),
            (40, "Stanilesti","Poganesti", NOW(), NOW()),
            (40, "Stanilesti","Saratu", NOW(), NOW()),
            (40, "Stefan Cel Mare","Brahasoaia", NOW(), NOW()),
            (40, "Stefan Cel Mare","Barzesti", NOW(), NOW()),
            (40, "Stefan Cel Mare","Calugareni", NOW(), NOW()),
            (40, "Stefan Cel Mare","Cantalaresti", NOW(), NOW()),
            (40, "Stefan Cel Mare","Muntenesti", NOW(), NOW()),
            (40, "Stefan Cel Mare","Maraseni", NOW(), NOW()),
            (40, "Suletea","Fedesti", NOW(), NOW()),
            (40, "Suletea","Jigalia", NOW(), NOW()),
            (40, "Suletea","Rascani", NOW(), NOW()),
            (40, "Tacuta","Cujba", NOW(), NOW()),
            (40, "Tacuta","Dumasca", NOW(), NOW()),
            (40, "Tacuta","Focseasca", NOW(), NOW()),
            (40, "Tacuta","Mircesti", NOW(), NOW()),
            (40, "Tacuta","Protopopesti", NOW(), NOW()),
            (40, "Tacuta","Sofieni", NOW(), NOW()),
            (40, "Tanacu","Benesti", NOW(), NOW()),
            (40, "Tanacu","Muntenii de Sus", NOW(), NOW()),
            (40, "Tanacu","Satu Nou", NOW(), NOW()),
            (40, "Tatarani","Baltati", NOW(), NOW()),
            (40, "Tatarani","Crasnaseni", NOW(), NOW()),
            (40, "Tatarani","Giurgesti", NOW(), NOW()),
            (40, "Tatarani","Leosti", NOW(), NOW()),
            (40, "Tatarani","Mantu", NOW(), NOW()),
            (40, "Tatarani","Stroiesti", NOW(), NOW()),
            (40, "Tatarani","Valea Seaca", NOW(), NOW()),
            (40, "Tatarani","Valea lui Bosie", NOW(), NOW()),
            (40, "Todiresti","Cotic", NOW(), NOW()),
            (40, "Todiresti","Dragesti", NOW(), NOW()),
            (40, "Todiresti","Huc", NOW(), NOW()),
            (40, "Todiresti","Plopoasa", NOW(), NOW()),
            (40, "Todiresti","Rafaila", NOW(), NOW()),
            (40, "Todiresti","Silistea", NOW(), NOW()),
            (40, "Todiresti","Sofronesti", NOW(), NOW()),
            (40, "Todiresti","Valea Popii", NOW(), NOW()),
            (40, "Todiresti","Viisoara", NOW(), NOW()),
            (40, "Tutova","Borodesti", NOW(), NOW()),
            (40, "Tutova","Badeana", NOW(), NOW()),
            (40, "Tutova","Ciortolom", NOW(), NOW()),
            (40, "Tutova","Coroiu", NOW(), NOW()),
            (40, "Tutova","Crivesti", NOW(), NOW()),
            (40, "Tutova","Pochidia", NOW(), NOW()),
            (40, "Tutova","Satu Nou", NOW(), NOW()),
            (40, "Tutova","Salceni", NOW(), NOW()),
            (40, "Tutova","Vizureni", NOW(), NOW()),
            (40, "Valeni","Feresti", NOW(), NOW()),
            (40, "Valeni","Moara Domneasca", NOW(), NOW()),
            (40, "Vaslui","Bahnari", NOW(), NOW()),
            (40, "Vaslui","Brodoc", NOW(), NOW()),
            (40, "Vaslui","Moara Grecilor", NOW(), NOW()),
            (40, "Vaslui","Rediu", NOW(), NOW()),
            (40, "Vaslui","Viisoara", NOW(), NOW()),
            (40, "Vetrisoaia","Bumbata", NOW(), NOW()),
            (40, "Viisoara","Dodesti", NOW(), NOW()),
            (40, "Viisoara","Halta Dodesti", NOW(), NOW()),
            (40, "Viisoara","Urdesti", NOW(), NOW()),
            (40, "Viisoara","Viltotesti", NOW(), NOW()),
            (40, "Viisoara","Valeni", NOW(), NOW()),
            (40, "Vinderei","Bradesti", NOW(), NOW()),
            (40, "Vinderei","Docani", NOW(), NOW()),
            (40, "Vinderei","Docaneasa", NOW(), NOW()),
            (40, "Vinderei","Gara Docaneasa", NOW(), NOW()),
            (40, "Vinderei","Gara Talasman", NOW(), NOW()),
            (40, "Vinderei","Obarseni", NOW(), NOW()),
            (40, "Vinderei","Valea Lunga", NOW(), NOW()),
            (40, "Voinesti","Avramesti", NOW(), NOW()),
            (40, "Voinesti","Bancesti", NOW(), NOW()),
            (40, "Voinesti","Corobanesti", NOW(), NOW()),
            (40, "Voinesti","Gardesti", NOW(), NOW()),
            (40, "Voinesti","Marasesti", NOW(), NOW()),
            (40, "Voinesti","Obarseni", NOW(), NOW()),
            (40, "Voinesti","Obarsenii Lingurari", NOW(), NOW()),
            (40, "Voinesti","Rugaria", NOW(), NOW()),
            (40, "Voinesti","Stancaseni", NOW(), NOW()),
            (40, "Voinesti","Uricari", NOW(), NOW()),
            (40, "Vulturesti","Buhaiesti", NOW(), NOW()),
            (40, "Vulturesti","Podeni", NOW(), NOW()),
            (40, "Vulturesti","Voinesti", NOW(), NOW()),
            (40, "Vutcani","Malaiesti", NOW(), NOW()),
            (40, "Vutcani","Posta Elan", NOW(), NOW()),
            (40, "Zapodeni","Butucaria", NOW(), NOW()),
            (40, "Zapodeni","Ciofeni", NOW(), NOW()),
            (40, "Zapodeni","Delea", NOW(), NOW()),
            (40, "Zapodeni","Dobroslovesti", NOW(), NOW()),
            (40, "Zapodeni","Macresti", NOW(), NOW()),
            (40, "Zapodeni","Portari", NOW(), NOW()),
            (40, "Zapodeni","Telejna", NOW(), NOW()),
            (40, "Zapodeni","Uncesti", NOW(), NOW()),
            (40, "Zorleni","Dealu Mare", NOW(), NOW()),
            (40, "Zorleni","Popeni", NOW(), NOW()),
            (40, "Zorleni","Simila", NOW(), NOW())
        ;';
        DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = "DELETE FROM localities WHERE county_id=40;";
        DB::connection()->getPdo()->exec($sql);
    }
}
