<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForCL extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (22, "","Alexandru Odobescu", NOW(), NOW()),
            (22, "","Belciugatele", NOW(), NOW()),
            (22, "","Borcea", NOW(), NOW()),
            (22, "","Budesti", NOW(), NOW()),
            (22, "","Chirnogi", NOW(), NOW()),
            (22, "","Chiselet", NOW(), NOW()),
            (22, "","Ciocanesti", NOW(), NOW()),
            (22, "","Curcani", NOW(), NOW()),
            (22, "","Cuza Voda", NOW(), NOW()),
            (22, "","Calarasi", NOW(), NOW()),
            (22, "","Cascioarele", NOW(), NOW()),
            (22, "","Dichiseni", NOW(), NOW()),
            (22, "","Dor Marunt", NOW(), NOW()),
            (22, "","Dorobantu", NOW(), NOW()),
            (22, "","Dragalina", NOW(), NOW()),
            (22, "","Dragos Voda", NOW(), NOW()),
            (22, "","Frumusani", NOW(), NOW()),
            (22, "","Frasinet", NOW(), NOW()),
            (22, "","Fundeni", NOW(), NOW()),
            (22, "","Fundulea", NOW(), NOW()),
            (22, "","Gradistea", NOW(), NOW()),
            (22, "","Gurbanesti", NOW(), NOW()),
            (22, "","Ileana", NOW(), NOW()),
            (22, "","Independenta", NOW(), NOW()),
            (22, "","Jegalia", NOW(), NOW()),
            (22, "","Lehliu", NOW(), NOW()),
            (22, "","Luica", NOW(), NOW()),
            (22, "","Lupsanu", NOW(), NOW()),
            (22, "","Mitreni", NOW(), NOW()),
            (22, "","Modelu", NOW(), NOW()),
            (22, "","Manastirea", NOW(), NOW()),
            (22, "","Nana", NOW(), NOW()),
            (22, "","Nicolae Balcescu", NOW(), NOW()),
            (22, "","Oltenita", NOW(), NOW()),
            (22, "","Perisoru", NOW(), NOW()),
            (22, "","Plataresti", NOW(), NOW()),
            (22, "","Radovanu", NOW(), NOW()),
            (22, "","Roseti", NOW(), NOW()),
            (22, "","Sohatu", NOW(), NOW()),
            (22, "","Spantov", NOW(), NOW()),
            (22, "","Sarulesti", NOW(), NOW()),
            (22, "","Tamadau Mare", NOW(), NOW()),
            (22, "","Ulmeni", NOW(), NOW()),
            (22, "","Ulmu", NOW(), NOW()),
            (22, "","Unirea", NOW(), NOW()),
            (22, "","Valea Argovei", NOW(), NOW()),
            (22, "","Vasilati", NOW(), NOW()),
            (22, "","Vlad Tepes", NOW(), NOW()),
            (22, "","Valcelele", NOW(), NOW()),
            (22, "","Soldanu", NOW(), NOW()),
            (22, "","Stefan Voda", NOW(), NOW()),
            (22, "","Stefan cel Mare", NOW(), NOW()),
            (22, "Alexandru Odobescu","Galatui", NOW(), NOW()),
            (22, "Alexandru Odobescu","Nicolae Balcescu", NOW(), NOW()),
            (22, "Belciugatele","Cojesti", NOW(), NOW()),
            (22, "Belciugatele","Candeasca", NOW(), NOW()),
            (22, "Belciugatele","Mataraua", NOW(), NOW()),
            (22, "Belciugatele","Mariuta", NOW(), NOW()),
            (22, "Budesti","Aprozi", NOW(), NOW()),
            (22, "Budesti","Buciumeni", NOW(), NOW()),
            (22, "Budesti","Crivat", NOW(), NOW()),
            (22, "Budesti","Gruiu", NOW(), NOW()),
            (22, "Curcani","Salcioara", NOW(), NOW()),
            (22, "Cuza Voda","Ceacu", NOW(), NOW()),
            (22, "Cuza Voda","Calarasii Vechi", NOW(), NOW()),
            (22, "Dichiseni","Coslogeni", NOW(), NOW()),
            (22, "Dichiseni","Libertatea", NOW(), NOW()),
            (22, "Dichiseni","Satnoeni", NOW(), NOW()),
            (22, "Dor Marunt","Dalga", NOW(), NOW()),
            (22, "Dor Marunt","Dalga-Gara", NOW(), NOW()),
            (22, "Dor Marunt","Ogoru", NOW(), NOW()),
            (22, "Dor Marunt","Pelinu", NOW(), NOW()),
            (22, "Dor Marunt","Infratirea", NOW(), NOW()),
            (22, "Dorobantu","Bosneagu", NOW(), NOW()),
            (22, "Dorobantu","Varasti", NOW(), NOW()),
            (22, "Dragalina","Constantin Brancoveanu", NOW(), NOW()),
            (22, "Dragalina","Drajna Noua", NOW(), NOW()),
            (22, "Dragos Voda","Bogdana", NOW(), NOW()),
            (22, "Dragos Voda","Socoalele", NOW(), NOW()),
            (22, "Frasinet","Curatesti", NOW(), NOW()),
            (22, "Frasinet","Danesti", NOW(), NOW()),
            (22, "Frasinet","Frasinetu de Jos", NOW(), NOW()),
            (22, "Frasinet","Luptatori", NOW(), NOW()),
            (22, "Frasinet","Tariceni", NOW(), NOW()),
            (22, "Frumusani","Orasti", NOW(), NOW()),
            (22, "Frumusani","Pasarea", NOW(), NOW()),
            (22, "Frumusani","Pitigaia", NOW(), NOW()),
            (22, "Frumusani","Postavari", NOW(), NOW()),
            (22, "Frumusani","Padurisu", NOW(), NOW()),
            (22, "Fundulea","Alexandru I. Cuza", NOW(), NOW()),
            (22, "Fundulea","Gostilele", NOW(), NOW()),
            (22, "Gradistea","Bogata", NOW(), NOW()),
            (22, "Gradistea","Cunesti", NOW(), NOW()),
            (22, "Gradistea","Rasa", NOW(), NOW()),
            (22, "Gurbanesti","Codreni", NOW(), NOW()),
            (22, "Gurbanesti","Cotofanca", NOW(), NOW()),
            (22, "Gurbanesti","Preasna", NOW(), NOW()),
            (22, "Gurbanesti","Preasna Veche", NOW(), NOW()),
            (22, "Gurbanesti","Valea Presnei", NOW(), NOW()),
            (22, "Ileana","Artari", NOW(), NOW()),
            (22, "Ileana","Florica", NOW(), NOW()),
            (22, "Ileana","Podari", NOW(), NOW()),
            (22, "Ileana","Rasurile", NOW(), NOW()),
            (22, "Ileana","Razoarele", NOW(), NOW()),
            (22, "Ileana","Satu Nou", NOW(), NOW()),
            (22, "Ileana","Vlaiculesti", NOW(), NOW()),
            (22, "Ileana","Stefanesti", NOW(), NOW()),
            (22, "Independenta","Potcoava", NOW(), NOW()),
            (22, "Independenta","Visinii", NOW(), NOW()),
            (22, "Jegalia","Galdau", NOW(), NOW()),
            (22, "Jegalia","Iezeru", NOW(), NOW()),
            (22, "Lehliu","Sapunari", NOW(), NOW()),
            (22, "Lehliu Gara","Buzoeni", NOW(), NOW()),
            (22, "Lehliu Gara","Lehliu-Gara", NOW(), NOW()),
            (22, "Lehliu Gara","Razvani", NOW(), NOW()),
            (22, "Lehliu Gara","Valea Seaca", NOW(), NOW()),
            (22, "Luica","Valea Stanii", NOW(), NOW()),
            (22, "Lupsanu","Nucetu", NOW(), NOW()),
            (22, "Lupsanu","Plevna", NOW(), NOW()),
            (22, "Lupsanu","Radu Voda", NOW(), NOW()),
            (22, "Lupsanu","Valea Rusului", NOW(), NOW()),
            (22, "Manastirea","Coconi", NOW(), NOW()),
            (22, "Manastirea","Sultana", NOW(), NOW()),
            (22, "Mitreni","Clatesti", NOW(), NOW()),
            (22, "Mitreni","Valea Rosie", NOW(), NOW()),
            (22, "Modelu","Radu Negru", NOW(), NOW()),
            (22, "Modelu","Stoenesti", NOW(), NOW()),
            (22, "Modelu","Tonea", NOW(), NOW()),
            (22, "Nicolae Balcescu","Fantana Doamnei", NOW(), NOW()),
            (22, "Nicolae Balcescu","Paicu", NOW(), NOW()),
            (22, "Perisoru","Marculesti-Gara", NOW(), NOW()),
            (22, "Perisoru","Tudor Vladimirescu", NOW(), NOW()),
            (22, "Plataresti","Cucuieti", NOW(), NOW()),
            (22, "Plataresti","Dorobantu", NOW(), NOW()),
            (22, "Plataresti","Podu Pitarului", NOW(), NOW()),
            (22, "Radovanu","Valea Popii", NOW(), NOW()),
            (22, "Sarulesti","Magureni", NOW(), NOW()),
            (22, "Sarulesti","Polcesti", NOW(), NOW()),
            (22, "Sarulesti","Solacolu", NOW(), NOW()),
            (22, "Sarulesti","Sandulita", NOW(), NOW()),
            (22, "Sarulesti","Sarulesti-Gara", NOW(), NOW()),
            (22, "Sarulesti","Satucu", NOW(), NOW()),
            (22, "Sohatu","Progresu", NOW(), NOW()),
            (22, "Soldanu","Negoesti", NOW(), NOW()),
            (22, "Spantov","Cetatea Veche", NOW(), NOW()),
            (22, "Spantov","Stancea", NOW(), NOW()),
            (22, "Tamadau Mare","Calareti", NOW(), NOW()),
            (22, "Tamadau Mare","Darvari", NOW(), NOW()),
            (22, "Tamadau Mare","Plumbuita", NOW(), NOW()),
            (22, "Tamadau Mare","Sacele", NOW(), NOW()),
            (22, "Tamadau Mare","Tamadau Mic", NOW(), NOW()),
            (22, "Tamadau Mare","Seinoiu", NOW(), NOW()),
            (22, "Ulmu","Chirnogi", NOW(), NOW()),
            (22, "Ulmu","Faurei", NOW(), NOW()),
            (22, "Ulmu","Zimbru", NOW(), NOW()),
            (22, "Unirea","Oltina", NOW(), NOW()),
            (22, "Valcelele","Floroaica", NOW(), NOW()),
            (22, "Valea Argovei","Lunca", NOW(), NOW()),
            (22, "Valea Argovei","Ostrovu", NOW(), NOW()),
            (22, "Valea Argovei","Silistea", NOW(), NOW()),
            (22, "Valea Argovei","Vladiceasca", NOW(), NOW()),
            (22, "Vasilati","Galbinasi", NOW(), NOW()),
            (22, "Vasilati","Nuci", NOW(), NOW()),
            (22, "Vasilati","Popesti", NOW(), NOW()),
            (22, "Vlad Tepes","Mihai Viteazu", NOW(), NOW())
        ;';
        if (config('app.env') !== 'testing') {
            DB::connection()->getPdo()->exec($sql);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=22;';
        DB::connection()->getPdo()->exec($sql);
    }
}
