<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForVL extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (41, "","Alunu", NOW(), NOW()),
            (41, "","Amarasti", NOW(), NOW()),
            (41, "","Berbesti", NOW(), NOW()),
            (41, "","Berislavesti", NOW(), NOW()),
            (41, "","Boisoara", NOW(), NOW()),
            (41, "","Brezoi", NOW(), NOW()),
            (41, "","Budesti", NOW(), NOW()),
            (41, "","Bujoreni", NOW(), NOW()),
            (41, "","Bunesti", NOW(), NOW()),
            (41, "","Babeni", NOW(), NOW()),
            (41, "","Balcesti", NOW(), NOW()),
            (41, "","Barbatesti", NOW(), NOW()),
            (41, "","Cernisoara", NOW(), NOW()),
            (41, "","Copaceni", NOW(), NOW()),
            (41, "","Costesti", NOW(), NOW()),
            (41, "","Creteni", NOW(), NOW()),
            (41, "","Calimanesti", NOW(), NOW()),
            (41, "","Dragoesti", NOW(), NOW()),
            (41, "","Dragasani", NOW(), NOW()),
            (41, "","Daesti", NOW(), NOW()),
            (41, "","Francesti", NOW(), NOW()),
            (41, "","Fartatesti", NOW(), NOW()),
            (41, "","Fauresti", NOW(), NOW()),
            (41, "","Galicea", NOW(), NOW()),
            (41, "","Ghioroiu", NOW(), NOW()),
            (41, "","Glavile", NOW(), NOW()),
            (41, "","Gradistea", NOW(), NOW()),
            (41, "","Gusoeni", NOW(), NOW()),
            (41, "","Horezu", NOW(), NOW()),
            (41, "","Ionesti", NOW(), NOW()),
            (41, "","Lalosu", NOW(), NOW()),
            (41, "","Livezi", NOW(), NOW()),
            (41, "","Lungesti", NOW(), NOW()),
            (41, "","Ladesti", NOW(), NOW()),
            (41, "","Malaia", NOW(), NOW()),
            (41, "","Mateesti", NOW(), NOW()),
            (41, "","Mihaesti", NOW(), NOW()),
            (41, "","Milcoiu", NOW(), NOW()),
            (41, "","Muereasca", NOW(), NOW()),
            (41, "","Madulari", NOW(), NOW()),
            (41, "","Maldaresti", NOW(), NOW()),
            (41, "","Olanu", NOW(), NOW()),
            (41, "","Orlesti", NOW(), NOW()),
            (41, "","Otesani", NOW(), NOW()),
            (41, "","Perisani", NOW(), NOW()),
            (41, "","Pesceana", NOW(), NOW()),
            (41, "","Pietrari", NOW(), NOW()),
            (41, "","Popesti", NOW(), NOW()),
            (41, "","Prundeni", NOW(), NOW()),
            (41, "","Pausesti", NOW(), NOW()),
            (41, "","Pausesti-Maglasi", NOW(), NOW()),
            (41, "","Racovita", NOW(), NOW()),
            (41, "","Roesti", NOW(), NOW()),
            (41, "","Rosiile", NOW(), NOW()),
            (41, "","Runcu", NOW(), NOW()),
            (41, "","Ramnicu Valcea", NOW(), NOW()),
            (41, "","Scundu", NOW(), NOW()),
            (41, "","Sinesti", NOW(), NOW()),
            (41, "","Slatioara", NOW(), NOW()),
            (41, "","Stoenesti", NOW(), NOW()),
            (41, "","Stoilesti", NOW(), NOW()),
            (41, "","Stroesti", NOW(), NOW()),
            (41, "","Stanesti", NOW(), NOW()),
            (41, "","Sutesti", NOW(), NOW()),
            (41, "","Salatrucel", NOW(), NOW()),
            (41, "","Tetoiu", NOW(), NOW()),
            (41, "","Titesti", NOW(), NOW()),
            (41, "","Tomsani", NOW(), NOW()),
            (41, "","Vaideeni", NOW(), NOW()),
            (41, "","Valea Mare", NOW(), NOW()),
            (41, "","Vladesti", NOW(), NOW()),
            (41, "","Voicesti", NOW(), NOW()),
            (41, "","Voineasa", NOW(), NOW()),
            (41, "","Zatreni", NOW(), NOW()),
            (41, "","Sirineasa", NOW(), NOW()),
            (41, "","Stefanesti", NOW(), NOW()),
            (41, "","Susani", NOW(), NOW()),
            (41, "Alunu","Bodesti", NOW(), NOW()),
            (41, "Alunu","Coltesti", NOW(), NOW()),
            (41, "Alunu","Igoiu", NOW(), NOW()),
            (41, "Alunu","Ilaciu", NOW(), NOW()),
            (41, "Alunu","Ocracu", NOW(), NOW()),
            (41, "Alunu","Rosia", NOW(), NOW()),
            (41, "Amarasti","Meresesti", NOW(), NOW()),
            (41, "Amarasti","Nemoiu", NOW(), NOW()),
            (41, "Amarasti","Padina", NOW(), NOW()),
            (41, "Amarasti","Palanga", NOW(), NOW()),
            (41, "Amarasti","Teiul", NOW(), NOW()),
            (41, "Babeni","Bonciu", NOW(), NOW()),
            (41, "Babeni","Capu Dealului", NOW(), NOW()),
            (41, "Babeni","Paduretu", NOW(), NOW()),
            (41, "Babeni","Romani", NOW(), NOW()),
            (41, "Babeni","Tatarani", NOW(), NOW()),
            (41, "Babeni","Valea Mare", NOW(), NOW()),
            (41, "Baile Govora","Curaturile", NOW(), NOW()),
            (41, "Baile Govora","Gatejesti", NOW(), NOW()),
            (41, "Baile Govora","Prajila", NOW(), NOW()),
            (41, "Baile Olanesti","Cheia", NOW(), NOW()),
            (41, "Baile Olanesti","Comanca", NOW(), NOW()),
            (41, "Baile Olanesti","Gurguiata", NOW(), NOW()),
            (41, "Baile Olanesti","Livadia", NOW(), NOW()),
            (41, "Baile Olanesti","Mosoroasa", NOW(), NOW()),
            (41, "Baile Olanesti","Olanesti", NOW(), NOW()),
            (41, "Baile Olanesti","Pietrisu", NOW(), NOW()),
            (41, "Baile Olanesti","Tisa", NOW(), NOW()),
            (41, "Balcesti","Benesti", NOW(), NOW()),
            (41, "Balcesti","Chirculesti", NOW(), NOW()),
            (41, "Balcesti","Carlogani", NOW(), NOW()),
            (41, "Balcesti","Gorunesti", NOW(), NOW()),
            (41, "Balcesti","Irimesti", NOW(), NOW()),
            (41, "Balcesti","Otetelisu", NOW(), NOW()),
            (41, "Balcesti","Preotesti", NOW(), NOW()),
            (41, "Balcesti","Satu Poieni", NOW(), NOW()),
            (41, "Barbatesti","Bodesti", NOW(), NOW()),
            (41, "Barbatesti","Barzesti", NOW(), NOW()),
            (41, "Barbatesti","Negrulesti", NOW(), NOW()),
            (41, "Berbesti","Dealu Alunis", NOW(), NOW()),
            (41, "Berbesti","Damteni", NOW(), NOW()),
            (41, "Berbesti","Rosioara", NOW(), NOW()),
            (41, "Berbesti","Targu Gangulesti", NOW(), NOW()),
            (41, "Berbesti","Valea Mare", NOW(), NOW()),
            (41, "Berislavesti","Bradisor", NOW(), NOW()),
            (41, "Berislavesti","Dangesti", NOW(), NOW()),
            (41, "Berislavesti","Robaia", NOW(), NOW()),
            (41, "Berislavesti","Radacinesti", NOW(), NOW()),
            (41, "Berislavesti","Scaueni", NOW(), NOW()),
            (41, "Berislavesti","Stoenesti", NOW(), NOW()),
            (41, "Boisoara","Bumbuesti", NOW(), NOW()),
            (41, "Boisoara","Gaujani", NOW(), NOW()),
            (41, "Brezoi","Corbu", NOW(), NOW()),
            (41, "Brezoi","Calinesti", NOW(), NOW()),
            (41, "Brezoi","Draganesti", NOW(), NOW()),
            (41, "Brezoi","Golotreni", NOW(), NOW()),
            (41, "Brezoi","Proieni", NOW(), NOW()),
            (41, "Brezoi","Pascoaia", NOW(), NOW()),
            (41, "Brezoi","Valea lui Stan", NOW(), NOW()),
            (41, "Brezoi","Varatica", NOW(), NOW()),
            (41, "Budesti","Barza", NOW(), NOW()),
            (41, "Budesti","Bercioiu", NOW(), NOW()),
            (41, "Budesti","Barsesti", NOW(), NOW()),
            (41, "Budesti","Linia", NOW(), NOW()),
            (41, "Budesti","Piscu Pietrei", NOW(), NOW()),
            (41, "Budesti","Racovita", NOW(), NOW()),
            (41, "Budesti","Ruda", NOW(), NOW()),
            (41, "Bujoreni","Bogdanesti", NOW(), NOW()),
            (41, "Bujoreni","Gura Vaii", NOW(), NOW()),
            (41, "Bujoreni","Lunca", NOW(), NOW()),
            (41, "Bujoreni","Malu Alb", NOW(), NOW()),
            (41, "Bujoreni","Malu Vartop", NOW(), NOW()),
            (41, "Bujoreni","Olteni", NOW(), NOW()),
            (41, "Bunesti","Coasta Mare", NOW(), NOW()),
            (41, "Bunesti","Firesti", NOW(), NOW()),
            (41, "Bunesti","Rapanesti", NOW(), NOW()),
            (41, "Bunesti","Teiusu", NOW(), NOW()),
            (41, "Bunesti","Titireci", NOW(), NOW()),
            (41, "Caineni","Cainenii Mari", NOW(), NOW()),
            (41, "Caineni","Cainenii Mici", NOW(), NOW()),
            (41, "Caineni","Greblesti", NOW(), NOW()),
            (41, "Caineni","Priloage", NOW(), NOW()),
            (41, "Caineni","Robesti", NOW(), NOW()),
            (41, "Caineni","Rau Vadului", NOW(), NOW()),
            (41, "Calimanesti","Caciulata", NOW(), NOW()),
            (41, "Calimanesti","Jiblea Noua", NOW(), NOW()),
            (41, "Calimanesti","Jiblea Veche", NOW(), NOW()),
            (41, "Calimanesti","Pausa", NOW(), NOW()),
            (41, "Calimanesti","Seaca", NOW(), NOW()),
            (41, "Cernisoara","Armasesti", NOW(), NOW()),
            (41, "Cernisoara","Grosi", NOW(), NOW()),
            (41, "Cernisoara","Modoia", NOW(), NOW()),
            (41, "Cernisoara","Madulari", NOW(), NOW()),
            (41, "Cernisoara","Obarsia", NOW(), NOW()),
            (41, "Cernisoara","Sarsanesti", NOW(), NOW()),
            (41, "Copaceni","Bondoci", NOW(), NOW()),
            (41, "Copaceni","Balteni", NOW(), NOW()),
            (41, "Copaceni","Hotarasa", NOW(), NOW()),
            (41, "Copaceni","Ulmetu", NOW(), NOW()),
            (41, "Copaceni","Vetelu", NOW(), NOW()),
            (41, "Costesti","Bistrita", NOW(), NOW()),
            (41, "Costesti","Pietreni", NOW(), NOW()),
            (41, "Costesti","Varatici", NOW(), NOW()),
            (41, "Creteni","Izvoru", NOW(), NOW()),
            (41, "Creteni","Mrenesti", NOW(), NOW()),
            (41, "Creteni","Streminoasa", NOW(), NOW()),
            (41, "Daesti","Babuesti", NOW(), NOW()),
            (41, "Daesti","Fedelesoiu", NOW(), NOW()),
            (41, "Daesti","Sanbotin", NOW(), NOW()),
            (41, "Danicei","Badeni", NOW(), NOW()),
            (41, "Danicei","Ceretu", NOW(), NOW()),
            (41, "Danicei","Ciresul", NOW(), NOW()),
            (41, "Danicei","Dealu Launele", NOW(), NOW()),
            (41, "Danicei","Dealu Scheiului", NOW(), NOW()),
            (41, "Danicei","Dobresti", NOW(), NOW()),
            (41, "Danicei","Dragulesti", NOW(), NOW()),
            (41, "Danicei","Glodu", NOW(), NOW()),
            (41, "Danicei","Gura Crucilor", NOW(), NOW()),
            (41, "Danicei","Linia pe Vale", NOW(), NOW()),
            (41, "Danicei","Launele de Jos", NOW(), NOW()),
            (41, "Danicei","Udresti", NOW(), NOW()),
            (41, "Danicei","Valea Scheiului", NOW(), NOW()),
            (41, "Dragasani","Valea Caselor", NOW(), NOW()),
            (41, "Dragasani","Zlatarei", NOW(), NOW()),
            (41, "Dragasani","Zarneni", NOW(), NOW()),
            (41, "Dragoesti","Buciumeni", NOW(), NOW()),
            (41, "Dragoesti","Geamana", NOW(), NOW()),
            (41, "Fartatesti","Afanata", NOW(), NOW()),
            (41, "Fartatesti","Becsani", NOW(), NOW()),
            (41, "Fartatesti","Cuci", NOW(), NOW()),
            (41, "Fartatesti","Catetu", NOW(), NOW()),
            (41, "Fartatesti","Dejoi", NOW(), NOW()),
            (41, "Fartatesti","Dozesti", NOW(), NOW()),
            (41, "Fartatesti","Dancai", NOW(), NOW()),
            (41, "Fartatesti","Giulesti", NOW(), NOW()),
            (41, "Fartatesti","Giulestii de Sus", NOW(), NOW()),
            (41, "Fartatesti","Garnicet", NOW(), NOW()),
            (41, "Fartatesti","Maricesti", NOW(), NOW()),
            (41, "Fartatesti","Nisipi", NOW(), NOW()),
            (41, "Fartatesti","Popesti", NOW(), NOW()),
            (41, "Fartatesti","Rusanesti", NOW(), NOW()),
            (41, "Fartatesti","Seciu", NOW(), NOW()),
            (41, "Fartatesti","Stanculesti", NOW(), NOW()),
            (41, "Fartatesti","Tanislavi", NOW(), NOW()),
            (41, "Fartatesti","Valea Ursului", NOW(), NOW()),
            (41, "Fartatesti","Sotani", NOW(), NOW()),
            (41, "Fauresti","Budesti", NOW(), NOW()),
            (41, "Fauresti","Bungetani", NOW(), NOW()),
            (41, "Fauresti","Babeni-Oltetu", NOW(), NOW()),
            (41, "Fauresti","Colelia", NOW(), NOW()),
            (41, "Fauresti","Diculesti", NOW(), NOW()),
            (41, "Fauresti","Gainesti", NOW(), NOW()),
            (41, "Fauresti","Milesti", NOW(), NOW()),
            (41, "Fauresti","Marcusu", NOW(), NOW()),
            (41, "Francesti","Balutoaia", NOW(), NOW()),
            (41, "Francesti","Cosani", NOW(), NOW()),
            (41, "Francesti","Dezrobiti", NOW(), NOW()),
            (41, "Francesti","Genuneni", NOW(), NOW()),
            (41, "Francesti","Mosteni", NOW(), NOW()),
            (41, "Francesti","Manailesti", NOW(), NOW()),
            (41, "Francesti","Surpatele", NOW(), NOW()),
            (41, "Francesti","Viisoara", NOW(), NOW()),
            (41, "Galicea","Bratia din Deal", NOW(), NOW()),
            (41, "Galicea","Bratia din Vale", NOW(), NOW()),
            (41, "Galicea","Cocoru", NOW(), NOW()),
            (41, "Galicea","Cremenari", NOW(), NOW()),
            (41, "Galicea","Dealu Mare", NOW(), NOW()),
            (41, "Galicea","Ostroveni", NOW(), NOW()),
            (41, "Galicea","Teiu", NOW(), NOW()),
            (41, "Galicea","Valea Raului", NOW(), NOW()),
            (41, "Ghioroiu","Cazanesti", NOW(), NOW()),
            (41, "Ghioroiu","Herasti", NOW(), NOW()),
            (41, "Ghioroiu","Mierea", NOW(), NOW()),
            (41, "Ghioroiu","Poienari", NOW(), NOW()),
            (41, "Ghioroiu","Stirbesti", NOW(), NOW()),
            (41, "Glavile","Aninoasa", NOW(), NOW()),
            (41, "Glavile","Jarostea", NOW(), NOW()),
            (41, "Glavile","Olteanca", NOW(), NOW()),
            (41, "Glavile","Voiculeasa", NOW(), NOW()),
            (41, "Golesti","Aldesti", NOW(), NOW()),
            (41, "Golesti","Blidari", NOW(), NOW()),
            (41, "Golesti","Coasta", NOW(), NOW()),
            (41, "Golesti","Draganesti", NOW(), NOW()),
            (41, "Golesti","Gibesti", NOW(), NOW()),
            (41, "Golesti","Giurgiuveni", NOW(), NOW()),
            (41, "Golesti","Opatesti", NOW(), NOW()),
            (41, "Golesti","Poenita", NOW(), NOW()),
            (41, "Golesti","Popesti", NOW(), NOW()),
            (41, "Golesti","Tulei-Campeni", NOW(), NOW()),
            (41, "Golesti","Vatasesti", NOW(), NOW()),
            (41, "Gradistea","Diaconesti", NOW(), NOW()),
            (41, "Gradistea","Dobricea", NOW(), NOW()),
            (41, "Gradistea","Linia", NOW(), NOW()),
            (41, "Gradistea","Obislavu", NOW(), NOW()),
            (41, "Gradistea","Strachinesti", NOW(), NOW()),
            (41, "Gradistea","Turburea", NOW(), NOW()),
            (41, "Gradistea","Valea Gradistei", NOW(), NOW()),
            (41, "Gradistea","Tuturu", NOW(), NOW()),
            (41, "Gusoeni","Burdalesti", NOW(), NOW()),
            (41, "Gusoeni","Dealu Mare", NOW(), NOW()),
            (41, "Gusoeni","Gusoianca", NOW(), NOW()),
            (41, "Gusoeni","Magureni", NOW(), NOW()),
            (41, "Gusoeni","Sparleni", NOW(), NOW()),
            (41, "Horezu","Ifrimesti", NOW(), NOW()),
            (41, "Horezu","Romanii de Jos", NOW(), NOW()),
            (41, "Horezu","Romanii de Sus", NOW(), NOW()),
            (41, "Horezu","Ramesti", NOW(), NOW()),
            (41, "Horezu","Tanasesti", NOW(), NOW()),
            (41, "Horezu","Ursani", NOW(), NOW()),
            (41, "Ionesti","Bucsani", NOW(), NOW()),
            (41, "Ionesti","Dealu Mare", NOW(), NOW()),
            (41, "Ionesti","Delureni", NOW(), NOW()),
            (41, "Ionesti","Fiscalia", NOW(), NOW()),
            (41, "Ionesti","Fotesti", NOW(), NOW()),
            (41, "Ionesti","Guguianca", NOW(), NOW()),
            (41, "Ionesti","Marcea", NOW(), NOW()),
            (41, "Ionesti","Prodanesti", NOW(), NOW()),
            (41, "Ladesti","Cermegesti", NOW(), NOW()),
            (41, "Ladesti","Chiricesti", NOW(), NOW()),
            (41, "Ladesti","Ciumagi", NOW(), NOW()),
            (41, "Ladesti","Dealu Corni", NOW(), NOW()),
            (41, "Ladesti","Gageni", NOW(), NOW()),
            (41, "Ladesti","Maldaresti", NOW(), NOW()),
            (41, "Ladesti","Olteanca", NOW(), NOW()),
            (41, "Ladesti","Popesti", NOW(), NOW()),
            (41, "Ladesti","Pasculesti", NOW(), NOW()),
            (41, "Lalosu","Berbesti", NOW(), NOW()),
            (41, "Lalosu","Ghindari", NOW(), NOW()),
            (41, "Lalosu","Mologesti", NOW(), NOW()),
            (41, "Lalosu","Oltetani", NOW(), NOW()),
            (41, "Lalosu","Portaresti", NOW(), NOW()),
            (41, "Lapusata","Beresti", NOW(), NOW()),
            (41, "Lapusata","Brosteni", NOW(), NOW()),
            (41, "Lapusata","Mijati", NOW(), NOW()),
            (41, "Lapusata","Scorusu", NOW(), NOW()),
            (41, "Lapusata","Sarulesti", NOW(), NOW()),
            (41, "Lapusata","Zarnesti", NOW(), NOW()),
            (41, "Lapusata","Serbanesti", NOW(), NOW()),
            (41, "Livezi","Plesoiu", NOW(), NOW()),
            (41, "Livezi","Paraienii de Jos", NOW(), NOW()),
            (41, "Livezi","Paraienii de Mijloc", NOW(), NOW()),
            (41, "Livezi","Paraienii de Sus", NOW(), NOW()),
            (41, "Livezi","Parausani", NOW(), NOW()),
            (41, "Livezi","Tina", NOW(), NOW()),
            (41, "Lungesti","Carcadiesti", NOW(), NOW()),
            (41, "Lungesti","Dumbrava", NOW(), NOW()),
            (41, "Lungesti","Fumureni", NOW(), NOW()),
            (41, "Lungesti","Gantulei", NOW(), NOW()),
            (41, "Lungesti","Stanesti-Lunca", NOW(), NOW()),
            (41, "Maciuca","Bocsa", NOW(), NOW()),
            (41, "Maciuca","Botorani", NOW(), NOW()),
            (41, "Maciuca","Ciocanari", NOW(), NOW()),
            (41, "Maciuca","Maciuceni", NOW(), NOW()),
            (41, "Maciuca","Maldaresti", NOW(), NOW()),
            (41, "Maciuca","Oveselu", NOW(), NOW()),
            (41, "Maciuca","Popesti", NOW(), NOW()),
            (41, "Maciuca","Zavoieni", NOW(), NOW()),
            (41, "Maciuca","Stefanesti", NOW(), NOW()),
            (41, "Madulari","Balsoara", NOW(), NOW()),
            (41, "Madulari","Bantesti", NOW(), NOW()),
            (41, "Madulari","Dimulesti", NOW(), NOW()),
            (41, "Madulari","Iacovile", NOW(), NOW()),
            (41, "Madulari","Mamu", NOW(), NOW()),
            (41, "Malaia","Ciungetu", NOW(), NOW()),
            (41, "Malaia","Salistea", NOW(), NOW()),
            (41, "Maldaresti","Maldarestii de Jos", NOW(), NOW()),
            (41, "Maldaresti","Rosoveni", NOW(), NOW()),
            (41, "Maldaresti","Telechesti", NOW(), NOW()),
            (41, "Mateesti","Greci", NOW(), NOW()),
            (41, "Mateesti","Turcesti", NOW(), NOW()),
            (41, "Mihaesti","Arsanca", NOW(), NOW()),
            (41, "Mihaesti","Buleta", NOW(), NOW()),
            (41, "Mihaesti","Barsesti", NOW(), NOW()),
            (41, "Mihaesti","Govora", NOW(), NOW()),
            (41, "Mihaesti","Gurisoara", NOW(), NOW()),
            (41, "Mihaesti","Munteni", NOW(), NOW()),
            (41, "Mihaesti","Magura", NOW(), NOW()),
            (41, "Mihaesti","Negreni", NOW(), NOW()),
            (41, "Mihaesti","Rugetu", NOW(), NOW()),
            (41, "Mihaesti","Scarisoara", NOW(), NOW()),
            (41, "Mihaesti","Stuparei", NOW(), NOW()),
            (41, "Mihaesti","Vulpuesti", NOW(), NOW()),
            (41, "Milcoiu","Ciutesti", NOW(), NOW()),
            (41, "Milcoiu","Cazanesti", NOW(), NOW()),
            (41, "Milcoiu","Izbasesti", NOW(), NOW()),
            (41, "Milcoiu","Tepsenari", NOW(), NOW()),
            (41, "Milcoiu","Suricaru", NOW(), NOW()),
            (41, "Muereasca","Andreiesti", NOW(), NOW()),
            (41, "Muereasca","Francesti-Coasta", NOW(), NOW()),
            (41, "Muereasca","Gavanesti", NOW(), NOW()),
            (41, "Muereasca","Hotarele", NOW(), NOW()),
            (41, "Muereasca","Muereasca de Sus", NOW(), NOW()),
            (41, "Muereasca","Pripoara", NOW(), NOW()),
            (41, "Muereasca","Suta", NOW(), NOW()),
            (41, "Nicolae Balcescu","Banesti", NOW(), NOW()),
            (41, "Nicolae Balcescu","Corbii din Vale", NOW(), NOW()),
            (41, "Nicolae Balcescu","Dosu Raului", NOW(), NOW()),
            (41, "Nicolae Balcescu","Ginerica", NOW(), NOW()),
            (41, "Nicolae Balcescu","Galtofani", NOW(), NOW()),
            (41, "Nicolae Balcescu","Linia Hanului", NOW(), NOW()),
            (41, "Nicolae Balcescu","Mangureni", NOW(), NOW()),
            (41, "Nicolae Balcescu","Mazararu", NOW(), NOW()),
            (41, "Nicolae Balcescu","Plesoiu", NOW(), NOW()),
            (41, "Nicolae Balcescu","Popesti", NOW(), NOW()),
            (41, "Nicolae Balcescu","Predesti", NOW(), NOW()),
            (41, "Nicolae Balcescu","Rotarasti", NOW(), NOW()),
            (41, "Nicolae Balcescu","Schitu", NOW(), NOW()),
            (41, "Nicolae Balcescu","Tufanii", NOW(), NOW()),
            (41, "Nicolae Balcescu","Valea Balceasca", NOW(), NOW()),
            (41, "Nicolae Balcescu","Valea Viei", NOW(), NOW()),
            (41, "Nicolae Balcescu","Serbaneasa", NOW(), NOW()),
            (41, "Ocnele Mari","Buda", NOW(), NOW()),
            (41, "Ocnele Mari","Cosota", NOW(), NOW()),
            (41, "Ocnele Mari","Facai", NOW(), NOW()),
            (41, "Ocnele Mari","Gura Suhasului", NOW(), NOW()),
            (41, "Ocnele Mari","Lunca", NOW(), NOW()),
            (41, "Ocnele Mari","Ocnita", NOW(), NOW()),
            (41, "Ocnele Mari","Slatioarele", NOW(), NOW()),
            (41, "Ocnele Mari","Teica", NOW(), NOW()),
            (41, "Olanu","Casa Veche", NOW(), NOW()),
            (41, "Olanu","Cioboti", NOW(), NOW()),
            (41, "Olanu","Dragioiu", NOW(), NOW()),
            (41, "Olanu","Nicolesti", NOW(), NOW()),
            (41, "Olanu","Stoicanesti", NOW(), NOW()),
            (41, "Orlesti","Auresti", NOW(), NOW()),
            (41, "Orlesti","Procopoaia", NOW(), NOW()),
            (41, "Orlesti","Scaiosi", NOW(), NOW()),
            (41, "Orlesti","Silea", NOW(), NOW()),
            (41, "Otesani","Bogdanesti", NOW(), NOW()),
            (41, "Otesani","Cucesti", NOW(), NOW()),
            (41, "Otesani","Carstanesti", NOW(), NOW()),
            (41, "Otesani","Sub Deal", NOW(), NOW()),
            (41, "Pausesti","Barcanele", NOW(), NOW()),
            (41, "Pausesti","Buzdugan", NOW(), NOW()),
            (41, "Pausesti","Cernelele", NOW(), NOW()),
            (41, "Pausesti","Pausesti-Otasau", NOW(), NOW()),
            (41, "Pausesti","Valeni", NOW(), NOW()),
            (41, "Pausesti","Serbanesti", NOW(), NOW()),
            (41, "Pausesti","Solicesti", NOW(), NOW()),
            (41, "Pausesti-Maglasi","Coasta", NOW(), NOW()),
            (41, "Pausesti-Maglasi","Pietrari", NOW(), NOW()),
            (41, "Pausesti-Maglasi","Ulmetel", NOW(), NOW()),
            (41, "Pausesti-Maglasi","Valea Cheii", NOW(), NOW()),
            (41, "Pausesti-Maglasi","Vladuceni", NOW(), NOW()),
            (41, "Perisani","Baiasu", NOW(), NOW()),
            (41, "Perisani","Mlaceni", NOW(), NOW()),
            (41, "Perisani","Podeni", NOW(), NOW()),
            (41, "Perisani","Poiana", NOW(), NOW()),
            (41, "Perisani","Pripoare", NOW(), NOW()),
            (41, "Perisani","Spinu", NOW(), NOW()),
            (41, "Perisani","Surdoiu", NOW(), NOW()),
            (41, "Pesceana","Cermegesti", NOW(), NOW()),
            (41, "Pesceana","Lupoaia", NOW(), NOW()),
            (41, "Pesceana","Negraia", NOW(), NOW()),
            (41, "Pesceana","Roesti", NOW(), NOW()),
            (41, "Pesceana","Ursoaia", NOW(), NOW()),
            (41, "Pietrari","Pietrarii de Sus", NOW(), NOW()),
            (41, "Popesti","Curtea", NOW(), NOW()),
            (41, "Popesti","Daesti", NOW(), NOW()),
            (41, "Popesti","Firijba", NOW(), NOW()),
            (41, "Popesti","Meieni", NOW(), NOW()),
            (41, "Popesti","Ursi", NOW(), NOW()),
            (41, "Popesti","Valea Caselor", NOW(), NOW()),
            (41, "Prundeni","Barbuceni", NOW(), NOW()),
            (41, "Prundeni","Calina", NOW(), NOW()),
            (41, "Prundeni","Zavideni", NOW(), NOW()),
            (41, "Racovita","Balota", NOW(), NOW()),
            (41, "Racovita","Blanoiu", NOW(), NOW()),
            (41, "Racovita","Bradu-Clocotici", NOW(), NOW()),
            (41, "Racovita","Copaceni", NOW(), NOW()),
            (41, "Racovita","Gruiu Lupului", NOW(), NOW()),
            (41, "Racovita","Tutulesti", NOW(), NOW()),
            (41, "Ramnicu Valcea","Aranghel", NOW(), NOW()),
            (41, "Ramnicu Valcea","Copacelu", NOW(), NOW()),
            (41, "Ramnicu Valcea","Cazanesti", NOW(), NOW()),
            (41, "Ramnicu Valcea","Dealu Malului", NOW(), NOW()),
            (41, "Ramnicu Valcea","Feteni", NOW(), NOW()),
            (41, "Ramnicu Valcea","Goranu", NOW(), NOW()),
            (41, "Ramnicu Valcea","Lespezi", NOW(), NOW()),
            (41, "Ramnicu Valcea","Poenari", NOW(), NOW()),
            (41, "Ramnicu Valcea","Priba", NOW(), NOW()),
            (41, "Ramnicu Valcea","Raureni", NOW(), NOW()),
            (41, "Ramnicu Valcea","Stolniceni", NOW(), NOW()),
            (41, "Ramnicu Valcea","Salistea", NOW(), NOW()),
            (41, "Ramnicu Valcea","Troian", NOW(), NOW()),
            (41, "Roesti","Baiasa", NOW(), NOW()),
            (41, "Roesti","Bajenari", NOW(), NOW()),
            (41, "Roesti","Barbarigeni", NOW(), NOW()),
            (41, "Roesti","Ciocaltei", NOW(), NOW()),
            (41, "Roesti","Cueni", NOW(), NOW()),
            (41, "Roesti","Frasina", NOW(), NOW()),
            (41, "Roesti","Piscu Scoartei", NOW(), NOW()),
            (41, "Roesti","Rapa Caramizii", NOW(), NOW()),
            (41, "Roesti","Saioci", NOW(), NOW()),
            (41, "Rosiile","Balaciu", NOW(), NOW()),
            (41, "Rosiile","Cherasti", NOW(), NOW()),
            (41, "Rosiile","Hotaroaia", NOW(), NOW()),
            (41, "Rosiile","Lupuiesti", NOW(), NOW()),
            (41, "Rosiile","Pertesti", NOW(), NOW()),
            (41, "Rosiile","Plesesti", NOW(), NOW()),
            (41, "Rosiile","Pasarei", NOW(), NOW()),
            (41, "Rosiile","Romanesti", NOW(), NOW()),
            (41, "Rosiile","Ratalesti", NOW(), NOW()),
            (41, "Rosiile","Zgubea", NOW(), NOW()),
            (41, "Runcu","Caligi", NOW(), NOW()),
            (41, "Runcu","Gropeni", NOW(), NOW()),
            (41, "Runcu","Snamana", NOW(), NOW()),
            (41, "Runcu","Surpati", NOW(), NOW()),
            (41, "Runcu","Valea Babei", NOW(), NOW()),
            (41, "Runcu","Varateci", NOW(), NOW()),
            (41, "Salatrucel","Patesti", NOW(), NOW()),
            (41, "Salatrucel","Seaca", NOW(), NOW()),
            (41, "Salatrucel","Serbanesti", NOW(), NOW()),
            (41, "Scundu","Avramesti", NOW(), NOW()),
            (41, "Scundu","Blejani", NOW(), NOW()),
            (41, "Scundu","Crangu", NOW(), NOW()),
            (41, "Sinesti","Ciucheti", NOW(), NOW()),
            (41, "Sinesti","Dealu Bisericii", NOW(), NOW()),
            (41, "Sinesti","Mijlocu", NOW(), NOW()),
            (41, "Sinesti","Popesti", NOW(), NOW()),
            (41, "Sinesti","Urzica", NOW(), NOW()),
            (41, "Sirineasa","Aricioaia", NOW(), NOW()),
            (41, "Sirineasa","Ciorasti", NOW(), NOW()),
            (41, "Sirineasa","Slavitesti", NOW(), NOW()),
            (41, "Sirineasa","Valea Alunisului", NOW(), NOW()),
            (41, "Slatioara","Coasta Cerbului", NOW(), NOW()),
            (41, "Slatioara","Gorunesti", NOW(), NOW()),
            (41, "Slatioara","Milostea", NOW(), NOW()),
            (41, "Slatioara","Mogesti", NOW(), NOW()),
            (41, "Slatioara","Rugetu", NOW(), NOW()),
            (41, "Stanesti","Barcanesti", NOW(), NOW()),
            (41, "Stanesti","Cioponesti", NOW(), NOW()),
            (41, "Stanesti","Cuculesti", NOW(), NOW()),
            (41, "Stanesti","Garnicetu", NOW(), NOW()),
            (41, "Stanesti","Linia Dealului", NOW(), NOW()),
            (41, "Stanesti","Suiesti", NOW(), NOW()),
            (41, "Stanesti","Valea Lunga", NOW(), NOW()),
            (41, "Stanesti","Varleni", NOW(), NOW()),
            (41, "Stefanesti","Condoiesti", NOW(), NOW()),
            (41, "Stefanesti","Dobrusa", NOW(), NOW()),
            (41, "Stefanesti","Serbanesti", NOW(), NOW()),
            (41, "Stoenesti","Budurasti", NOW(), NOW()),
            (41, "Stoenesti","Barlogu", NOW(), NOW()),
            (41, "Stoenesti","Deleni", NOW(), NOW()),
            (41, "Stoenesti","Dobriceni", NOW(), NOW()),
            (41, "Stoenesti","Gruieri", NOW(), NOW()),
            (41, "Stoenesti","Gruiu", NOW(), NOW()),
            (41, "Stoenesti","Mogosesti", NOW(), NOW()),
            (41, "Stoenesti","Neghinesti", NOW(), NOW()),
            (41, "Stoenesti","Piscu Mare", NOW(), NOW()),
            (41, "Stoenesti","Popesti", NOW(), NOW()),
            (41, "Stoenesti","Suseni", NOW(), NOW()),
            (41, "Stoenesti","Zmeuratu", NOW(), NOW()),
            (41, "Stoilesti","Balomireasa", NOW(), NOW()),
            (41, "Stoilesti","Bulagei", NOW(), NOW()),
            (41, "Stoilesti","Barsoiu", NOW(), NOW()),
            (41, "Stoilesti","Delureni", NOW(), NOW()),
            (41, "Stoilesti","Geamana", NOW(), NOW()),
            (41, "Stoilesti","Ghiobesti", NOW(), NOW()),
            (41, "Stoilesti","Giuroiu", NOW(), NOW()),
            (41, "Stoilesti","Izvoru Rece", NOW(), NOW()),
            (41, "Stoilesti","Malu", NOW(), NOW()),
            (41, "Stoilesti","Netesti", NOW(), NOW()),
            (41, "Stoilesti","Obogeni", NOW(), NOW()),
            (41, "Stoilesti","Stanesti", NOW(), NOW()),
            (41, "Stoilesti","Ursi", NOW(), NOW()),
            (41, "Stoilesti","Vladulesti", NOW(), NOW()),
            (41, "Stroesti","Ciresu", NOW(), NOW()),
            (41, "Stroesti","Dianu", NOW(), NOW()),
            (41, "Stroesti","Obrocesti", NOW(), NOW()),
            (41, "Stroesti","Pojogi-Cerna", NOW(), NOW()),
            (41, "Susani","Ramesti", NOW(), NOW()),
            (41, "Susani","Stoiculesti", NOW(), NOW()),
            (41, "Susani","Sarbi", NOW(), NOW()),
            (41, "Susani","Usurei", NOW(), NOW()),
            (41, "Sutesti","Borosesti", NOW(), NOW()),
            (41, "Sutesti","Cetateaua", NOW(), NOW()),
            (41, "Sutesti","Izvorasu", NOW(), NOW()),
            (41, "Sutesti","Mitrofani", NOW(), NOW()),
            (41, "Sutesti","Mazili", NOW(), NOW()),
            (41, "Sutesti","Racu", NOW(), NOW()),
            (41, "Sutesti","Verdea", NOW(), NOW()),
            (41, "Tetoiu","Budele", NOW(), NOW()),
            (41, "Tetoiu","Baroiu", NOW(), NOW()),
            (41, "Tetoiu","Maneasa", NOW(), NOW()),
            (41, "Tetoiu","Nenciulesti", NOW(), NOW()),
            (41, "Tetoiu","Popesti", NOW(), NOW()),
            (41, "Tetoiu","Tepesti", NOW(), NOW()),
            (41, "Titesti","Bratovesti", NOW(), NOW()),
            (41, "Titesti","Cucoiu", NOW(), NOW()),
            (41, "Tomsani","Bogdanesti", NOW(), NOW()),
            (41, "Tomsani","Baltateni", NOW(), NOW()),
            (41, "Tomsani","Chiceni", NOW(), NOW()),
            (41, "Tomsani","Dumbravesti", NOW(), NOW()),
            (41, "Tomsani","Folestii de Jos", NOW(), NOW()),
            (41, "Tomsani","Folestii de Sus", NOW(), NOW()),
            (41, "Tomsani","Miresti", NOW(), NOW()),
            (41, "Vaideeni","Cerna", NOW(), NOW()),
            (41, "Vaideeni","Cornet", NOW(), NOW()),
            (41, "Vaideeni","Izvoru Rece", NOW(), NOW()),
            (41, "Vaideeni","Marita", NOW(), NOW()),
            (41, "Valea Mare","Batasani", NOW(), NOW()),
            (41, "Valea Mare","Delureni", NOW(), NOW()),
            (41, "Valea Mare","Draganu", NOW(), NOW()),
            (41, "Valea Mare","Margineni", NOW(), NOW()),
            (41, "Valea Mare","Pietroasa", NOW(), NOW()),
            (41, "Vladesti","Fundatura", NOW(), NOW()),
            (41, "Vladesti","Pleasa", NOW(), NOW()),
            (41, "Vladesti","Priporu", NOW(), NOW()),
            (41, "Vladesti","Trundin", NOW(), NOW()),
            (41, "Voicesti","Tighina", NOW(), NOW()),
            (41, "Voicesti","Voicestii din Vale", NOW(), NOW()),
            (41, "Voineasa","Valea Macesului", NOW(), NOW()),
            (41, "Voineasa","Voinesita", NOW(), NOW()),
            (41, "Zatreni","Butanu", NOW(), NOW()),
            (41, "Zatreni","Ciortesti", NOW(), NOW()),
            (41, "Zatreni","Contea", NOW(), NOW()),
            (41, "Zatreni","Dealu Glameia", NOW(), NOW()),
            (41, "Zatreni","Dealu Valeni", NOW(), NOW()),
            (41, "Zatreni","Fauresti", NOW(), NOW()),
            (41, "Zatreni","Ganesti", NOW(), NOW()),
            (41, "Zatreni","Lacusteni", NOW(), NOW()),
            (41, "Zatreni","Lacustenii de Jos", NOW(), NOW()),
            (41, "Zatreni","Lacustenii de Sus", NOW(), NOW()),
            (41, "Zatreni","Mecea", NOW(), NOW()),
            (41, "Zatreni","Manicea", NOW(), NOW()),
            (41, "Zatreni","Oltetu", NOW(), NOW()),
            (41, "Zatreni","Stanomiru", NOW(), NOW()),
            (41, "Zatreni","Sascioara", NOW(), NOW()),
            (41, "Zatreni","Valea Valeni", NOW(), NOW()),
            (41, "Zatreni","Valeni", NOW(), NOW()),
            (41, "Zatreni","Zatrenii de Sus", NOW(), NOW())
        ;';
        DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = "DELETE FROM localities WHERE county_id=41;";
        DB::connection()->getPdo()->exec($sql);
    }
}
