<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForAR extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            ( 2, "","Almas", NOW(), NOW() ),
            ( 2, "","Apateu", NOW(), NOW() ),
            ( 2, "","Arad", NOW(), NOW() ),
            ( 2, "","Archis", NOW(), NOW() ),
            ( 2, "","Bata", NOW(), NOW() ),
            ( 2, "","Beliu", NOW(), NOW() ),
            ( 2, "","Birchis", NOW(), NOW() ),
            ( 2, "","Bocsig", NOW(), NOW() ),
            ( 2, "","Brazii", NOW(), NOW() ),
            ( 2, "","Buteni", NOW(), NOW() ),
            ( 2, "","Barsa", NOW(), NOW() ),
            ( 2, "","Barzava", NOW(), NOW() ),
            ( 2, "","Cermei", NOW(), NOW() ),
            ( 2, "","Chisindia", NOW(), NOW() ),
            ( 2, "","Chisineu-Cris", NOW(), NOW() ),
            ( 2, "","Conop", NOW(), NOW() ),
            ( 2, "","Covasint", NOW(), NOW() ),
            ( 2, "","Craiva", NOW(), NOW() ),
            ( 2, "","Curtici", NOW(), NOW() ),
            ( 2, "","Carand", NOW(), NOW() ),
            ( 2, "","Dezna", NOW(), NOW() ),
            ( 2, "","Dieci", NOW(), NOW() ),
            ( 2, "","Dorgos", NOW(), NOW() ),
            ( 2, "","Felnac", NOW(), NOW() ),
            ( 2, "","Ghioroc", NOW(), NOW() ),
            ( 2, "","Graniceri", NOW(), NOW() ),
            ( 2, "","Gurahont", NOW(), NOW() ),
            ( 2, "","Halmagiu", NOW(), NOW() ),
            ( 2, "","Halmagel", NOW(), NOW() ),
            ( 2, "","Hasmas", NOW(), NOW() ),
            ( 2, "","Ignesti", NOW(), NOW() ),
            ( 2, "","Ineu", NOW(), NOW() ),
            ( 2, "","Iratosu", NOW(), NOW() ),
            ( 2, "","Lipova", NOW(), NOW() ),
            ( 2, "","Livada", NOW(), NOW() ),
            ( 2, "","Macea", NOW(), NOW() ),
            ( 2, "","Misca", NOW(), NOW() ),
            ( 2, "","Moneasa", NOW(), NOW() ),
            ( 2, "","Nadlac", NOW(), NOW() ),
            ( 2, "","Olari", NOW(), NOW() ),
            ( 2, "","Pecica", NOW(), NOW() ),
            ( 2, "","Peregu Mare", NOW(), NOW() ),
            ( 2, "","Petris", NOW(), NOW() ),
            ( 2, "","Pilu", NOW(), NOW() ),
            ( 2, "","Plescuta", NOW(), NOW() ),
            ( 2, "","Pancota", NOW(), NOW() ),
            ( 2, "","Paulis", NOW(), NOW() ),
            ( 2, "","Sebis", NOW(), NOW() ),
            ( 2, "","Secusigiu", NOW(), NOW() ),
            ( 2, "","Seleus", NOW(), NOW() ),
            ( 2, "","Semlac", NOW(), NOW() ),
            ( 2, "","Sintea Mare", NOW(), NOW() ),
            ( 2, "","Socodor", NOW(), NOW() ),
            ( 2, "","Santana", NOW(), NOW() ),
            ( 2, "","Savarsin", NOW(), NOW() ),
            ( 2, "","Taut", NOW(), NOW() ),
            ( 2, "","Tarnova", NOW(), NOW() ),
            ( 2, "","Vinga", NOW(), NOW() ),
            ( 2, "","Vladimirescu", NOW(), NOW() ),
            ( 2, "","Varfurile", NOW(), NOW() ),
            ( 2, "","Varadia de Mures", NOW(), NOW() ),
            ( 2, "","Zerind", NOW(), NOW() ),
            ( 2, "","Zimandu Nou", NOW(), NOW() ),
            ( 2, "","Zabrani", NOW(), NOW() ),
            ( 2, "","Zarand", NOW(), NOW() ),
            ( 2, "","Sagu", NOW(), NOW() ),
            ( 2, "","Seitin", NOW(), NOW() ),
            ( 2, "","Sepreus", NOW(), NOW() ),
            ( 2, "","Sicula", NOW(), NOW() ),
            ( 2, "","Silindia", NOW(), NOW() ),
            ( 2, "","Simand", NOW(), NOW() ),
            ( 2, "","Siria", NOW(), NOW() ),
            ( 2, "","Sistarovat", NOW(), NOW() ),
            ( 2, "","Sofronea", NOW(), NOW() ),
            ( 2, "Almas","Cil", NOW(), NOW() ),
            ( 2, "Almas","Joia Mare", NOW(), NOW() ),
            ( 2, "Almas","Radesti", NOW(), NOW() ),
            ( 2, "Apateu","Berechiu", NOW(), NOW() ),
            ( 2, "Apateu","Motiori", NOW(), NOW() ),
            ( 2, "Archis","Barzesti", NOW(), NOW() ),
            ( 2, "Archis","Groseni", NOW(), NOW() ),
            ( 2, "Archis","Nermis", NOW(), NOW() ),
            ( 2, "Barsa","Aldesti", NOW(), NOW() ),
            ( 2, "Barsa","Hodis", NOW(), NOW() ),
            ( 2, "Barsa","Voivodeni", NOW(), NOW() ),
            ( 2, "Barzava","Batuta", NOW(), NOW() ),
            ( 2, "Barzava","Capruta", NOW(), NOW() ),
            ( 2, "Barzava","Dumbravita", NOW(), NOW() ),
            ( 2, "Barzava","Grosii Noi", NOW(), NOW() ),
            ( 2, "Barzava","Lalasint", NOW(), NOW() ),
            ( 2, "Barzava","Monorostia", NOW(), NOW() ),
            ( 2, "Barzava","Slatina de Mures", NOW(), NOW() ),
            ( 2, "Bata","Bacau de Mijloc", NOW(), NOW() ),
            ( 2, "Bata","Bulci", NOW(), NOW() ),
            ( 2, "Bata","Tela", NOW(), NOW() ),
            ( 2, "Beliu","Benesti", NOW(), NOW() ),
            ( 2, "Beliu","Bochia", NOW(), NOW() ),
            ( 2, "Beliu","Secaci", NOW(), NOW() ),
            ( 2, "Beliu","Tagadau", NOW(), NOW() ),
            ( 2, "Beliu","Vasile Goldis", NOW(), NOW() ),
            ( 2, "Birchis","Capalnas", NOW(), NOW() ),
            ( 2, "Birchis","Ostrov", NOW(), NOW() ),
            ( 2, "Birchis","Virismort", NOW(), NOW() ),
            ( 2, "Bocsig","Manerau", NOW(), NOW() ),
            ( 2, "Bocsig","Rapsig", NOW(), NOW() ),
            ( 2, "Brazii","Buceava-Soimus", NOW(), NOW() ),
            ( 2, "Brazii","Iacobini", NOW(), NOW() ),
            ( 2, "Brazii","Madrigesti", NOW(), NOW() ),
            ( 2, "Brazii","Secas", NOW(), NOW() ),
            ( 2, "Buteni","Berindia", NOW(), NOW() ),
            ( 2, "Buteni","Cuied", NOW(), NOW() ),
            ( 2, "Buteni","Paulian", NOW(), NOW() ),
            ( 2, "Carand","Selistea", NOW(), NOW() ),
            ( 2, "Cermei","Avram Iancu", NOW(), NOW() ),
            ( 2, "Cermei","Somosches", NOW(), NOW() ),
            ( 2, "Chisindia","Paiuseni", NOW(), NOW() ),
            ( 2, "Chisindia","Vasoaia", NOW(), NOW() ),
            ( 2, "Chisineu-Cris","Nadab", NOW(), NOW() ),
            ( 2, "Conop","Belotint", NOW(), NOW() ),
            ( 2, "Conop","Chelmac", NOW(), NOW() ),
            ( 2, "Conop","Milova", NOW(), NOW() ),
            ( 2, "Conop","Odvos", NOW(), NOW() ),
            ( 2, "Craiva","Chislaca", NOW(), NOW() ),
            ( 2, "Craiva","Ciuntesti", NOW(), NOW() ),
            ( 2, "Craiva","Coroi", NOW(), NOW() ),
            ( 2, "Craiva","Maraus", NOW(), NOW() ),
            ( 2, "Craiva","Rogoz de Beliu", NOW(), NOW() ),
            ( 2, "Craiva","Stoinesti", NOW(), NOW() ),
            ( 2, "Craiva","Susag", NOW(), NOW() ),
            ( 2, "Craiva","Talmaci", NOW(), NOW() ),
            ( 2, "Craiva","Siad", NOW(), NOW() ),
            ( 2, "Curtici","Dorobanti", NOW(), NOW() ),
            ( 2, "Dezna","Buhani", NOW(), NOW() ),
            ( 2, "Dezna","Laz", NOW(), NOW() ),
            ( 2, "Dezna","Neagra", NOW(), NOW() ),
            ( 2, "Dezna","Slatina de Cris", NOW(), NOW() ),
            ( 2, "Dieci","Cociuba", NOW(), NOW() ),
            ( 2, "Dieci","Crocna", NOW(), NOW() ),
            ( 2, "Dieci","Revetis", NOW(), NOW() ),
            ( 2, "Dieci","Rosia", NOW(), NOW() ),
            ( 2, "Dorgos","Bruznic", NOW(), NOW() ),
            ( 2, "Dorgos","Patars", NOW(), NOW() ),
            ( 2, "Dorgos","Ususau", NOW(), NOW() ),
            ( 2, "Dorgos","Zabalt", NOW(), NOW() ),
            ( 2, "Fantinele","Alunis", NOW(), NOW() ),
            ( 2, "Fantinele","Frumuseni", NOW(), NOW() ),
            ( 2, "Fantinele","Fantanele", NOW(), NOW() ),
            ( 2, "Fantinele","Tisa Noua", NOW(), NOW() ),
            ( 2, "Felnac","Bodrogu Nou", NOW(), NOW() ),
            ( 2, "Felnac","Calugareni", NOW(), NOW() ),
            ( 2, "Felnac","Zadareni", NOW(), NOW() ),
            ( 2, "Ghioroc","Cuvin", NOW(), NOW() ),
            ( 2, "Ghioroc","Minis", NOW(), NOW() ),
            ( 2, "Graniceri","Siclau", NOW(), NOW() ),
            ( 2, "Gurahont","Bontesti", NOW(), NOW() ),
            ( 2, "Gurahont","Dulcele", NOW(), NOW() ),
            ( 2, "Gurahont","Fenis", NOW(), NOW() ),
            ( 2, "Gurahont","Hontisor", NOW(), NOW() ),
            ( 2, "Gurahont","Iosas", NOW(), NOW() ),
            ( 2, "Gurahont","Mustesti", NOW(), NOW() ),
            ( 2, "Gurahont","Pescari", NOW(), NOW() ),
            ( 2, "Gurahont","Valea Mare", NOW(), NOW() ),
            ( 2, "Gurahont","Zimbru", NOW(), NOW() ),
            ( 2, "Halmagel","Luncsoara", NOW(), NOW() ),
            ( 2, "Halmagel","Sarbi", NOW(), NOW() ),
            ( 2, "Halmagel","Tarnavita", NOW(), NOW() ),
            ( 2, "Halmagel","Tohesti", NOW(), NOW() ),
            ( 2, "Halmagiu","Bodesti", NOW(), NOW() ),
            ( 2, "Halmagiu","Brusturi", NOW(), NOW() ),
            ( 2, "Halmagiu","Banesti", NOW(), NOW() ),
            ( 2, "Halmagiu","Cristesti", NOW(), NOW() ),
            ( 2, "Halmagiu","Ionesti", NOW(), NOW() ),
            ( 2, "Halmagiu","Leasa", NOW(), NOW() ),
            ( 2, "Halmagiu","Lestioara", NOW(), NOW() ),
            ( 2, "Halmagiu","Poienari", NOW(), NOW() ),
            ( 2, "Halmagiu","Tisa", NOW(), NOW() ),
            ( 2, "Halmagiu","Tarmure", NOW(), NOW() ),
            ( 2, "Hasmas","Agrisu Mic", NOW(), NOW() ),
            ( 2, "Hasmas","Botfei", NOW(), NOW() ),
            ( 2, "Hasmas","Clit", NOW(), NOW() ),
            ( 2, "Hasmas","Comanesti", NOW(), NOW() ),
            ( 2, "Hasmas","Urvisu de Beliu", NOW(), NOW() ),
            ( 2, "Ignesti","Minead", NOW(), NOW() ),
            ( 2, "Ignesti","Nadalbesti", NOW(), NOW() ),
            ( 2, "Ignesti","Susani", NOW(), NOW() ),
            ( 2, "Ineu","Mocrea", NOW(), NOW() ),
            ( 2, "Iratosu","Variasu Mare", NOW(), NOW() ),
            ( 2, "Iratosu","Variasu Mic", NOW(), NOW() ),
            ( 2, "Lipova","Radna", NOW(), NOW() ),
            ( 2, "Lipova","Soimos", NOW(), NOW() ),
            ( 2, "Livada","Sanleani", NOW(), NOW() ),
            ( 2, "Macea","Sanmartin", NOW(), NOW() ),
            ( 2, "Misca","Satu Nou", NOW(), NOW() ),
            ( 2, "Misca","Vanatori", NOW(), NOW() ),
            ( 2, "Misca","Zerindu Mic", NOW(), NOW() ),
            ( 2, "Moneasa","Ranusa", NOW(), NOW() ),
            ( 2, "Olari","Sintea Mica", NOW(), NOW() ),
            ( 2, "Pancota","Maderat", NOW(), NOW() ),
            ( 2, "Paulis","Baratca", NOW(), NOW() ),
            ( 2, "Paulis","Cladova", NOW(), NOW() ),
            ( 2, "Paulis","Sambateni", NOW(), NOW() ),
            ( 2, "Pecica","Bodrogu Vechi", NOW(), NOW() ),
            ( 2, "Pecica","Sederhat", NOW(), NOW() ),
            ( 2, "Pecica","Turnu", NOW(), NOW() ),
            ( 2, "Peregu Mare","Peregu Mic", NOW(), NOW() ),
            ( 2, "Petris","Corbesti", NOW(), NOW() ),
            ( 2, "Petris","Ilteu", NOW(), NOW() ),
            ( 2, "Petris","Obarsia", NOW(), NOW() ),
            ( 2, "Petris","Rosia Noua", NOW(), NOW() ),
            ( 2, "Petris","Seliste", NOW(), NOW() ),
            ( 2, "Pilu","Varsand", NOW(), NOW() ),
            ( 2, "Plescuta","Aciuta", NOW(), NOW() ),
            ( 2, "Plescuta","Budesti", NOW(), NOW() ),
            ( 2, "Plescuta","Dumbrava", NOW(), NOW() ),
            ( 2, "Plescuta","Gura Vaii", NOW(), NOW() ),
            ( 2, "Plescuta","Rostoci", NOW(), NOW() ),
            ( 2, "Plescuta","Talagiu", NOW(), NOW() ),
            ( 2, "Sagu","Cruceni", NOW(), NOW() ),
            ( 2, "Sagu","Firiteaz", NOW(), NOW() ),
            ( 2, "Sagu","Fiscut", NOW(), NOW() ),
            ( 2, "Sagu","Hunedoara Timisana", NOW(), NOW() ),
            ( 2, "Santana","Caporal Alexa", NOW(), NOW() ),
            ( 2, "Savarsin","Cuias", NOW(), NOW() ),
            ( 2, "Savarsin","Caprioara", NOW(), NOW() ),
            ( 2, "Savarsin","Halalis", NOW(), NOW() ),
            ( 2, "Savarsin","Parnesti", NOW(), NOW() ),
            ( 2, "Savarsin","Temesesti", NOW(), NOW() ),
            ( 2, "Savarsin","Toc", NOW(), NOW() ),
            ( 2, "Savarsin","Troas", NOW(), NOW() ),
            ( 2, "Savarsin","Valea Mare", NOW(), NOW() ),
            ( 2, "Sebis","Donceni", NOW(), NOW() ),
            ( 2, "Sebis","Prunisor", NOW(), NOW() ),
            ( 2, "Sebis","Salajeni", NOW(), NOW() ),
            ( 2, "Secusigiu","Munar", NOW(), NOW() ),
            ( 2, "Secusigiu","Satu Mare", NOW(), NOW() ),
            ( 2, "Secusigiu","Sanpetru German", NOW(), NOW() ),
            ( 2, "Seleus","Iermata", NOW(), NOW() ),
            ( 2, "Seleus","Moroda", NOW(), NOW() ),
            ( 2, "Sicula","Cherelus", NOW(), NOW() ),
            ( 2, "Sicula","Gurba", NOW(), NOW() ),
            ( 2, "Silindia","Camna", NOW(), NOW() ),
            ( 2, "Silindia","Iercoseni", NOW(), NOW() ),
            ( 2, "Silindia","Luguzau", NOW(), NOW() ),
            ( 2, "Silindia","Satu Mic", NOW(), NOW() ),
            ( 2, "Sintea Mare","Adea", NOW(), NOW() ),
            ( 2, "Sintea Mare","Tipar", NOW(), NOW() ),
            ( 2, "Siria","Galsa", NOW(), NOW() ),
            ( 2, "Siria","Masca", NOW(), NOW() ),
            ( 2, "Sistarovat","Cuvesdia", NOW(), NOW() ),
            ( 2, "Sistarovat","Labasint", NOW(), NOW() ),
            ( 2, "Sistarovat","Varnita", NOW(), NOW() ),
            ( 2, "Sofronea","Sanpaul", NOW(), NOW() ),
            ( 2, "Tarnova","Agrisu Mare", NOW(), NOW() ),
            ( 2, "Tarnova","Araneag", NOW(), NOW() ),
            ( 2, "Tarnova","Chier", NOW(), NOW() ),
            ( 2, "Tarnova","Draut", NOW(), NOW() ),
            ( 2, "Tarnova","Dud", NOW(), NOW() ),
            ( 2, "Taut","Minisel", NOW(), NOW() ),
            ( 2, "Taut","Minisu de Sus", NOW(), NOW() ),
            ( 2, "Taut","Nadas", NOW(), NOW() ),
            ( 2, "Varadia De Mures","Baia", NOW(), NOW() ),
            ( 2, "Varadia De Mures","Julita", NOW(), NOW() ),
            ( 2, "Varadia De Mures","Lupesti", NOW(), NOW() ),
            ( 2, "Varadia De Mures","Nicolae Balcescu", NOW(), NOW() ),
            ( 2, "Varadia De Mures","Stejar", NOW(), NOW() ),
            ( 2, "Varfurile","Avram Iancu", NOW(), NOW() ),
            ( 2, "Varfurile","Grosi", NOW(), NOW() ),
            ( 2, "Varfurile","Lazuri", NOW(), NOW() ),
            ( 2, "Varfurile","Mermesti", NOW(), NOW() ),
            ( 2, "Varfurile","Magulicea", NOW(), NOW() ),
            ( 2, "Varfurile","Poiana", NOW(), NOW() ),
            ( 2, "Varfurile","Vidra", NOW(), NOW() ),
            ( 2, "Vinga","Mailat", NOW(), NOW() ),
            ( 2, "Vinga","Manastur", NOW(), NOW() ),
            ( 2, "Vladimirescu","Cicir", NOW(), NOW() ),
            ( 2, "Vladimirescu","Horia", NOW(), NOW() ),
            ( 2, "Vladimirescu","Mandruloc", NOW(), NOW() ),
            ( 2, "Zabrani","Chesint", NOW(), NOW() ),
            ( 2, "Zabrani","Neudorf", NOW(), NOW() ),
            ( 2, "Zarand","Cintei", NOW(), NOW() ),
            ( 2, "Zerind","Iermata Neagra", NOW(), NOW() ),
            ( 2, "Zimandu Nou","Andrei Saguna", NOW(), NOW() ),
            ( 2, "Zimandu Nou","Zimandcuz", NOW(), NOW() )

        ;';
        if (config('app.env') !== 'testing') {
            DB::connection()->getPdo()->exec($sql);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=2;';
        DB::connection()->getPdo()->exec($sql);
    }
}
