<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForAG extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (3, "","Albota", NOW(), NOW() ),
            (3, "","Aninoasa", NOW(), NOW() ),
            (3, "","Arefu", NOW(), NOW() ),
            (3, "","Bascov", NOW(), NOW() ),
            (3, "","Berevoesti", NOW(), NOW() ),
            (3, "","Bogati", NOW(), NOW() ),
            (3, "","Boteni", NOW(), NOW() ),
            (3, "","Botesti", NOW(), NOW() ),
            (3, "","Bradu", NOW(), NOW() ),
            (3, "","Bradulet", NOW(), NOW() ),
            (3, "","Bughea de Jos", NOW(), NOW() ),
            (3, "","Buzoesti", NOW(), NOW() ),
            (3, "","Barla", NOW(), NOW() ),
            (3, "","Babana", NOW(), NOW() ),
            (3, "","Baiculesti", NOW(), NOW() ),
            (3, "","Balilesti", NOW(), NOW() ),
            (3, "","Cetateni", NOW(), NOW() ),
            (3, "","Cicanesti", NOW(), NOW() ),
            (3, "","Ciofrangeni", NOW(), NOW() ),
            (3, "","Ciomagesti", NOW(), NOW() ),
            (3, "","Cocu", NOW(), NOW() ),
            (3, "","Corbeni", NOW(), NOW() ),
            (3, "","Corbi", NOW(), NOW() ),
            (3, "","Costesti", NOW(), NOW() ),
            (3, "","Cotmeana", NOW(), NOW() ),
            (3, "","Cosesti", NOW(), NOW() ),
            (3, "","Cuca", NOW(), NOW() ),
            (3, "","Curtea de Arges", NOW(), NOW() ),
            (3, "","Campulung", NOW(), NOW() ),
            (3, "","Caldararu", NOW(), NOW() ),
            (3, "","Calinesti", NOW(), NOW() ),
            (3, "","Cateasca", NOW(), NOW() ),
            (3, "","Davidesti", NOW(), NOW() ),
            (3, "","Dobresti", NOW(), NOW() ),
            (3, "","Domnesti", NOW(), NOW() ),
            (3, "","Dragoslavele", NOW(), NOW() ),
            (3, "","Dambovicioara", NOW(), NOW() ),
            (3, "","Darmanesti", NOW(), NOW() ),
            (3, "","Godeni", NOW(), NOW() ),
            (3, "","Harsesti", NOW(), NOW() ),
            (3, "","Hartiesti", NOW(), NOW() ),
            (3, "","Izvoru", NOW(), NOW() ),
            (3, "","Leordeni", NOW(), NOW() ),
            (3, "","Leresti", NOW(), NOW() ),
            (3, "","Lunca Corbului", NOW(), NOW() ),
            (3, "","Merisani", NOW(), NOW() ),
            (3, "","Micesti", NOW(), NOW() ),
            (3, "","Mihaesti", NOW(), NOW() ),
            (3, "","Mioveni", NOW(), NOW() ),
            (3, "","Mirosi", NOW(), NOW() ),
            (3, "","Moraresti", NOW(), NOW() ),
            (3, "","Mozaceni", NOW(), NOW() ),
            (3, "","Mosoaia", NOW(), NOW() ),
            (3, "","Musatesti", NOW(), NOW() ),
            (3, "","Malureni", NOW(), NOW() ),
            (3, "","Maracineni", NOW(), NOW() ),
            (3, "","Negrasi", NOW(), NOW() ),
            (3, "","Nucsoara", NOW(), NOW() ),
            (3, "","Oarja", NOW(), NOW() ),
            (3, "","Pietrosani", NOW(), NOW() ),
            (3, "","Pitesti", NOW(), NOW() ),
            (3, "","Poiana Lacului", NOW(), NOW() ),
            (3, "","Popesti", NOW(), NOW() ),
            (3, "","Priboieni", NOW(), NOW() ),
            (3, "","Recea", NOW(), NOW() ),
            (3, "","Rociu", NOW(), NOW() ),
            (3, "","Rucar", NOW(), NOW() ),
            (3, "","Raca", NOW(), NOW() ),
            (3, "","Ratesti", NOW(), NOW() ),
            (3, "","Schitu Golesti", NOW(), NOW() ),
            (3, "","Slobozia", NOW(), NOW() ),
            (3, "","Stoenesti", NOW(), NOW() ),
            (3, "","Stolnici", NOW(), NOW() ),
            (3, "","Stalpeni", NOW(), NOW() ),
            (3, "","Suseni", NOW(), NOW() ),
            (3, "","Salatrucu", NOW(), NOW() ),
            (3, "","Teiu", NOW(), NOW() ),
            (3, "","Tigveni", NOW(), NOW() ),
            (3, "","Topoloveni", NOW(), NOW() ),
            (3, "","Uda", NOW(), NOW() ),
            (3, "","Ungheni", NOW(), NOW() ),
            (3, "","Valea Danului", NOW(), NOW() ),
            (3, "","Valea Iasului", NOW(), NOW() ),
            (3, "","Valea Mare Pravat", NOW(), NOW() ),
            (3, "","Vedea", NOW(), NOW() ),
            (3, "","Vladesti", NOW(), NOW() ),
            (3, "","Vulturesti", NOW(), NOW() ),
            (3, "","Stefan cel Mare", NOW(), NOW() ),
            (3, "","Stefanesti", NOW(), NOW() ),
            (3, "","Suici", NOW(), NOW() ),
            (3, "","Titesti", NOW(), NOW() ),
            (3, "Albestii De Arges","Albestii Pamanteni", NOW(), NOW() ),
            (3, "Albestii De Arges","Albestii Ungureni", NOW(), NOW() ),
            (3, "Albestii De Arges","Bratesti", NOW(), NOW() ),
            (3, "Albestii De Arges","Doblea", NOW(), NOW() ),
            (3, "Albestii De Arges","Dobrotu", NOW(), NOW() ),
            (3, "Albestii De Arges","Dumiresti", NOW(), NOW() ),
            (3, "Albestii De Arges","Florieni", NOW(), NOW() ),
            (3, "Albestii De Muscel","Albesti", NOW(), NOW() ),
            (3, "Albestii De Muscel","Bughea de Sus", NOW(), NOW() ),
            (3, "Albestii De Muscel","Candesti", NOW(), NOW() ),
            (3, "Albota","Cerbu", NOW(), NOW() ),
            (3, "Albota","Fratesti", NOW(), NOW() ),
            (3, "Albota","Gura Vaii", NOW(), NOW() ),
            (3, "Albota","Mares", NOW(), NOW() ),
            (3, "Aninoasa","Brosteni", NOW(), NOW() ),
            (3, "Aninoasa","Slanic", NOW(), NOW() ),
            (3, "Aninoasa","Valea Silistii", NOW(), NOW() ),
            (3, "Arefu","Capatanenii Pamanteni", NOW(), NOW() ),
            (3, "Arefu","Capatanenii Ungureni", NOW(), NOW() ),
            (3, "Babana","Bajanesti", NOW(), NOW() ),
            (3, "Babana","Ciobanesti", NOW(), NOW() ),
            (3, "Babana","Cotmenita", NOW(), NOW() ),
            (3, "Babana","Grosi", NOW(), NOW() ),
            (3, "Babana","Lupueni", NOW(), NOW() ),
            (3, "Babana","Slaatioarele", NOW(), NOW() ),
            (3, "Baiculesti","Alunisu", NOW(), NOW() ),
            (3, "Baiculesti","Anghinesti", NOW(), NOW() ),
            (3, "Baiculesti","Argesani", NOW(), NOW() ),
            (3, "Baiculesti","Manicesti", NOW(), NOW() ),
            (3, "Baiculesti","Stejari", NOW(), NOW() ),
            (3, "Baiculesti","Tutana", NOW(), NOW() ),
            (3, "Baiculesti","Valea Brazilor", NOW(), NOW() ),
            (3, "Baiculesti","Valea lui Enache", NOW(), NOW() ),
            (3, "Baiculesti","Zigoneni", NOW(), NOW() ),
            (3, "Balilesti","Bajesti", NOW(), NOW() ),
            (3, "Balilesti","Golesti", NOW(), NOW() ),
            (3, "Balilesti","Poienita", NOW(), NOW() ),
            (3, "Balilesti","Priboaia", NOW(), NOW() ),
            (3, "Balilesti","Ulita", NOW(), NOW() ),
            (3, "Balilesti","Valea Mare-Bratia", NOW(), NOW() ),
            (3, "Barla","Afrimesti", NOW(), NOW() ),
            (3, "Barla","Brabeti", NOW(), NOW() ),
            (3, "Barla","Badesti", NOW(), NOW() ),
            (3, "Barla","Ciocesti", NOW(), NOW() ),
            (3, "Barla","Malu", NOW(), NOW() ),
            (3, "Barla","Mozacenii-Vale", NOW(), NOW() ),
            (3, "Barla","Mandra", NOW(), NOW() ),
            (3, "Barla","Podisoru", NOW(), NOW() ),
            (3, "Barla","Urlueni", NOW(), NOW() ),
            (3, "Barla","Zuvelcati", NOW(), NOW() ),
            (3, "Barla","Selareasca", NOW(), NOW() ),
            (3, "Bascov","Braileni", NOW(), NOW() ),
            (3, "Bascov","Glambocu", NOW(), NOW() ),
            (3, "Bascov","Mica", NOW(), NOW() ),
            (3, "Bascov","Prislopu Mic", NOW(), NOW() ),
            (3, "Bascov","Scheau", NOW(), NOW() ),
            (3, "Bascov","Uiasca", NOW(), NOW() ),
            (3, "Bascov","Valea Ursului", NOW(), NOW() ),
            (3, "Beleti-Negresti","Beleti", NOW(), NOW() ),
            (3, "Beleti-Negresti","Lentea", NOW(), NOW() ),
            (3, "Beleti-Negresti","Negresti", NOW(), NOW() ),
            (3, "Beleti-Negresti","Zgripcesti", NOW(), NOW() ),
            (3, "Berevoesti","Bratia", NOW(), NOW() ),
            (3, "Berevoesti","Gamacesti", NOW(), NOW() ),
            (3, "Berevoesti","Otelu", NOW(), NOW() ),
            (3, "Bogati","Bujoi", NOW(), NOW() ),
            (3, "Bogati","Barloi", NOW(), NOW() ),
            (3, "Bogati","Chitesti", NOW(), NOW() ),
            (3, "Bogati","Dumbrava", NOW(), NOW() ),
            (3, "Bogati","Glambocel", NOW(), NOW() ),
            (3, "Bogati","Glambocelu", NOW(), NOW() ),
            (3, "Bogati","Suseni", NOW(), NOW() ),
            (3, "Boteni","Balabani", NOW(), NOW() ),
            (3, "Boteni","Lunca", NOW(), NOW() ),
            (3, "Boteni","Muscel", NOW(), NOW() ),
            (3, "Botesti","Mosteni-Greci", NOW(), NOW() ),
            (3, "Bradu","Geamana", NOW(), NOW() ),
            (3, "Bradulet","Alunisu", NOW(), NOW() ),
            (3, "Bradulet","Bradetu", NOW(), NOW() ),
            (3, "Bradulet","Cosaci", NOW(), NOW() ),
            (3, "Bradulet","Galesu", NOW(), NOW() ),
            (3, "Bradulet","Piatra", NOW(), NOW() ),
            (3, "Bradulet","Slamnesti", NOW(), NOW() ),
            (3, "Bradulet","Uleni", NOW(), NOW() ),
            (3, "Bradulet","Ungureni", NOW(), NOW() ),
            (3, "Budeasa","Budeasa Mare", NOW(), NOW() ),
            (3, "Budeasa","Budeasa Mica", NOW(), NOW() ),
            (3, "Budeasa","Calotesti", NOW(), NOW() ),
            (3, "Budeasa","Galasesti", NOW(), NOW() ),
            (3, "Budeasa","Rogojina", NOW(), NOW() ),
            (3, "Budeasa","Valea Marului", NOW(), NOW() ),
            (3, "Buzoesti","Bujoreni", NOW(), NOW() ),
            (3, "Buzoesti","Cornatel", NOW(), NOW() ),
            (3, "Buzoesti","Curteanca", NOW(), NOW() ),
            (3, "Buzoesti","Ionesti", NOW(), NOW() ),
            (3, "Buzoesti","Podeni", NOW(), NOW() ),
            (3, "Buzoesti","Redea", NOW(), NOW() ),
            (3, "Buzoesti","Tomsanca", NOW(), NOW() ),
            (3, "Buzoesti","Vladuta", NOW(), NOW() ),
            (3, "Buzoesti","Vulpesti", NOW(), NOW() ),
            (3, "Buzoesti","Serboeni", NOW(), NOW() ),
            (3, "Caldararu","Burdea", NOW(), NOW() ),
            (3, "Caldararu","Strambeni", NOW(), NOW() ),
            (3, "Calinesti","Ciocanesti", NOW(), NOW() ),
            (3, "Calinesti","Carstieni", NOW(), NOW() ),
            (3, "Calinesti","Glodu", NOW(), NOW() ),
            (3, "Calinesti","Gorganu", NOW(), NOW() ),
            (3, "Calinesti","Radu Negru", NOW(), NOW() ),
            (3, "Calinesti","Rancaciov", NOW(), NOW() ),
            (3, "Calinesti","Udeni-Zavoi", NOW(), NOW() ),
            (3, "Calinesti","Urlucea", NOW(), NOW() ),
            (3, "Calinesti","Valea Corbului", NOW(), NOW() ),
            (3, "Calinesti","Vranesti", NOW(), NOW() ),
            (3, "Calinesti","Valeni-Podgoria", NOW(), NOW() ),
            (3, "Campulung","Valea Rumanestilor", NOW(), NOW() ),
            (3, "Cateasca","Catanele", NOW(), NOW() ),
            (3, "Cateasca","Ciresu", NOW(), NOW() ),
            (3, "Cateasca","Coseri", NOW(), NOW() ),
            (3, "Cateasca","Gruiu", NOW(), NOW() ),
            (3, "Cateasca","Recea", NOW(), NOW() ),
            (3, "Cateasca","Silistea", NOW(), NOW() ),
            (3, "Cepari","Ceparii Pamanteni", NOW(), NOW() ),
            (3, "Cepari","Ceparii Ungureni", NOW(), NOW() ),
            (3, "Cepari","Carpenis", NOW(), NOW() ),
            (3, "Cepari","Morasti", NOW(), NOW() ),
            (3, "Cepari","Urluiesti", NOW(), NOW() ),
            (3, "Cepari","Valea Magurei", NOW(), NOW() ),
            (3, "Cepari","Zamfiresti", NOW(), NOW() ),
            (3, "Cepari","Sendrulesti", NOW(), NOW() ),
            (3, "Cetateni","Laicai", NOW(), NOW() ),
            (3, "Cetateni","Valea Cetatuia", NOW(), NOW() ),
            (3, "Cicanesti","Barasti", NOW(), NOW() ),
            (3, "Cicanesti","Mioarele", NOW(), NOW() ),
            (3, "Cicanesti","Urechesti", NOW(), NOW() ),
            (3, "Ciofrangeni","Burlusi", NOW(), NOW() ),
            (3, "Ciofrangeni","Lacurile", NOW(), NOW() ),
            (3, "Ciofrangeni","Piatra", NOW(), NOW() ),
            (3, "Ciofrangeni","Schitu-Matei", NOW(), NOW() ),
            (3, "Ciomagesti","Beculesti", NOW(), NOW() ),
            (3, "Ciomagesti","Bratia", NOW(), NOW() ),
            (3, "Ciomagesti","Cungrea", NOW(), NOW() ),
            (3, "Ciomagesti","Dogari", NOW(), NOW() ),
            (3, "Ciomagesti","Fedelesoiu", NOW(), NOW() ),
            (3, "Ciomagesti","Giuclani", NOW(), NOW() ),
            (3, "Ciomagesti","Paunesti", NOW(), NOW() ),
            (3, "Ciomagesti","Radutesti", NOW(), NOW() ),
            (3, "Cocu","Barbatesti", NOW(), NOW() ),
            (3, "Cocu","Crucisoara", NOW(), NOW() ),
            (3, "Cocu","Facaletesti", NOW(), NOW() ),
            (3, "Cocu","Greabanu", NOW(), NOW() ),
            (3, "Cocu","Popesti", NOW(), NOW() ),
            (3, "Cocu","Rachitele de Jos", NOW(), NOW() ),
            (3, "Cocu","Rachitele de Sus", NOW(), NOW() ),
            (3, "Corbeni","Berindesti", NOW(), NOW() ),
            (3, "Corbeni","Bucsenesti", NOW(), NOW() ),
            (3, "Corbeni","Oestii Pamanteni", NOW(), NOW() ),
            (3, "Corbeni","Oestii Ungureni", NOW(), NOW() ),
            (3, "Corbeni","Poienari", NOW(), NOW() ),
            (3, "Corbeni","Rotunda", NOW(), NOW() ),
            (3, "Corbeni","Turburea", NOW(), NOW() ),
            (3, "Corbi","Corbsori", NOW(), NOW() ),
            (3, "Corbi","Jgheaburi", NOW(), NOW() ),
            (3, "Corbi","Poduri", NOW(), NOW() ),
            (3, "Corbi","Poienarei", NOW(), NOW() ),
            (3, "Corbi","Stanesti", NOW(), NOW() ),
            (3, "Cosesti","Jupanesti", NOW(), NOW() ),
            (3, "Cosesti","Leicesti", NOW(), NOW() ),
            (3, "Cosesti","Lapusani", NOW(), NOW() ),
            (3, "Cosesti","Petresti", NOW(), NOW() ),
            (3, "Cosesti","Priseaca", NOW(), NOW() ),
            (3, "Cosesti","Pacioiu", NOW(), NOW() ),
            (3, "Costesti","Brosteni", NOW(), NOW() ),
            (3, "Costesti","Laceni", NOW(), NOW() ),
            (3, "Costesti","Podu Brosteni", NOW(), NOW() ),
            (3, "Costesti","Parvu Rosu", NOW(), NOW() ),
            (3, "Costesti","Smei", NOW(), NOW() ),
            (3, "Costesti","Starci", NOW(), NOW() ),
            (3, "Cotmeana","Bascovele", NOW(), NOW() ),
            (3, "Cotmeana","Bunesti", NOW(), NOW() ),
            (3, "Cotmeana","Costesti", NOW(), NOW() ),
            (3, "Cotmeana","Dealu Padurii", NOW(), NOW() ),
            (3, "Cotmeana","Dragolesti", NOW(), NOW() ),
            (3, "Cotmeana","Lintesti", NOW(), NOW() ),
            (3, "Cotmeana","Negesti", NOW(), NOW() ),
            (3, "Cotmeana","Pielesti", NOW(), NOW() ),
            (3, "Cotmeana","Spiridoni", NOW(), NOW() ),
            (3, "Cotmeana","Sandulesti", NOW(), NOW() ),
            (3, "Cotmeana","Ursoaia", NOW(), NOW() ),
            (3, "Cotmeana","Varloveni", NOW(), NOW() ),
            (3, "Cotmeana","Zamfiresti", NOW(), NOW() ),
            (3, "Cuca","Baltata", NOW(), NOW() ),
            (3, "Cuca","Barbalani", NOW(), NOW() ),
            (3, "Cuca","Cotu", NOW(), NOW() ),
            (3, "Cuca","Crivatu", NOW(), NOW() ),
            (3, "Cuca","Carcesti", NOW(), NOW() ),
            (3, "Cuca","Launele de Sus", NOW(), NOW() ),
            (3, "Cuca","Macai", NOW(), NOW() ),
            (3, "Cuca","Manesti", NOW(), NOW() ),
            (3, "Cuca","Sinesti", NOW(), NOW() ),
            (3, "Cuca","Stanicei", NOW(), NOW() ),
            (3, "Cuca","Teodoresti", NOW(), NOW() ),
            (3, "Cuca","Valea Cucii", NOW(), NOW() ),
            (3, "Cuca","Vonigeasa", NOW(), NOW() ),
            (3, "Curtea De Arges","Noaptes", NOW(), NOW() ),
            (3, "Dambovicioara","Ciocanu", NOW(), NOW() ),
            (3, "Dambovicioara","Podu Dambovitei", NOW(), NOW() ),
            (3, "Darmanesti","Negreni", NOW(), NOW() ),
            (3, "Darmanesti","Piscani", NOW(), NOW() ),
            (3, "Darmanesti","Valea Nandrii", NOW(), NOW() ),
            (3, "Darmanesti","Valea Rizii", NOW(), NOW() ),
            (3, "Davidesti","Contesti", NOW(), NOW() ),
            (3, "Davidesti","Voroveni", NOW(), NOW() ),
            (3, "Dobresti","Furesti", NOW(), NOW() ),
            (3, "Draganu","Bacesti", NOW(), NOW() ),
            (3, "Draganu","Draganu-Olteni", NOW(), NOW() ),
            (3, "Draganu","Dumbravesti", NOW(), NOW() ),
            (3, "Draganu","Prislopu Mare", NOW(), NOW() ),
            (3, "Dragoslavele","Valea Hotarului", NOW(), NOW() ),
            (3, "Godeni","Bordeieni", NOW(), NOW() ),
            (3, "Godeni","Capu Piscului", NOW(), NOW() ),
            (3, "Godeni","Cotesti", NOW(), NOW() ),
            (3, "Godeni","Malu", NOW(), NOW() ),
            (3, "Harsesti","Ciobani", NOW(), NOW() ),
            (3, "Harsesti","Martalogi", NOW(), NOW() ),
            (3, "Hartiesti","Dealu", NOW(), NOW() ),
            (3, "Hartiesti","Lespezi", NOW(), NOW() ),
            (3, "Hartiesti","Lucieni", NOW(), NOW() ),
            (3, "Leordeni","Baloteasca", NOW(), NOW() ),
            (3, "Leordeni","Budisteni", NOW(), NOW() ),
            (3, "Leordeni","Bantau", NOW(), NOW() ),
            (3, "Leordeni","Baila", NOW(), NOW() ),
            (3, "Leordeni","Ciolcesti", NOW(), NOW() ),
            (3, "Leordeni","Ciulnita", NOW(), NOW() ),
            (3, "Leordeni","Cotu Malului", NOW(), NOW() ),
            (3, "Leordeni","Carciumaresti", NOW(), NOW() ),
            (3, "Leordeni","Glodu", NOW(), NOW() ),
            (3, "Leordeni","Glambocata", NOW(), NOW() ),
            (3, "Leordeni","Glambocata-Deal", NOW(), NOW() ),
            (3, "Leordeni","Moara Mocanului", NOW(), NOW() ),
            (3, "Leordeni","Schitu Scoicesti", NOW(), NOW() ),
            (3, "Leresti","Pojorata", NOW(), NOW() ),
            (3, "Leresti","Voinesti", NOW(), NOW() ),
            (3, "Lunca Corbului","Bumbueni", NOW(), NOW() ),
            (3, "Lunca Corbului","Catane", NOW(), NOW() ),
            (3, "Lunca Corbului","Ciesti", NOW(), NOW() ),
            (3, "Lunca Corbului","Langesti", NOW(), NOW() ),
            (3, "Lunca Corbului","Marghia de Jos", NOW(), NOW() ),
            (3, "Lunca Corbului","Marghia de Sus", NOW(), NOW() ),
            (3, "Lunca Corbului","Padureti", NOW(), NOW() ),
            (3, "Lunca Corbului","Silisteni", NOW(), NOW() ),
            (3, "Malureni","Bunesti", NOW(), NOW() ),
            (3, "Malureni","Pauleasca", NOW(), NOW() ),
            (3, "Malureni","Toplita", NOW(), NOW() ),
            (3, "Malureni","Zarnesti", NOW(), NOW() ),
            (3, "Maracineni","Argeselu", NOW(), NOW() ),
            (3, "Merisani","Borlesti", NOW(), NOW() ),
            (3, "Merisani","Brateasca", NOW(), NOW() ),
            (3, "Merisani","Capu Piscului", NOW(), NOW() ),
            (3, "Merisani","Crampotani", NOW(), NOW() ),
            (3, "Merisani","Dobrogostea", NOW(), NOW() ),
            (3, "Merisani","Malu Vanat", NOW(), NOW() ),
            (3, "Merisani","Valcelele", NOW(), NOW() ),
            (3, "Merisani","Varzaru", NOW(), NOW() ),
            (3, "Micesti","Branzari", NOW(), NOW() ),
            (3, "Micesti","Purcareni", NOW(), NOW() ),
            (3, "Micesti","Pauleasca", NOW(), NOW() ),
            (3, "Mihaesti","Draghici", NOW(), NOW() ),
            (3, "Mihaesti","Furnicosi", NOW(), NOW() ),
            (3, "Mihaesti","Rudeni", NOW(), NOW() ),
            (3, "Mihaesti","Valea Bradului", NOW(), NOW() ),
            (3, "Mihaesti","Valea Popii", NOW(), NOW() ),
            (3, "Mihaesti","Vacarea", NOW(), NOW() ),
            (3, "Mioarele","Alunis", NOW(), NOW() ),
            (3, "Mioarele","Chilii", NOW(), NOW() ),
            (3, "Mioarele","Cocenesti", NOW(), NOW() ),
            (3, "Mioarele","Matau", NOW(), NOW() ),
            (3, "Mioarele","Suslanesti", NOW(), NOW() ),
            (3, "Mioveni","Clucereasa", NOW(), NOW() ),
            (3, "Mioveni","Colibasi", NOW(), NOW() ),
            (3, "Mioveni","Fagetu", NOW(), NOW() ),
            (3, "Mioveni","Racovita", NOW(), NOW() ),
            (3, "Mirosi","Surdulesti", NOW(), NOW() ),
            (3, "Moraresti","Dealu Obejdeanului", NOW(), NOW() ),
            (3, "Moraresti","Dedulesti", NOW(), NOW() ),
            (3, "Moraresti","Luminile", NOW(), NOW() ),
            (3, "Moraresti","Mancioiu", NOW(), NOW() ),
            (3, "Moraresti","Sapunari", NOW(), NOW() ),
            (3, "Mosoaia","Batrani", NOW(), NOW() ),
            (3, "Mosoaia","Ciocanai", NOW(), NOW() ),
            (3, "Mosoaia","Dealu Viilor", NOW(), NOW() ),
            (3, "Mosoaia","Hintesti", NOW(), NOW() ),
            (3, "Mosoaia","Lazaresti", NOW(), NOW() ),
            (3, "Mosoaia","Smeura", NOW(), NOW() ),
            (3, "Mozaceni","Babaroaga", NOW(), NOW() ),
            (3, "Mozaceni","Zidurile", NOW(), NOW() ),
            (3, "Musatesti","Bolovanesti", NOW(), NOW() ),
            (3, "Musatesti","Costesti-Vaslan", NOW(), NOW() ),
            (3, "Musatesti","Prosia", NOW(), NOW() ),
            (3, "Musatesti","Robaia", NOW(), NOW() ),
            (3, "Musatesti","Stroesti", NOW(), NOW() ),
            (3, "Musatesti","Valea Faurului", NOW(), NOW() ),
            (3, "Musatesti","Valea Muscelului", NOW(), NOW() ),
            (3, "Musatesti","Valea lui Mas", NOW(), NOW() ),
            (3, "Musatesti","Valsanesti", NOW(), NOW() ),
            (3, "Negrasi","Buta", NOW(), NOW() ),
            (3, "Negrasi","Barlogu", NOW(), NOW() ),
            (3, "Negrasi","Mozacu", NOW(), NOW() ),
            (3, "Nucsoara","Gruiu", NOW(), NOW() ),
            (3, "Nucsoara","Sboghitesti", NOW(), NOW() ),
            (3, "Nucsoara","Slatina", NOW(), NOW() ),
            (3, "Oarja","Ceausesti", NOW(), NOW() ),
            (3, "Pietrosani","Badesti", NOW(), NOW() ),
            (3, "Pietrosani","Ganesti", NOW(), NOW() ),
            (3, "Pietrosani","Retevoiesti", NOW(), NOW() ),
            (3, "Pietrosani","Varzaroaia", NOW(), NOW() ),
            (3, "Poiana Lacului","Cepari", NOW(), NOW() ),
            (3, "Poiana Lacului","Catunasi", NOW(), NOW() ),
            (3, "Poiana Lacului","Dealu Orasului", NOW(), NOW() ),
            (3, "Poiana Lacului","Dealu Viilor", NOW(), NOW() ),
            (3, "Poiana Lacului","Dinculesti", NOW(), NOW() ),
            (3, "Poiana Lacului","Galcesti", NOW(), NOW() ),
            (3, "Poiana Lacului","Galeteanu", NOW(), NOW() ),
            (3, "Poiana Lacului","Gardinesti", NOW(), NOW() ),
            (3, "Poiana Lacului","Metofu", NOW(), NOW() ),
            (3, "Poiana Lacului","Paduroiu din Deal", NOW(), NOW() ),
            (3, "Poiana Lacului","Paduroiu din Vale", NOW(), NOW() ),
            (3, "Poiana Lacului","Samara", NOW(), NOW() ),
            (3, "Poienarii De Arges","Ceauresti", NOW(), NOW() ),
            (3, "Poienarii De Arges","Ioanicesti", NOW(), NOW() ),
            (3, "Poienarii De Arges","Poienari", NOW(), NOW() ),
            (3, "Poienarii De Arges","Tomulesti", NOW(), NOW() ),
            (3, "Poienarii De Muscel","Grosani", NOW(), NOW() ),
            (3, "Poienarii De Muscel","Jugur", NOW(), NOW() ),
            (3, "Poienarii De Muscel","Poienari", NOW(), NOW() ),
            (3, "Poienarii De Muscel","Valea Indarat", NOW(), NOW() ),
            (3, "Poienarii De Muscel","Serbanesti", NOW(), NOW() ),
            (3, "Popesti","Palanga", NOW(), NOW() ),
            (3, "Popesti","Purcareni", NOW(), NOW() ),
            (3, "Popesti","Slobozia", NOW(), NOW() ),
            (3, "Priboieni","Albotele", NOW(), NOW() ),
            (3, "Priboieni","Paraschivesti", NOW(), NOW() ),
            (3, "Priboieni","Pitoi", NOW(), NOW() ),
            (3, "Priboieni","Samaila", NOW(), NOW() ),
            (3, "Priboieni","Valea Mare", NOW(), NOW() ),
            (3, "Priboieni","Valea Nenii", NOW(), NOW() ),
            (3, "Priboieni","Valea Popii", NOW(), NOW() ),
            (3, "Raca","Adunati", NOW(), NOW() ),
            (3, "Raca","Bucov", NOW(), NOW() ),
            (3, "Ratesti","Ciupa-Manciulescu", NOW(), NOW() ),
            (3, "Ratesti","Furduesti", NOW(), NOW() ),
            (3, "Ratesti","Mavrodolu", NOW(), NOW() ),
            (3, "Ratesti","Nejlovelu", NOW(), NOW() ),
            (3, "Ratesti","Patuleni", NOW(), NOW() ),
            (3, "Ratesti","Tigveni", NOW(), NOW() ),
            (3, "Recea","Deagu de Jos", NOW(), NOW() ),
            (3, "Recea","Deagu de Sus", NOW(), NOW() ),
            (3, "Recea","Goleasca", NOW(), NOW() ),
            (3, "Recea","Orodel", NOW(), NOW() ),
            (3, "Rociu","Gliganu de Jos", NOW(), NOW() ),
            (3, "Rociu","Gliganu de Sus", NOW(), NOW() ),
            (3, "Rociu","Serbanesti", NOW(), NOW() ),
            (3, "Rucar","Satic", NOW(), NOW() ),
            (3, "Salatrucu","Valeni", NOW(), NOW() ),
            (3, "Sapata","Banaresti", NOW(), NOW() ),
            (3, "Sapata","Dealu Bradului", NOW(), NOW() ),
            (3, "Sapata","Draghicesti", NOW(), NOW() ),
            (3, "Sapata","Gainusa", NOW(), NOW() ),
            (3, "Sapata","Lipia", NOW(), NOW() ),
            (3, "Sapata","Martesti", NOW(), NOW() ),
            (3, "Sapata","Popesti", NOW(), NOW() ),
            (3, "Sapata","Turcesti", NOW(), NOW() ),
            (3, "Schitu Golesti","Burnesti", NOW(), NOW() ),
            (3, "Schitu Golesti","Costita", NOW(), NOW() ),
            (3, "Schitu Golesti","Loturi", NOW(), NOW() ),
            (3, "Schitu Golesti","Lazaresti", NOW(), NOW() ),
            (3, "Schitu Golesti","Valea Pechii", NOW(), NOW() ),
            (3, "Slobozia","Nigrisoara", NOW(), NOW() ),
            (3, "Stalpeni","Dealu Frumos", NOW(), NOW() ),
            (3, "Stalpeni","Livezeni", NOW(), NOW() ),
            (3, "Stalpeni","Ogrezea", NOW(), NOW() ),
            (3, "Stalpeni","Opresti", NOW(), NOW() ),
            (3, "Stalpeni","Pitigaia", NOW(), NOW() ),
            (3, "Stalpeni","Radesti", NOW(), NOW() ),
            (3, "Stefan Cel Mare","Glavacioc", NOW(), NOW() ),
            (3, "Stefanesti","Enculesti", NOW(), NOW() ),
            (3, "Stefanesti","Golesti", NOW(), NOW() ),
            (3, "Stefanesti","Izvorani", NOW(), NOW() ),
            (3, "Stefanesti","Valea Mare-Podgoria", NOW(), NOW() ),
            (3, "Stefanesti","Viisoara", NOW(), NOW() ),
            (3, "Stefanesti","Zavoi", NOW(), NOW() ),
            (3, "Stefanesti","Stefanestii Noi", NOW(), NOW() ),
            (3, "Stoenesti","Badeni", NOW(), NOW() ),
            (3, "Stoenesti","Cotenesti", NOW(), NOW() ),
            (3, "Stoenesti","Lunca Gartii", NOW(), NOW() ),
            (3, "Stoenesti","Piatra", NOW(), NOW() ),
            (3, "Stoenesti","Slobozia", NOW(), NOW() ),
            (3, "Stoenesti","Valea Badenilor", NOW(), NOW() ),
            (3, "Stolnici","Cochinesti", NOW(), NOW() ),
            (3, "Stolnici","Cotmeana", NOW(), NOW() ),
            (3, "Stolnici","Falfani", NOW(), NOW() ),
            (3, "Stolnici","Izbasesti", NOW(), NOW() ),
            (3, "Stolnici","Vlascuta", NOW(), NOW() ),
            (3, "Suici","Ianculesti", NOW(), NOW() ),
            (3, "Suici","Paltenu", NOW(), NOW() ),
            (3, "Suici","Pauleni", NOW(), NOW() ),
            (3, "Suici","Rudeni", NOW(), NOW() ),
            (3, "Suici","Valea Calului", NOW(), NOW() ),
            (3, "Suseni","Burdesti", NOW(), NOW() ),
            (3, "Suseni","Cersani", NOW(), NOW() ),
            (3, "Suseni","Chiritesti", NOW(), NOW() ),
            (3, "Suseni","Galesesti", NOW(), NOW() ),
            (3, "Suseni","Odaeni", NOW(), NOW() ),
            (3, "Suseni","Padureni", NOW(), NOW() ),
            (3, "Suseni","Stefanesti", NOW(), NOW() ),
            (3, "Suseni","Strambeni", NOW(), NOW() ),
            (3, "Suseni","Tutulesti", NOW(), NOW() ),
            (3, "Teiu","Lesile", NOW(), NOW() ),
            (3, "Tigveni","Blaju", NOW(), NOW() ),
            (3, "Tigveni","Barsestii de Jos", NOW(), NOW() ),
            (3, "Tigveni","Barsestii de Sus", NOW(), NOW() ),
            (3, "Tigveni","Badislava", NOW(), NOW() ),
            (3, "Tigveni","Balilesti", NOW(), NOW() ),
            (3, "Tigveni","Balteni", NOW(), NOW() ),
            (3, "Tigveni","Vladesti", NOW(), NOW() ),
            (3, "Titesti","Bucsenesti-Lotasi", NOW(), NOW() ),
            (3, "Titesti","Cismea", NOW(), NOW() ),
            (3, "Titesti","Valea Manastirii", NOW(), NOW() ),
            (3, "Titesti","Valea Stanii", NOW(), NOW() ),
            (3, "Topoloveni","Botarcani", NOW(), NOW() ),
            (3, "Topoloveni","Crintesti", NOW(), NOW() ),
            (3, "Topoloveni","Goranesti", NOW(), NOW() ),
            (3, "Topoloveni","Tiganesti", NOW(), NOW() ),
            (3, "Uda","Branistea", NOW(), NOW() ),
            (3, "Uda","Badulesti", NOW(), NOW() ),
            (3, "Uda","Baranesti", NOW(), NOW() ),
            (3, "Uda","Chiritesti", NOW(), NOW() ),
            (3, "Uda","Cotu", NOW(), NOW() ),
            (3, "Uda","Dealu Bisericii", NOW(), NOW() ),
            (3, "Uda","Dealu Tolcesii", NOW(), NOW() ),
            (3, "Uda","Diconesti", NOW(), NOW() ),
            (3, "Uda","Gorani", NOW(), NOW() ),
            (3, "Uda","Greaban", NOW(), NOW() ),
            (3, "Uda","Lungulesti", NOW(), NOW() ),
            (3, "Uda","Miercani", NOW(), NOW() ),
            (3, "Uda","Romana", NOW(), NOW() ),
            (3, "Uda","Rajletu-Govora", NOW(), NOW() ),
            (3, "Uda","Salistea", NOW(), NOW() ),
            (3, "Ungheni","Coltu", NOW(), NOW() ),
            (3, "Ungheni","Goia", NOW(), NOW() ),
            (3, "Ungheni","Gaujani", NOW(), NOW() ),
            (3, "Ungheni","Humele", NOW(), NOW() ),
            (3, "Ungheni","Satu Nou", NOW(), NOW() ),
            (3, "Valea Danului","Bolculesti", NOW(), NOW() ),
            (3, "Valea Danului","Borobanesti", NOW(), NOW() ),
            (3, "Valea Danului","Banicesti", NOW(), NOW() ),
            (3, "Valea Danului","Vernesti", NOW(), NOW() ),
            (3, "Valea Iasului","Borovinesti", NOW(), NOW() ),
            (3, "Valea Iasului","Badila", NOW(), NOW() ),
            (3, "Valea Iasului","Barbalatesti", NOW(), NOW() ),
            (3, "Valea Iasului","Cerbureni", NOW(), NOW() ),
            (3, "Valea Iasului","Mustatesti", NOW(), NOW() ),
            (3, "Valea Iasului","Ruginoasa", NOW(), NOW() ),
            (3, "Valea Iasului","Ungureni", NOW(), NOW() ),
            (3, "Valea Iasului","Valea Uleiului", NOW(), NOW() ),
            (3, "Valea Mare Pravat","Bilcesti", NOW(), NOW() ),
            (3, "Valea Mare Pravat","Colnic", NOW(), NOW() ),
            (3, "Valea Mare Pravat","Fantanea", NOW(), NOW() ),
            (3, "Valea Mare Pravat","Gura Pravat", NOW(), NOW() ),
            (3, "Valea Mare Pravat","Namaesti", NOW(), NOW() ),
            (3, "Valea Mare Pravat","Pietroasa", NOW(), NOW() ),
            (3, "Valea Mare Pravat","Selari", NOW(), NOW() ),
            (3, "Vedea","Blejani", NOW(), NOW() ),
            (3, "Vedea","Buretesti", NOW(), NOW() ),
            (3, "Vedea","Badicea", NOW(), NOW() ),
            (3, "Vedea","Chiritesti", NOW(), NOW() ),
            (3, "Vedea","Chitani", NOW(), NOW() ),
            (3, "Vedea","Ciuresti", NOW(), NOW() ),
            (3, "Vedea","Dincani", NOW(), NOW() ),
            (3, "Vedea","Fata", NOW(), NOW() ),
            (3, "Vedea","Fratici", NOW(), NOW() ),
            (3, "Vedea","Izvoru de Jos", NOW(), NOW() ),
            (3, "Vedea","Izvoru de Sus", NOW(), NOW() ),
            (3, "Vedea","Lungani", NOW(), NOW() ),
            (3, "Vedea","Mogosesti", NOW(), NOW() ),
            (3, "Vedea","Prodani", NOW(), NOW() ),
            (3, "Vedea","Ratoi", NOW(), NOW() ),
            (3, "Vedea","Vata", NOW(), NOW() ),
            (3, "Vedea","Vetisoara", NOW(), NOW() ),
            (3, "Vedea","Varsesti", NOW(), NOW() ),
            (3, "Vladesti","Coteasca", NOW(), NOW() ),
            (3, "Vladesti","Draghescu", NOW(), NOW() ),
            (3, "Vladesti","Putina", NOW(), NOW() ),
            (3, "Vulturesti","Barzesti", NOW(), NOW() ),
            (3, "Vulturesti","Huluba", NOW(), NOW() )
        ;';
        DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=3;';
        DB::connection()->getPdo()->exec($sql);
    }
}
