<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForHD extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (21, "","Aninoasa", NOW(), NOW()),
            (21, "","Baia de Cris", NOW(), NOW()),
            (21, "","Balsa", NOW(), NOW()),
            (21, "","Baru", NOW(), NOW()),
            (21, "","Beriu", NOW(), NOW()),
            (21, "","Blajeni", NOW(), NOW()),
            (21, "","Bosorod", NOW(), NOW()),
            (21, "","Brad", NOW(), NOW()),
            (21, "","Bretea Romana", NOW(), NOW()),
            (21, "","Branisca", NOW(), NOW()),
            (21, "","Buces", NOW(), NOW()),
            (21, "","Bucuresci", NOW(), NOW()),
            (21, "","Bulzestii de Sus", NOW(), NOW()),
            (21, "","Bunila", NOW(), NOW()),
            (21, "","Burjuc", NOW(), NOW()),
            (21, "","Bacia", NOW(), NOW()),
            (21, "","Baita", NOW(), NOW()),
            (21, "","Banita", NOW(), NOW()),
            (21, "","Batrana", NOW(), NOW()),
            (21, "","Cerbal", NOW(), NOW()),
            (21, "","Certeju de Sus", NOW(), NOW()),
            (21, "","Criscior", NOW(), NOW()),
            (21, "","Carjiti", NOW(), NOW()),
            (21, "","Calan", NOW(), NOW()),
            (21, "","Densus", NOW(), NOW()),
            (21, "","Deva", NOW(), NOW()),
            (21, "","Dobra", NOW(), NOW()),
            (21, "","General Berthelot", NOW(), NOW()),
            (21, "","Geoagiu", NOW(), NOW()),
            (21, "","Ghelari", NOW(), NOW()),
            (21, "","Gurasada", NOW(), NOW()),
            (21, "","Hateg", NOW(), NOW()),
            (21, "","Hunedoara", NOW(), NOW()),
            (21, "","Harau", NOW(), NOW()),
            (21, "","Ilia", NOW(), NOW()),
            (21, "","Lelese", NOW(), NOW()),
            (21, "","Lunca Cernii de Jos", NOW(), NOW()),
            (21, "","Luncoiu de Jos", NOW(), NOW()),
            (21, "","Lupeni", NOW(), NOW()),
            (21, "","Lapugiu de Jos", NOW(), NOW()),
            (21, "","Martinesti", NOW(), NOW()),
            (21, "","Orastie", NOW(), NOW()),
            (21, "","Orastioara de Sus", NOW(), NOW()),
            (21, "","Pestisu Mic", NOW(), NOW()),
            (21, "","Petrila", NOW(), NOW()),
            (21, "","Petrosani", NOW(), NOW()),
            (21, "","Pui", NOW(), NOW()),
            (21, "","Rapoltu Mare", NOW(), NOW()),
            (21, "","Ribita", NOW(), NOW()),
            (21, "","Romos", NOW(), NOW()),
            (21, "","Rau de Mori", NOW(), NOW()),
            (21, "","Rachitova", NOW(), NOW()),
            (21, "","Sarmizegetusa", NOW(), NOW()),
            (21, "","Simeria", NOW(), NOW()),
            (21, "","Santamaria-Orlea", NOW(), NOW()),
            (21, "","Salasu de Sus", NOW(), NOW()),
            (21, "","Teliucu Inferior", NOW(), NOW()),
            (21, "","Tomesti", NOW(), NOW()),
            (21, "","Toplita", NOW(), NOW()),
            (21, "","Totesti", NOW(), NOW()),
            (21, "","Turdas", NOW(), NOW()),
            (21, "","Uricani", NOW(), NOW()),
            (21, "","Vata de Jos", NOW(), NOW()),
            (21, "","Vetel", NOW(), NOW()),
            (21, "","Vorta", NOW(), NOW()),
            (21, "","Vulcan", NOW(), NOW()),
            (21, "","Valisoara", NOW(), NOW()),
            (21, "","Zam", NOW(), NOW()),
            (21, "","Soimus", NOW(), NOW()),
            (21, "Aninoasa","Iscroni", NOW(), NOW()),
            (21, "Bacia","Petreni", NOW(), NOW()),
            (21, "Bacia","Totia", NOW(), NOW()),
            (21, "Bacia","Tampa", NOW(), NOW()),
            (21, "Baia De Cris","Baldovin", NOW(), NOW()),
            (21, "Baia De Cris","Caraci", NOW(), NOW()),
            (21, "Baia De Cris","Carastau", NOW(), NOW()),
            (21, "Baia De Cris","Lunca", NOW(), NOW()),
            (21, "Baia De Cris","Risca", NOW(), NOW()),
            (21, "Baia De Cris","Risculita", NOW(), NOW()),
            (21, "Baia De Cris","Valeni", NOW(), NOW()),
            (21, "Baia De Cris","Tebea", NOW(), NOW()),
            (21, "Baita","Barbura", NOW(), NOW()),
            (21, "Baita","Craciunesti", NOW(), NOW()),
            (21, "Baita","Cainelu de Sus", NOW(), NOW()),
            (21, "Baita","Fizes", NOW(), NOW()),
            (21, "Baita","Hartagani", NOW(), NOW()),
            (21, "Baita","Lunca", NOW(), NOW()),
            (21, "Baita","Ormindea", NOW(), NOW()),
            (21, "Baita","Pestera", NOW(), NOW()),
            (21, "Baita","Saliste", NOW(), NOW()),
            (21, "Baita","Trestia", NOW(), NOW()),
            (21, "Balsa","Almasu Mic de Munte", NOW(), NOW()),
            (21, "Balsa","Ardeu", NOW(), NOW()),
            (21, "Balsa","Bunesti", NOW(), NOW()),
            (21, "Balsa","Galbina", NOW(), NOW()),
            (21, "Balsa","Mada", NOW(), NOW()),
            (21, "Balsa","Oprisesti", NOW(), NOW()),
            (21, "Balsa","Poiana", NOW(), NOW()),
            (21, "Balsa","Poienita", NOW(), NOW()),
            (21, "Balsa","Rosia", NOW(), NOW()),
            (21, "Balsa","Stauini", NOW(), NOW()),
            (21, "Balsa","Techereu", NOW(), NOW()),
            (21, "Balsa","Voia", NOW(), NOW()),
            (21, "Balsa","Valisoara", NOW(), NOW()),
            (21, "Banita","Crivadia", NOW(), NOW()),
            (21, "Banita","Merisor", NOW(), NOW()),
            (21, "Baru","Livadia", NOW(), NOW()),
            (21, "Baru","Petros", NOW(), NOW()),
            (21, "Baru","Valea Lupului", NOW(), NOW()),
            (21, "Batrana","Fata Rosie", NOW(), NOW()),
            (21, "Batrana","Piatra", NOW(), NOW()),
            (21, "Batrana","Rachitaua", NOW(), NOW()),
            (21, "Beriu","Cucuis", NOW(), NOW()),
            (21, "Beriu","Castau", NOW(), NOW()),
            (21, "Beriu","Magureni", NOW(), NOW()),
            (21, "Beriu","Orastioara de Jos", NOW(), NOW()),
            (21, "Beriu","Poieni", NOW(), NOW()),
            (21, "Beriu","Sereca", NOW(), NOW()),
            (21, "Beriu","Sibisel", NOW(), NOW()),
            (21, "Blajeni","Blajeni-Vulcan", NOW(), NOW()),
            (21, "Blajeni","Cris", NOW(), NOW()),
            (21, "Blajeni","Dragu-Brad", NOW(), NOW()),
            (21, "Blajeni","Grosuri", NOW(), NOW()),
            (21, "Blajeni","Plai", NOW(), NOW()),
            (21, "Blajeni","Ret", NOW(), NOW()),
            (21, "Blajeni","Salatruc", NOW(), NOW()),
            (21, "Bosorod","Alun", NOW(), NOW()),
            (21, "Bosorod","Bobaia", NOW(), NOW()),
            (21, "Bosorod","Chitid", NOW(), NOW()),
            (21, "Bosorod","Cioclovina", NOW(), NOW()),
            (21, "Bosorod","Luncani", NOW(), NOW()),
            (21, "Bosorod","Prihodiste", NOW(), NOW()),
            (21, "Bosorod","Tarsa", NOW(), NOW()),
            (21, "Bosorod","Ursici", NOW(), NOW()),
            (21, "Brad","Mesteacan", NOW(), NOW()),
            (21, "Brad","Potingani", NOW(), NOW()),
            (21, "Brad","Ruda-Brad", NOW(), NOW()),
            (21, "Brad","Valea Bradului", NOW(), NOW()),
            (21, "Brad","Taratel", NOW(), NOW()),
            (21, "Branisca","Boz", NOW(), NOW()),
            (21, "Branisca","Barastii Iliei", NOW(), NOW()),
            (21, "Branisca","Cabesti", NOW(), NOW()),
            (21, "Branisca","Furcsoara", NOW(), NOW()),
            (21, "Branisca","Gialacuta", NOW(), NOW()),
            (21, "Branisca","Rovina", NOW(), NOW()),
            (21, "Branisca","Tarnava", NOW(), NOW()),
            (21, "Branisca","Tarnavita", NOW(), NOW()),
            (21, "Bretea Romana","Bercu", NOW(), NOW()),
            (21, "Bretea Romana","Bretea Streiului", NOW(), NOW()),
            (21, "Bretea Romana","Batalar", NOW(), NOW()),
            (21, "Bretea Romana","Covragiu", NOW(), NOW()),
            (21, "Bretea Romana","Gantaga", NOW(), NOW()),
            (21, "Bretea Romana","Maceu", NOW(), NOW()),
            (21, "Bretea Romana","Ocolisu Mare", NOW(), NOW()),
            (21, "Bretea Romana","Plopi", NOW(), NOW()),
            (21, "Bretea Romana","Rusi", NOW(), NOW()),
            (21, "Bretea Romana","Valcele", NOW(), NOW()),
            (21, "Bretea Romana","Valcelele Bune", NOW(), NOW()),
            (21, "Bretea Romana","Valceluta", NOW(), NOW()),
            (21, "Buces","Buces-Vulcan", NOW(), NOW()),
            (21, "Buces","Dupapiatra", NOW(), NOW()),
            (21, "Buces","Grohotele", NOW(), NOW()),
            (21, "Buces","Mihaileni", NOW(), NOW()),
            (21, "Buces","Stanija", NOW(), NOW()),
            (21, "Buces","Tarnita", NOW(), NOW()),
            (21, "Bucuresci","Curechiu", NOW(), NOW()),
            (21, "Bucuresci","Merisor", NOW(), NOW()),
            (21, "Bucuresci","Rovina", NOW(), NOW()),
            (21, "Bucuresci","Sesuri", NOW(), NOW()),
            (21, "Bulzestii De Sus","Bulzestii de Jos", NOW(), NOW()),
            (21, "Bulzestii De Sus","Giurgesti", NOW(), NOW()),
            (21, "Bulzestii De Sus","Grohot", NOW(), NOW()),
            (21, "Bulzestii De Sus","Paulesti", NOW(), NOW()),
            (21, "Bulzestii De Sus","Rusesti", NOW(), NOW()),
            (21, "Bulzestii De Sus","Stanculesti", NOW(), NOW()),
            (21, "Bulzestii De Sus","Ticera", NOW(), NOW()),
            (21, "Bulzestii De Sus","Tomnatec", NOW(), NOW()),
            (21, "Bunila","Alun", NOW(), NOW()),
            (21, "Bunila","Cernisoara Florese", NOW(), NOW()),
            (21, "Bunila","Poienita Voinii", NOW(), NOW()),
            (21, "Bunila","Vadu Dobrii", NOW(), NOW()),
            (21, "Burjuc","Bradatel", NOW(), NOW()),
            (21, "Burjuc","Glodghilesti", NOW(), NOW()),
            (21, "Burjuc","Petresti", NOW(), NOW()),
            (21, "Burjuc","Tisa", NOW(), NOW()),
            (21, "Burjuc","Tatarasti", NOW(), NOW()),
            (21, "Calan","Batiz", NOW(), NOW()),
            (21, "Calan","Calanu Mic", NOW(), NOW()),
            (21, "Calan","Grid", NOW(), NOW()),
            (21, "Calan","Nadastia de Jos", NOW(), NOW()),
            (21, "Calan","Nadastia de Sus", NOW(), NOW()),
            (21, "Calan","Ohaba Streiului", NOW(), NOW()),
            (21, "Calan","Strei", NOW(), NOW()),
            (21, "Calan","Strei-Sacel", NOW(), NOW()),
            (21, "Calan","Streisangeorgiu", NOW(), NOW()),
            (21, "Calan","Sancrai", NOW(), NOW()),
            (21, "Calan","Santamaria de Piatra", NOW(), NOW()),
            (21, "Calan","Valea Sangeorgiului", NOW(), NOW()),
            (21, "Carjiti","Almasu Sec", NOW(), NOW()),
            (21, "Carjiti","Cherghes", NOW(), NOW()),
            (21, "Carjiti","Cozia", NOW(), NOW()),
            (21, "Carjiti","Popesti", NOW(), NOW()),
            (21, "Cerbal","Aranies", NOW(), NOW()),
            (21, "Cerbal","Feregi", NOW(), NOW()),
            (21, "Cerbal","Merisoru de Munte", NOW(), NOW()),
            (21, "Cerbal","Poiana Rachitelii", NOW(), NOW()),
            (21, "Cerbal","Poienita Tomii", NOW(), NOW()),
            (21, "Cerbal","Socet", NOW(), NOW()),
            (21, "Cerbal","Ulm", NOW(), NOW()),
            (21, "Certeju De Sus","Bocsa Mare", NOW(), NOW()),
            (21, "Certeju De Sus","Bocsa Mica", NOW(), NOW()),
            (21, "Certeju De Sus","Hondol", NOW(), NOW()),
            (21, "Certeju De Sus","Magura-Toplita", NOW(), NOW()),
            (21, "Certeju De Sus","Nojag", NOW(), NOW()),
            (21, "Certeju De Sus","Sacaramb", NOW(), NOW()),
            (21, "Certeju De Sus","Toplita Muresului", NOW(), NOW()),
            (21, "Certeju De Sus","Varmaga", NOW(), NOW()),
            (21, "Criscior","Barza", NOW(), NOW()),
            (21, "Criscior","Valea Arsului", NOW(), NOW()),
            (21, "Criscior","Zdrapti", NOW(), NOW()),
            (21, "Densus","Criva", NOW(), NOW()),
            (21, "Densus","Hatagel", NOW(), NOW()),
            (21, "Densus","Pesteana", NOW(), NOW()),
            (21, "Densus","Pestenita", NOW(), NOW()),
            (21, "Densus","Poieni", NOW(), NOW()),
            (21, "Densus","Stei", NOW(), NOW()),
            (21, "Deva","Archia", NOW(), NOW()),
            (21, "Deva","Barcea Mica", NOW(), NOW()),
            (21, "Deva","Cristur", NOW(), NOW()),
            (21, "Deva","Santuhalm", NOW(), NOW()),
            (21, "Dobra","Abucea", NOW(), NOW()),
            (21, "Dobra","Bujoru", NOW(), NOW()),
            (21, "Dobra","Fagetel", NOW(), NOW()),
            (21, "Dobra","Lapusnic", NOW(), NOW()),
            (21, "Dobra","Mihaiesti", NOW(), NOW()),
            (21, "Dobra","Panc", NOW(), NOW()),
            (21, "Dobra","Panc-Saliste", NOW(), NOW()),
            (21, "Dobra","Roscani", NOW(), NOW()),
            (21, "Dobra","Radulesti", NOW(), NOW()),
            (21, "Dobra","Stretea", NOW(), NOW()),
            (21, "Dobra","Stancesti", NOW(), NOW()),
            (21, "Dobra","Stancesti-Ohaba", NOW(), NOW()),
            (21, "General Berthelot","Craguis", NOW(), NOW()),
            (21, "General Berthelot","Farcadin", NOW(), NOW()),
            (21, "General Berthelot","Livezi", NOW(), NOW()),
            (21, "General Berthelot","Tustea", NOW(), NOW()),
            (21, "Geoagiu","Aurel Vlaicu", NOW(), NOW()),
            (21, "Geoagiu","Bacaia", NOW(), NOW()),
            (21, "Geoagiu","Bozes", NOW(), NOW()),
            (21, "Geoagiu","Cigmau", NOW(), NOW()),
            (21, "Geoagiu","Gelmar", NOW(), NOW()),
            (21, "Geoagiu","Geoagiu-Bai", NOW(), NOW()),
            (21, "Geoagiu","Homorod", NOW(), NOW()),
            (21, "Geoagiu","Mermezeu-Valeni", NOW(), NOW()),
            (21, "Geoagiu","Renghet", NOW(), NOW()),
            (21, "Geoagiu","Valeni", NOW(), NOW()),
            (21, "Ghelari","Govajdia", NOW(), NOW()),
            (21, "Ghelari","Plop", NOW(), NOW()),
            (21, "Ghelari","Ruda", NOW(), NOW()),
            (21, "Gurasada","Boiu de Jos", NOW(), NOW()),
            (21, "Gurasada","Boiu de Sus", NOW(), NOW()),
            (21, "Gurasada","Campuri de Sus", NOW(), NOW()),
            (21, "Gurasada","Campuri-Surduc", NOW(), NOW()),
            (21, "Gurasada","Carmazanesti", NOW(), NOW()),
            (21, "Gurasada","Danulesti", NOW(), NOW()),
            (21, "Gurasada","Gothatea", NOW(), NOW()),
            (21, "Gurasada","Runcsor", NOW(), NOW()),
            (21, "Gurasada","Ulies", NOW(), NOW()),
            (21, "Gurasada","Vica", NOW(), NOW()),
            (21, "Harau","Banpotoc", NOW(), NOW()),
            (21, "Harau","Barsau", NOW(), NOW()),
            (21, "Harau","Chimindia", NOW(), NOW()),
            (21, "Hateg","Nalatvad", NOW(), NOW()),
            (21, "Hateg","Silvasu de Jos", NOW(), NOW()),
            (21, "Hateg","Silvasu de Sus", NOW(), NOW()),
            (21, "Hunedoara","Bos", NOW(), NOW()),
            (21, "Hunedoara","Gros", NOW(), NOW()),
            (21, "Hunedoara","Hasdat", NOW(), NOW()),
            (21, "Hunedoara","Pestisu Mare", NOW(), NOW()),
            (21, "Hunedoara","Racastia", NOW(), NOW()),
            (21, "Ilia","Bacea", NOW(), NOW()),
            (21, "Ilia","Bretea Muresana", NOW(), NOW()),
            (21, "Ilia","Braznic", NOW(), NOW()),
            (21, "Ilia","Cuies", NOW(), NOW()),
            (21, "Ilia","Dumbravita", NOW(), NOW()),
            (21, "Ilia","Sarbi", NOW(), NOW()),
            (21, "Ilia","Sacamas", NOW(), NOW()),
            (21, "Ilia","Valea Lunga", NOW(), NOW()),
            (21, "Lapugiu De Jos","Bastea", NOW(), NOW()),
            (21, "Lapugiu De Jos","Cosesti", NOW(), NOW()),
            (21, "Lapugiu De Jos","Fintoag", NOW(), NOW()),
            (21, "Lapugiu De Jos","Grind", NOW(), NOW()),
            (21, "Lapugiu De Jos","Holdea", NOW(), NOW()),
            (21, "Lapugiu De Jos","Lapugiu de Sus", NOW(), NOW()),
            (21, "Lapugiu De Jos","Lasau", NOW(), NOW()),
            (21, "Lapugiu De Jos","Ohaba", NOW(), NOW()),
            (21, "Lapugiu De Jos","Teiu", NOW(), NOW()),
            (21, "Lelese","Cerisor", NOW(), NOW()),
            (21, "Lelese","Runcu Mare", NOW(), NOW()),
            (21, "Lelese","Sohodol", NOW(), NOW()),
            (21, "Lunca Cernii De Jos","Ciumita", NOW(), NOW()),
            (21, "Lunca Cernii De Jos","Fantana", NOW(), NOW()),
            (21, "Lunca Cernii De Jos","Gura Bordului", NOW(), NOW()),
            (21, "Lunca Cernii De Jos","Lunca Cernii de Sus", NOW(), NOW()),
            (21, "Lunca Cernii De Jos","Meria", NOW(), NOW()),
            (21, "Lunca Cernii De Jos","Negoiu", NOW(), NOW()),
            (21, "Lunca Cernii De Jos","Valea Babii", NOW(), NOW()),
            (21, "Luncoiu De Jos","Dudesti", NOW(), NOW()),
            (21, "Luncoiu De Jos","Luncoiu de Sus", NOW(), NOW()),
            (21, "Luncoiu De Jos","Podele", NOW(), NOW()),
            (21, "Luncoiu De Jos","Stejarel", NOW(), NOW()),
            (21, "Martinesti","Dancu Mare", NOW(), NOW()),
            (21, "Martinesti","Dancu Mic", NOW(), NOW()),
            (21, "Martinesti","Jeledinti", NOW(), NOW()),
            (21, "Martinesti","Magura", NOW(), NOW()),
            (21, "Martinesti","Turmas", NOW(), NOW()),
            (21, "Martinesti","Tamasasa", NOW(), NOW()),
            (21, "Orastioara De Sus","Bucium", NOW(), NOW()),
            (21, "Orastioara De Sus","Costesti", NOW(), NOW()),
            (21, "Orastioara De Sus","Costesti-Deal", NOW(), NOW()),
            (21, "Orastioara De Sus","Gradistea de Munte", NOW(), NOW()),
            (21, "Orastioara De Sus","Ludestii de Jos", NOW(), NOW()),
            (21, "Orastioara De Sus","Ludestii de Sus", NOW(), NOW()),
            (21, "Orastioara De Sus","Ocolisu Mic", NOW(), NOW()),
            (21, "Pestisu Mic","Almasu Mic", NOW(), NOW()),
            (21, "Pestisu Mic","Ciulpaz", NOW(), NOW()),
            (21, "Pestisu Mic","Cutin", NOW(), NOW()),
            (21, "Pestisu Mic","Dumbrava", NOW(), NOW()),
            (21, "Pestisu Mic","Josani", NOW(), NOW()),
            (21, "Pestisu Mic","Manerau", NOW(), NOW()),
            (21, "Pestisu Mic","Nandru", NOW(), NOW()),
            (21, "Pestisu Mic","Valea Nandrului", NOW(), NOW()),
            (21, "Petrila","Cimpa", NOW(), NOW()),
            (21, "Petrila","Jiet", NOW(), NOW()),
            (21, "Petrila","Rascoala", NOW(), NOW()),
            (21, "Petrila","Tirici", NOW(), NOW()),
            (21, "Petrosani","Dalja Mare", NOW(), NOW()),
            (21, "Petrosani","Dalja Mica", NOW(), NOW()),
            (21, "Petrosani","Pestera", NOW(), NOW()),
            (21, "Petrosani","Slatinioara", NOW(), NOW()),
            (21, "Pui","Baiesti", NOW(), NOW()),
            (21, "Pui","Federi", NOW(), NOW()),
            (21, "Pui","Fizesti", NOW(), NOW()),
            (21, "Pui","Galati", NOW(), NOW()),
            (21, "Pui","Hobita", NOW(), NOW()),
            (21, "Pui","Ohaba-Ponor", NOW(), NOW()),
            (21, "Pui","Ponor", NOW(), NOW()),
            (21, "Pui","Rusor", NOW(), NOW()),
            (21, "Pui","Rau Barbat", NOW(), NOW()),
            (21, "Pui","Uric", NOW(), NOW()),
            (21, "Pui","Serel", NOW(), NOW()),
            (21, "Rachitova","Boita", NOW(), NOW()),
            (21, "Rachitova","Ciula Mare", NOW(), NOW()),
            (21, "Rachitova","Ciula Mica", NOW(), NOW()),
            (21, "Rachitova","Gotesti", NOW(), NOW()),
            (21, "Rachitova","Mesteacan", NOW(), NOW()),
            (21, "Rachitova","Valioara", NOW(), NOW()),
            (21, "Rapoltu Mare","Bobalna", NOW(), NOW()),
            (21, "Rapoltu Mare","Boiu", NOW(), NOW()),
            (21, "Rapoltu Mare","Folt", NOW(), NOW()),
            (21, "Rapoltu Mare","Rapoltel", NOW(), NOW()),
            (21, "Rau De Mori","Brazi", NOW(), NOW()),
            (21, "Rau De Mori","Clopotiva", NOW(), NOW()),
            (21, "Rau De Mori","Ohaba-Sibisel", NOW(), NOW()),
            (21, "Rau De Mori","Ostrov", NOW(), NOW()),
            (21, "Rau De Mori","Ostrovel", NOW(), NOW()),
            (21, "Rau De Mori","Ostrovu Mic", NOW(), NOW()),
            (21, "Rau De Mori","Sibisel", NOW(), NOW()),
            (21, "Rau De Mori","Suseni", NOW(), NOW()),
            (21, "Rau De Mori","Unciuc", NOW(), NOW()),
            (21, "Rau De Mori","Valea Daljii", NOW(), NOW()),
            (21, "Ribita","Crisan", NOW(), NOW()),
            (21, "Ribita","Dumbrava de Jos", NOW(), NOW()),
            (21, "Ribita","Dumbrava de Sus", NOW(), NOW()),
            (21, "Ribita","Ribicioara", NOW(), NOW()),
            (21, "Ribita","Uibaresti", NOW(), NOW()),
            (21, "Romos","Ciungu Mare", NOW(), NOW()),
            (21, "Romos","Pischinti", NOW(), NOW()),
            (21, "Romos","Romosel", NOW(), NOW()),
            (21, "Romos","Vaidei", NOW(), NOW()),
            (21, "Salasu De Sus","Coroiesti", NOW(), NOW()),
            (21, "Salasu De Sus","Malaiesti", NOW(), NOW()),
            (21, "Salasu De Sus","Nucsoara", NOW(), NOW()),
            (21, "Salasu De Sus","Ohaba de Sub Piatra", NOW(), NOW()),
            (21, "Salasu De Sus","Paros", NOW(), NOW()),
            (21, "Salasu De Sus","Pestera", NOW(), NOW()),
            (21, "Salasu De Sus","Rau Alb", NOW(), NOW()),
            (21, "Salasu De Sus","Rau Mic", NOW(), NOW()),
            (21, "Salasu De Sus","Salasu de Jos", NOW(), NOW()),
            (21, "Salasu De Sus","Zavoi", NOW(), NOW()),
            (21, "Santamaria-Orlea","Balomir", NOW(), NOW()),
            (21, "Santamaria-Orlea","Bucium-Orlea", NOW(), NOW()),
            (21, "Santamaria-Orlea","Barastii Hategului", NOW(), NOW()),
            (21, "Santamaria-Orlea","Ciopeia", NOW(), NOW()),
            (21, "Santamaria-Orlea","Subcetate", NOW(), NOW()),
            (21, "Santamaria-Orlea","Sanpetru", NOW(), NOW()),
            (21, "Santamaria-Orlea","Sacel", NOW(), NOW()),
            (21, "Santamaria-Orlea","Vadu", NOW(), NOW()),
            (21, "Sarmizegetusa","Breazova", NOW(), NOW()),
            (21, "Sarmizegetusa","Hobita-Gradiste", NOW(), NOW()),
            (21, "Sarmizegetusa","Paucinesti", NOW(), NOW()),
            (21, "Sarmizegetusa","Zeicani", NOW(), NOW()),
            (21, "Simeria","Barcea Mare", NOW(), NOW()),
            (21, "Simeria","Carpinis", NOW(), NOW()),
            (21, "Simeria","Simeria Veche", NOW(), NOW()),
            (21, "Simeria","Santandrei", NOW(), NOW()),
            (21, "Simeria","Uroi", NOW(), NOW()),
            (21, "Simeria","Saulesti", NOW(), NOW()),
            (21, "Soimus","Bejan", NOW(), NOW()),
            (21, "Soimus","Bejan-Tarnavita", NOW(), NOW()),
            (21, "Soimus","Boholt", NOW(), NOW()),
            (21, "Soimus","Balata", NOW(), NOW()),
            (21, "Soimus","Chiscadaga", NOW(), NOW()),
            (21, "Soimus","Cainelu de Jos", NOW(), NOW()),
            (21, "Soimus","Fornadia", NOW(), NOW()),
            (21, "Soimus","Paulis", NOW(), NOW()),
            (21, "Soimus","Sulighete", NOW(), NOW()),
            (21, "Teliucu Inferior","Cincis-Cerna", NOW(), NOW()),
            (21, "Teliucu Inferior","Izvoarele", NOW(), NOW()),
            (21, "Teliucu Inferior","Teliucu Superior", NOW(), NOW()),
            (21, "Tomesti","Dobrot", NOW(), NOW()),
            (21, "Tomesti","Leaut", NOW(), NOW()),
            (21, "Tomesti","Livada", NOW(), NOW()),
            (21, "Tomesti","Obarsa", NOW(), NOW()),
            (21, "Tomesti","Steia", NOW(), NOW()),
            (21, "Tomesti","Tiulesti", NOW(), NOW()),
            (21, "Tomesti","Valea Mare de Cris", NOW(), NOW()),
            (21, "Toplita","Curpenii Silvasului", NOW(), NOW()),
            (21, "Toplita","Dealu Mic", NOW(), NOW()),
            (21, "Toplita","Dabaca", NOW(), NOW()),
            (21, "Toplita","Goles", NOW(), NOW()),
            (21, "Toplita","Hasdau", NOW(), NOW()),
            (21, "Toplita","Mosoru", NOW(), NOW()),
            (21, "Toplita","Valari", NOW(), NOW()),
            (21, "Totesti","Copaci", NOW(), NOW()),
            (21, "Totesti","Carnesti", NOW(), NOW()),
            (21, "Totesti","Paclisa", NOW(), NOW()),
            (21, "Totesti","Reea", NOW(), NOW()),
            (21, "Turdas","Pricaz", NOW(), NOW()),
            (21, "Turdas","Rapas", NOW(), NOW()),
            (21, "Turdas","Spini", NOW(), NOW()),
            (21, "Uricani","Campu lui Neag", NOW(), NOW()),
            (21, "Uricani","Valea de Brazi", NOW(), NOW()),
            (21, "Valisoara","Dealu Mare", NOW(), NOW()),
            (21, "Valisoara","Stoieneasa", NOW(), NOW()),
            (21, "Valisoara","Salistioara", NOW(), NOW()),
            (21, "Vata De Jos","Basarabasa", NOW(), NOW()),
            (21, "Vata De Jos","Birtin", NOW(), NOW()),
            (21, "Vata De Jos","Brotuna", NOW(), NOW()),
            (21, "Vata De Jos","Ciungani", NOW(), NOW()),
            (21, "Vata De Jos","Cazanesti", NOW(), NOW()),
            (21, "Vata De Jos","Ociu", NOW(), NOW()),
            (21, "Vata De Jos","Ocisor", NOW(), NOW()),
            (21, "Vata De Jos","Prihodiste", NOW(), NOW()),
            (21, "Vata De Jos","Pravaleni", NOW(), NOW()),
            (21, "Vata De Jos","Tarnava de Cris", NOW(), NOW()),
            (21, "Vata De Jos","Tatarastii de Cris", NOW(), NOW()),
            (21, "Vata De Jos","Vata de Sus", NOW(), NOW()),
            (21, "Vetel","Boia Barzii", NOW(), NOW()),
            (21, "Vetel","Bretelin", NOW(), NOW()),
            (21, "Vetel","Caoi", NOW(), NOW()),
            (21, "Vetel","Herepeia", NOW(), NOW()),
            (21, "Vetel","Lesnic", NOW(), NOW()),
            (21, "Vetel","Mintia", NOW(), NOW()),
            (21, "Vetel","Muncelu Mare", NOW(), NOW()),
            (21, "Vetel","Muncelu Mic", NOW(), NOW()),
            (21, "Vetel","Runcu Mic", NOW(), NOW()),
            (21, "Vorta","Certeju de Jos", NOW(), NOW()),
            (21, "Vorta","Coaja", NOW(), NOW()),
            (21, "Vorta","Dumesti", NOW(), NOW()),
            (21, "Vorta","Luncsoara", NOW(), NOW()),
            (21, "Vorta","Valea Poienii", NOW(), NOW()),
            (21, "Vorta","Visca", NOW(), NOW()),
            (21, "Vulcan","Dealu Babii", NOW(), NOW()),
            (21, "Vulcan","Jiu-Paroseni", NOW(), NOW()),
            (21, "Zam","Almas-Saliste", NOW(), NOW()),
            (21, "Zam","Almasel", NOW(), NOW()),
            (21, "Zam","Braseu", NOW(), NOW()),
            (21, "Zam","Cerbia", NOW(), NOW()),
            (21, "Zam","Deleni", NOW(), NOW()),
            (21, "Zam","Godinesti", NOW(), NOW()),
            (21, "Zam","Micanesti", NOW(), NOW()),
            (21, "Zam","Poganesti", NOW(), NOW()),
            (21, "Zam","Pojoga", NOW(), NOW()),
            (21, "Zam","Salciva", NOW(), NOW()),
            (21, "Zam","Tamasesti", NOW(), NOW()),
            (21, "Zam","Valea", NOW(), NOW())
        ;';
        if (config('app.env') !== 'testing') {
            DB::connection()->getPdo()->exec($sql);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=21;';
        DB::connection()->getPdo()->exec($sql);
    }
}
