<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForNT extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (30, "","Agapia", NOW(), NOW()),
            (30, "","Bahna", NOW(), NOW()),
            (30, "","Bicaz", NOW(), NOW()),
            (30, "","Bicaz-Chei", NOW(), NOW()),
            (30, "","Bicazu Ardelean", NOW(), NOW()),
            (30, "","Bira", NOW(), NOW()),
            (30, "","Bodesti", NOW(), NOW()),
            (30, "","Borca", NOW(), NOW()),
            (30, "","Borlesti", NOW(), NOW()),
            (30, "","Botesti", NOW(), NOW()),
            (30, "","Bozieni", NOW(), NOW()),
            (30, "","Bargauani", NOW(), NOW()),
            (30, "","Baltatesti", NOW(), NOW()),
            (30, "","Ceahlau", NOW(), NOW()),
            (30, "","Cordun", NOW(), NOW()),
            (30, "","Costisa", NOW(), NOW()),
            (30, "","Cracaoani", NOW(), NOW()),
            (30, "","Candesti", NOW(), NOW()),
            (30, "","Dobreni", NOW(), NOW()),
            (30, "","Dochia", NOW(), NOW()),
            (30, "","Doljesti", NOW(), NOW()),
            (30, "","Dragomiresti", NOW(), NOW()),
            (30, "","Dulcesti", NOW(), NOW()),
            (30, "","Dumbrava Rosie", NOW(), NOW()),
            (30, "","Damuc", NOW(), NOW()),
            (30, "","Farcasa", NOW(), NOW()),
            (30, "","Faurei", NOW(), NOW()),
            (30, "","Gheraesti", NOW(), NOW()),
            (30, "","Ghindaoani", NOW(), NOW()),
            (30, "","Girov", NOW(), NOW()),
            (30, "","Grinties", NOW(), NOW()),
            (30, "","Grumazesti", NOW(), NOW()),
            (30, "","Garcina", NOW(), NOW()),
            (30, "","Hangu", NOW(), NOW()),
            (30, "","Horia", NOW(), NOW()),
            (30, "","Icusesti", NOW(), NOW()),
            (30, "","Ion Creanga", NOW(), NOW()),
            (30, "","Moldoveni", NOW(), NOW()),
            (30, "","Margineni", NOW(), NOW()),
            (30, "","Oniceni", NOW(), NOW()),
            (30, "","Petricani", NOW(), NOW()),
            (30, "","Piatra Soimului", NOW(), NOW()),
            (30, "","Pipirig", NOW(), NOW()),
            (30, "","Podoleni", NOW(), NOW()),
            (30, "","Poiana Teiului", NOW(), NOW()),
            (30, "","Poienari", NOW(), NOW()),
            (30, "","Pangarati", NOW(), NOW()),
            (30, "","Pastraveni", NOW(), NOW()),
            (30, "","Rediu", NOW(), NOW()),
            (30, "","Roman", NOW(), NOW()),
            (30, "","Romani", NOW(), NOW()),
            (30, "","Roznov", NOW(), NOW()),
            (30, "","Ruginoasa", NOW(), NOW()),
            (30, "","Raucesti", NOW(), NOW()),
            (30, "","Razboieni", NOW(), NOW()),
            (30, "","Sagna", NOW(), NOW()),
            (30, "","Secuieni", NOW(), NOW()),
            (30, "","Stanita", NOW(), NOW()),
            (30, "","Sabaoani", NOW(), NOW()),
            (30, "","Savinesti", NOW(), NOW()),
            (30, "","Tarcau", NOW(), NOW()),
            (30, "","Tazlau", NOW(), NOW()),
            (30, "","Tasca", NOW(), NOW()),
            (30, "","Timisesti", NOW(), NOW()),
            (30, "","Trifesti", NOW(), NOW()),
            (30, "","Tupilati", NOW(), NOW()),
            (30, "","Targu Neamt", NOW(), NOW()),
            (30, "","Tamaseni", NOW(), NOW()),
            (30, "","Urecheni", NOW(), NOW()),
            (30, "","Valea Ursului", NOW(), NOW()),
            (30, "","Vanatori-Neamt", NOW(), NOW()),
            (30, "","Zanesti", NOW(), NOW()),
            (30, "","Stefan cel Mare", NOW(), NOW()),
            (30, "","Tibucani", NOW(), NOW()),
            (30, "Agapia","Filioara", NOW(), NOW()),
            (30, "Agapia","Sacalusesti", NOW(), NOW()),
            (30, "Agapia","Varatec", NOW(), NOW()),
            (30, "Alexandru Cel Bun","Agarcia", NOW(), NOW()),
            (30, "Alexandru Cel Bun","Bisericani", NOW(), NOW()),
            (30, "Alexandru Cel Bun","Bistrita", NOW(), NOW()),
            (30, "Alexandru Cel Bun","Scaricica", NOW(), NOW()),
            (30, "Alexandru Cel Bun","Vaduri", NOW(), NOW()),
            (30, "Alexandru Cel Bun","Viisoara", NOW(), NOW()),
            (30, "Alexandru Cel Bun","Vadurele", NOW(), NOW()),
            (30, "Bahna","Aramesti", NOW(), NOW()),
            (30, "Bahna","Brosteni", NOW(), NOW()),
            (30, "Bahna","Bahnisoara", NOW(), NOW()),
            (30, "Bahna","Izvoare", NOW(), NOW()),
            (30, "Bahna","Liliac", NOW(), NOW()),
            (30, "Bahna","Tutcanii din Deal", NOW(), NOW()),
            (30, "Bahna","Tutcanii din Vale", NOW(), NOW()),
            (30, "Baltatesti","Valea Arini", NOW(), NOW()),
            (30, "Baltatesti","Valea Seaca", NOW(), NOW()),
            (30, "Bargauani","Bahna Mare", NOW(), NOW()),
            (30, "Bargauani","Baratca", NOW(), NOW()),
            (30, "Bargauani","Breaza", NOW(), NOW()),
            (30, "Bargauani","Balanesti", NOW(), NOW()),
            (30, "Bargauani","Certieni", NOW(), NOW()),
            (30, "Bargauani","Chilia", NOW(), NOW()),
            (30, "Bargauani","Darloaia", NOW(), NOW()),
            (30, "Bargauani","Ghelaiesti", NOW(), NOW()),
            (30, "Bargauani","Homiceni", NOW(), NOW()),
            (30, "Bargauani","Hartop", NOW(), NOW()),
            (30, "Bargauani","Talpa", NOW(), NOW()),
            (30, "Bargauani","Vladiceni", NOW(), NOW()),
            (30, "Bicaz","Capsa", NOW(), NOW()),
            (30, "Bicaz","Dodeni", NOW(), NOW()),
            (30, "Bicaz","Izvoru Muntelui", NOW(), NOW()),
            (30, "Bicaz","Izvorul Alb", NOW(), NOW()),
            (30, "Bicaz","Potoci", NOW(), NOW()),
            (30, "Bicaz","Secu", NOW(), NOW()),
            (30, "Bicaz-Chei","Barnadu", NOW(), NOW()),
            (30, "Bicaz-Chei","Gherman", NOW(), NOW()),
            (30, "Bicaz-Chei","Ivanes", NOW(), NOW()),
            (30, "Bicazu Ardelean","Telec", NOW(), NOW()),
            (30, "Bicazu Ardelean","Ticos", NOW(), NOW()),
            (30, "Bira","Boghicea", NOW(), NOW()),
            (30, "Bira","Causeni", NOW(), NOW()),
            (30, "Bira","Negresti", NOW(), NOW()),
            (30, "Bira","Nistria", NOW(), NOW()),
            (30, "Bira","Rediu", NOW(), NOW()),
            (30, "Bira","Slobozia", NOW(), NOW()),
            (30, "Bodesti","Bodestii de Jos", NOW(), NOW()),
            (30, "Bodesti","Corni", NOW(), NOW()),
            (30, "Bodesti","Oslobeni", NOW(), NOW()),
            (30, "Borca","Lunca", NOW(), NOW()),
            (30, "Borca","Madei", NOW(), NOW()),
            (30, "Borca","Paraul Carjei", NOW(), NOW()),
            (30, "Borca","Paraul Pantei", NOW(), NOW()),
            (30, "Borca","Sabasa", NOW(), NOW()),
            (30, "Borca","Soci", NOW(), NOW()),
            (30, "Borlesti","Mastacan", NOW(), NOW()),
            (30, "Borlesti","Nechit", NOW(), NOW()),
            (30, "Borlesti","Ruseni", NOW(), NOW()),
            (30, "Borlesti","Sovoaia", NOW(), NOW()),
            (30, "Botesti","Barticesti", NOW(), NOW()),
            (30, "Botesti","David", NOW(), NOW()),
            (30, "Botesti","Moreni", NOW(), NOW()),
            (30, "Botesti","Munteni", NOW(), NOW()),
            (30, "Botesti","Nisiporesti", NOW(), NOW()),
            (30, "Botesti","Valeni", NOW(), NOW()),
            (30, "Bozieni","Baneasa", NOW(), NOW()),
            (30, "Bozieni","Craiesti", NOW(), NOW()),
            (30, "Bozieni","Cuci", NOW(), NOW()),
            (30, "Bozieni","Iucsa", NOW(), NOW()),
            (30, "Brusturi-Draganesti","Brusturi", NOW(), NOW()),
            (30, "Brusturi-Draganesti","Draganesti", NOW(), NOW()),
            (30, "Brusturi-Draganesti","Grosi", NOW(), NOW()),
            (30, "Brusturi-Draganesti","Ortasti", NOW(), NOW()),
            (30, "Brusturi-Draganesti","Poiana", NOW(), NOW()),
            (30, "Brusturi-Draganesti","Rasca", NOW(), NOW()),
            (30, "Brusturi-Draganesti","Tarzia", NOW(), NOW()),
            (30, "Brusturi-Draganesti","Soimaresti", NOW(), NOW()),
            (30, "Candesti","Barcanesti", NOW(), NOW()),
            (30, "Candesti","Dragova", NOW(), NOW()),
            (30, "Candesti","Padureni", NOW(), NOW()),
            (30, "Candesti","Vadurele", NOW(), NOW()),
            (30, "Candesti","Tardenii Mici", NOW(), NOW()),
            (30, "Ceahlau","Bistricioara", NOW(), NOW()),
            (30, "Ceahlau","Paraul Mare", NOW(), NOW()),
            (30, "Cordun","Pildesti", NOW(), NOW()),
            (30, "Cordun","Simionesti", NOW(), NOW()),
            (30, "Costisa","Dornesti", NOW(), NOW()),
            (30, "Costisa","Frunzeni", NOW(), NOW()),
            (30, "Costisa","Manoaia", NOW(), NOW()),
            (30, "Cracaoani","Cracaul Negru", NOW(), NOW()),
            (30, "Cracaoani","Magazia", NOW(), NOW()),
            (30, "Cracaoani","Mitocu Balan", NOW(), NOW()),
            (30, "Cracaoani","Poiana Cracaoani", NOW(), NOW()),
            (30, "Damuc","Huisurez", NOW(), NOW()),
            (30, "Damuc","Trei Fantani", NOW(), NOW()),
            (30, "Dobreni","Casaria", NOW(), NOW()),
            (30, "Dobreni","Negresti", NOW(), NOW()),
            (30, "Dobreni","Poiana", NOW(), NOW()),
            (30, "Dobreni","Sarata", NOW(), NOW()),
            (30, "Dochia","Balusesti", NOW(), NOW()),
            (30, "Doljesti","Buhonca", NOW(), NOW()),
            (30, "Doljesti","Buruienesti", NOW(), NOW()),
            (30, "Doljesti","Rotunda", NOW(), NOW()),
            (30, "Dragomiresti","Bornis", NOW(), NOW()),
            (30, "Dragomiresti","Hlapesti", NOW(), NOW()),
            (30, "Dragomiresti","Mastacan", NOW(), NOW()),
            (30, "Dragomiresti","Unghi", NOW(), NOW()),
            (30, "Dragomiresti","Vad", NOW(), NOW()),
            (30, "Dulcesti","Britcani", NOW(), NOW()),
            (30, "Dulcesti","Corhana", NOW(), NOW()),
            (30, "Dulcesti","Carlig", NOW(), NOW()),
            (30, "Dulcesti","Poiana", NOW(), NOW()),
            (30, "Dulcesti","Rosiori", NOW(), NOW()),
            (30, "Dumbrava Rosie","Brasauti", NOW(), NOW()),
            (30, "Dumbrava Rosie","Cut", NOW(), NOW()),
            (30, "Dumbrava Rosie","Izvoare", NOW(), NOW()),
            (30, "Farcasa","Busmei", NOW(), NOW()),
            (30, "Farcasa","Frumosu", NOW(), NOW()),
            (30, "Farcasa","Popesti", NOW(), NOW()),
            (30, "Farcasa","Stejaru", NOW(), NOW()),
            (30, "Faurei","Budesti", NOW(), NOW()),
            (30, "Faurei","Climesti", NOW(), NOW()),
            (30, "Faurei","Micsunesti", NOW(), NOW()),
            (30, "Garcina","Almas", NOW(), NOW()),
            (30, "Garcina","Cuejdiu", NOW(), NOW()),
            (30, "Gheraesti","Gheraestii Noi", NOW(), NOW()),
            (30, "Gheraesti","Tetcani", NOW(), NOW()),
            (30, "Girov","Botesti", NOW(), NOW()),
            (30, "Girov","Caciulesti", NOW(), NOW()),
            (30, "Girov","Doina", NOW(), NOW()),
            (30, "Girov","Danesti", NOW(), NOW()),
            (30, "Girov","Gura Vaii", NOW(), NOW()),
            (30, "Girov","Popesti", NOW(), NOW()),
            (30, "Girov","Turturesti", NOW(), NOW()),
            (30, "Girov","Versesti", NOW(), NOW()),
            (30, "Grinties","Bradu", NOW(), NOW()),
            (30, "Grinties","Poiana", NOW(), NOW()),
            (30, "Grumazesti","Curechistea", NOW(), NOW()),
            (30, "Grumazesti","Netezi", NOW(), NOW()),
            (30, "Grumazesti","Topolita", NOW(), NOW()),
            (30, "Hangu","Buhalnita", NOW(), NOW()),
            (30, "Hangu","Chiriteni", NOW(), NOW()),
            (30, "Hangu","Grozavesti", NOW(), NOW()),
            (30, "Hangu","Ruginesti", NOW(), NOW()),
            (30, "Horia","Cotu Vames", NOW(), NOW()),
            (30, "Icusesti","Balusesti", NOW(), NOW()),
            (30, "Icusesti","Batranesti", NOW(), NOW()),
            (30, "Icusesti","Mesteacan", NOW(), NOW()),
            (30, "Icusesti","Rocna", NOW(), NOW()),
            (30, "Icusesti","Spiridonesti", NOW(), NOW()),
            (30, "Icusesti","Tabara", NOW(), NOW()),
            (30, "Ion Creanga","Averesti", NOW(), NOW()),
            (30, "Ion Creanga","Izvoru", NOW(), NOW()),
            (30, "Ion Creanga","Muncelu", NOW(), NOW()),
            (30, "Ion Creanga","Recea", NOW(), NOW()),
            (30, "Ion Creanga","Stejaru", NOW(), NOW()),
            (30, "Margineni","Hoisesti", NOW(), NOW()),
            (30, "Margineni","Hartesti", NOW(), NOW()),
            (30, "Margineni","Itrinesti", NOW(), NOW()),
            (30, "Moldoveni","Hociungi", NOW(), NOW()),
            (30, "Oniceni","Ciornei", NOW(), NOW()),
            (30, "Oniceni","Gorun", NOW(), NOW()),
            (30, "Oniceni","Linsesti", NOW(), NOW()),
            (30, "Oniceni","Lunca", NOW(), NOW()),
            (30, "Oniceni","Marmureni", NOW(), NOW()),
            (30, "Oniceni","Pietrosu", NOW(), NOW()),
            (30, "Oniceni","Poiana Humei", NOW(), NOW()),
            (30, "Oniceni","Pustieta", NOW(), NOW()),
            (30, "Oniceni","Solca", NOW(), NOW()),
            (30, "Oniceni","Valea Enei", NOW(), NOW()),
            (30, "Pangarati","Oantu", NOW(), NOW()),
            (30, "Pangarati","Poiana", NOW(), NOW()),
            (30, "Pangarati","Preluca", NOW(), NOW()),
            (30, "Pangarati","Pangaracior", NOW(), NOW()),
            (30, "Pangarati","Stejaru", NOW(), NOW()),
            (30, "Pastraveni","Lunca Moldovei", NOW(), NOW()),
            (30, "Pastraveni","Radeni", NOW(), NOW()),
            (30, "Pastraveni","Spiesti", NOW(), NOW()),
            (30, "Petricani","Boistea", NOW(), NOW()),
            (30, "Petricani","Tarpesti", NOW(), NOW()),
            (30, "Petricani","Tolici", NOW(), NOW()),
            (30, "Piatra Neamt","Ciritei", NOW(), NOW()),
            (30, "Piatra Neamt","Doamna", NOW(), NOW()),
            (30, "Piatra Neamt","Piatra-Neamt", NOW(), NOW()),
            (30, "Piatra Neamt","Valeni", NOW(), NOW()),
            (30, "Piatra Soimului","Luminis", NOW(), NOW()),
            (30, "Piatra Soimului","Negulesti", NOW(), NOW()),
            (30, "Piatra Soimului","Poieni", NOW(), NOW()),
            (30, "Pipirig","Boboiesti", NOW(), NOW()),
            (30, "Pipirig","Dolhesti", NOW(), NOW()),
            (30, "Pipirig","Leghin", NOW(), NOW()),
            (30, "Pipirig","Pluton", NOW(), NOW()),
            (30, "Pipirig","Pataligeni", NOW(), NOW()),
            (30, "Pipirig","Stanca", NOW(), NOW()),
            (30, "Podoleni","Negritesti", NOW(), NOW()),
            (30, "Poiana Teiului","Calugareni", NOW(), NOW()),
            (30, "Poiana Teiului","Dreptu", NOW(), NOW()),
            (30, "Poiana Teiului","Galu", NOW(), NOW()),
            (30, "Poiana Teiului","Petru Voda", NOW(), NOW()),
            (30, "Poiana Teiului","Poiana Largului", NOW(), NOW()),
            (30, "Poiana Teiului","Paraul Fagului", NOW(), NOW()),
            (30, "Poiana Teiului","Roseni", NOW(), NOW()),
            (30, "Poiana Teiului","Ruseni", NOW(), NOW()),
            (30, "Poiana Teiului","Savinesti", NOW(), NOW()),
            (30, "Poiana Teiului","Topoliceni", NOW(), NOW()),
            (30, "Poienari","Bunghi", NOW(), NOW()),
            (30, "Poienari","Ciurea", NOW(), NOW()),
            (30, "Poienari","Holm", NOW(), NOW()),
            (30, "Poienari","Patricheni", NOW(), NOW()),
            (30, "Poienari","Pancesti", NOW(), NOW()),
            (30, "Poienari","Sacaleni", NOW(), NOW()),
            (30, "Poienari","Talpalai", NOW(), NOW()),
            (30, "Raucesti","Oglinzi", NOW(), NOW()),
            (30, "Raucesti","Savesti", NOW(), NOW()),
            (30, "Raucesti","Ungheni", NOW(), NOW()),
            (30, "Razboieni","Borseni", NOW(), NOW()),
            (30, "Razboieni","Razboienii de Jos", NOW(), NOW()),
            (30, "Razboieni","Valea Alba", NOW(), NOW()),
            (30, "Razboieni","Valea Mare", NOW(), NOW()),
            (30, "Rediu","Betesti", NOW(), NOW()),
            (30, "Rediu","Poloboc", NOW(), NOW()),
            (30, "Rediu","Socea", NOW(), NOW()),
            (30, "Romani","Gosmani", NOW(), NOW()),
            (30, "Romani","Silistea", NOW(), NOW()),
            (30, "Roznov","Chintinici", NOW(), NOW()),
            (30, "Roznov","Slobozia", NOW(), NOW()),
            (30, "Ruginoasa","Bozienii de Sus", NOW(), NOW()),
            (30, "Sabaoani","Traian", NOW(), NOW()),
            (30, "Sagna","Gadinti", NOW(), NOW()),
            (30, "Sagna","Lutca", NOW(), NOW()),
            (30, "Sagna","Vulpasesti", NOW(), NOW()),
            (30, "Savinesti","Dumbrava Deal", NOW(), NOW()),
            (30, "Secuieni","Basta", NOW(), NOW()),
            (30, "Secuieni","Bogzesti", NOW(), NOW()),
            (30, "Secuieni","Butnaresti", NOW(), NOW()),
            (30, "Secuieni","Barjoveni", NOW(), NOW()),
            (30, "Secuieni","Giulesti", NOW(), NOW()),
            (30, "Secuieni","Prajesti", NOW(), NOW()),
            (30, "Secuieni","Secuienii Noi", NOW(), NOW()),
            (30, "Secuieni","Uncesti", NOW(), NOW()),
            (30, "Stanita","Chicerea", NOW(), NOW()),
            (30, "Stanita","Ghidion", NOW(), NOW()),
            (30, "Stanita","Poienile Oancei", NOW(), NOW()),
            (30, "Stanita","Todireni", NOW(), NOW()),
            (30, "Stanita","Veja", NOW(), NOW()),
            (30, "Stanita","Vladnicele", NOW(), NOW()),
            (30, "Stefan Cel Mare","Bordea", NOW(), NOW()),
            (30, "Stefan Cel Mare","Carligi", NOW(), NOW()),
            (30, "Stefan Cel Mare","Deleni", NOW(), NOW()),
            (30, "Stefan Cel Mare","Dusesti", NOW(), NOW()),
            (30, "Stefan Cel Mare","Ghigoiesti", NOW(), NOW()),
            (30, "Stefan Cel Mare","Soci", NOW(), NOW()),
            (30, "Tamaseni","Adjudeni", NOW(), NOW()),
            (30, "Tarcau","Ardeluta", NOW(), NOW()),
            (30, "Tarcau","Brates", NOW(), NOW()),
            (30, "Tarcau","Cazaci", NOW(), NOW()),
            (30, "Tarcau","Schitu Tarcau", NOW(), NOW()),
            (30, "Tarcau","Straja", NOW(), NOW()),
            (30, "Targu Neamt","Blebea", NOW(), NOW()),
            (30, "Targu Neamt","Humulesti", NOW(), NOW()),
            (30, "Targu Neamt","Humulestii Noi", NOW(), NOW()),
            (30, "Tasca","Hamzoaia", NOW(), NOW()),
            (30, "Tasca","Neagra", NOW(), NOW()),
            (30, "Tasca","Ticos-Floarea", NOW(), NOW()),
            (30, "Tibucani","Davideni", NOW(), NOW()),
            (30, "Tibucani","Tibucanii de Jos", NOW(), NOW()),
            (30, "Timisesti","Dumbrava", NOW(), NOW()),
            (30, "Timisesti","Plaiesu", NOW(), NOW()),
            (30, "Timisesti","Preutesti", NOW(), NOW()),
            (30, "Timisesti","Zvoranesti", NOW(), NOW()),
            (30, "Trifesti","Miron Costin", NOW(), NOW()),
            (30, "Tupilati","Aramoaia", NOW(), NOW()),
            (30, "Tupilati","Hanul Ancutei", NOW(), NOW()),
            (30, "Tupilati","Totoiesti", NOW(), NOW()),
            (30, "Urecheni","Ingaresti", NOW(), NOW()),
            (30, "Urecheni","Plugari", NOW(), NOW()),
            (30, "Valea Ursului","Bucium", NOW(), NOW()),
            (30, "Valea Ursului","Chilii", NOW(), NOW()),
            (30, "Valea Ursului","Giurgeni", NOW(), NOW()),
            (30, "Valea Ursului","Muncelu de Jos", NOW(), NOW()),
            (30, "Vanatori-Neamt","Lunca", NOW(), NOW()),
            (30, "Vanatori-Neamt","Manastirea Neamt", NOW(), NOW()),
            (30, "Vanatori-Neamt","Nemtisor", NOW(), NOW()),
            (30, "Zanesti","Traian", NOW(), NOW())
        ;';
        DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=30;';
        DB::connection()->getPdo()->exec($sql);
    }
}
