<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForBT extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (8, "","Albesti", NOW(), NOW()),
            (8, "","Avrameni", NOW(), NOW()),
            (8, "","Botosani", NOW(), NOW()),
            (8, "","Broscauti", NOW(), NOW()),
            (8, "","Braesti", NOW(), NOW()),
            (8, "","Bucecea", NOW(), NOW()),
            (8, "","Baluseni", NOW(), NOW()),
            (8, "","Concesti", NOW(), NOW()),
            (8, "","Copalau", NOW(), NOW()),
            (8, "","Cordareni", NOW(), NOW()),
            (8, "","Corlateni", NOW(), NOW()),
            (8, "","Corni", NOW(), NOW()),
            (8, "","Cosula", NOW(), NOW()),
            (8, "","Cotusca", NOW(), NOW()),
            (8, "","Cristesti", NOW(), NOW()),
            (8, "","Cristinesti", NOW(), NOW()),
            (8, "","Curtesti", NOW(), NOW()),
            (8, "","Candesti", NOW(), NOW()),
            (8, "","Calarasi", NOW(), NOW()),
            (8, "","Darabani", NOW(), NOW()),
            (8, "","Dersca", NOW(), NOW()),
            (8, "","Dimacheni", NOW(), NOW()),
            (8, "","Dobarceni", NOW(), NOW()),
            (8, "","Dorohoi", NOW(), NOW()),
            (8, "","Draguseni", NOW(), NOW()),
            (8, "","Durnesti", NOW(), NOW()),
            (8, "","Dangeni", NOW(), NOW()),
            (8, "","Flamanzi", NOW(), NOW()),
            (8, "","Frumusica", NOW(), NOW()),
            (8, "","George Enescu", NOW(), NOW()),
            (8, "","Gorbanesti", NOW(), NOW()),
            (8, "","Havarna", NOW(), NOW()),
            (8, "","Hiliseu-Horia", NOW(), NOW()),
            (8, "","Hlipiceni", NOW(), NOW()),
            (8, "","Hudesti", NOW(), NOW()),
            (8, "","Hanesti", NOW(), NOW()),
            (8, "","Ibanesti", NOW(), NOW()),
            (8, "","Leorda", NOW(), NOW()),
            (8, "","Lozna", NOW(), NOW()),
            (8, "","Lunca", NOW(), NOW()),
            (8, "","Manoleasa", NOW(), NOW()),
            (8, "","Mihaileni", NOW(), NOW()),
            (8, "","Mihalaseni", NOW(), NOW()),
            (8, "","Mileanca", NOW(), NOW()),
            (8, "","Mitoc", NOW(), NOW()),
            (8, "","Nicseni", NOW(), NOW()),
            (8, "","Pomarla", NOW(), NOW()),
            (8, "","Prajeni", NOW(), NOW()),
            (8, "","Paltinis", NOW(), NOW()),
            (8, "","Ripiceni", NOW(), NOW()),
            (8, "","Roma", NOW(), NOW()),
            (8, "","Romanesti", NOW(), NOW()),
            (8, "","Rachiti", NOW(), NOW()),
            (8, "","Radauti-Prut", NOW(), NOW()),
            (8, "","Rauseni", NOW(), NOW()),
            (8, "","Santa Mare", NOW(), NOW()),
            (8, "","Stauceni", NOW(), NOW()),
            (8, "","Suharau", NOW(), NOW()),
            (8, "","Sulita", NOW(), NOW()),
            (8, "","Saveni", NOW(), NOW()),
            (8, "","Todireni", NOW(), NOW()),
            (8, "","Trusesti", NOW(), NOW()),
            (8, "","Tudora", NOW(), NOW()),
            (8, "","Ungureni", NOW(), NOW()),
            (8, "","Unteni", NOW(), NOW()),
            (8, "","Viisoara", NOW(), NOW()),
            (8, "","Vladeni", NOW(), NOW()),
            (8, "","Vlasinesti", NOW(), NOW()),
            (8, "","Vorniceni", NOW(), NOW()),
            (8, "","Vorona", NOW(), NOW()),
            (8, "","Varfu Campului", NOW(), NOW()),
            (8, "","Vaculesti", NOW(), NOW()),
            (8, "","Sendriceni", NOW(), NOW()),
            (8, "","Stefanesti", NOW(), NOW()),
            (8, "","Stiubieni", NOW(), NOW()),
            (8, "Albesti","Buimaceni", NOW(), NOW()),
            (8, "Albesti","Costiugeni", NOW(), NOW()),
            (8, "Albesti","Jijia", NOW(), NOW()),
            (8, "Albesti","Mascateni", NOW(), NOW()),
            (8, "Albesti","Tudor Vladimirescu", NOW(), NOW()),
            (8, "Avrameni","Adaseni", NOW(), NOW()),
            (8, "Avrameni","Aurel Vlaicu", NOW(), NOW()),
            (8, "Avrameni","Dimitrie Cantemir", NOW(), NOW()),
            (8, "Avrameni","Ichimeni", NOW(), NOW()),
            (8, "Avrameni","Panaitoaia", NOW(), NOW()),
            (8, "Avrameni","Timus", NOW(), NOW()),
            (8, "Avrameni","Tudor Vladimirescu", NOW(), NOW()),
            (8, "Avrameni","Zoitani", NOW(), NOW()),
            (8, "Baluseni","Buzeni", NOW(), NOW()),
            (8, "Baluseni","Balusenii Noi", NOW(), NOW()),
            (8, "Baluseni","Cosuleni", NOW(), NOW()),
            (8, "Baluseni","Draxini", NOW(), NOW()),
            (8, "Baluseni","Zaicesti", NOW(), NOW()),
            (8, "Blindesti","Blandesti", NOW(), NOW()),
            (8, "Blindesti","Cerchejeni", NOW(), NOW()),
            (8, "Blindesti","Soldanesti", NOW(), NOW()),
            (8, "Braesti","Poiana", NOW(), NOW()),
            (8, "Braesti","Popeni", NOW(), NOW()),
            (8, "Braesti","Valcelele", NOW(), NOW()),
            (8, "Broscauti","Slobozia", NOW(), NOW()),
            (8, "Bucecea","Bohoghina", NOW(), NOW()),
            (8, "Bucecea","Calinesti", NOW(), NOW()),
            (8, "Calarasi","Libertatea", NOW(), NOW()),
            (8, "Calarasi","Plesani", NOW(), NOW()),
            (8, "Candesti","Calinesti", NOW(), NOW()),
            (8, "Candesti","Talpa", NOW(), NOW()),
            (8, "Candesti","Vitcani", NOW(), NOW()),
            (8, "Concesti","Movileni", NOW(), NOW()),
            (8, "Copalau","Cerbu", NOW(), NOW()),
            (8, "Copalau","Cotu", NOW(), NOW()),
            (8, "Cordareni","Grivita", NOW(), NOW()),
            (8, "Cordăreni","Slobozia", NOW(), NOW()),
            (8, "Corlateni","Carasa", NOW(), NOW()),
            (8, "Corlateni","Podeni", NOW(), NOW()),
            (8, "Corlateni","Vladeni", NOW(), NOW()),
            (8, "Corni","Balta Arsa", NOW(), NOW()),
            (8, "Corni","Mesteacan", NOW(), NOW()),
            (8, "Corni","Sarafinesti", NOW(), NOW()),
            (8, "Cosula","Buda", NOW(), NOW()),
            (8, "Cosula","Padureni", NOW(), NOW()),
            (8, "Cosula","Supitca", NOW(), NOW()),
            (8, "Cotusca","Avram Iancu", NOW(), NOW()),
            (8, "Cotusca","Cotu Miculinti", NOW(), NOW()),
            (8, "Cotusca","Crasnaleuca", NOW(), NOW()),
            (8, "Cotusca","Ghireni", NOW(), NOW()),
            (8, "Cotusca","Mihail Kogalniceanu", NOW(), NOW()),
            (8, "Cotusca","Nichiteni", NOW(), NOW()),
            (8, "Cotusca","Nicolae Balcescu", NOW(), NOW()),
            (8, "Cotusca","Putureni", NOW(), NOW()),
            (8, "Cristesti","Oneaga", NOW(), NOW()),
            (8, "Cristesti","Schit-Oraseni", NOW(), NOW()),
            (8, "Cristesti","Unguroaia", NOW(), NOW()),
            (8, "Cristinesti","Baranca", NOW(), NOW()),
            (8, "Cristinesti","Dragalina", NOW(), NOW()),
            (8, "Cristinesti","Fundu Hertii", NOW(), NOW()),
            (8, "Cristinesti","Poiana", NOW(), NOW()),
            (8, "Cristinești","Damileni", NOW(), NOW()),
            (8, "Curtesti","Agafton", NOW(), NOW()),
            (8, "Curtesti","Baiceni", NOW(), NOW()),
            (8, "Curtesti","Hudum", NOW(), NOW()),
            (8, "Curtesti","Manastirea Doamnei", NOW(), NOW()),
            (8, "Curtesti","Oraseni-Deal", NOW(), NOW()),
            (8, "Curtesti","Oraseni-Vale", NOW(), NOW()),
            (8, "Dangeni","Hulub", NOW(), NOW()),
            (8, "Dangeni","Iacobeni", NOW(), NOW()),
            (8, "Dangeni","Strahotin", NOW(), NOW()),
            (8, "Darabani","Bajura", NOW(), NOW()),
            (8, "Darabani","Esanca", NOW(), NOW()),
            (8, "Darabani","Lismanita", NOW(), NOW()),
            (8, "Dimacheni","Mateieni", NOW(), NOW()),
            (8, "Dimacheni","Recia-Verbia", NOW(), NOW()),
            (8, "Dobarceni","Bivolari", NOW(), NOW()),
            (8, "Dobarceni","Brateni", NOW(), NOW()),
            (8, "Dobarceni","Cismanesti", NOW(), NOW()),
            (8, "Dobarceni","Livada", NOW(), NOW()),
            (8, "Dobarceni","Murguta", NOW(), NOW()),
            (8, "Dorohoi","Dealu Mare", NOW(), NOW()),
            (8, "Dorohoi","Loturi Enescu", NOW(), NOW()),
            (8, "Dorohoi","Progresul", NOW(), NOW()),
            (8, "Draguseni","Podriga", NOW(), NOW()),
            (8, "Draguseni","Sarata-Draguseni", NOW(), NOW()),
            (8, "Durnesti","Brosteni", NOW(), NOW()),
            (8, "Durnesti","Barsanesti", NOW(), NOW()),
            (8, "Durnesti","Babiceni", NOW(), NOW()),
            (8, "Durnesti","Cucuteni", NOW(), NOW()),
            (8, "Durnesti","Guranda", NOW(), NOW()),
            (8, "Flamanzi","Chitoveni", NOW(), NOW()),
            (8, "Flamanzi","Nicolae Balcescu", NOW(), NOW()),
            (8, "Flamanzi","Poiana", NOW(), NOW()),
            (8, "Flamanzi","Prisacani", NOW(), NOW()),
            (8, "Frumusica","Boscoteni", NOW(), NOW()),
            (8, "Frumusica","Radeni", NOW(), NOW()),
            (8, "Frumusica","Storesti", NOW(), NOW()),
            (8, "Frumusica","Vladeni-Deal", NOW(), NOW()),
            (8, "Frumusica","Sendreni", NOW(), NOW()),
            (8, "George Enescu","Arborea", NOW(), NOW()),
            (8, "George Enescu","Dumeni", NOW(), NOW()),
            (8, "George Enescu","Popeni", NOW(), NOW()),
            (8, "George Enescu","Stanca", NOW(), NOW()),
            (8, "Gorbanesti","Batranesti", NOW(), NOW()),
            (8, "Gorbanesti","George Cosbuc", NOW(), NOW()),
            (8, "Gorbanesti","Mihai Eminescu", NOW(), NOW()),
            (8, "Gorbanesti","Siliscani", NOW(), NOW()),
            (8, "Gorbanesti","Socrujeni", NOW(), NOW()),
            (8, "Gorbanesti","Viforeni", NOW(), NOW()),
            (8, "Gorbanesti","Vanatori", NOW(), NOW()),
            (8, "Hanesti","Borolea", NOW(), NOW()),
            (8, "Hanesti","Moara Jorii", NOW(), NOW()),
            (8, "Hanesti","Sarata-Basarab", NOW(), NOW()),
            (8, "Hanesti","Slobozia Hanesti", NOW(), NOW()),
            (8, "Havarna","Balinti", NOW(), NOW()),
            (8, "Havarna","Galbeni", NOW(), NOW()),
            (8, "Havarna","Garbeni", NOW(), NOW()),
            (8, "Havarna","Niculcea", NOW(), NOW()),
            (8, "Havarna","Tataraseni", NOW(), NOW()),
            (8, "Hiliseu-Horia","Corjauti", NOW(), NOW()),
            (8, "Hiliseu-Horia","Hiliseu-Closca", NOW(), NOW()),
            (8, "Hiliseu-Horia","Hiliseu-Crisan", NOW(), NOW()),
            (8, "Hiliseu-Horia","Iezer", NOW(), NOW()),
            (8, "Hlipiceni","Dragalina", NOW(), NOW()),
            (8, "Hlipiceni","Victoria", NOW(), NOW()),
            (8, "Hudesti","Alba", NOW(), NOW()),
            (8, "Hudesti","Baranca", NOW(), NOW()),
            (8, "Hudesti","Mlenauti", NOW(), NOW()),
            (8, "Hudești","Baseu", NOW(), NOW()),
            (8, "Hudești","Vatra", NOW(), NOW()),
            (8, "Ibanesti","Dumbravita", NOW(), NOW()),
            (8, "Leorda","Belcea", NOW(), NOW()),
            (8, "Leorda","Costinesti", NOW(), NOW()),
            (8, "Leorda","Dolina", NOW(), NOW()),
            (8, "Leorda","Mitoc", NOW(), NOW()),
            (8, "Lozna","Strateni", NOW(), NOW()),
            (8, "Lunca","Stroiesti", NOW(), NOW()),
            (8, "Lunca","Zlatunoaia", NOW(), NOW()),
            (8, "Manoleasa","Bold", NOW(), NOW()),
            (8, "Manoleasa","Flondora", NOW(), NOW()),
            (8, "Manoleasa","Iorga", NOW(), NOW()),
            (8, "Manoleasa","Liveni", NOW(), NOW()),
            (8, "Manoleasa","Loturi", NOW(), NOW()),
            (8, "Manoleasa","Manoleasa-Prut", NOW(), NOW()),
            (8, "Manoleasa","Sadoveni", NOW(), NOW()),
            (8, "Manoleasa","Zahoreni", NOW(), NOW()),
            (8, "Manoleasa","Serpenita", NOW(), NOW()),
            (8, "Mihai Eminescu","Baisa", NOW(), NOW()),
            (8, "Mihai Eminescu","Cervicesti", NOW(), NOW()),
            (8, "Mihai Eminescu","Cervicesti-Deal", NOW(), NOW()),
            (8, "Mihai Eminescu","Cucorani", NOW(), NOW()),
            (8, "Mihai Eminescu","Catamaresti", NOW(), NOW()),
            (8, "Mihai Eminescu","Catamaresti-Deal", NOW(), NOW()),
            (8, "Mihai Eminescu","Ipotesti", NOW(), NOW()),
            (8, "Mihai Eminescu","Manolesti", NOW(), NOW()),
            (8, "Mihai Eminescu","Stancesti", NOW(), NOW()),
            (8, "Mihaileni","Parau Negru", NOW(), NOW()),
            (8, "Mihaileni","Rogojesti", NOW(), NOW()),
            (8, "Mihalaseni","Caraiman", NOW(), NOW()),
            (8, "Mihalaseni","Negresti", NOW(), NOW()),
            (8, "Mihalaseni","Nastase", NOW(), NOW()),
            (8, "Mihalaseni","Paun", NOW(), NOW()),
            (8, "Mihalaseni","Sarata", NOW(), NOW()),
            (8, "Mihalaseni","Slobozia Siliscani", NOW(), NOW()),
            (8, "Mileanca","Codreni", NOW(), NOW()),
            (8, "Mileanca","Scutari", NOW(), NOW()),
            (8, "Mileanca","Selistea", NOW(), NOW()),
            (8, "Mitoc","Horia", NOW(), NOW()),
            (8, "Nicseni","Dacia", NOW(), NOW()),
            (8, "Nicseni","Dorobanti", NOW(), NOW()),
            (8, "Paltinis","Cuzlau", NOW(), NOW()),
            (8, "Paltinis","Horodistea", NOW(), NOW()),
            (8, "Paltinis","Slobozia", NOW(), NOW()),
            (8, "Pomarla","Hulubesti", NOW(), NOW()),
            (8, "Pomarla","Racovat", NOW(), NOW()),
            (8, "Prajeni","Campeni", NOW(), NOW()),
            (8, "Prajeni","Luparia", NOW(), NOW()),
            (8, "Prajeni","Miletin", NOW(), NOW()),
            (8, "Rachiti","Cismea", NOW(), NOW()),
            (8, "Rachiti","Costesti", NOW(), NOW()),
            (8, "Rachiti","Rosiori", NOW(), NOW()),
            (8, "Radauti-Prut","Miorcani", NOW(), NOW()),
            (8, "Radauti-Prut","Rediu", NOW(), NOW()),
            (8, "Rauseni","Doina", NOW(), NOW()),
            (8, "Rauseni","Pogorasti", NOW(), NOW()),
            (8, "Rauseni","Rediu", NOW(), NOW()),
            (8, "Rauseni","Stolniceni", NOW(), NOW()),
            (8, "Ripiceni","Cinghiniia", NOW(), NOW()),
            (8, "Ripiceni","Lehnesti", NOW(), NOW()),
            (8, "Ripiceni","Movila Rupta", NOW(), NOW()),
            (8, "Ripiceni","Popoaia", NOW(), NOW()),
            (8, "Ripiceni","Ripicenii Vechi", NOW(), NOW()),
            (8, "Ripiceni","Rasca", NOW(), NOW()),
            (8, "Roma","Cotargaci", NOW(), NOW()),
            (8, "Romanesti","Damideni", NOW(), NOW()),
            (8, "Romanesti","Romanesti-Vale", NOW(), NOW()),
            (8, "Romanesti","Sarata", NOW(), NOW()),
            (8, "Santa Mare","Berza", NOW(), NOW()),
            (8, "Santa Mare","Bogdanesti", NOW(), NOW()),
            (8, "Santa Mare","Badarai", NOW(), NOW()),
            (8, "Santa Mare","Durnesti", NOW(), NOW()),
            (8, "Santa Mare","Iliseni", NOW(), NOW()),
            (8, "Santa Mare","Ranghilesti", NOW(), NOW()),
            (8, "Santa Mare","Ranghilesti-Deal", NOW(), NOW()),
            (8, "Saveni","Bodeasa", NOW(), NOW()),
            (8, "Saveni","Bozieni", NOW(), NOW()),
            (8, "Saveni","Chiscareni", NOW(), NOW()),
            (8, "Saveni","Petricani", NOW(), NOW()),
            (8, "Saveni","Sat Nou", NOW(), NOW()),
            (8, "Sendriceni","Horlaceni", NOW(), NOW()),
            (8, "Sendriceni","Padureni", NOW(), NOW()),
            (8, "Stauceni","Silistea", NOW(), NOW()),
            (8, "Stauceni","Tocileni", NOW(), NOW()),
            (8, "Stauceni","Victoria", NOW(), NOW()),
            (8, "Stefanesti","Bobulesti", NOW(), NOW()),
            (8, "Stefanesti","Badiuti", NOW(), NOW()),
            (8, "Stefanesti","Stanca", NOW(), NOW()),
            (8, "Stefanesti","Stefanesti-Sat", NOW(), NOW()),
            (8, "Stiubieni","Ibaneasa", NOW(), NOW()),
            (8, "Stiubieni","Negreni", NOW(), NOW()),
            (8, "Suharau","Izvoare", NOW(), NOW()),
            (8, "Suharau","Lisna", NOW(), NOW()),
            (8, "Suharau","Oroftiana", NOW(), NOW()),
            (8, "Suharau","Plevna", NOW(), NOW()),
            (8, "Suharau","Smardan", NOW(), NOW()),
            (8, "Sulita","Chelis", NOW(), NOW()),
            (8, "Sulita","Dracsani", NOW(), NOW()),
            (8, "Todireni","Cernesti", NOW(), NOW()),
            (8, "Todireni","Floresti", NOW(), NOW()),
            (8, "Todireni","Garbesti", NOW(), NOW()),
            (8, "Todireni","Iuresti", NOW(), NOW()),
            (8, "Trusesti","Buhaceni", NOW(), NOW()),
            (8, "Trusesti","Ciritei", NOW(), NOW()),
            (8, "Trusesti","Drislea", NOW(), NOW()),
            (8, "Trusesti","Ionaseni", NOW(), NOW()),
            (8, "Trusesti","Pasateni", NOW(), NOW()),
            (8, "Ungureni","Borzesti", NOW(), NOW()),
            (8, "Ungureni","Calugareni", NOW(), NOW()),
            (8, "Ungureni","Calugarenii Noi", NOW(), NOW()),
            (8, "Ungureni","Durnesti", NOW(), NOW()),
            (8, "Ungureni","Mihai Viteazu", NOW(), NOW()),
            (8, "Ungureni","Mandresti", NOW(), NOW()),
            (8, "Ungureni","Plopenii Mari", NOW(), NOW()),
            (8, "Ungureni","Plopenii Mici", NOW(), NOW()),
            (8, "Ungureni","Tautesti", NOW(), NOW()),
            (8, "Ungureni","Vicoleni", NOW(), NOW()),
            (8, "Unteni","Burla", NOW(), NOW()),
            (8, "Unteni","Burlesti", NOW(), NOW()),
            (8, "Unteni","Manastireni", NOW(), NOW()),
            (8, "Unteni","Soroceni", NOW(), NOW()),
            (8, "Unteni","Valea Grajdului", NOW(), NOW()),
            (8, "Unteni","Vultureni", NOW(), NOW()),
            (8, "Vaculesti","Gorovei", NOW(), NOW()),
            (8, "Vaculesti","Saucenita", NOW(), NOW()),
            (8, "Varfu Campului","Ionaseni", NOW(), NOW()),
            (8, "Varfu Campului","Lunca", NOW(), NOW()),
            (8, "Viisoara","Cuza Voda", NOW(), NOW()),
            (8, "Viisoara","Viisoara Mica", NOW(), NOW()),
            (8, "Vladeni","Brehuiesti", NOW(), NOW()),
            (8, "Vladeni","Hriscani", NOW(), NOW()),
            (8, "Vladeni","Hutani", NOW(), NOW()),
            (8, "Vladeni","Mandresti", NOW(), NOW()),
            (8, "Vlasinesti","Miron Costin", NOW(), NOW()),
            (8, "Vlasinesti","Sarbi", NOW(), NOW()),
            (8, "Vorniceni","Davidoaia", NOW(), NOW()),
            (8, "Vorniceni","Dealu Crucii", NOW(), NOW()),
            (8, "Vorona","Icuseni", NOW(), NOW()),
            (8, "Vorona","Joldesti", NOW(), NOW()),
            (8, "Vorona","Poiana", NOW(), NOW()),
            (8, "Vorona","Vorona Mare", NOW(), NOW()),
            (8, "Vorona","Vorona-Teodoru", NOW(), NOW()),
            (8, "Vârfu Câmpului","Dobrinauti-Hapai", NOW(), NOW()),
            (8, "Vârfu Câmpului","Maghera", NOW(), NOW()),
            (8, "Vârfu Câmpului","Pustoaia", NOW(), NOW())
        ;';
        if (config('app.env') !== 'testing') {
            DB::connection()->getPdo()->exec($sql);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=8;';
        DB::connection()->getPdo()->exec($sql);
    }
}
