<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForGL extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
          (18, "","Barcea", NOW(), NOW()),
          (18, "","Beresti", NOW(), NOW()),
          (18, "","Beresti-Meria", NOW(), NOW()),
          (18, "","Branistea", NOW(), NOW()),
          (18, "","Brahasesti", NOW(), NOW()),
          (18, "","Buciumeni", NOW(), NOW()),
          (18, "","Baleni", NOW(), NOW()),
          (18, "","Balabanesti", NOW(), NOW()),
          (18, "","Balasesti", NOW(), NOW()),
          (18, "","Baneasa", NOW(), NOW()),
          (18, "","Cavadinesti", NOW(), NOW()),
          (18, "","Certesti", NOW(), NOW()),
          (18, "","Corni", NOW(), NOW()),
          (18, "","Corod", NOW(), NOW()),
          (18, "","Cosmesti", NOW(), NOW()),
          (18, "","Costache Negri", NOW(), NOW()),
          (18, "","Cuca", NOW(), NOW()),
          (18, "","Cudalbi", NOW(), NOW()),
          (18, "","Draguseni", NOW(), NOW()),
          (18, "","Draganesti", NOW(), NOW()),
          (18, "","Foltesti", NOW(), NOW()),
          (18, "","Frumusita", NOW(), NOW()),
          (18, "","Fundeni", NOW(), NOW()),
          (18, "","Fartanesti", NOW(), NOW()),
          (18, "","Galati", NOW(), NOW()),
          (18, "","Ghidigeni", NOW(), NOW()),
          (18, "","Gohor", NOW(), NOW()),
          (18, "","Grivita", NOW(), NOW()),
          (18, "","Independenta", NOW(), NOW()),
          (18, "","Ivesti", NOW(), NOW()),
          (18, "","Jorasti", NOW(), NOW()),
          (18, "","Liesti", NOW(), NOW()),
          (18, "","Matca", NOW(), NOW()),
          (18, "","Movileni", NOW(), NOW()),
          (18, "","Munteni", NOW(), NOW()),
          (18, "","Mastacani", NOW(), NOW()),
          (18, "","Nicoresti", NOW(), NOW()),
          (18, "","Namoloasa", NOW(), NOW()),
          (18, "","Oancea", NOW(), NOW()),
          (18, "","Pechea", NOW(), NOW()),
          (18, "","Piscu", NOW(), NOW()),
          (18, "","Priponesti", NOW(), NOW()),
          (18, "","Rediu", NOW(), NOW()),
          (18, "","Schela", NOW(), NOW()),
          (18, "","Scanteiesti", NOW(), NOW()),
          (18, "","Slobozia Conachi", NOW(), NOW()),
          (18, "","Smulti", NOW(), NOW()),
          (18, "","Smardan", NOW(), NOW()),
          (18, "","Suceveni", NOW(), NOW()),
          (18, "","Tecuci", NOW(), NOW()),
          (18, "","Tudor Vladimirescu", NOW(), NOW()),
          (18, "","Tulucesti", NOW(), NOW()),
          (18, "","Targu Bujor", NOW(), NOW()),
          (18, "","Umbraresti", NOW(), NOW()),
          (18, "","Valea Marului", NOW(), NOW()),
          (18, "","Vladesti", NOW(), NOW()),
          (18, "","Vanatori", NOW(), NOW()),
          (18, "","Varlezi", NOW(), NOW()),
          (18, "","Sendreni", NOW(), NOW()),
          (18, "","Tepu", NOW(), NOW()),
          (18, "Balabanesti","Bursucani", NOW(), NOW()),
          (18, "Balabanesti","Cruceanu", NOW(), NOW()),
          (18, "Balabanesti","Lungesti", NOW(), NOW()),
          (18, "Balabanesti","Radesti", NOW(), NOW()),
          (18, "Balabanesti","Zimbru", NOW(), NOW()),
          (18, "Balasesti","Ciuresti", NOW(), NOW()),
          (18, "Balasesti","Ciurestii Noi", NOW(), NOW()),
          (18, "Balasesti","Pupezeni", NOW(), NOW()),
          (18, "Baneasa","Roscani", NOW(), NOW()),
          (18, "Barcea","Podoleni", NOW(), NOW()),
          (18, "Beresti-Meria","Aldesti", NOW(), NOW()),
          (18, "Beresti-Meria","Balintesti", NOW(), NOW()),
          (18, "Beresti-Meria","Onciu", NOW(), NOW()),
          (18, "Beresti-Meria","Plesa", NOW(), NOW()),
          (18, "Beresti-Meria","Prodanesti", NOW(), NOW()),
          (18, "Beresti-Meria","Puricani", NOW(), NOW()),
          (18, "Beresti-Meria","Slivna", NOW(), NOW()),
          (18, "Beresti-Meria","Saseni", NOW(), NOW()),
          (18, "Beresti-Meria","Sipote", NOW(), NOW()),
          (18, "Brahasesti","Corcioveni", NOW(), NOW()),
          (18, "Brahasesti","Cositeni", NOW(), NOW()),
          (18, "Brahasesti","Toflea", NOW(), NOW()),
          (18, "Branistea","Lozova", NOW(), NOW()),
          (18, "Branistea","Traian", NOW(), NOW()),
          (18, "Branistea","Vasile Alecsandri", NOW(), NOW()),
          (18, "Buciumeni","Hantesti", NOW(), NOW()),
          (18, "Buciumeni","Tecucelu Sec", NOW(), NOW()),
          (18, "Buciumeni","Vizuresti", NOW(), NOW()),
          (18, "Cavadinesti","Comanesti", NOW(), NOW()),
          (18, "Cavadinesti","Ganesti", NOW(), NOW()),
          (18, "Cavadinesti","Vadeni", NOW(), NOW()),
          (18, "Certesti","Cotoroaia", NOW(), NOW()),
          (18, "Certesti","Carlomanesti", NOW(), NOW()),
          (18, "Corni","Maciseni", NOW(), NOW()),
          (18, "Corni","Urlesti", NOW(), NOW()),
          (18, "Corod","Blanzi", NOW(), NOW()),
          (18, "Corod","Bratulesti", NOW(), NOW()),
          (18, "Corod","Carapcesti", NOW(), NOW()),
          (18, "Cosmesti","Baltareti", NOW(), NOW()),
          (18, "Cosmesti","Cosmestii-Vale", NOW(), NOW()),
          (18, "Cosmesti","Furcenii Noi", NOW(), NOW()),
          (18, "Cosmesti","Furcenii Vechi", NOW(), NOW()),
          (18, "Cosmesti","Satu Nou", NOW(), NOW()),
          (18, "Draganesti","Malu Alb", NOW(), NOW()),
          (18, "Draguseni","Adam", NOW(), NOW()),
          (18, "Draguseni","Cauiesti", NOW(), NOW()),
          (18, "Draguseni","Fundeanu", NOW(), NOW()),
          (18, "Draguseni","Ghinghesti", NOW(), NOW()),
          (18, "Draguseni","Nicopole", NOW(), NOW()),
          (18, "Draguseni","Stietesti", NOW(), NOW()),
          (18, "Fartanesti","Viile", NOW(), NOW()),
          (18, "Foltesti","Stoicani", NOW(), NOW()),
          (18, "Frumusita","Ijdileni", NOW(), NOW()),
          (18, "Frumusita","Tamaoani", NOW(), NOW()),
          (18, "Fundeni","Fundenii Noi", NOW(), NOW()),
          (18, "Fundeni","Hanu Conachi", NOW(), NOW()),
          (18, "Fundeni","Lungoci", NOW(), NOW()),
          (18, "Ghidigeni","Gara Ghidigeni", NOW(), NOW()),
          (18, "Ghidigeni","Gefu", NOW(), NOW()),
          (18, "Ghidigeni","Gura Garbovatului", NOW(), NOW()),
          (18, "Ghidigeni","Garbovat", NOW(), NOW()),
          (18, "Ghidigeni","Slobozia Corni", NOW(), NOW()),
          (18, "Ghidigeni","Talpigi", NOW(), NOW()),
          (18, "Ghidigeni","Taplau", NOW(), NOW()),
          (18, "Gohor","Gara Berheci", NOW(), NOW()),
          (18, "Gohor","Ireasca", NOW(), NOW()),
          (18, "Gohor","Nartesti", NOW(), NOW()),
          (18, "Gohor","Posta", NOW(), NOW()),
          (18, "Grivita","Calmatui", NOW(), NOW()),
          (18, "Ivesti","Bucesti", NOW(), NOW()),
          (18, "Jorasti","Lunca", NOW(), NOW()),
          (18, "Jorasti","Zarnesti", NOW(), NOW()),
          (18, "Mastacani","Chiraftei", NOW(), NOW()),
          (18, "Munteni","Frunzeasca", NOW(), NOW()),
          (18, "Munteni","Negrilesti", NOW(), NOW()),
          (18, "Munteni","Slobozia Blaneasa", NOW(), NOW()),
          (18, "Munteni","Ungureni", NOW(), NOW()),
          (18, "Munteni","Tiganesti", NOW(), NOW()),
          (18, "Namoloasa","Crangeni", NOW(), NOW()),
          (18, "Namoloasa","Namoloasa Sat", NOW(), NOW()),
          (18, "Nicoresti","Branistea", NOW(), NOW()),
          (18, "Nicoresti","Coasta Lupei", NOW(), NOW()),
          (18, "Nicoresti","Dobrinesti", NOW(), NOW()),
          (18, "Nicoresti","Fantani", NOW(), NOW()),
          (18, "Nicoresti","Grozavesti", NOW(), NOW()),
          (18, "Nicoresti","Ionasesti", NOW(), NOW()),
          (18, "Nicoresti","Malureni", NOW(), NOW()),
          (18, "Nicoresti","Piscu Corbului", NOW(), NOW()),
          (18, "Nicoresti","Poiana", NOW(), NOW()),
          (18, "Nicoresti","Sarbi", NOW(), NOW()),
          (18, "Nicoresti","Visina", NOW(), NOW()),
          (18, "Oancea","Slobozia Oancea", NOW(), NOW()),
          (18, "Pechea","Lupele", NOW(), NOW()),
          (18, "Piscu","Vames", NOW(), NOW()),
          (18, "Priponesti","Ciorasti", NOW(), NOW()),
          (18, "Priponesti","Hustiu", NOW(), NOW()),
          (18, "Priponesti","Liesti", NOW(), NOW()),
          (18, "Priponesti","Priponestii de Jos", NOW(), NOW()),
          (18, "Rediu","Plevna", NOW(), NOW()),
          (18, "Rediu","Suhurlui", NOW(), NOW()),
          (18, "Scanteiesti","Fantanele", NOW(), NOW()),
          (18, "Schela","Negrea", NOW(), NOW()),
          (18, "Sendreni","Movileni", NOW(), NOW()),
          (18, "Sendreni","Serbestii Vechi", NOW(), NOW()),
          (18, "Slobozia Conachi","Cuza Voda", NOW(), NOW()),
          (18, "Slobozia Conachi","Izvoarele", NOW(), NOW()),
          (18, "Smardan","Cismele", NOW(), NOW()),
          (18, "Smardan","Mihail Kogalniceanu", NOW(), NOW()),
          (18, "Suceveni","Rogojeni", NOW(), NOW()),
          (18, "Targu Bujor","Moscu", NOW(), NOW()),
          (18, "Targu Bujor","Umbraresti", NOW(), NOW()),
          (18, "Tepu","Tepu de Sus", NOW(), NOW()),
          (18, "Tulucesti","Tatarca", NOW(), NOW()),
          (18, "Tulucesti","Sivita", NOW(), NOW()),
          (18, "Umbraresti","Condrea", NOW(), NOW()),
          (18, "Umbraresti","Salcia", NOW(), NOW()),
          (18, "Umbraresti","Silistea", NOW(), NOW()),
          (18, "Umbraresti","Torcesti", NOW(), NOW()),
          (18, "Umbraresti","Umbraresti-Deal", NOW(), NOW()),
          (18, "Valea Marului","Mandresti", NOW(), NOW()),
          (18, "Vanatori","Costi", NOW(), NOW()),
          (18, "Vanatori","Odaia Manolache", NOW(), NOW()),
          (18, "Varlezi","Craiesti", NOW(), NOW()),
          (18, "Vladesti","Branesti", NOW(), NOW())
        ;';
        DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {

        $sql = "DELETE FROM localities WHERE county_id=18;";
        DB::connection()->getPdo()->exec($sql);
    }
}