<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForTL extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
          (39, "","Babadag", NOW(), NOW()),
          (39, "","Baia", NOW(), NOW()),
          (39, "","Beidaud", NOW(), NOW()),
          (39, "","C.a. Rosetti", NOW(), NOW()),
          (39, "","Carcaliu", NOW(), NOW()),
          (39, "","Casimcea", NOW(), NOW()),
          (39, "","Ceamurlia de Jos", NOW(), NOW()),
          (39, "","Ceatalchioi", NOW(), NOW()),
          (39, "","Cerna", NOW(), NOW()),
          (39, "","Chilia Veche", NOW(), NOW()),
          (39, "","Ciucurova", NOW(), NOW()),
          (39, "","Crisan", NOW(), NOW()),
          (39, "","Dorobantu", NOW(), NOW()),
          (39, "","Daeni", NOW(), NOW()),
          (39, "","Frecatei", NOW(), NOW()),
          (39, "","Greci", NOW(), NOW()),
          (39, "","Grindu", NOW(), NOW()),
          (39, "","Hamcearca", NOW(), NOW()),
          (39, "","Horia", NOW(), NOW()),
          (39, "","I.c.bratianu", NOW(), NOW()),
          (39, "","Isaccea", NOW(), NOW()),
          (39, "","Izvoarele", NOW(), NOW()),
          (39, "","Jijila", NOW(), NOW()),
          (39, "","Jurilovca", NOW(), NOW()),
          (39, "","Luncavita", NOW(), NOW()),
          (39, "","Mahmudia", NOW(), NOW()),
          (39, "","Maliuc", NOW(), NOW()),
          (39, "","Mihai Bravu", NOW(), NOW()),
          (39, "","Mihail Kogalniceanu", NOW(), NOW()),
          (39, "","Murighiol", NOW(), NOW()),
          (39, "","Macin", NOW(), NOW()),
          (39, "","Nalbant", NOW(), NOW()),
          (39, "","Niculitel", NOW(), NOW()),
          (39, "","Nufaru", NOW(), NOW()),
          (39, "","Ostrov", NOW(), NOW()),
          (39, "","Pardina", NOW(), NOW()),
          (39, "","Peceneaga", NOW(), NOW()),
          (39, "","Sarichioi", NOW(), NOW()),
          (39, "","Sfantu Gheorghe", NOW(), NOW()),
          (39, "","Slava Cercheza", NOW(), NOW()),
          (39, "","Smardan", NOW(), NOW()),
          (39, "","Somova", NOW(), NOW()),
          (39, "","Stejaru", NOW(), NOW()),
          (39, "","Sulina", NOW(), NOW()),
          (39, "","Topolog", NOW(), NOW()),
          (39, "","Tulcea", NOW(), NOW()),
          (39, "","Turcoaia", NOW(), NOW()),
          (39, "","Valea Nucarilor", NOW(), NOW()),
          (39, "","Vacareni", NOW(), NOW()),
          (39, "Baia","Camena", NOW(), NOW()),
          (39, "Baia","Caugagia", NOW(), NOW()),
          (39, "Baia","Ceamurlia de Sus", NOW(), NOW()),
          (39, "Baia","Panduru", NOW(), NOW()),
          (39, "Beidaud","Neatarnarea", NOW(), NOW()),
          (39, "Beidaud","Sarighiol de Deal", NOW(), NOW()),
          (39, "C.A. Rosetti","Cardon", NOW(), NOW()),
          (39, "C.A. Rosetti","Letea", NOW(), NOW()),
          (39, "C.A. Rosetti","Periprava", NOW(), NOW()),
          (39, "C.A. Rosetti","Sfistofca", NOW(), NOW()),
          (39, "Casimcea","Cismeaua Noua", NOW(), NOW()),
          (39, "Casimcea","Corugea", NOW(), NOW()),
          (39, "Casimcea","Haidar", NOW(), NOW()),
          (39, "Casimcea","Rahman", NOW(), NOW()),
          (39, "Casimcea","Razboieni", NOW(), NOW()),
          (39, "Casimcea","Stanca", NOW(), NOW()),
          (39, "Ceamurlia De Jos","Lunca", NOW(), NOW()),
          (39, "Ceatalchioi","Plauru", NOW(), NOW()),
          (39, "Ceatalchioi","Patlageanca", NOW(), NOW()),
          (39, "Ceatalchioi","Salceni", NOW(), NOW()),
          (39, "Cerna","General Praporgescu", NOW(), NOW()),
          (39, "Cerna","Mircea Voda", NOW(), NOW()),
          (39, "Cerna","Traian", NOW(), NOW()),
          (39, "Chilia Veche","Caslita", NOW(), NOW()),
          (39, "Chilia Veche","Ostrovu Tataru", NOW(), NOW()),
          (39, "Chilia Veche","Tatanir", NOW(), NOW()),
          (39, "Ciucurova","Atmagea", NOW(), NOW()),
          (39, "Ciucurova","Fantana Mare", NOW(), NOW()),
          (39, "Crisan","Caraorman", NOW(), NOW()),
          (39, "Crisan","Mila 23", NOW(), NOW()),
          (39, "Dorobantu","Ardealu", NOW(), NOW()),
          (39, "Dorobantu","Carjelari", NOW(), NOW()),
          (39, "Dorobantu","Fantana Oilor", NOW(), NOW()),
          (39, "Dorobantu","Mesteru", NOW(), NOW()),
          (39, "Frecatei","Cataloi", NOW(), NOW()),
          (39, "Frecatei","Posta", NOW(), NOW()),
          (39, "Frecatei","Telita", NOW(), NOW()),
          (39, "Hamcearca","Balabancea", NOW(), NOW()),
          (39, "Hamcearca","Caprioara", NOW(), NOW()),
          (39, "Hamcearca","Nifon", NOW(), NOW()),
          (39, "Horia","Closca", NOW(), NOW()),
          (39, "Horia","Floresti", NOW(), NOW()),
          (39, "Isaccea","Revarsarea", NOW(), NOW()),
          (39, "Isaccea","Tichilesti", NOW(), NOW()),
          (39, "Izvoarele","Alba", NOW(), NOW()),
          (39, "Izvoarele","Iulia", NOW(), NOW()),
          (39, "Izvoarele","Valea Teilor", NOW(), NOW()),
          (39, "Jijila","Garvan", NOW(), NOW()),
          (39, "Jurilovca","Salcioara", NOW(), NOW()),
          (39, "Jurilovca","Visina", NOW(), NOW()),
          (39, "Luncavita","Rachelu", NOW(), NOW()),
          (39, "Mahmudia","Bestepe", NOW(), NOW()),
          (39, "Mahmudia","Baltenii de Jos", NOW(), NOW()),
          (39, "Mahmudia","Baltenii de Sus", NOW(), NOW()),
          (39, "Maliuc","Gorgova", NOW(), NOW()),
          (39, "Maliuc","Ilganii de Sus", NOW(), NOW()),
          (39, "Maliuc","Partizani", NOW(), NOW()),
          (39, "Maliuc","Vulturu", NOW(), NOW()),
          (39, "Mihai Bravu","Satu Nou", NOW(), NOW()),
          (39, "Mihai Bravu","Turda", NOW(), NOW()),
          (39, "Mihail Kogalniceanu","Lastuni", NOW(), NOW()),
          (39, "Mihail Kogalniceanu","Randunica", NOW(), NOW()),
          (39, "Murighiol","Colina", NOW(), NOW()),
          (39, "Murighiol","Dunavatu de Jos", NOW(), NOW()),
          (39, "Murighiol","Dunavatu de Sus", NOW(), NOW()),
          (39, "Murighiol","Plopul", NOW(), NOW()),
          (39, "Murighiol","Sarinasuf", NOW(), NOW()),
          (39, "Murighiol","Uzlina", NOW(), NOW()),
          (39, "Nalbant","Nicolae Balcescu", NOW(), NOW()),
          (39, "Nalbant","Trestenic", NOW(), NOW()),
          (39, "Nufaru","Ilganii de Jos", NOW(), NOW()),
          (39, "Nufaru","Malcoci", NOW(), NOW()),
          (39, "Nufaru","Victoria", NOW(), NOW()),
          (39, "Ostrov","Piatra", NOW(), NOW()),
          (39, "Sarichioi","Enisala", NOW(), NOW()),
          (39, "Sarichioi","Sabangia", NOW(), NOW()),
          (39, "Sarichioi","Visterna", NOW(), NOW()),
          (39, "Sarichioi","Zebil", NOW(), NOW()),
          (39, "Slava Cercheza","Slava Rusa", NOW(), NOW()),
          (39, "Somova","Mineri", NOW(), NOW()),
          (39, "Somova","Parches", NOW(), NOW()),
          (39, "Stejaru","Mina Altan Tepe", NOW(), NOW()),
          (39, "Stejaru","Vasile Alecsandri", NOW(), NOW()),
          (39, "Topolog","Calfa", NOW(), NOW()),
          (39, "Topolog","Cerbu", NOW(), NOW()),
          (39, "Topolog","Fagarasu Nou", NOW(), NOW()),
          (39, "Topolog","Luminita", NOW(), NOW()),
          (39, "Topolog","Magurele", NOW(), NOW()),
          (39, "Topolog","Sambata Noua", NOW(), NOW()),
          (39, "Tulcea","Tudor Vladimirescu", NOW(), NOW()),
          (39, "Valea Nucarilor","Agighiol", NOW(), NOW()),
          (39, "Valea Nucarilor","Iazurile", NOW(), NOW())
        ;';
        if (config('app.env') !== 'testing') {
            DB::connection()->getPdo()->exec($sql);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=39;';
        DB::connection()->getPdo()->exec($sql);
    }
}
