<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForBZ extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql='INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (11, "","Amaru", NOW(), NOW()),
            (11, "","Balta Alba", NOW(), NOW()),
            (11, "","Beceni", NOW(), NOW()),
            (11, "","Berca", NOW(), NOW()),
            (11, "","Bisoca", NOW(), NOW()),
            (11, "","Blajani", NOW(), NOW()),
            (11, "","Boldu", NOW(), NOW()),
            (11, "","Bozioru", NOW(), NOW()),
            (11, "","Breaza", NOW(), NOW()),
            (11, "","Bradeanu", NOW(), NOW()),
            (11, "","Braesti", NOW(), NOW()),
            (11, "","Buda", NOW(), NOW()),
            (11, "","Buzau", NOW(), NOW()),
            (11, "","Balaceanu", NOW(), NOW()),
            (11, "","C.a. Rosetti", NOW(), NOW()),
            (11, "","Calvini", NOW(), NOW()),
            (11, "","Cernatesti", NOW(), NOW()),
            (11, "","Chiliile", NOW(), NOW()),
            (11, "","Chiojdu", NOW(), NOW()),
            (11, "","Cilibia", NOW(), NOW()),
            (11, "","Cislau", NOW(), NOW()),
            (11, "","Cochirleanca", NOW(), NOW()),
            (11, "","Colti", NOW(), NOW()),
            (11, "","Costesti", NOW(), NOW()),
            (11, "","Cozieni", NOW(), NOW()),
            (11, "","Canesti", NOW(), NOW()),
            (11, "","Catina", NOW(), NOW()),
            (11, "","Ghergheasa", NOW(), NOW()),
            (11, "","Gheraseni", NOW(), NOW()),
            (11, "","Glodeanu Sarat", NOW(), NOW()),
            (11, "","Glodeanu-Silistea", NOW(), NOW()),
            (11, "","Grebanu", NOW(), NOW()),
            (11, "","Gura Teghii", NOW(), NOW()),
            (11, "","Galbinasi", NOW(), NOW()),
            (11, "","Largu", NOW(), NOW()),
            (11, "","Lopatari", NOW(), NOW()),
            (11, "","Luciu", NOW(), NOW()),
            (11, "","Merei", NOW(), NOW()),
            (11, "","Mihailesti", NOW(), NOW()),
            (11, "","Movila Banului", NOW(), NOW()),
            (11, "","Murgesti", NOW(), NOW()),
            (11, "","Manzalesti", NOW(), NOW()),
            (11, "","Magura", NOW(), NOW()),
            (11, "","Margaritesti", NOW(), NOW()),
            (11, "","Maracineni", NOW(), NOW()),
            (11, "","Nehoiu", NOW(), NOW()),
            (11, "","Naeni", NOW(), NOW()),
            (11, "","Odaile", NOW(), NOW()),
            (11, "","Padina", NOW(), NOW()),
            (11, "","Pardosi", NOW(), NOW()),
            (11, "","Pietroasele", NOW(), NOW()),
            (11, "","Podgoria", NOW(), NOW()),
            (11, "","Pogoanele", NOW(), NOW()),
            (11, "","Posta Calnau", NOW(), NOW()),
            (11, "","Parscov", NOW(), NOW()),
            (11, "","Panatau", NOW(), NOW()),
            (11, "","Patarlagele", NOW(), NOW()),
            (11, "","Racoviteni", NOW(), NOW()),
            (11, "","Robeasca", NOW(), NOW()),
            (11, "","Rusetu", NOW(), NOW()),
            (11, "","Ramnicelu", NOW(), NOW()),
            (11, "","Ramnicu Sarat", NOW(), NOW()),
            (11, "","Scortoasa", NOW(), NOW()),
            (11, "","Scutelnici", NOW(), NOW()),
            (11, "","Smeeni", NOW(), NOW()),
            (11, "","Stalpu", NOW(), NOW()),
            (11, "","Sageata", NOW(), NOW()),
            (11, "","Sahateni", NOW(), NOW()),
            (11, "","Sapoca", NOW(), NOW()),
            (11, "","Sarulesti", NOW(), NOW()),
            (11, "","Tisau", NOW(), NOW()),
            (11, "","Topliceni", NOW(), NOW()),
            (11, "","Ulmeni", NOW(), NOW()),
            (11, "","Vadu Pasii", NOW(), NOW()),
            (11, "","Valea Ramnicului", NOW(), NOW()),
            (11, "","Valea Salciei", NOW(), NOW()),
            (11, "","Vernesti", NOW(), NOW()),
            (11, "","Vintila Voda", NOW(), NOW()),
            (11, "","Viperesti", NOW(), NOW()),
            (11, "","Valcelele", NOW(), NOW()),
            (11, "","Ziduri", NOW(), NOW()),
            (11, "","Zarnesti", NOW(), NOW()),
            (11, "","Tintesti", NOW(), NOW()),
            (11, "Amaru","Campeni", NOW(), NOW()),
            (11, "Amaru","Dulbanu", NOW(), NOW()),
            (11, "Amaru","Lacu Sinaia", NOW(), NOW()),
            (11, "Amaru","Lunca", NOW(), NOW()),
            (11, "Amaru","Scorteanca", NOW(), NOW()),
            (11, "Balta Alba","Amara", NOW(), NOW()),
            (11, "Balta Alba","Baile", NOW(), NOW()),
            (11, "Balta Alba","Stavarasti", NOW(), NOW()),
            (11, "Beceni","Arbanasi", NOW(), NOW()),
            (11, "Beceni","Carpinistea", NOW(), NOW()),
            (11, "Beceni","Dogari", NOW(), NOW()),
            (11, "Beceni","Floresti", NOW(), NOW()),
            (11, "Beceni","Gura Dimienii", NOW(), NOW()),
            (11, "Beceni","Izvoru Dulce", NOW(), NOW()),
            (11, "Beceni","Margariti", NOW(), NOW()),
            (11, "Beceni","Valea Parului", NOW(), NOW()),
            (11, "Berca","Baceni", NOW(), NOW()),
            (11, "Berca","Cojanu", NOW(), NOW()),
            (11, "Berca","Joseni", NOW(), NOW()),
            (11, "Berca","Manastirea Ratesti", NOW(), NOW()),
            (11, "Berca","Plescoi", NOW(), NOW()),
            (11, "Berca","Plesesti", NOW(), NOW()),
            (11, "Berca","Paclele", NOW(), NOW()),
            (11, "Berca","Ratesti", NOW(), NOW()),
            (11, "Berca","Satuc", NOW(), NOW()),
            (11, "Berca","Tatarligu", NOW(), NOW()),
            (11, "Berca","Valea Nucului", NOW(), NOW()),
            (11, "Berca","Viforata", NOW(), NOW()),
            (11, "Bisoca","Baltagari", NOW(), NOW()),
            (11, "Bisoca","Lacurile", NOW(), NOW()),
            (11, "Bisoca","Lopatareasa", NOW(), NOW()),
            (11, "Bisoca","Plesi", NOW(), NOW()),
            (11, "Bisoca","Recea", NOW(), NOW()),
            (11, "Bisoca","Sarile", NOW(), NOW()),
            (11, "Bisoca","Sindrila", NOW(), NOW()),
            (11, "Blajani","Soresti", NOW(), NOW()),
            (11, "Bozioru","Buduile", NOW(), NOW()),
            (11, "Bozioru","Fisici", NOW(), NOW()),
            (11, "Bozioru","Gresia", NOW(), NOW()),
            (11, "Bozioru","Gavanele", NOW(), NOW()),
            (11, "Bozioru","Izvoarele", NOW(), NOW()),
            (11, "Bozioru","Nucu", NOW(), NOW()),
            (11, "Bozioru","Scaeni", NOW(), NOW()),
            (11, "Bozioru","Ulmet", NOW(), NOW()),
            (11, "Bozioru","Vavalucile", NOW(), NOW()),
            (11, "Bradeanu","Mitropolia", NOW(), NOW()),
            (11, "Bradeanu","Smardan", NOW(), NOW()),
            (11, "Braesti","Bratilesti", NOW(), NOW()),
            (11, "Braesti","Goidesti", NOW(), NOW()),
            (11, "Braesti","Ivanetu", NOW(), NOW()),
            (11, "Braesti","Pinu", NOW(), NOW()),
            (11, "Braesti","Parscovelu", NOW(), NOW()),
            (11, "Braesti","Ruginoasa", NOW(), NOW()),
            (11, "Breaza","Badeni", NOW(), NOW()),
            (11, "Breaza","Greceanca", NOW(), NOW()),
            (11, "Breaza","Vispesti", NOW(), NOW()),
            (11, "Breaza","Valeanca-Vilanesti", NOW(), NOW()),
            (11, "Buda","Alexandru Odobescu", NOW(), NOW()),
            (11, "Buda","Danulesti", NOW(), NOW()),
            (11, "Buda","Mucesti-Danulesti", NOW(), NOW()),
            (11, "Buda","Spidele", NOW(), NOW()),
            (11, "Buda","Toropalesti", NOW(), NOW()),
            (11, "Buda","Valea Larga", NOW(), NOW()),
            (11, "C.A. Rosetti","Balhacu", NOW(), NOW()),
            (11, "C.A. Rosetti","Balteni", NOW(), NOW()),
            (11, "C.A. Rosetti","Cotu Ciorii", NOW(), NOW()),
            (11, "C.A. Rosetti","Lunca", NOW(), NOW()),
            (11, "C.A. Rosetti","Vizireni", NOW(), NOW()),
            (11, "Calvini","Bascenii de Jos", NOW(), NOW()),
            (11, "Calvini","Bascenii de Sus", NOW(), NOW()),
            (11, "Calvini","Frasinet", NOW(), NOW()),
            (11, "Calvini","Olari", NOW(), NOW()),
            (11, "Canesti","Gontesti", NOW(), NOW()),
            (11, "Canesti","Negosina", NOW(), NOW()),
            (11, "Canesti","Pacurile", NOW(), NOW()),
            (11, "Canesti","Valea Verzei", NOW(), NOW()),
            (11, "Canesti","Suchea", NOW(), NOW()),
            (11, "Catina","Corbu", NOW(), NOW()),
            (11, "Catina","Slobozia", NOW(), NOW()),
            (11, "Catina","Valea Catinei", NOW(), NOW()),
            (11, "Catina","Zeletin", NOW(), NOW()),
            (11, "Cernatesti","Aldeni", NOW(), NOW()),
            (11, "Cernatesti","Baesti", NOW(), NOW()),
            (11, "Cernatesti","Caldarusa", NOW(), NOW()),
            (11, "Cernatesti","Fulga", NOW(), NOW()),
            (11, "Cernatesti","Manasia", NOW(), NOW()),
            (11, "Cernatesti","Vladeni", NOW(), NOW()),
            (11, "Cernatesti","Zarnestii de Slanic", NOW(), NOW()),
            (11, "Chiliile","Budesti", NOW(), NOW()),
            (11, "Chiliile","Crevelesti", NOW(), NOW()),
            (11, "Chiliile","Ghiocari", NOW(), NOW()),
            (11, "Chiliile","Glodu-Petcari", NOW(), NOW()),
            (11, "Chiliile","Poiana Pletari", NOW(), NOW()),
            (11, "Chiliile","Trestioara", NOW(), NOW()),
            (11, "Chiojdu","Basca Chiojdului", NOW(), NOW()),
            (11, "Chiojdu","Catiasu", NOW(), NOW()),
            (11, "Chiojdu","Lera", NOW(), NOW()),
            (11, "Chiojdu","Plescioara", NOW(), NOW()),
            (11, "Chiojdu","Poenitele", NOW(), NOW()),
            (11, "Cilibia","Gara Cilibia", NOW(), NOW()),
            (11, "Cilibia","Movila Oii", NOW(), NOW()),
            (11, "Cilibia","Manzu", NOW(), NOW()),
            (11, "Cilibia","Posta", NOW(), NOW()),
            (11, "Cislau","Buda Craciunesti", NOW(), NOW()),
            (11, "Cislau","Barasti", NOW(), NOW()),
            (11, "Cislau","Gura Bascei", NOW(), NOW()),
            (11, "Cislau","Scarisoara", NOW(), NOW()),
            (11, "Cochirleanca","Boboc", NOW(), NOW()),
            (11, "Cochirleanca","Gara Bobocu", NOW(), NOW()),
            (11, "Cochirleanca","Rosioru", NOW(), NOW()),
            (11, "Cochirleanca","Tarlele", NOW(), NOW()),
            (11, "Colti","Alunis", NOW(), NOW()),
            (11, "Colti","Coltii de Jos", NOW(), NOW()),
            (11, "Colti","Muscelu Caramanesti", NOW(), NOW()),
            (11, "Costesti","Budisteni", NOW(), NOW()),
            (11, "Costesti","Gomoesti", NOW(), NOW()),
            (11, "Costesti","Grosani", NOW(), NOW()),
            (11, "Costesti","Pietrosu", NOW(), NOW()),
            (11, "Costesti","Spataru", NOW(), NOW()),
            (11, "Cozieni","Anini", NOW(), NOW()),
            (11, "Cozieni","Bercesti", NOW(), NOW()),
            (11, "Cozieni","Balanesti", NOW(), NOW()),
            (11, "Cozieni","Ciocanesti", NOW(), NOW()),
            (11, "Cozieni","Cocarceni", NOW(), NOW()),
            (11, "Cozieni","Colteni", NOW(), NOW()),
            (11, "Cozieni","Fata lui Nan", NOW(), NOW()),
            (11, "Cozieni","Glodurile", NOW(), NOW()),
            (11, "Cozieni","Izvoru", NOW(), NOW()),
            (11, "Cozieni","Lungesti", NOW(), NOW()),
            (11, "Cozieni","Nistoresti", NOW(), NOW()),
            (11, "Cozieni","Pietraru", NOW(), NOW()),
            (11, "Cozieni","Punga", NOW(), NOW()),
            (11, "Cozieni","Teisu", NOW(), NOW()),
            (11, "Cozieni","Trestia", NOW(), NOW()),
            (11, "Cozieni","Tulburea", NOW(), NOW()),
            (11, "Cozieni","Valea Banului", NOW(), NOW()),
            (11, "Cozieni","Valea Roatei", NOW(), NOW()),
            (11, "Cozieni","Zapodia", NOW(), NOW()),
            (11, "Galbinasi","Bentu", NOW(), NOW()),
            (11, "Galbinasi","Tabarasti", NOW(), NOW()),
            (11, "Gheraseni","Suditi", NOW(), NOW()),
            (11, "Ghergheasa","Salcioara", NOW(), NOW()),
            (11, "Glodeanu Sarat","Caldaruseanca", NOW(), NOW()),
            (11, "Glodeanu Sarat","Ileana", NOW(), NOW()),
            (11, "Glodeanu Sarat","Pitulicea", NOW(), NOW()),
            (11, "Glodeanu-Silistea","Casota", NOW(), NOW()),
            (11, "Glodeanu-Silistea","Corbu", NOW(), NOW()),
            (11, "Glodeanu-Silistea","Cotorca", NOW(), NOW()),
            (11, "Glodeanu-Silistea","Carligu Mare", NOW(), NOW()),
            (11, "Glodeanu-Silistea","Carligu Mic", NOW(), NOW()),
            (11, "Glodeanu-Silistea","Satu Nou", NOW(), NOW()),
            (11, "Glodeanu-Silistea","Vacareasca", NOW(), NOW()),
            (11, "Grebanu","Homesti", NOW(), NOW()),
            (11, "Grebanu","Livada", NOW(), NOW()),
            (11, "Grebanu","Livada Mica", NOW(), NOW()),
            (11, "Grebanu","Plevna", NOW(), NOW()),
            (11, "Grebanu","Zaplazi", NOW(), NOW()),
            (11, "Gura Teghii","Furtunesti", NOW(), NOW()),
            (11, "Gura Teghii","Nemertea", NOW(), NOW()),
            (11, "Gura Teghii","Paltinis", NOW(), NOW()),
            (11, "Gura Teghii","Secuiu", NOW(), NOW()),
            (11, "Gura Teghii","Vadu Oii", NOW(), NOW()),
            (11, "Gura Teghii","Varlaam", NOW(), NOW()),
            (11, "Largu","Scarlatesti", NOW(), NOW()),
            (11, "Lopatari","Brebu", NOW(), NOW()),
            (11, "Lopatari","Fundata", NOW(), NOW()),
            (11, "Lopatari","Luncile", NOW(), NOW()),
            (11, "Lopatari","Pestritu", NOW(), NOW()),
            (11, "Lopatari","Plaiu Nucului", NOW(), NOW()),
            (11, "Lopatari","Plostina", NOW(), NOW()),
            (11, "Lopatari","Potecu", NOW(), NOW()),
            (11, "Lopatari","Sareni", NOW(), NOW()),
            (11, "Lopatari","Terca", NOW(), NOW()),
            (11, "Lopatari","Varteju", NOW(), NOW()),
            (11, "Luciu","Caragele", NOW(), NOW()),
            (11, "Magura","Ciuta", NOW(), NOW()),
            (11, "Magura","Unguriu", NOW(), NOW()),
            (11, "Manzalesti","Beslii", NOW(), NOW()),
            (11, "Manzalesti","Bustea", NOW(), NOW()),
            (11, "Manzalesti","Ciresu", NOW(), NOW()),
            (11, "Manzalesti","Ghizdita", NOW(), NOW()),
            (11, "Manzalesti","Gura Badicului", NOW(), NOW()),
            (11, "Manzalesti","Jghiab", NOW(), NOW()),
            (11, "Manzalesti","Plavatu", NOW(), NOW()),
            (11, "Manzalesti","Poiana Valcului", NOW(), NOW()),
            (11, "Manzalesti","Satu Vechi", NOW(), NOW()),
            (11, "Manzalesti","Trestioara", NOW(), NOW()),
            (11, "Manzalesti","Valea Cotoarei", NOW(), NOW()),
            (11, "Manzalesti","Valea Ursului", NOW(), NOW()),
            (11, "Maracineni","Capatanesti", NOW(), NOW()),
            (11, "Maracineni","Potoceni", NOW(), NOW()),
            (11, "Margaritesti","Campulungeanca", NOW(), NOW()),
            (11, "Margaritesti","Fantanele", NOW(), NOW()),
            (11, "Merei","Ciobanoaia", NOW(), NOW()),
            (11, "Merei","Dealul Viei", NOW(), NOW()),
            (11, "Merei","Dobrilesti", NOW(), NOW()),
            (11, "Merei","Gura Saratii", NOW(), NOW()),
            (11, "Merei","Izvoru Dulce", NOW(), NOW()),
            (11, "Merei","Lipia", NOW(), NOW()),
            (11, "Merei","Nenciulesti", NOW(), NOW()),
            (11, "Merei","Ograzile", NOW(), NOW()),
            (11, "Merei","Sarata-Monteoru", NOW(), NOW()),
            (11, "Merei","Valea Putului Merei", NOW(), NOW()),
            (11, "Mihailesti","Coltaneni", NOW(), NOW()),
            (11, "Mihailesti","Florica", NOW(), NOW()),
            (11, "Mihailesti","Margineanu", NOW(), NOW()),
            (11, "Mihailesti","Satu Nou", NOW(), NOW()),
            (11, "Movila Banului","Cioranca", NOW(), NOW()),
            (11, "Movila Banului","Limpezis", NOW(), NOW()),
            (11, "Murgesti","Batogu", NOW(), NOW()),
            (11, "Murgesti","Valea Ratei", NOW(), NOW()),
            (11, "Naeni","Fintesti", NOW(), NOW()),
            (11, "Naeni","Fantanele", NOW(), NOW()),
            (11, "Naeni","Prosca", NOW(), NOW()),
            (11, "Naeni","Varf", NOW(), NOW()),
            (11, "Nehoiu","Basca Rozilei", NOW(), NOW()),
            (11, "Nehoiu","Chirlesti", NOW(), NOW()),
            (11, "Nehoiu","Curmatura", NOW(), NOW()),
            (11, "Nehoiu","Lunca Priporului", NOW(), NOW()),
            (11, "Nehoiu","Mlajet", NOW(), NOW()),
            (11, "Nehoiu","Nehoiasu", NOW(), NOW()),
            (11, "Nehoiu","Paltineni", NOW(), NOW()),
            (11, "Nehoiu","Stanila", NOW(), NOW()),
            (11, "Nehoiu","Vinetisu", NOW(), NOW()),
            (11, "Odaile","Capu Satului", NOW(), NOW()),
            (11, "Odaile","Corneanu", NOW(), NOW()),
            (11, "Odaile","Gorani", NOW(), NOW()),
            (11, "Odaile","Lacu", NOW(), NOW()),
            (11, "Odaile","Piatra Alba", NOW(), NOW()),
            (11, "Odaile","Posobesti", NOW(), NOW()),
            (11, "Odaile","Scorosesti", NOW(), NOW()),
            (11, "Odaile","Valea Fantanei", NOW(), NOW()),
            (11, "Odaile","Valea Stefanului", NOW(), NOW()),
            (11, "Padina","Tatulesti", NOW(), NOW()),
            (11, "Panatau","Begu", NOW(), NOW()),
            (11, "Panatau","Lacu cu Anini", NOW(), NOW()),
            (11, "Panatau","Maguricea", NOW(), NOW()),
            (11, "Panatau","Plaisor", NOW(), NOW()),
            (11, "Panatau","Rapile", NOW(), NOW()),
            (11, "Panatau","Sibiciu de Jos", NOW(), NOW()),
            (11, "Panatau","Tega", NOW(), NOW()),
            (11, "Panatau","Zaharesti", NOW(), NOW()),
            (11, "Pardosi","Chiperu", NOW(), NOW()),
            (11, "Pardosi","Costomiru", NOW(), NOW()),
            (11, "Pardosi","Valea lui Lalu", NOW(), NOW()),
            (11, "Pardosi","Valea Schiopului", NOW(), NOW()),
            (11, "Parscov","Badila", NOW(), NOW()),
            (11, "Parscov","Curcanesti", NOW(), NOW()),
            (11, "Parscov","Lunca Frumoasa", NOW(), NOW()),
            (11, "Parscov","Olesesti", NOW(), NOW()),
            (11, "Parscov","Parjolesti", NOW(), NOW()),
            (11, "Parscov","Robesti", NOW(), NOW()),
            (11, "Parscov","Runcu", NOW(), NOW()),
            (11, "Parscov","Tocileni", NOW(), NOW()),
            (11, "Parscov","Trestieni", NOW(), NOW()),
            (11, "Parscov","Tarcov", NOW(), NOW()),
            (11, "Parscov","Valea Purcarului", NOW(), NOW()),
            (11, "Patarlagele","Calea Chiojdului", NOW(), NOW()),
            (11, "Patarlagele","Crang", NOW(), NOW()),
            (11, "Patarlagele","Fundaturile", NOW(), NOW()),
            (11, "Patarlagele","Gornet", NOW(), NOW()),
            (11, "Patarlagele","Lunca", NOW(), NOW()),
            (11, "Patarlagele","Muscel", NOW(), NOW()),
            (11, "Patarlagele","Manastirea", NOW(), NOW()),
            (11, "Patarlagele","Maruntisu", NOW(), NOW()),
            (11, "Patarlagele","Poienile", NOW(), NOW()),
            (11, "Patarlagele","Sibiciu de Sus", NOW(), NOW()),
            (11, "Patarlagele","Stroesti", NOW(), NOW()),
            (11, "Patarlagele","Valea Lupului", NOW(), NOW()),
            (11, "Patarlagele","Valea Sibiciului", NOW(), NOW()),
            (11, "Patarlagele","Valea Viei", NOW(), NOW()),
            (11, "Pietroasele","Clondiru de Sus", NOW(), NOW()),
            (11, "Pietroasele","Caltesti", NOW(), NOW()),
            (11, "Pietroasele","Dara", NOW(), NOW()),
            (11, "Pietroasele","Pietroasa Mica", NOW(), NOW()),
            (11, "Pietroasele","Saranga", NOW(), NOW()),
            (11, "Podgoria","Cotatcu", NOW(), NOW()),
            (11, "Podgoria","Oratia", NOW(), NOW()),
            (11, "Podgoria","Plesesti", NOW(), NOW()),
            (11, "Podgoria","Tabacari", NOW(), NOW()),
            (11, "Pogoanele","Caldarasti", NOW(), NOW()),
            (11, "Posta Calnau","Aliceni", NOW(), NOW()),
            (11, "Posta Calnau","Coconari", NOW(), NOW()),
            (11, "Posta Calnau","Potarnichesti", NOW(), NOW()),
            (11, "Posta Calnau","Suditi", NOW(), NOW()),
            (11, "Posta Calnau","Zilisteanca", NOW(), NOW()),
            (11, "Puiesti","Dascalesti", NOW(), NOW()),
            (11, "Puiesti","Lunca", NOW(), NOW()),
            (11, "Puiesti","Macrina", NOW(), NOW()),
            (11, "Puiesti","Nicolesti", NOW(), NOW()),
            (11, "Puiesti","Plopi", NOW(), NOW()),
            (11, "Puiesti","Puiestii de Jos", NOW(), NOW()),
            (11, "Puiesti","Puiestii de Sus", NOW(), NOW()),
            (11, "Racoviteni","Budrea", NOW(), NOW()),
            (11, "Racoviteni","Petrisoru", NOW(), NOW()),
            (11, "Ramnicelu","Colibasi", NOW(), NOW()),
            (11, "Ramnicelu","Fotin", NOW(), NOW()),
            (11, "Ramnicelu","Stiubei", NOW(), NOW()),
            (11, "Robeasca","Mosesti", NOW(), NOW()),
            (11, "Rusetu","Sergent Ionel Stefan", NOW(), NOW()),
            (11, "Sageata","Banita", NOW(), NOW()),
            (11, "Sageata","Beilic", NOW(), NOW()),
            (11, "Sageata","Bordusani", NOW(), NOW()),
            (11, "Sageata","Dambroca", NOW(), NOW()),
            (11, "Sageata","Gavanesti", NOW(), NOW()),
            (11, "Sageata","Movilita", NOW(), NOW()),
            (11, "Sahateni","Gageni", NOW(), NOW()),
            (11, "Sahateni","Istrita de Jos", NOW(), NOW()),
            (11, "Sahateni","Vintileanca", NOW(), NOW()),
            (11, "Sapoca","Matesti", NOW(), NOW()),
            (11, "Sarulesti","Caratnau de Jos", NOW(), NOW()),
            (11, "Sarulesti","Caratnau de Sus", NOW(), NOW()),
            (11, "Sarulesti","Goicelu", NOW(), NOW()),
            (11, "Sarulesti","Sarile-Catun", NOW(), NOW()),
            (11, "Sarulesti","Valea Larga-Sarulesti", NOW(), NOW()),
            (11, "Sarulesti","Valea Stanei", NOW(), NOW()),
            (11, "Scortoasa","Balta Tocila", NOW(), NOW()),
            (11, "Scortoasa","Beciu", NOW(), NOW()),
            (11, "Scortoasa","Deleni", NOW(), NOW()),
            (11, "Scortoasa","Dalma", NOW(), NOW()),
            (11, "Scortoasa","Golu Grabicina", NOW(), NOW()),
            (11, "Scortoasa","Grabicina de Jos", NOW(), NOW()),
            (11, "Scortoasa","Grabicina de Sus", NOW(), NOW()),
            (11, "Scortoasa","Gura Vaii", NOW(), NOW()),
            (11, "Scortoasa","Plopeasa", NOW(), NOW()),
            (11, "Scortoasa","Policiori", NOW(), NOW()),
            (11, "Scutelnici","Arcanu", NOW(), NOW()),
            (11, "Scutelnici","Bragareasa", NOW(), NOW()),
            (11, "Scutelnici","Lipanescu", NOW(), NOW()),
            (11, "Siriu","Casoca", NOW(), NOW()),
            (11, "Siriu","Coltu Pietrii", NOW(), NOW()),
            (11, "Siriu","Gura Siriului", NOW(), NOW()),
            (11, "Siriu","Lunca Jaristei", NOW(), NOW()),
            (11, "Siriu","Muscelusa", NOW(), NOW()),
            (11, "Smeeni","Albesti", NOW(), NOW()),
            (11, "Smeeni","Balaia", NOW(), NOW()),
            (11, "Smeeni","Caltuna", NOW(), NOW()),
            (11, "Smeeni","Moisica", NOW(), NOW()),
            (11, "Smeeni","Udati-Lucieni", NOW(), NOW()),
            (11, "Smeeni","Udati-Manzu", NOW(), NOW()),
            (11, "Tintesti","Maxenu", NOW(), NOW()),
            (11, "Tintesti","Odaia Banului", NOW(), NOW()),
            (11, "Tintesti","Pogonele", NOW(), NOW()),
            (11, "Tisau","Barbuncesti", NOW(), NOW()),
            (11, "Tisau","Grajdana", NOW(), NOW()),
            (11, "Tisau","Hales", NOW(), NOW()),
            (11, "Tisau","Izvoranu", NOW(), NOW()),
            (11, "Tisau","Izvoru", NOW(), NOW()),
            (11, "Tisau","Leiculesti", NOW(), NOW()),
            (11, "Tisau","Padurenii", NOW(), NOW()),
            (11, "Tisau","Salcia", NOW(), NOW()),
            (11, "Tisau","Strezeni", NOW(), NOW()),
            (11, "Tisau","Valea Salciilor", NOW(), NOW()),
            (11, "Topliceni","Babeni", NOW(), NOW()),
            (11, "Topliceni","Ceairu", NOW(), NOW()),
            (11, "Topliceni","Dedulesti", NOW(), NOW()),
            (11, "Topliceni","Gura Fagetului", NOW(), NOW()),
            (11, "Topliceni","Posta", NOW(), NOW()),
            (11, "Topliceni","Raducesti", NOW(), NOW()),
            (11, "Ulmeni","Baltareti", NOW(), NOW()),
            (11, "Ulmeni","Clondiru", NOW(), NOW()),
            (11, "Ulmeni","Sarata", NOW(), NOW()),
            (11, "Ulmeni","Valcele", NOW(), NOW()),
            (11, "Unguriu","Ojasca", NOW(), NOW()),
            (11, "Vadu Pasii","Bajani", NOW(), NOW()),
            (11, "Vadu Pasii","Focsanei", NOW(), NOW()),
            (11, "Vadu Pasii","Gura Calnaului", NOW(), NOW()),
            (11, "Vadu Pasii","Scurtesti", NOW(), NOW()),
            (11, "Vadu Pasii","Stancesti", NOW(), NOW()),
            (11, "Valea Ramnicului","Oreavul", NOW(), NOW()),
            (11, "Valea Ramnicului","Rubla", NOW(), NOW()),
            (11, "Valea Salciei","Modreni", NOW(), NOW()),
            (11, "Valea Salciei","Valea Salciei-Catun", NOW(), NOW()),
            (11, "Vernesti","Bradeanca", NOW(), NOW()),
            (11, "Vernesti","Candesti", NOW(), NOW()),
            (11, "Vernesti","Carlomanesti", NOW(), NOW()),
            (11, "Vernesti","Mierea", NOW(), NOW()),
            (11, "Vernesti","Nenciu", NOW(), NOW()),
            (11, "Vernesti","Niscov", NOW(), NOW()),
            (11, "Vernesti","Sasenii Noi", NOW(), NOW()),
            (11, "Vernesti","Sasenii Vechi", NOW(), NOW()),
            (11, "Vernesti","Sasenii pe Vale", NOW(), NOW()),
            (11, "Vernesti","Zoresti", NOW(), NOW()),
            (11, "Vintila Voda","Bodinesti", NOW(), NOW()),
            (11, "Vintila Voda","Coca-Antimiresti", NOW(), NOW()),
            (11, "Vintila Voda","Coca-Niculesti", NOW(), NOW()),
            (11, "Vintila Voda","Niculesti", NOW(), NOW()),
            (11, "Vintila Voda","Petrachesti", NOW(), NOW()),
            (11, "Vintila Voda","Podu Muncii", NOW(), NOW()),
            (11, "Vintila Voda","Smeesti", NOW(), NOW()),
            (11, "Vintila Voda","Sarbesti", NOW(), NOW()),
            (11, "Viperesti","Muscel", NOW(), NOW()),
            (11, "Viperesti","Palici", NOW(), NOW()),
            (11, "Viperesti","Rusavat", NOW(), NOW()),
            (11, "Viperesti","Tronari", NOW(), NOW()),
            (11, "Viperesti","Ursoaia", NOW(), NOW()),
            (11, "Zarnesti","Comisoaia", NOW(), NOW()),
            (11, "Zarnesti","Fundeni", NOW(), NOW()),
            (11, "Zarnesti","Pruneni", NOW(), NOW()),
            (11, "Zarnesti","Vadu Soresti", NOW(), NOW()),
            (11, "Ziduri","Costieni", NOW(), NOW()),
            (11, "Ziduri","Cuculeasa", NOW(), NOW()),
            (11, "Ziduri","Heliade Radulescu", NOW(), NOW()),
            (11, "Ziduri","Lanurile", NOW(), NOW()),
            (11, "Ziduri","Zoita", NOW(), NOW())
        ;';
        DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql="DELETE FROM localities WHERE county_id=11;";
        DB::connection()->getPdo()->exec($sql);
    }
}

