<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForSJ extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (34, "","Agrij", NOW(), NOW()),
            (34, "","Almasu", NOW(), NOW()),
            (34, "","Benesat", NOW(), NOW()),
            (34, "","Bobota", NOW(), NOW()),
            (34, "","Bocsa", NOW(), NOW()),
            (34, "","Buciumi", NOW(), NOW()),
            (34, "","Babeni", NOW(), NOW()),
            (34, "","Balan", NOW(), NOW()),
            (34, "","Banisor", NOW(), NOW()),
            (34, "","Camar", NOW(), NOW()),
            (34, "","Carastelec", NOW(), NOW()),
            (34, "","Cehu Silvaniei", NOW(), NOW()),
            (34, "","Chiesd", NOW(), NOW()),
            (34, "","Cizer", NOW(), NOW()),
            (34, "","Coseiu", NOW(), NOW()),
            (34, "","Crasna", NOW(), NOW()),
            (34, "","Creaca", NOW(), NOW()),
            (34, "","Cristolt", NOW(), NOW()),
            (34, "","Criseni", NOW(), NOW()),
            (34, "","Cuzaplac", NOW(), NOW()),
            (34, "","Dobrin", NOW(), NOW()),
            (34, "","Dragu", NOW(), NOW()),
            (34, "","Fildu de Jos", NOW(), NOW()),
            (34, "","Galgau", NOW(), NOW()),
            (34, "","Garbou", NOW(), NOW()),
            (34, "","Halmasd", NOW(), NOW()),
            (34, "","Hereclean", NOW(), NOW()),
            (34, "","Hida", NOW(), NOW()),
            (34, "","Horoatu Crasnei", NOW(), NOW()),
            (34, "","Ileanda", NOW(), NOW()),
            (34, "","Ip", NOW(), NOW()),
            (34, "","Jibou", NOW(), NOW()),
            (34, "","Letca", NOW(), NOW()),
            (34, "","Lozna", NOW(), NOW()),
            (34, "","Marca", NOW(), NOW()),
            (34, "","Mesesenii de Jos", NOW(), NOW()),
            (34, "","Mirsid", NOW(), NOW()),
            (34, "","Maeriste", NOW(), NOW()),
            (34, "","Nusfalau", NOW(), NOW()),
            (34, "","Napradea", NOW(), NOW()),
            (34, "","Pericei", NOW(), NOW()),
            (34, "","Plopis", NOW(), NOW()),
            (34, "","Poiana Blenchii", NOW(), NOW()),
            (34, "","Romanasi", NOW(), NOW()),
            (34, "","Rus", NOW(), NOW()),
            (34, "","Somes-Odorhei", NOW(), NOW()),
            (34, "","Surduc", NOW(), NOW()),
            (34, "","Sag", NOW(), NOW()),
            (34, "","Sanmihaiu Almasului", NOW(), NOW()),
            (34, "","Salatig", NOW(), NOW()),
            (34, "","Treznea", NOW(), NOW()),
            (34, "","Valcau de Jos", NOW(), NOW()),
            (34, "","Varsolt", NOW(), NOW()),
            (34, "","Zalha", NOW(), NOW()),
            (34, "","Zalau", NOW(), NOW()),
            (34, "","Zimbor", NOW(), NOW()),
            (34, "","Samsud", NOW(), NOW()),
            (34, "","Simisna", NOW(), NOW()),
            (34, "","Simleu Silvaniei", NOW(), NOW()),
            (34, "","Sarmasag", NOW(), NOW()),
            (34, "Agrij","Rastoltu Desert", NOW(), NOW()),
            (34, "Almasu","Babiu", NOW(), NOW()),
            (34, "Almasu","Cutis", NOW(), NOW()),
            (34, "Almasu","Jebucu", NOW(), NOW()),
            (34, "Almasu","Mesteacanu", NOW(), NOW()),
            (34, "Almasu","Petrinzel", NOW(), NOW()),
            (34, "Almasu","Sfaras", NOW(), NOW()),
            (34, "Almasu","Stana", NOW(), NOW()),
            (34, "Almasu","Taudu", NOW(), NOW()),
            (34, "Babeni","Ciocmani", NOW(), NOW()),
            (34, "Babeni","Clit", NOW(), NOW()),
            (34, "Babeni","Pirosa", NOW(), NOW()),
            (34, "Babeni","Poienita", NOW(), NOW()),
            (34, "Balan","Chechis", NOW(), NOW()),
            (34, "Balan","Chendrea", NOW(), NOW()),
            (34, "Balan","Galgau Almasului", NOW(), NOW()),
            (34, "Balan","Galpaia", NOW(), NOW()),
            (34, "Banisor","Ban", NOW(), NOW()),
            (34, "Banisor","Peceiu", NOW(), NOW()),
            (34, "Benesat","Alunis", NOW(), NOW()),
            (34, "Benesat","Biusa", NOW(), NOW()),
            (34, "Bobota","Dersida", NOW(), NOW()),
            (34, "Bobota","Zalnoc", NOW(), NOW()),
            (34, "Bocsa","Borla", NOW(), NOW()),
            (34, "Bocsa","Campia", NOW(), NOW()),
            (34, "Bocsa","Salajeni", NOW(), NOW()),
            (34, "Buciumi","Bodia", NOW(), NOW()),
            (34, "Buciumi","Bogdana", NOW(), NOW()),
            (34, "Buciumi","Huta", NOW(), NOW()),
            (34, "Buciumi","Rastolt", NOW(), NOW()),
            (34, "Buciumi","Sangeorgiu de Meses", NOW(), NOW()),
            (34, "Camar","Padureni", NOW(), NOW()),
            (34, "Carastelec","Dumuslau", NOW(), NOW()),
            (34, "Cehu Silvaniei","Horoatu Cehului", NOW(), NOW()),
            (34, "Cehu Silvaniei","Motis", NOW(), NOW()),
            (34, "Cehu Silvaniei","Nadis", NOW(), NOW()),
            (34, "Cehu Silvaniei","Ulciug", NOW(), NOW()),
            (34, "Chiesd","Colonia Sighetu Silvaniei", NOW(), NOW()),
            (34, "Chiesd","Sighetu Silvaniei", NOW(), NOW()),
            (34, "Cizer","Plesca", NOW(), NOW()),
            (34, "Cizer","Pria", NOW(), NOW()),
            (34, "Coseiu","Archid", NOW(), NOW()),
            (34, "Coseiu","Chilioara", NOW(), NOW()),
            (34, "Crasna","Huseni", NOW(), NOW()),
            (34, "Crasna","Marin", NOW(), NOW()),
            (34, "Crasna","Ratin", NOW(), NOW()),
            (34, "Creaca","Borza", NOW(), NOW()),
            (34, "Creaca","Brebi", NOW(), NOW()),
            (34, "Creaca","Brusturi", NOW(), NOW()),
            (34, "Creaca","Ciglean", NOW(), NOW()),
            (34, "Creaca","Jac", NOW(), NOW()),
            (34, "Creaca","Lupoaia", NOW(), NOW()),
            (34, "Creaca","Prodanesti", NOW(), NOW()),
            (34, "Creaca","Viile Jacului", NOW(), NOW()),
            (34, "Criseni","Cristur Criseni", NOW(), NOW()),
            (34, "Criseni","Garceiu", NOW(), NOW()),
            (34, "Cristolt","Muncel", NOW(), NOW()),
            (34, "Cristolt","Poiana Ontii", NOW(), NOW()),
            (34, "Cristolt","Valeni", NOW(), NOW()),
            (34, "Cuzaplac","Cublesu", NOW(), NOW()),
            (34, "Cuzaplac","Galaseni", NOW(), NOW()),
            (34, "Cuzaplac","Mierta", NOW(), NOW()),
            (34, "Cuzaplac","Petrindu", NOW(), NOW()),
            (34, "Cuzaplac","Ruginoasa", NOW(), NOW()),
            (34, "Cuzaplac","Stoboru", NOW(), NOW()),
            (34, "Cuzaplac","Tamasa", NOW(), NOW()),
            (34, "Dobrin","Deleni", NOW(), NOW()),
            (34, "Dobrin","Doba", NOW(), NOW()),
            (34, "Dobrin","Naimon", NOW(), NOW()),
            (34, "Dobrin","Sancraiu Silvaniei", NOW(), NOW()),
            (34, "Dobrin","Verveghiu", NOW(), NOW()),
            (34, "Dragu","Adalin", NOW(), NOW()),
            (34, "Dragu","Fantanele", NOW(), NOW()),
            (34, "Dragu","Ugrutiu", NOW(), NOW()),
            (34, "Dragu","Voivodeni", NOW(), NOW()),
            (34, "Fildu De Jos","Fildu de Mijloc", NOW(), NOW()),
            (34, "Fildu De Jos","Fildu de Sus", NOW(), NOW()),
            (34, "Fildu De Jos","Tetisu", NOW(), NOW()),
            (34, "Galgau","Barsau Mare", NOW(), NOW()),
            (34, "Galgau","Chizeni", NOW(), NOW()),
            (34, "Galgau","Capalna", NOW(), NOW()),
            (34, "Galgau","Dobrocina", NOW(), NOW()),
            (34, "Galgau","Fodora", NOW(), NOW()),
            (34, "Galgau","Francenii de Piatra", NOW(), NOW()),
            (34, "Galgau","Glod", NOW(), NOW()),
            (34, "Galgau","Gura Vladesei", NOW(), NOW()),
            (34, "Garbou","Bezded", NOW(), NOW()),
            (34, "Garbou","Cernuc", NOW(), NOW()),
            (34, "Garbou","Calacea", NOW(), NOW()),
            (34, "Garbou","Fabrica", NOW(), NOW()),
            (34, "Garbou","Popteleac", NOW(), NOW()),
            (34, "Garbou","Solomon", NOW(), NOW()),
            (34, "Halmasd","Aleus", NOW(), NOW()),
            (34, "Halmasd","Cerisa", NOW(), NOW()),
            (34, "Halmasd","Drighiu", NOW(), NOW()),
            (34, "Halmasd","Fufez", NOW(), NOW()),
            (34, "Hereclean","Badon", NOW(), NOW()),
            (34, "Hereclean","Bocsita", NOW(), NOW()),
            (34, "Hereclean","Diosod", NOW(), NOW()),
            (34, "Hereclean","Guruslau", NOW(), NOW()),
            (34, "Hereclean","Panic", NOW(), NOW()),
            (34, "Hida","Baica", NOW(), NOW()),
            (34, "Hida","Miluani", NOW(), NOW()),
            (34, "Hida","Paduris", NOW(), NOW()),
            (34, "Hida","Racas", NOW(), NOW()),
            (34, "Hida","Stupini", NOW(), NOW()),
            (34, "Hida","Sanpetru Almasului", NOW(), NOW()),
            (34, "Hida","Trestia", NOW(), NOW()),
            (34, "Horoatu Crasnei","Hurez", NOW(), NOW()),
            (34, "Horoatu Crasnei","Starciu", NOW(), NOW()),
            (34, "Horoatu Crasnei","Seredeiu", NOW(), NOW()),
            (34, "Ileanda","Bizusa Bai", NOW(), NOW()),
            (34, "Ileanda","Barsauta", NOW(), NOW()),
            (34, "Ileanda","Dolheni", NOW(), NOW()),
            (34, "Ileanda","Dabaceni", NOW(), NOW()),
            (34, "Ileanda","Luminisu", NOW(), NOW()),
            (34, "Ileanda","Maleni", NOW(), NOW()),
            (34, "Ileanda","Negreni", NOW(), NOW()),
            (34, "Ileanda","Perii Vadului", NOW(), NOW()),
            (34, "Ileanda","Podisu", NOW(), NOW()),
            (34, "Ileanda","Rogna", NOW(), NOW()),
            (34, "Ileanda","Rastoci", NOW(), NOW()),
            (34, "Ileanda","Sasa", NOW(), NOW()),
            (34, "Ip","Cosniciu de Jos", NOW(), NOW()),
            (34, "Ip","Cosniciu de Sus", NOW(), NOW()),
            (34, "Ip","Zauan", NOW(), NOW()),
            (34, "Ip","Zauan Bai", NOW(), NOW()),
            (34, "Jibou","Cuceu", NOW(), NOW()),
            (34, "Jibou","Husia", NOW(), NOW()),
            (34, "Jibou","Rona", NOW(), NOW()),
            (34, "Jibou","Var", NOW(), NOW()),
            (34, "Letca","Ciula", NOW(), NOW()),
            (34, "Letca","Cozla", NOW(), NOW()),
            (34, "Letca","Cuciulat", NOW(), NOW()),
            (34, "Letca","Lemniu", NOW(), NOW()),
            (34, "Letca","Purcaret", NOW(), NOW()),
            (34, "Letca","Toplita", NOW(), NOW()),
            (34, "Letca","Valisoara", NOW(), NOW()),
            (34, "Letca","Soimuseni", NOW(), NOW()),
            (34, "Lozna","Cormenis", NOW(), NOW()),
            (34, "Lozna","Preluci", NOW(), NOW()),
            (34, "Lozna","Valea Lesului", NOW(), NOW()),
            (34, "Lozna","Valea Loznei", NOW(), NOW()),
            (34, "Maeriste","Cristelec", NOW(), NOW()),
            (34, "Maeriste","Doh", NOW(), NOW()),
            (34, "Maeriste","Giurtelecu Simleului", NOW(), NOW()),
            (34, "Maeriste","Maladia", NOW(), NOW()),
            (34, "Maeriste","Uileacu Simleului", NOW(), NOW()),
            (34, "Marca","Lesmir", NOW(), NOW()),
            (34, "Marca","Marca Huta", NOW(), NOW()),
            (34, "Marca","Port", NOW(), NOW()),
            (34, "Marca","Sumal", NOW(), NOW()),
            (34, "Mesesenii De Jos","Aghires", NOW(), NOW()),
            (34, "Mesesenii De Jos","Fetindia", NOW(), NOW()),
            (34, "Mesesenii De Jos","Mesesenii de Sus", NOW(), NOW()),
            (34, "Mirsid","Firminis", NOW(), NOW()),
            (34, "Mirsid","Moigrad-Porolissum", NOW(), NOW()),
            (34, "Mirsid","Popeni", NOW(), NOW()),
            (34, "Napradea","Cheud", NOW(), NOW()),
            (34, "Napradea","Somes Guruslau", NOW(), NOW()),
            (34, "Napradea","Tranis", NOW(), NOW()),
            (34, "Napradea","Vadurele", NOW(), NOW()),
            (34, "Nusfalau","Bilghez", NOW(), NOW()),
            (34, "Nusfalau","Boghis", NOW(), NOW()),
            (34, "Nusfalau","Bozies", NOW(), NOW()),
            (34, "Pericei","Badacin", NOW(), NOW()),
            (34, "Pericei","Periceiu Mic", NOW(), NOW()),
            (34, "Pericei","Sici", NOW(), NOW()),
            (34, "Plopis","Fagetu", NOW(), NOW()),
            (34, "Plopis","Iaz", NOW(), NOW()),
            (34, "Poiana Blenchii","Falcusa", NOW(), NOW()),
            (34, "Poiana Blenchii","Gostila", NOW(), NOW()),
            (34, "Poiana Blenchii","Magura", NOW(), NOW()),
            (34, "Romanasi","Chichisa", NOW(), NOW()),
            (34, "Romanasi","Ciumarna", NOW(), NOW()),
            (34, "Romanasi","Poarta Salajului", NOW(), NOW()),
            (34, "Romanasi","Pausa", NOW(), NOW()),
            (34, "Romanasi","Romita", NOW(), NOW()),
            (34, "Rus","Buzas", NOW(), NOW()),
            (34, "Rus","Fantanele Rus", NOW(), NOW()),
            (34, "Sag","Fizes", NOW(), NOW()),
            (34, "Sag","Mal", NOW(), NOW()),
            (34, "Sag","Sarbi", NOW(), NOW()),
            (34, "Sag","Tusa", NOW(), NOW()),
            (34, "Salatig","Bulgari", NOW(), NOW()),
            (34, "Salatig","Deja", NOW(), NOW()),
            (34, "Salatig","Mineu", NOW(), NOW()),
            (34, "Salatig","Notig", NOW(), NOW()),
            (34, "Samsud","Valea Pomilor", NOW(), NOW()),
            (34, "Sanmihaiu Almasului","Bercea", NOW(), NOW()),
            (34, "Sanmihaiu Almasului","Santa Maria", NOW(), NOW()),
            (34, "Sarmasag","Ilisua", NOW(), NOW()),
            (34, "Sarmasag","Lompirt", NOW(), NOW()),
            (34, "Sarmasag","Moiad", NOW(), NOW()),
            (34, "Sarmasag","Poiana Magura", NOW(), NOW()),
            (34, "Sarmasag","Tarmure", NOW(), NOW()),
            (34, "Simisna","Hasmas", NOW(), NOW()),
            (34, "Simleu Silvaniei","Bic", NOW(), NOW()),
            (34, "Simleu Silvaniei","Cehei", NOW(), NOW()),
            (34, "Simleu Silvaniei","Pusta", NOW(), NOW()),
            (34, "Somes-Odorhei","Barsa", NOW(), NOW()),
            (34, "Somes-Odorhei","Domnin", NOW(), NOW()),
            (34, "Somes-Odorhei","Inau", NOW(), NOW()),
            (34, "Somes-Odorhei","Soimus", NOW(), NOW()),
            (34, "Surduc","Braglez", NOW(), NOW()),
            (34, "Surduc","Cristoltel", NOW(), NOW()),
            (34, "Surduc","Solona", NOW(), NOW()),
            (34, "Surduc","Testioara", NOW(), NOW()),
            (34, "Surduc","Tihau", NOW(), NOW()),
            (34, "Surduc","Turbuta", NOW(), NOW()),
            (34, "Treznea","Bozna", NOW(), NOW()),
            (34, "Valcau De Jos","Lazuri", NOW(), NOW()),
            (34, "Valcau De Jos","Preoteasa", NOW(), NOW()),
            (34, "Valcau De Jos","Ratovei", NOW(), NOW()),
            (34, "Valcau De Jos","Sub Cetate", NOW(), NOW()),
            (34, "Valcau De Jos","Valcau de Sus", NOW(), NOW()),
            (34, "Varsolt","Recea", NOW(), NOW()),
            (34, "Varsolt","Recea Mica", NOW(), NOW()),
            (34, "Zalau","Stana", NOW(), NOW()),
            (34, "Zalha","Ceaca", NOW(), NOW()),
            (34, "Zalha","Ciureni", NOW(), NOW()),
            (34, "Zalha","Valea Ciurenilor", NOW(), NOW()),
            (34, "Zalha","Valea Hranei", NOW(), NOW()),
            (34, "Zalha","Valea Lunga", NOW(), NOW()),
            (34, "Zalha","Vartesca", NOW(), NOW()),
            (34, "Zimbor","Chendremal", NOW(), NOW()),
            (34, "Zimbor","Dolu", NOW(), NOW()),
            (34, "Zimbor","Sutoru", NOW(), NOW()),
            (34, "Zimbor","Sancraiu Almasului", NOW(), NOW())
        ;';
        if (config('app.env') !== 'testing') {
            DB::connection()->getPdo()->exec($sql);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=34;';
        DB::connection()->getPdo()->exec($sql);
    }
}
