<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForTM extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (38, "","Balint", NOW(), NOW()),
            (38, "","Banloc", NOW(), NOW()),
            (38, "","Bara", NOW(), NOW()),
            (38, "","Beba Veche", NOW(), NOW()),
            (38, "","Becicherecu Mic", NOW(), NOW()),
            (38, "","Belint", NOW(), NOW()),
            (38, "","Bethausen", NOW(), NOW()),
            (38, "","Biled", NOW(), NOW()),
            (38, "","Bogda", NOW(), NOW()),
            (38, "","Boldur", NOW(), NOW()),
            (38, "","Brestovat", NOW(), NOW()),
            (38, "","Buzias", NOW(), NOW()),
            (38, "","Barna", NOW(), NOW()),
            (38, "","Cenad", NOW(), NOW()),
            (38, "","Cenei", NOW(), NOW()),
            (38, "","Cheveresu Mare", NOW(), NOW()),
            (38, "","Ciacova", NOW(), NOW()),
            (38, "","Comlosu Mare", NOW(), NOW()),
            (38, "","Costeiu", NOW(), NOW()),
            (38, "","Criciova", NOW(), NOW()),
            (38, "","Curtea", NOW(), NOW()),
            (38, "","Carpinis", NOW(), NOW()),
            (38, "","Darova", NOW(), NOW()),
            (38, "","Denta", NOW(), NOW()),
            (38, "","Deta", NOW(), NOW()),
            (38, "","Dudestii Vechi", NOW(), NOW()),
            (38, "","Dumbrava", NOW(), NOW()),
            (38, "","Dumbravita", NOW(), NOW()),
            (38, "","Foeni", NOW(), NOW()),
            (38, "","Fardea", NOW(), NOW()),
            (38, "","Faget", NOW(), NOW()),
            (38, "","Gavojdia", NOW(), NOW()),
            (38, "","Ghiroda", NOW(), NOW()),
            (38, "","Ghizela", NOW(), NOW()),
            (38, "","Giarmata", NOW(), NOW()),
            (38, "","Giera", NOW(), NOW()),
            (38, "","Giroc", NOW(), NOW()),
            (38, "","Giulvaz", NOW(), NOW()),
            (38, "","Gataia", NOW(), NOW()),
            (38, "","Jamu Mare", NOW(), NOW()),
            (38, "","Jebel", NOW(), NOW()),
            (38, "","Jimbolia", NOW(), NOW()),
            (38, "","Lenauheim", NOW(), NOW()),
            (38, "","Liebling", NOW(), NOW()),
            (38, "","Lovrin", NOW(), NOW()),
            (38, "","Lugoj", NOW(), NOW()),
            (38, "","Margina", NOW(), NOW()),
            (38, "","Masloc", NOW(), NOW()),
            (38, "","Moravita", NOW(), NOW()),
            (38, "","Mosnita Noua", NOW(), NOW()),
            (38, "","Manastiur", NOW(), NOW()),
            (38, "","Nitchidorf", NOW(), NOW()),
            (38, "","Nadrag", NOW(), NOW()),
            (38, "","Ohaba Lunga", NOW(), NOW()),
            (38, "","Ortisoara", NOW(), NOW()),
            (38, "","Peciu Nou", NOW(), NOW()),
            (38, "","Periam", NOW(), NOW()),
            (38, "","Pietroasa", NOW(), NOW()),
            (38, "","Pischia", NOW(), NOW()),
            (38, "","Racovita", NOW(), NOW()),
            (38, "","Recas", NOW(), NOW()),
            (38, "","Remetea Mare", NOW(), NOW()),
            (38, "","Sacosu Turcesc", NOW(), NOW()),
            (38, "","Satchinez", NOW(), NOW()),
            (38, "","Secas", NOW(), NOW()),
            (38, "","Sanandrei", NOW(), NOW()),
            (38, "","Sanmihaiu Roman", NOW(), NOW()),
            (38, "","Sannicolau Mare", NOW(), NOW()),
            (38, "","Sanpetru Mare", NOW(), NOW()),
            (38, "","Sacalaz", NOW(), NOW()),
            (38, "","Teremia Mare", NOW(), NOW()),
            (38, "","Timisoara", NOW(), NOW()),
            (38, "","Tomesti", NOW(), NOW()),
            (38, "","Topolovatu Mare", NOW(), NOW()),
            (38, "","Tormac", NOW(), NOW()),
            (38, "","Traian Vuia", NOW(), NOW()),
            (38, "","Uivar", NOW(), NOW()),
            (38, "","Varias", NOW(), NOW()),
            (38, "","Victor Vlad Delamarina", NOW(), NOW()),
            (38, "","Voiteg", NOW(), NOW()),
            (38, "","Sag", NOW(), NOW()),
            (38, "","Stiuca", NOW(), NOW()),
            (38, "Balint","Bodo", NOW(), NOW()),
            (38, "Balint","Fadimac", NOW(), NOW()),
            (38, "Balint","Targoviste", NOW(), NOW()),
            (38, "Banloc","Dolat", NOW(), NOW()),
            (38, "Banloc","Livezile", NOW(), NOW()),
            (38, "Banloc","Ofsenita", NOW(), NOW()),
            (38, "Banloc","Partos", NOW(), NOW()),
            (38, "Banloc","Soca", NOW(), NOW()),
            (38, "Bara","Dobresti", NOW(), NOW()),
            (38, "Bara","Lapusnic", NOW(), NOW()),
            (38, "Bara","Radmanesti", NOW(), NOW()),
            (38, "Bara","Spata", NOW(), NOW()),
            (38, "Barna","Botesti", NOW(), NOW()),
            (38, "Barna","Botinesti", NOW(), NOW()),
            (38, "Barna","Drinova", NOW(), NOW()),
            (38, "Barna","Juresti", NOW(), NOW()),
            (38, "Barna","Poganesti", NOW(), NOW()),
            (38, "Barna","Sarazani", NOW(), NOW()),
            (38, "Beba Veche","Cherestur", NOW(), NOW()),
            (38, "Beba Veche","Pordeanu", NOW(), NOW()),
            (38, "Becicherecu Mic","Dudestii Noi", NOW(), NOW()),
            (38, "Belint","Babsa", NOW(), NOW()),
            (38, "Belint","Chizatau", NOW(), NOW()),
            (38, "Belint","Gruni", NOW(), NOW()),
            (38, "Bethausen","Cladova", NOW(), NOW()),
            (38, "Bethausen","Cliciova", NOW(), NOW()),
            (38, "Bethausen","Cutina", NOW(), NOW()),
            (38, "Bethausen","Leucusesti", NOW(), NOW()),
            (38, "Bethausen","Nevrincea", NOW(), NOW()),
            (38, "Biled","Uihei", NOW(), NOW()),
            (38, "Biled","Sandra", NOW(), NOW()),
            (38, "Bogda","Altringen", NOW(), NOW()),
            (38, "Bogda","Buzad", NOW(), NOW()),
            (38, "Bogda","Charlotenburg", NOW(), NOW()),
            (38, "Bogda","Comeat", NOW(), NOW()),
            (38, "Bogda","Sintar", NOW(), NOW()),
            (38, "Boldur","Jabar", NOW(), NOW()),
            (38, "Boldur","Ohaba-Forgaci", NOW(), NOW()),
            (38, "Boldur","Sinersig", NOW(), NOW()),
            (38, "Brestovat","Cosarii", NOW(), NOW()),
            (38, "Brestovat","Hodos", NOW(), NOW()),
            (38, "Brestovat","Lucaret", NOW(), NOW()),
            (38, "Brestovat","Tes", NOW(), NOW()),
            (38, "Buzias","Bacova", NOW(), NOW()),
            (38, "Buzias","Silagiu", NOW(), NOW()),
            (38, "Carpinis","Iecea Mare", NOW(), NOW()),
            (38, "Carpinis","Iecea Mica", NOW(), NOW()),
            (38, "Cenei","Bobda", NOW(), NOW()),
            (38, "Cenei","Checea", NOW(), NOW()),
            (38, "Cheveresu Mare","Dragsina", NOW(), NOW()),
            (38, "Cheveresu Mare","Vucova", NOW(), NOW()),
            (38, "Ciacova","Cebza", NOW(), NOW()),
            (38, "Ciacova","Gad", NOW(), NOW()),
            (38, "Ciacova","Ghilad", NOW(), NOW()),
            (38, "Ciacova","Macedonia", NOW(), NOW()),
            (38, "Ciacova","Obad", NOW(), NOW()),
            (38, "Ciacova","Petroman", NOW(), NOW()),
            (38, "Comlosu Mare","Comlosu Mic", NOW(), NOW()),
            (38, "Comlosu Mare","Lunga", NOW(), NOW()),
            (38, "Costeiu","Hezeris", NOW(), NOW()),
            (38, "Costeiu","Paru", NOW(), NOW()),
            (38, "Costeiu","Valea Lunga Romana", NOW(), NOW()),
            (38, "Costeiu","Tipari", NOW(), NOW()),
            (38, "Criciova","Ciresu", NOW(), NOW()),
            (38, "Criciova","Ciresu Mic", NOW(), NOW()),
            (38, "Criciova","Jdioara", NOW(), NOW()),
            (38, "Curtea","Cosava", NOW(), NOW()),
            (38, "Curtea","Homojdia", NOW(), NOW()),
            (38, "Darova","Hodos", NOW(), NOW()),
            (38, "Darova","Sacosu Mare", NOW(), NOW()),
            (38, "Denta","Brestea", NOW(), NOW()),
            (38, "Denta","Rovinita Mare", NOW(), NOW()),
            (38, "Denta","Rovinita Mica", NOW(), NOW()),
            (38, "Deta","Opatita", NOW(), NOW()),
            (38, "Dudestii Vechi","Cheglevici", NOW(), NOW()),
            (38, "Dudestii Vechi","Colonia Bulgara", NOW(), NOW()),
            (38, "Dudestii Vechi","Valcani", NOW(), NOW()),
            (38, "Dumbrava","Bucovat", NOW(), NOW()),
            (38, "Dumbrava","Rachita", NOW(), NOW()),
            (38, "Faget","Begheiu Mic", NOW(), NOW()),
            (38, "Faget","Bichigi", NOW(), NOW()),
            (38, "Faget","Branesti", NOW(), NOW()),
            (38, "Faget","Bunea Mare", NOW(), NOW()),
            (38, "Faget","Bunea Mica", NOW(), NOW()),
            (38, "Faget","Batesti", NOW(), NOW()),
            (38, "Faget","Colonia Mica", NOW(), NOW()),
            (38, "Faget","Jupanesti", NOW(), NOW()),
            (38, "Faget","Povargina", NOW(), NOW()),
            (38, "Faget","Temeresti", NOW(), NOW()),
            (38, "Fardea","Dragsinesti", NOW(), NOW()),
            (38, "Fardea","Gladna Montana", NOW(), NOW()),
            (38, "Fardea","Gladna Romana", NOW(), NOW()),
            (38, "Fardea","Hauzesti", NOW(), NOW()),
            (38, "Fardea","Matnicu Mic", NOW(), NOW()),
            (38, "Fardea","Zolt", NOW(), NOW()),
            (38, "Foeni","Cruceni", NOW(), NOW()),
            (38, "Gataia","Berecuta", NOW(), NOW()),
            (38, "Gataia","Birda", NOW(), NOW()),
            (38, "Gataia","Butin", NOW(), NOW()),
            (38, "Gataia","Manastire", NOW(), NOW()),
            (38, "Gataia","Percosova", NOW(), NOW()),
            (38, "Gataia","Sculia", NOW(), NOW()),
            (38, "Gataia","Sangeorge", NOW(), NOW()),
            (38, "Gataia","Semlacu Mare", NOW(), NOW()),
            (38, "Gataia","Semlacu Mic", NOW(), NOW()),
            (38, "Gavojdia","Jena", NOW(), NOW()),
            (38, "Gavojdia","Lugojel", NOW(), NOW()),
            (38, "Gavojdia","Salbagel", NOW(), NOW()),
            (38, "Ghiroda","Giarmata-Vii", NOW(), NOW()),
            (38, "Ghizela","Hisias", NOW(), NOW()),
            (38, "Ghizela","Paniova", NOW(), NOW()),
            (38, "Ghizela","Sanovita", NOW(), NOW()),
            (38, "Giarmata","Cerneteaz", NOW(), NOW()),
            (38, "Giera","Granicerii", NOW(), NOW()),
            (38, "Giera","Toager", NOW(), NOW()),
            (38, "Giroc","Chisoda", NOW(), NOW()),
            (38, "Giulvaz","Crai Nou", NOW(), NOW()),
            (38, "Giulvaz","Ivanda", NOW(), NOW()),
            (38, "Giulvaz","Rudna", NOW(), NOW()),
            (38, "Jamu Mare","Clopodia", NOW(), NOW()),
            (38, "Jamu Mare","Ferendia", NOW(), NOW()),
            (38, "Jamu Mare","Gherman", NOW(), NOW()),
            (38, "Jamu Mare","Latunas", NOW(), NOW()),
            (38, "Jebel","Padureni", NOW(), NOW()),
            (38, "Lenauheim","Bulgarus", NOW(), NOW()),
            (38, "Lenauheim","Grabat", NOW(), NOW()),
            (38, "Liebling","Cerna", NOW(), NOW()),
            (38, "Liebling","Iosif", NOW(), NOW()),
            (38, "Lovrin","Gottlob", NOW(), NOW()),
            (38, "Lovrin","Tomnatic", NOW(), NOW()),
            (38, "Lovrin","Vizejdia", NOW(), NOW()),
            (38, "Lugoj","Maguri", NOW(), NOW()),
            (38, "Lugoj","Tapia", NOW(), NOW()),
            (38, "Manastiur","Padurani", NOW(), NOW()),
            (38, "Manastiur","Remetea-Lunca", NOW(), NOW()),
            (38, "Manastiur","Topla", NOW(), NOW()),
            (38, "Margina","Breazova", NOW(), NOW()),
            (38, "Margina","Bulza", NOW(), NOW()),
            (38, "Margina","Cosevita", NOW(), NOW()),
            (38, "Margina","Costeiu de Sus", NOW(), NOW()),
            (38, "Margina","Grosi", NOW(), NOW()),
            (38, "Margina","Nemesesti", NOW(), NOW()),
            (38, "Margina","Sintesti", NOW(), NOW()),
            (38, "Margina","Zorani", NOW(), NOW()),
            (38, "Masloc","Alios", NOW(), NOW()),
            (38, "Masloc","Fibis", NOW(), NOW()),
            (38, "Masloc","Remetea Mica", NOW(), NOW()),
            (38, "Moravita","Dejan", NOW(), NOW()),
            (38, "Moravita","Gaiu Mic", NOW(), NOW()),
            (38, "Moravita","Stamora Germana", NOW(), NOW()),
            (38, "Mosnita Noua","Albina", NOW(), NOW()),
            (38, "Mosnita Noua","Mosnita Veche", NOW(), NOW()),
            (38, "Mosnita Noua","Rudicica", NOW(), NOW()),
            (38, "Mosnita Noua","Urseni", NOW(), NOW()),
            (38, "Nadrag","Crivina", NOW(), NOW()),
            (38, "Nitchidorf","Blajova", NOW(), NOW()),
            (38, "Nitchidorf","Duboz", NOW(), NOW()),
            (38, "Ohaba Lunga","Dubesti", NOW(), NOW()),
            (38, "Ohaba Lunga","Iersnic", NOW(), NOW()),
            (38, "Ohaba Lunga","Ohaba Romana", NOW(), NOW()),
            (38, "Ortisoara","Cornesti", NOW(), NOW()),
            (38, "Ortisoara","Calacea", NOW(), NOW()),
            (38, "Ortisoara","Seceani", NOW(), NOW()),
            (38, "Peciu Nou","Dinias", NOW(), NOW()),
            (38, "Peciu Nou","Sanmartinu Sarbesc", NOW(), NOW()),
            (38, "Periam","Pesac", NOW(), NOW()),
            (38, "Pietroasa","Crivina de Sus", NOW(), NOW()),
            (38, "Pietroasa","Farasesti", NOW(), NOW()),
            (38, "Pietroasa","Poieni", NOW(), NOW()),
            (38, "Pischia","Bencecu de Jos", NOW(), NOW()),
            (38, "Pischia","Bencecu de Sus", NOW(), NOW()),
            (38, "Pischia","Murani", NOW(), NOW()),
            (38, "Pischia","Salciua Noua", NOW(), NOW()),
            (38, "Racovita","Capat", NOW(), NOW()),
            (38, "Racovita","Dragoiesti", NOW(), NOW()),
            (38, "Racovita","Ficatar", NOW(), NOW()),
            (38, "Racovita","Hitias", NOW(), NOW()),
            (38, "Racovita","Sarbova", NOW(), NOW()),
            (38, "Recas","Bazos", NOW(), NOW()),
            (38, "Recas","Herneacova", NOW(), NOW()),
            (38, "Recas","Izvin", NOW(), NOW()),
            (38, "Recas","Nadas", NOW(), NOW()),
            (38, "Recas","Petrovaselo", NOW(), NOW()),
            (38, "Recas","Stanciova", NOW(), NOW()),
            (38, "Remetea Mare","Bazosu Nou", NOW(), NOW()),
            (38, "Remetea Mare","Bucovat", NOW(), NOW()),
            (38, "Remetea Mare","Ianova", NOW(), NOW()),
            (38, "Sacalaz","Beregsau Mare", NOW(), NOW()),
            (38, "Sacalaz","Beregsau Mic", NOW(), NOW()),
            (38, "Sacosu Turcesc","Berini", NOW(), NOW()),
            (38, "Sacosu Turcesc","Icloda", NOW(), NOW()),
            (38, "Sacosu Turcesc","Otvesti", NOW(), NOW()),
            (38, "Sacosu Turcesc","Stamora Romana", NOW(), NOW()),
            (38, "Sacosu Turcesc","Uliuc", NOW(), NOW()),
            (38, "Sacosu Turcesc","Unip", NOW(), NOW()),
            (38, "Sag","Parta", NOW(), NOW()),
            (38, "Sanandrei","Carani", NOW(), NOW()),
            (38, "Sanandrei","Covaci", NOW(), NOW()),
            (38, "Sanmihaiu Roman","Sanmihaiu German", NOW(), NOW()),
            (38, "Sanmihaiu Roman","Utvin", NOW(), NOW()),
            (38, "Sanpetru Mare","Igris", NOW(), NOW()),
            (38, "Sanpetru Mare","Saravale", NOW(), NOW()),
            (38, "Satchinez","Barateaz", NOW(), NOW()),
            (38, "Satchinez","Hodoni", NOW(), NOW()),
            (38, "Secas","Cheches", NOW(), NOW()),
            (38, "Secas","Crivobara", NOW(), NOW()),
            (38, "Secas","Vizma", NOW(), NOW()),
            (38, "Stiuca","Dragomiresti", NOW(), NOW()),
            (38, "Stiuca","Olosag", NOW(), NOW()),
            (38, "Stiuca","Zgribesti", NOW(), NOW()),
            (38, "Teremia Mare","Nerau", NOW(), NOW()),
            (38, "Teremia Mare","Teremia Mica", NOW(), NOW()),
            (38, "Tomesti","Balosesti", NOW(), NOW()),
            (38, "Tomesti","Colonia Fabricii", NOW(), NOW()),
            (38, "Tomesti","Luncanii de Jos", NOW(), NOW()),
            (38, "Tomesti","Luncanii de Sus", NOW(), NOW()),
            (38, "Tomesti","Romanesti", NOW(), NOW()),
            (38, "Topolovatu Mare","Cralovat", NOW(), NOW()),
            (38, "Topolovatu Mare","Ictar-Budinti", NOW(), NOW()),
            (38, "Topolovatu Mare","Iosifalau", NOW(), NOW()),
            (38, "Topolovatu Mare","Sustra", NOW(), NOW()),
            (38, "Topolovatu Mare","Topolovatu Mic", NOW(), NOW()),
            (38, "Tormac","Cadar", NOW(), NOW()),
            (38, "Tormac","Sipet", NOW(), NOW()),
            (38, "Traian Vuia","Jupani", NOW(), NOW()),
            (38, "Traian Vuia","Sudrias", NOW(), NOW()),
            (38, "Traian Vuia","Surducu Mic", NOW(), NOW()),
            (38, "Traian Vuia","Susani", NOW(), NOW()),
            (38, "Traian Vuia","Saceni", NOW(), NOW()),
            (38, "Uivar","Iohanisfeld", NOW(), NOW()),
            (38, "Uivar","Otelec", NOW(), NOW()),
            (38, "Uivar","Pustinis", NOW(), NOW()),
            (38, "Uivar","Rauti", NOW(), NOW()),
            (38, "Uivar","Sanmartinu Maghiar", NOW(), NOW()),
            (38, "Varias","Gelu", NOW(), NOW()),
            (38, "Varias","Sanpetru Mic", NOW(), NOW()),
            (38, "Victor Vlad Delamarina","Herendesti", NOW(), NOW()),
            (38, "Victor Vlad Delamarina","Honorici", NOW(), NOW()),
            (38, "Victor Vlad Delamarina","Petroasa Mare", NOW(), NOW()),
            (38, "Victor Vlad Delamarina","Pini", NOW(), NOW()),
            (38, "Victor Vlad Delamarina","Padureni", NOW(), NOW()),
            (38, "Victor Vlad Delamarina","Visag", NOW(), NOW()),
            (38, "Voiteg","Folea", NOW(), NOW())
        ;';
        DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=38;';
        DB::connection()->getPdo()->exec($sql);
    }
}
