<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForBR extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql='INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (10, "","Bertestii de Jos", NOW(), NOW()),
            (10, "","Bordei Verde", NOW(), NOW()),
            (10, "","Braila", NOW(), NOW()),
            (10, "","Baraganul", NOW(), NOW()),
            (10, "","Cazasu", NOW(), NOW()),
            (10, "","Chiscani", NOW(), NOW()),
            (10, "","Ciocile", NOW(), NOW()),
            (10, "","Ciresu", NOW(), NOW()),
            (10, "","Dudesti", NOW(), NOW()),
            (10, "","Frecatei", NOW(), NOW()),
            (10, "","Faurei", NOW(), NOW()),
            (10, "","Galbenu", NOW(), NOW()),
            (10, "","Gemenele", NOW(), NOW()),
            (10, "","Gradistea", NOW(), NOW()),
            (10, "","Gropeni", NOW(), NOW()),
            (10, "","Ianca", NOW(), NOW()),
            (10, "","Jirlau", NOW(), NOW()),
            (10, "","Mircea Voda", NOW(), NOW()),
            (10, "","Movila Miresii", NOW(), NOW()),
            (10, "","Marasu", NOW(), NOW()),
            (10, "","Maxineni", NOW(), NOW()),
            (10, "","Racovita", NOW(), NOW()),
            (10, "","Romanu", NOW(), NOW()),
            (10, "","Rosiori", NOW(), NOW()),
            (10, "","Ramnicelu", NOW(), NOW()),
            (10, "","Salcia Tudor", NOW(), NOW()),
            (10, "","Scortaru Nou", NOW(), NOW()),
            (10, "","Silistea", NOW(), NOW()),
            (10, "","Stancuta", NOW(), NOW()),
            (10, "","Surdila-Greci", NOW(), NOW()),
            (10, "","Surdila-Gaiseanca", NOW(), NOW()),
            (10, "","Tichilesti", NOW(), NOW()),
            (10, "","Traian", NOW(), NOW()),
            (10, "","Tudor Vladimirescu", NOW(), NOW()),
            (10, "","Tufesti", NOW(), NOW()),
            (10, "","Ulmu", NOW(), NOW()),
            (10, "","Unirea", NOW(), NOW()),
            (10, "","Victoria", NOW(), NOW()),
            (10, "","Viziru", NOW(), NOW()),
            (10, "","Visani", NOW(), NOW()),
            (10, "","Vadeni", NOW(), NOW()),
            (10, "","Zavoaia", NOW(), NOW()),
            (10, "","Insuratei", NOW(), NOW()),
            (10, "","Sutesti", NOW(), NOW()),
            (10, "Bertestii De Jos","Bertestii de Sus", NOW(), NOW()),
            (10, "Bertestii De Jos","Gura Calmatui", NOW(), NOW()),
            (10, "Bertestii De Jos","Gura Garlutei", NOW(), NOW()),
            (10, "Bertestii De Jos","Nicolesti", NOW(), NOW()),
            (10, "Bertestii De Jos","Spiru Haret", NOW(), NOW()),
            (10, "Bordei Verde","Constantin Gabrielescu", NOW(), NOW()),
            (10, "Bordei Verde","Filiu", NOW(), NOW()),
            (10, "Bordei Verde","Liscoteanca", NOW(), NOW()),
            (10, "Chiscani","Lacu Sarat", NOW(), NOW()),
            (10, "Chiscani","Varsatura", NOW(), NOW()),
            (10, "Ciocile","Chichinetu", NOW(), NOW()),
            (10, "Ciocile","Chioibasesti", NOW(), NOW()),
            (10, "Ciocile","Odaieni", NOW(), NOW()),
            (10, "Ciresu","Batogu", NOW(), NOW()),
            (10, "Ciresu","Ionesti", NOW(), NOW()),
            (10, "Ciresu","Scarlatesti", NOW(), NOW()),
            (10, "Ciresu","Vultureni", NOW(), NOW()),
            (10, "Dudesti","Bumbacari", NOW(), NOW()),
            (10, "Dudesti","Tataru", NOW(), NOW()),
            (10, "Frecatei","Agaua", NOW(), NOW()),
            (10, "Frecatei","Cistia", NOW(), NOW()),
            (10, "Frecatei","Salcia", NOW(), NOW()),
            (10, "Frecatei","Stoienesti", NOW(), NOW()),
            (10, "Frecatei","Titcov", NOW(), NOW()),
            (10, "Galbenu","Drogu", NOW(), NOW()),
            (10, "Galbenu","Pantecani", NOW(), NOW()),
            (10, "Galbenu","Satuc", NOW(), NOW()),
            (10, "Galbenu","Zamfiresti", NOW(), NOW()),
            (10, "Gemenele","Gavani", NOW(), NOW()),
            (10, "Gradistea","Ibrianu", NOW(), NOW()),
            (10, "Gradistea","Maraloiu", NOW(), NOW()),
            (10, "Ianca","Berlesti", NOW(), NOW()),
            (10, "Ianca","Gara Ianca", NOW(), NOW()),
            (10, "Ianca","Oprisenesti", NOW(), NOW()),
            (10, "Ianca","Perisoru", NOW(), NOW()),
            (10, "Ianca","Plopu", NOW(), NOW()),
            (10, "Ianca","Tarlele Filiu", NOW(), NOW()),
            (10, "Insuratei","Lacu Rezii", NOW(), NOW()),
            (10, "Insuratei","Maru Rosu", NOW(), NOW()),
            (10, "Insuratei","Valea Calmatuiului", NOW(), NOW()),
            (10, "Jirlau","Bradeanca", NOW(), NOW()),
            (10, "Marasu","Bandoiu", NOW(), NOW()),
            (10, "Marasu","Magureni", NOW(), NOW()),
            (10, "Marasu","Nedeicu", NOW(), NOW()),
            (10, "Marasu","Plopi", NOW(), NOW()),
            (10, "Marasu","Tacau", NOW(), NOW()),
            (10, "Maxineni","Corbu Nou", NOW(), NOW()),
            (10, "Maxineni","Corbu Vechi", NOW(), NOW()),
            (10, "Maxineni","Latinu", NOW(), NOW()),
            (10, "Maxineni","Voinesti", NOW(), NOW()),
            (10, "Mircea Voda","Dedulesti", NOW(), NOW()),
            (10, "Movila Miresii","Esna", NOW(), NOW()),
            (10, "Movila Miresii","Tepes Voda", NOW(), NOW()),
            (10, "Racovita","Corbeni", NOW(), NOW()),
            (10, "Racovita","Custura", NOW(), NOW()),
            (10, "Ramnicelu","Boarca", NOW(), NOW()),
            (10, "Ramnicelu","Constantinesti", NOW(), NOW()),
            (10, "Ramnicelu","Mihail Kogalniceanu", NOW(), NOW()),
            (10, "Romanu","Oancea", NOW(), NOW()),
            (10, "Rosiori","Coltea", NOW(), NOW()),
            (10, "Rosiori","Florica", NOW(), NOW()),
            (10, "Rosiori","Pribeagu", NOW(), NOW()),
            (10, "Salcia Tudor","Ariciu", NOW(), NOW()),
            (10, "Salcia Tudor","Cuza Voda", NOW(), NOW()),
            (10, "Salcia Tudor","Gulianca", NOW(), NOW()),
            (10, "Salcia Tudor","Olaneasca", NOW(), NOW()),
            (10, "Scortaru Nou","Desirati", NOW(), NOW()),
            (10, "Scortaru Nou","Gurguieti", NOW(), NOW()),
            (10, "Scortaru Nou","Nicolae Balcescu", NOW(), NOW()),
            (10, "Scortaru Nou","Pitulati", NOW(), NOW()),
            (10, "Scortaru Nou","Sihleanu", NOW(), NOW()),
            (10, "Silistea","Cotu Lung", NOW(), NOW()),
            (10, "Silistea","Cotu Mihalea", NOW(), NOW()),
            (10, "Silistea","Muchea", NOW(), NOW()),
            (10, "Silistea","Martacesti", NOW(), NOW()),
            (10, "Silistea","Vamesu", NOW(), NOW()),
            (10, "Stancuta","Cuza Voda", NOW(), NOW()),
            (10, "Stancuta","Polizesti", NOW(), NOW()),
            (10, "Stancuta","Stanca", NOW(), NOW()),
            (10, "Surdila-Gaiseanca","Filipesti", NOW(), NOW()),
            (10, "Surdila-Greci","Bratesu Vechi", NOW(), NOW()),
            (10, "Surdila-Greci","Faurei Sat", NOW(), NOW()),
            (10, "Surdila-Greci","Horia", NOW(), NOW()),
            (10, "Sutesti","Mihail Kogalniceanu", NOW(), NOW()),
            (10, "Tichilesti","Albina", NOW(), NOW()),
            (10, "Traian","Caldarusa", NOW(), NOW()),
            (10, "Traian","Silistraru", NOW(), NOW()),
            (10, "Traian","Urleasca", NOW(), NOW()),
            (10, "Tudor Vladimirescu","Comaneasca", NOW(), NOW()),
            (10, "Tudor Vladimirescu","Scortaru Vechi", NOW(), NOW()),
            (10, "Ulmu","Jugureanu", NOW(), NOW()),
            (10, "Unirea","Morotesti", NOW(), NOW()),
            (10, "Unirea","Valea Canepii", NOW(), NOW()),
            (10, "Vadeni","Baldovinesti", NOW(), NOW()),
            (10, "Vadeni","Pietroiu", NOW(), NOW()),
            (10, "Victoria","Mihai Bravu", NOW(), NOW()),
            (10, "Visani","Caineni-Bai", NOW(), NOW()),
            (10, "Visani","Plasoiu", NOW(), NOW()),
            (10, "Viziru","Lanurile", NOW(), NOW()),
            (10, "Zavoaia","Dudescu", NOW(), NOW())
        ;';
        DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql="DELETE FROM localities WHERE county_id=10;";
        DB::connection()->getPdo()->exec($sql);
    }
}
