<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForBH extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (6, "","Abram", NOW(), NOW()),
            (6, "","Abramut", NOW(), NOW()),
            (6, "","Alesd", NOW(), NOW()),
            (6, "","Auseu", NOW(), NOW()),
            (6, "","Avram Iancu", NOW(), NOW()),
            (6, "","Astileu", NOW(), NOW()),
            (6, "","Balc", NOW(), NOW()),
            (6, "","Batar", NOW(), NOW()),
            (6, "","Beius", NOW(), NOW()),
            (6, "","Biharia", NOW(), NOW()),
            (6, "","Boianu Mare", NOW(), NOW()),
            (6, "","Borod", NOW(), NOW()),
            (6, "","Bors", NOW(), NOW()),
            (6, "","Bratca", NOW(), NOW()),
            (6, "","Brusturi", NOW(), NOW()),
            (6, "","Budureasa", NOW(), NOW()),
            (6, "","Buduslau", NOW(), NOW()),
            (6, "","Bulz", NOW(), NOW()),
            (6, "","Buntesti", NOW(), NOW()),
            (6, "","Cefa", NOW(), NOW()),
            (6, "","Ceica", NOW(), NOW()),
            (6, "","Cetariu", NOW(), NOW()),
            (6, "","Cherechiu", NOW(), NOW()),
            (6, "","Chislaz", NOW(), NOW()),
            (6, "","Ciuhoi", NOW(), NOW()),
            (6, "","Ciumeghiu", NOW(), NOW()),
            (6, "","Cociuba Mare", NOW(), NOW()),
            (6, "","Copacel", NOW(), NOW()),
            (6, "","Cristioru de Jos", NOW(), NOW()),
            (6, "","Curtuiseni", NOW(), NOW()),
            (6, "","Curatele", NOW(), NOW()),
            (6, "","Campani", NOW(), NOW()),
            (6, "","Cabesti", NOW(), NOW()),
            (6, "","Capalna", NOW(), NOW()),
            (6, "","Carpinet", NOW(), NOW()),
            (6, "","Derna", NOW(), NOW()),
            (6, "","Diosig", NOW(), NOW()),
            (6, "","Dobresti", NOW(), NOW()),
            (6, "","Dragesti", NOW(), NOW()),
            (6, "","Draganesti", NOW(), NOW()),
            (6, "","Finis", NOW(), NOW()),
            (6, "","Gepiu", NOW(), NOW()),
            (6, "","Girisu de Cris", NOW(), NOW()),
            (6, "","Hidiselu de Sus", NOW(), NOW()),
            (6, "","Holod", NOW(), NOW()),
            (6, "","Husasau de Tinca", NOW(), NOW()),
            (6, "","Ineu", NOW(), NOW()),
            (6, "","Lazuri de Beius", NOW(), NOW()),
            (6, "","Lugasu de Jos", NOW(), NOW()),
            (6, "","Lunca", NOW(), NOW()),
            (6, "","Lazareni", NOW(), NOW()),
            (6, "","Marghita", NOW(), NOW()),
            (6, "","Madaras", NOW(), NOW()),
            (6, "","Magesti", NOW(), NOW()),
            (6, "","Nojorid", NOW(), NOW()),
            (6, "","Nucet", NOW(), NOW()),
            (6, "","Olcea", NOW(), NOW()),
            (6, "","Oradea", NOW(), NOW()),
            (6, "","Osorhei", NOW(), NOW()),
            (6, "","Paleu", NOW(), NOW()),
            (6, "","Pietroasa", NOW(), NOW()),
            (6, "","Pocola", NOW(), NOW()),
            (6, "","Pomezeu", NOW(), NOW()),
            (6, "","Popesti", NOW(), NOW()),
            (6, "","Remetea", NOW(), NOW()),
            (6, "","Rieni", NOW(), NOW()),
            (6, "","Rosia", NOW(), NOW()),
            (6, "","Rosiori", NOW(), NOW()),
            (6, "","Rabagani", NOW(), NOW()),
            (6, "","Salonta", NOW(), NOW()),
            (6, "","Spinus", NOW(), NOW()),
            (6, "","Suplacu de Barcau", NOW(), NOW()),
            (6, "","Sambata", NOW(), NOW()),
            (6, "","Sanmartin", NOW(), NOW()),
            (6, "","Sannicolau Roman", NOW(), NOW()),
            (6, "","Santandrei", NOW(), NOW()),
            (6, "","Sarbi", NOW(), NOW()),
            (6, "","Sacueni", NOW(), NOW()),
            (6, "","Sacadat", NOW(), NOW()),
            (6, "","Salacea", NOW(), NOW()),
            (6, "","Salard", NOW(), NOW()),
            (6, "","Tarcea", NOW(), NOW()),
            (6, "","Tileagd", NOW(), NOW()),
            (6, "","Tinca", NOW(), NOW()),
            (6, "","Tulca", NOW(), NOW()),
            (6, "","Tamaseu", NOW(), NOW()),
            (6, "","Tarcaia", NOW(), NOW()),
            (6, "","Tauteu", NOW(), NOW()),
            (6, "","Uileacu de Beius", NOW(), NOW()),
            (6, "","Vadu Crisului", NOW(), NOW()),
            (6, "","Valea lui Mihai", NOW(), NOW()),
            (6, "","Vascau", NOW(), NOW()),
            (6, "","Viisoara", NOW(), NOW()),
            (6, "","Varciorog", NOW(), NOW()),
            (6, "","Simian", NOW(), NOW()),
            (6, "","Sinteu", NOW(), NOW()),
            (6, "","Soimi", NOW(), NOW()),
            (6, "","Stei", NOW(), NOW()),
            (6, "","Suncuius", NOW(), NOW()),
            (6, "","Tetchea", NOW(), NOW()),
            (6, "Abram","Cohani", NOW(), NOW()),
            (6, "Abram","Dijir", NOW(), NOW()),
            (6, "Abram","Iteu", NOW(), NOW()),
            (6, "Abram","Iteu Nou", NOW(), NOW()),
            (6, "Abram","Margine", NOW(), NOW()),
            (6, "Abram","Satu Barba", NOW(), NOW()),
            (6, "Abram","Suiug", NOW(), NOW()),
            (6, "Abramut","Crestur", NOW(), NOW()),
            (6, "Abramut","Fancica", NOW(), NOW()),
            (6, "Abramut","Petreu", NOW(), NOW()),
            (6, "Alesd","Pestis", NOW(), NOW()),
            (6, "Alesd","Padurea Neagra", NOW(), NOW()),
            (6, "Alesd","Tinaud", NOW(), NOW()),
            (6, "Astileu","Chistag", NOW(), NOW()),
            (6, "Astileu","Calatea", NOW(), NOW()),
            (6, "Astileu","Pestere", NOW(), NOW()),
            (6, "Auseu","Cacuciu Vechi", NOW(), NOW()),
            (6, "Auseu","Codrisoru", NOW(), NOW()),
            (6, "Auseu","Gheghie", NOW(), NOW()),
            (6, "Auseu","Grosi", NOW(), NOW()),
            (6, "Auseu","Luncsoara", NOW(), NOW()),
            (6, "Avram Iancu","Ant", NOW(), NOW()),
            (6, "Avram Iancu","Tamasda", NOW(), NOW()),
            (6, "Balc","Almasu Mare", NOW(), NOW()),
            (6, "Balc","Almasu Mic", NOW(), NOW()),
            (6, "Balc","Ghida", NOW(), NOW()),
            (6, "Balc","Saldabagiu de Barcau", NOW(), NOW()),
            (6, "Batar","Arpasel", NOW(), NOW()),
            (6, "Batar","Talpos", NOW(), NOW()),
            (6, "Batar","Taut", NOW(), NOW()),
            (6, "Beius","Delani", NOW(), NOW()),
            (6, "Biharia","Cauaceu", NOW(), NOW()),
            (6, "Boianu Mare","Corboaia", NOW(), NOW()),
            (6, "Boianu Mare","Huta", NOW(), NOW()),
            (6, "Boianu Mare","Pagaia", NOW(), NOW()),
            (6, "Boianu Mare","Rugea", NOW(), NOW()),
            (6, "Borod","Borozel", NOW(), NOW()),
            (6, "Borod","Cetea", NOW(), NOW()),
            (6, "Borod","Cornitel", NOW(), NOW()),
            (6, "Borod","Valea Mare de Cris", NOW(), NOW()),
            (6, "Borod","Serani", NOW(), NOW()),
            (6, "Bors","Santaul Mare", NOW(), NOW()),
            (6, "Bors","Santaul Mic", NOW(), NOW()),
            (6, "Bors","Santion", NOW(), NOW()),
            (6, "Bratca","Beznea", NOW(), NOW()),
            (6, "Bratca","Damis", NOW(), NOW()),
            (6, "Bratca","Lorau", NOW(), NOW()),
            (6, "Bratca","Ponoara", NOW(), NOW()),
            (6, "Bratca","Valea Crisului", NOW(), NOW()),
            (6, "Brusturi","Cuiesd", NOW(), NOW()),
            (6, "Brusturi","Loranta", NOW(), NOW()),
            (6, "Brusturi","Orvisele", NOW(), NOW()),
            (6, "Brusturi","Picleu", NOW(), NOW()),
            (6, "Brusturi","Paulesti", NOW(), NOW()),
            (6, "Brusturi","Varasau", NOW(), NOW()),
            (6, "Brusturi","Tiganestii de Cris", NOW(), NOW()),
            (6, "Budureasa","Burda", NOW(), NOW()),
            (6, "Budureasa","Saca", NOW(), NOW()),
            (6, "Budureasa","Saliste de Beius", NOW(), NOW()),
            (6, "Budureasa","Teleac", NOW(), NOW()),
            (6, "Buduslau","Albis", NOW(), NOW()),
            (6, "Bulz","Munteni", NOW(), NOW()),
            (6, "Bulz","Remeti", NOW(), NOW()),
            (6, "Buntesti","Bradet", NOW(), NOW()),
            (6, "Buntesti","Dumbravani", NOW(), NOW()),
            (6, "Buntesti","Ferice", NOW(), NOW()),
            (6, "Buntesti","Lelesti", NOW(), NOW()),
            (6, "Buntesti","Poienii de Jos", NOW(), NOW()),
            (6, "Buntesti","Poienii de Sus", NOW(), NOW()),
            (6, "Buntesti","Stancesti", NOW(), NOW()),
            (6, "Buntesti","Saud", NOW(), NOW()),
            (6, "Cabesti","Goila", NOW(), NOW()),
            (6, "Cabesti","Gurbesti", NOW(), NOW()),
            (6, "Cabesti","Josani", NOW(), NOW()),
            (6, "Cabesti","Sohodol", NOW(), NOW()),
            (6, "Campani","Fanate", NOW(), NOW()),
            (6, "Campani","Harsesti", NOW(), NOW()),
            (6, "Campani","Sighistel", NOW(), NOW()),
            (6, "Campani","Valea de Sus", NOW(), NOW()),
            (6, "Capalna","Ginta", NOW(), NOW()),
            (6, "Capalna","Rohani", NOW(), NOW()),
            (6, "Capalna","Suplacu de Tinca", NOW(), NOW()),
            (6, "Capalna","Saldabagiu Mic", NOW(), NOW()),
            (6, "Carpinet","Calugari", NOW(), NOW()),
            (6, "Carpinet","Izbuc", NOW(), NOW()),
            (6, "Carpinet","Leheceni", NOW(), NOW()),
            (6, "Cefa","Ateas", NOW(), NOW()),
            (6, "Cefa","Inand", NOW(), NOW()),
            (6, "Ceica","Bucium", NOW(), NOW()),
            (6, "Ceica","Ceisoara", NOW(), NOW()),
            (6, "Ceica","Corbesti", NOW(), NOW()),
            (6, "Ceica","Cotiglet", NOW(), NOW()),
            (6, "Ceica","Dusesti", NOW(), NOW()),
            (6, "Ceica","Incesti", NOW(), NOW()),
            (6, "Cetariu","Tautelec", NOW(), NOW()),
            (6, "Cetariu","Sisterea", NOW(), NOW()),
            (6, "Cetariu","Susturogi", NOW(), NOW()),
            (6, "Cherechiu","Chesereu", NOW(), NOW()),
            (6, "Cherechiu","Targusor", NOW(), NOW()),
            (6, "Chislaz","Chiraleu", NOW(), NOW()),
            (6, "Chislaz","Haucesti", NOW(), NOW()),
            (6, "Chislaz","Misca", NOW(), NOW()),
            (6, "Chislaz","Poclusa de Barcau", NOW(), NOW()),
            (6, "Chislaz","Sanlazar", NOW(), NOW()),
            (6, "Chislaz","Sarsig", NOW(), NOW()),
            (6, "Ciuhoi","Cenalos", NOW(), NOW()),
            (6, "Ciuhoi","Sfarnas", NOW(), NOW()),
            (6, "Ciuhoi","Saniob", NOW(), NOW()),
            (6, "Ciumeghiu","Boiu", NOW(), NOW()),
            (6, "Ciumeghiu","Ghiorac", NOW(), NOW()),
            (6, "Cociuba Mare","Chesa", NOW(), NOW()),
            (6, "Cociuba Mare","Carasau", NOW(), NOW()),
            (6, "Cociuba Mare","Petid", NOW(), NOW()),
            (6, "Copacel","Bucuroaia", NOW(), NOW()),
            (6, "Copacel","Chijic", NOW(), NOW()),
            (6, "Copacel","Poiana Tasad", NOW(), NOW()),
            (6, "Copacel","Surduc", NOW(), NOW()),
            (6, "Copacel","Sarand", NOW(), NOW()),
            (6, "Cristioru De Jos","Balc", NOW(), NOW()),
            (6, "Cristioru De Jos","Cristioru de Sus", NOW(), NOW()),
            (6, "Cristioru De Jos","Poiana", NOW(), NOW()),
            (6, "Cristioru De Jos","Saliste de Vascau", NOW(), NOW()),
            (6, "Curatele","Beiusele", NOW(), NOW()),
            (6, "Curatele","Cresuia", NOW(), NOW()),
            (6, "Curatele","Nimaiesti", NOW(), NOW()),
            (6, "Curatele","Pocioveliste", NOW(), NOW()),
            (6, "Curtuiseni","Vasad", NOW(), NOW()),
            (6, "Derna","Dernisoara", NOW(), NOW()),
            (6, "Derna","Sacalasau", NOW(), NOW()),
            (6, "Derna","Sacalasau Nou", NOW(), NOW()),
            (6, "Derna","Tria", NOW(), NOW()),
            (6, "Diosig","Ianca", NOW(), NOW()),
            (6, "Dobresti","Cornisesti", NOW(), NOW()),
            (6, "Dobresti","Crancesti", NOW(), NOW()),
            (6, "Dobresti","Hidisel", NOW(), NOW()),
            (6, "Dobresti","Luncasprie", NOW(), NOW()),
            (6, "Dobresti","Racas", NOW(), NOW()),
            (6, "Dobresti","Topa de Jos", NOW(), NOW()),
            (6, "Dobresti","Topa de Sus", NOW(), NOW()),
            (6, "Draganesti","Belejeni", NOW(), NOW()),
            (6, "Draganesti","Gradinari", NOW(), NOW()),
            (6, "Draganesti","Livada Beiusului", NOW(), NOW()),
            (6, "Draganesti","Mizies", NOW(), NOW()),
            (6, "Draganesti","Pantasesti", NOW(), NOW()),
            (6, "Draganesti","Talpe", NOW(), NOW()),
            (6, "Draganesti","Sebis", NOW(), NOW()),
            (6, "Draganesti","Tiganestii de Beius", NOW(), NOW()),
            (6, "Dragesti","Dicanesti", NOW(), NOW()),
            (6, "Dragesti","Stracos", NOW(), NOW()),
            (6, "Dragesti","Topesti", NOW(), NOW()),
            (6, "Dragesti","Tasad", NOW(), NOW()),
            (6, "Drăgănești","Pacalesti", NOW(), NOW()),
            (6, "Finis","Brusturi", NOW(), NOW()),
            (6, "Finis","Fizis", NOW(), NOW()),
            (6, "Finis","Ioanis", NOW(), NOW()),
            (6, "Finis","Suncuis", NOW(), NOW()),
            (6, "Gepiu","Bicaci", NOW(), NOW()),
            (6, "Girisu De Cris","Cheresig", NOW(), NOW()),
            (6, "Girisu De Cris","Toboliu", NOW(), NOW()),
            (6, "Girisu De Cris","Tarian", NOW(), NOW()),
            (6, "Hidiselu De Sus","Hidiselu de Jos", NOW(), NOW()),
            (6, "Hidiselu De Sus","Mierlau", NOW(), NOW()),
            (6, "Hidiselu De Sus","Santelec", NOW(), NOW()),
            (6, "Hidiselu De Sus","Sumugiu", NOW(), NOW()),
            (6, "Holod","Dumbrava", NOW(), NOW()),
            (6, "Holod","Dumbravita", NOW(), NOW()),
            (6, "Holod","Forosig", NOW(), NOW()),
            (6, "Holod","Hodis", NOW(), NOW()),
            (6, "Holod","Lupoaia", NOW(), NOW()),
            (6, "Holod","Valea Mare de Codru", NOW(), NOW()),
            (6, "Holod","Vintere", NOW(), NOW()),
            (6, "Husasau De Tinca","Fonau", NOW(), NOW()),
            (6, "Husasau De Tinca","Miersig", NOW(), NOW()),
            (6, "Husasau De Tinca","Osand", NOW(), NOW()),
            (6, "Husasau De Tinca","Sititelec", NOW(), NOW()),
            (6, "Ineu","Botean", NOW(), NOW()),
            (6, "Ineu","Husasau de Cris", NOW(), NOW()),
            (6, "Lazareni","Bicacel", NOW(), NOW()),
            (6, "Lazareni","Calea Mare", NOW(), NOW()),
            (6, "Lazareni","Carandeni", NOW(), NOW()),
            (6, "Lazareni","Caranzel", NOW(), NOW()),
            (6, "Lazareni","Gepis", NOW(), NOW()),
            (6, "Lazareni","Gruilung", NOW(), NOW()),
            (6, "Lazareni","Miheleu", NOW(), NOW()),
            (6, "Lazuri De Beius","Baleni", NOW(), NOW()),
            (6, "Lazuri De Beius","Cusuius", NOW(), NOW()),
            (6, "Lazuri De Beius","Hinchiris", NOW(), NOW()),
            (6, "Lugasu De Jos","Lugasu de Sus", NOW(), NOW()),
            (6, "Lugasu De Jos","Urvind", NOW(), NOW()),
            (6, "Lunca","Briheni", NOW(), NOW()),
            (6, "Lunca","Hotarel", NOW(), NOW()),
            (6, "Lunca","Seghiste", NOW(), NOW()),
            (6, "Lunca","Sarbesti", NOW(), NOW()),
            (6, "Lunca","Sustiu", NOW(), NOW()),
            (6, "Madaras","Homorog", NOW(), NOW()),
            (6, "Madaras","Ianosda", NOW(), NOW()),
            (6, "Madaras","Martihaz", NOW(), NOW()),
            (6, "Magesti","Butani", NOW(), NOW()),
            (6, "Magesti","Cacuciu Nou", NOW(), NOW()),
            (6, "Magesti","Dobricionesti", NOW(), NOW()),
            (6, "Magesti","Galaseni", NOW(), NOW()),
            (6, "Magesti","Josani", NOW(), NOW()),
            (6, "Magesti","Ortiteag", NOW(), NOW()),
            (6, "Marghita","Chet", NOW(), NOW()),
            (6, "Marghita","Ghenetea", NOW(), NOW()),
            (6, "Nojorid","Apateu", NOW(), NOW()),
            (6, "Nojorid","Chisirid", NOW(), NOW()),
            (6, "Nojorid","Les", NOW(), NOW()),
            (6, "Nojorid","Livada de Bihor", NOW(), NOW()),
            (6, "Nojorid","Pausa", NOW(), NOW()),
            (6, "Nojorid","Sauaieu", NOW(), NOW()),
            (6, "Nucet","Baita", NOW(), NOW()),
            (6, "Nucet","Baita-Plai", NOW(), NOW()),
            (6, "Olcea","Calacea", NOW(), NOW()),
            (6, "Olcea","Hodisel", NOW(), NOW()),
            (6, "Olcea","Ucuris", NOW(), NOW()),
            (6, "Osorhei","Alparea", NOW(), NOW()),
            (6, "Osorhei","Cheriu", NOW(), NOW()),
            (6, "Osorhei","Felcheriu", NOW(), NOW()),
            (6, "Osorhei","Fughiu", NOW(), NOW()),
            (6, "Paleu","Saldabagiu de Munte", NOW(), NOW()),
            (6, "Paleu","Uileacu de Munte", NOW(), NOW()),
            (6, "Pietroasa","Chiscau", NOW(), NOW()),
            (6, "Pietroasa","Cociuba Mica", NOW(), NOW()),
            (6, "Pietroasa","Giulesti", NOW(), NOW()),
            (6, "Pietroasa","Gurani", NOW(), NOW()),
            (6, "Pietroasa","Motesti", NOW(), NOW()),
            (6, "Pietroasa","Magura", NOW(), NOW()),
            (6, "Pocola","Feneris", NOW(), NOW()),
            (6, "Pocola","Petrani", NOW(), NOW()),
            (6, "Pocola","Poietari", NOW(), NOW()),
            (6, "Pocola","Sanmartin de Beius", NOW(), NOW()),
            (6, "Pomezeu","Cosdeni", NOW(), NOW()),
            (6, "Pomezeu","Campani de Pomezeu", NOW(), NOW()),
            (6, "Pomezeu","Hidis", NOW(), NOW()),
            (6, "Pomezeu","Lacu Sarat", NOW(), NOW()),
            (6, "Pomezeu","Sitani", NOW(), NOW()),
            (6, "Pomezeu","Spinus de Pomezeu", NOW(), NOW()),
            (6, "Pomezeu","Valani de Pomezeu", NOW(), NOW()),
            (6, "Popesti","Bistra", NOW(), NOW()),
            (6, "Popesti","Budoi", NOW(), NOW()),
            (6, "Popesti","Cuzap", NOW(), NOW()),
            (6, "Popesti","Varviz", NOW(), NOW()),
            (6, "Popesti","Voivozi", NOW(), NOW()),
            (6, "Popesti","Varzari", NOW(), NOW()),
            (6, "Rabagani","Albesti", NOW(), NOW()),
            (6, "Rabagani","Bratesti", NOW(), NOW()),
            (6, "Rabagani","Saliste de Pomezeu", NOW(), NOW()),
            (6, "Rabagani","Saucani", NOW(), NOW()),
            (6, "Rabagani","Varaseni", NOW(), NOW()),
            (6, "Remetea","Dragoteni", NOW(), NOW()),
            (6, "Remetea","Meziad", NOW(), NOW()),
            (6, "Remetea","Petreasa", NOW(), NOW()),
            (6, "Remetea","Soimus", NOW(), NOW()),
            (6, "Rieni","Cucuceni", NOW(), NOW()),
            (6, "Rieni","Ghighiseni", NOW(), NOW()),
            (6, "Rieni","Petrileni", NOW(), NOW()),
            (6, "Rieni","Sudrigiu", NOW(), NOW()),
            (6, "Rieni","Valea de Jos", NOW(), NOW()),
            (6, "Rosia","Lazuri", NOW(), NOW()),
            (6, "Rosiori","Mihai Bravu", NOW(), NOW()),
            (6, "Rosiori","Vaida", NOW(), NOW()),
            (6, "Sacadat","Borsa", NOW(), NOW()),
            (6, "Sacadat","Sabolciu", NOW(), NOW()),
            (6, "Sacueni","Cadea", NOW(), NOW()),
            (6, "Sacueni","Ciocaia", NOW(), NOW()),
            (6, "Sacueni","Cubulcut", NOW(), NOW()),
            (6, "Sacueni","Olosig", NOW(), NOW()),
            (6, "Sacueni","Sannicolau de Munte", NOW(), NOW()),
            (6, "Salacea","Otomani", NOW(), NOW()),
            (6, "Salard","Hodos", NOW(), NOW()),
            (6, "Salard","Santimreu", NOW(), NOW()),
            (6, "Sambata","Copaceni", NOW(), NOW()),
            (6, "Sambata","Ogesti", NOW(), NOW()),
            (6, "Sambata","Rogoz", NOW(), NOW()),
            (6, "Sambata","Rotaresti", NOW(), NOW()),
            (6, "Sambata","Zavoiu", NOW(), NOW()),
            (6, "Sanmartin","Betfia", NOW(), NOW()),
            (6, "Sanmartin","Baile Felix", NOW(), NOW()),
            (6, "Sanmartin","Cihei", NOW(), NOW()),
            (6, "Sanmartin","Cordau", NOW(), NOW()),
            (6, "Sanmartin","Haieu", NOW(), NOW()),
            (6, "Sanmartin","Rontau", NOW(), NOW()),
            (6, "Sannicolau Roman","Berechiu", NOW(), NOW()),
            (6, "Sannicolau Roman","Roit", NOW(), NOW()),
            (6, "Santandrei","Palota", NOW(), NOW()),
            (6, "Sarbi","Almasu Mic", NOW(), NOW()),
            (6, "Sarbi","Burzuc", NOW(), NOW()),
            (6, "Sarbi","Chioag", NOW(), NOW()),
            (6, "Sarbi","Fegernic", NOW(), NOW()),
            (6, "Sarbi","Fegernicu Nou", NOW(), NOW()),
            (6, "Sarbi","Sarcau", NOW(), NOW()),
            (6, "Simian","Voivozi", NOW(), NOW()),
            (6, "Simian","Silindru", NOW(), NOW()),
            (6, "Sinteu","Huta Voivozi", NOW(), NOW()),
            (6, "Sinteu","Socet", NOW(), NOW()),
            (6, "Sinteu","Valea Tarnei", NOW(), NOW()),
            (6, "Soimi","Borz", NOW(), NOW()),
            (6, "Soimi","Codru", NOW(), NOW()),
            (6, "Soimi","Dumbravita de Codru", NOW(), NOW()),
            (6, "Soimi","Poclusa de Beius", NOW(), NOW()),
            (6, "Soimi","Sannicolau de Beius", NOW(), NOW()),
            (6, "Soimi","Ursad", NOW(), NOW()),
            (6, "Soimi","Urvis de Beius", NOW(), NOW()),
            (6, "Spinus","Ciulesti", NOW(), NOW()),
            (6, "Spinus","Gurbesti", NOW(), NOW()),
            (6, "Spinus","Nadar", NOW(), NOW()),
            (6, "Spinus","Saliste", NOW(), NOW()),
            (6, "Suncuius","Balnaca", NOW(), NOW()),
            (6, "Suncuius","Balnaca-Grosi", NOW(), NOW()),
            (6, "Suncuius","Zece Hotare", NOW(), NOW()),
            (6, "Suplacu De Barcau","Borumlaca", NOW(), NOW()),
            (6, "Suplacu De Barcau","Dolea", NOW(), NOW()),
            (6, "Suplacu De Barcau","Foglas", NOW(), NOW()),
            (6, "Suplacu De Barcau","Valea Cerului", NOW(), NOW()),
            (6, "Suplacu De Barcau","Valcelele", NOW(), NOW()),
            (6, "Tamaseu","Niuved", NOW(), NOW()),
            (6, "Tamaseu","Parhida", NOW(), NOW()),
            (6, "Tamaseu","Satu Nou", NOW(), NOW()),
            (6, "Tarcaia","Mierag", NOW(), NOW()),
            (6, "Tarcaia","Totoreni", NOW(), NOW()),
            (6, "Tarcaia","Tarcaita", NOW(), NOW()),
            (6, "Tarcea","Adoni", NOW(), NOW()),
            (6, "Tarcea","Galospetreu", NOW(), NOW()),
            (6, "Tauteu","Bogei", NOW(), NOW()),
            (6, "Tauteu","Chiribis", NOW(), NOW()),
            (6, "Tauteu","Ciutelec", NOW(), NOW()),
            (6, "Tauteu","Poiana", NOW(), NOW()),
            (6, "Tetchea","Hotar", NOW(), NOW()),
            (6, "Tetchea","Subpiatra", NOW(), NOW()),
            (6, "Tetchea","Telechiu", NOW(), NOW()),
            (6, "Tileagd","Balaia", NOW(), NOW()),
            (6, "Tileagd","Calatani", NOW(), NOW()),
            (6, "Tileagd","Posoloaca", NOW(), NOW()),
            (6, "Tileagd","Tilecus", NOW(), NOW()),
            (6, "Tileagd","Uileacu de Cris", NOW(), NOW()),
            (6, "Tinca","Belfir", NOW(), NOW()),
            (6, "Tinca","Girisu Negru", NOW(), NOW()),
            (6, "Tinca","Gurbediu", NOW(), NOW()),
            (6, "Tinca","Rapa", NOW(), NOW()),
            (6, "Tulca","Cauasd", NOW(), NOW()),
            (6, "Uileacu De Beius","Forau", NOW(), NOW()),
            (6, "Uileacu De Beius","Prisaca", NOW(), NOW()),
            (6, "Uileacu De Beius","Valanii de Beius", NOW(), NOW()),
            (6, "Vadu Crisului","Birtin", NOW(), NOW()),
            (6, "Vadu Crisului","Tomnatic", NOW(), NOW()),
            (6, "Vadu Crisului","Topa de Cris", NOW(), NOW()),
            (6, "Varciorog","Fasca", NOW(), NOW()),
            (6, "Varciorog","Surducel", NOW(), NOW()),
            (6, "Varciorog","Serghis", NOW(), NOW()),
            (6, "Vascau","Colesti", NOW(), NOW()),
            (6, "Vascau","Camp", NOW(), NOW()),
            (6, "Vascau","Camp-Moti", NOW(), NOW()),
            (6, "Vascau","Varzarii de Jos", NOW(), NOW()),
            (6, "Vascau","Varzarii de Sus", NOW(), NOW()),
            (6, "Viisoara","Izvoarele", NOW(), NOW()),
            (6, "Viisoara","Padureni", NOW(), NOW()),
            (6, "Viisoara","Reghea", NOW(), NOW())
        ;';
        if (config('app.env') !== 'testing') {
            DB::connection()->getPdo()->exec($sql);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=6;';
        DB::connection()->getPdo()->exec($sql);
    }
}
