<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForIS extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (24, "","Alexandru I. Cuza", NOW(), NOW()),
            (24, "","Andrieseni", NOW(), NOW()),
            (24, "","Aroneanu", NOW(), NOW()),
            (24, "","Bals", NOW(), NOW()),
            (24, "","Belcesti", NOW(), NOW()),
            (24, "","Bivolari", NOW(), NOW()),
            (24, "","Braesti", NOW(), NOW()),
            (24, "","Butea", NOW(), NOW()),
            (24, "","Barnova", NOW(), NOW()),
            (24, "","Baltati", NOW(), NOW()),
            (24, "","Ceplenita", NOW(), NOW()),
            (24, "","Ciortesti", NOW(), NOW()),
            (24, "","Ciurea", NOW(), NOW()),
            (24, "","Coarnele Caprei", NOW(), NOW()),
            (24, "","Comarna", NOW(), NOW()),
            (24, "","Costesti", NOW(), NOW()),
            (24, "","Costuleni", NOW(), NOW()),
            (24, "","Cotnari", NOW(), NOW()),
            (24, "","Cozmesti", NOW(), NOW()),
            (24, "","Cristesti", NOW(), NOW()),
            (24, "","Cucuteni", NOW(), NOW()),
            (24, "","Dagata", NOW(), NOW()),
            (24, "","Deleni", NOW(), NOW()),
            (24, "","Dobrovat", NOW(), NOW()),
            (24, "","Dolhesti", NOW(), NOW()),
            (24, "","Draguseni", NOW(), NOW()),
            (24, "","Dumesti", NOW(), NOW()),
            (24, "","Erbiceni", NOW(), NOW()),
            (24, "","Focuri", NOW(), NOW()),
            (24, "","Golaiesti", NOW(), NOW()),
            (24, "","Gorban", NOW(), NOW()),
            (24, "","Grajduri", NOW(), NOW()),
            (24, "","Gropnita", NOW(), NOW()),
            (24, "","Grozesti", NOW(), NOW()),
            (24, "","Helesteni", NOW(), NOW()),
            (24, "","Holboca", NOW(), NOW()),
            (24, "","Horlesti", NOW(), NOW()),
            (24, "","Harlau", NOW(), NOW()),
            (24, "","Halaucesti", NOW(), NOW()),
            (24, "","Iasi", NOW(), NOW()),
            (24, "","Ipatele", NOW(), NOW()),
            (24, "","Lespezi", NOW(), NOW()),
            (24, "","Letcani", NOW(), NOW()),
            (24, "","Lungani", NOW(), NOW()),
            (24, "","Mircesti", NOW(), NOW()),
            (24, "","Mironeasa", NOW(), NOW()),
            (24, "","Miroslava", NOW(), NOW()),
            (24, "","Miroslovesti", NOW(), NOW()),
            (24, "","Mogosesti", NOW(), NOW()),
            (24, "","Mogosesti-Siret", NOW(), NOW()),
            (24, "","Movileni", NOW(), NOW()),
            (24, "","Mosna", NOW(), NOW()),
            (24, "","Motca", NOW(), NOW()),
            (24, "","Madarjac", NOW(), NOW()),
            (24, "","Oteleni", NOW(), NOW()),
            (24, "","Pascani", NOW(), NOW()),
            (24, "","Plugari", NOW(), NOW()),
            (24, "","Podu Iloaiei", NOW(), NOW()),
            (24, "","Popesti", NOW(), NOW()),
            (24, "","Popricani", NOW(), NOW()),
            (24, "","Prisacani", NOW(), NOW()),
            (24, "","Probota", NOW(), NOW()),
            (24, "","Rediu", NOW(), NOW()),
            (24, "","Romanesti", NOW(), NOW()),
            (24, "","Ruginoasa", NOW(), NOW()),
            (24, "","Rachiteni", NOW(), NOW()),
            (24, "","Raducaneni", NOW(), NOW()),
            (24, "","Schitu Duca", NOW(), NOW()),
            (24, "","Scobinti", NOW(), NOW()),
            (24, "","Scanteia", NOW(), NOW()),
            (24, "","Sinesti", NOW(), NOW()),
            (24, "","Siretel", NOW(), NOW()),
            (24, "","Stolniceni-Prajescu", NOW(), NOW()),
            (24, "","Strunga", NOW(), NOW()),
            (24, "","Tansa", NOW(), NOW()),
            (24, "","Todiresti", NOW(), NOW()),
            (24, "","Tomesti", NOW(), NOW()),
            (24, "","Trifesti", NOW(), NOW()),
            (24, "","Targu Frumos", NOW(), NOW()),
            (24, "","Tatarusi", NOW(), NOW()),
            (24, "","Ungheni", NOW(), NOW()),
            (24, "","Valea Lupului", NOW(), NOW()),
            (24, "","Valea Seaca", NOW(), NOW()),
            (24, "","Victoria", NOW(), NOW()),
            (24, "","Vladeni", NOW(), NOW()),
            (24, "","Voinesti", NOW(), NOW()),
            (24, "","Vanatori", NOW(), NOW()),
            (24, "","Scheia", NOW(), NOW()),
            (24, "","Sipote", NOW(), NOW()),
            (24, "","Tibana", NOW(), NOW()),
            (24, "","Tibanesti", NOW(), NOW()),
            (24, "","Tiganasi", NOW(), NOW()),
            (24, "","Tutora", NOW(), NOW()),
            (24, "Alexandru I. Cuza","Kogalniceni", NOW(), NOW()),
            (24, "Alexandru I. Cuza","Scheia", NOW(), NOW()),
            (24, "Alexandru I. Cuza","Volintiresti", NOW(), NOW()),
            (24, "Andrieseni","Buhaeni", NOW(), NOW()),
            (24, "Andrieseni","Draganesti", NOW(), NOW()),
            (24, "Andrieseni","Fantanele", NOW(), NOW()),
            (24, "Andrieseni","Glavanesti", NOW(), NOW()),
            (24, "Andrieseni","Iepureni", NOW(), NOW()),
            (24, "Andrieseni","Spineni", NOW(), NOW()),
            (24, "Aroneanu","Dorobant", NOW(), NOW()),
            (24, "Aroneanu","Rediu Aldei", NOW(), NOW()),
            (24, "Aroneanu","Sorogani", NOW(), NOW()),
            (24, "Bals","Boureni", NOW(), NOW()),
            (24, "Baltati","Cotargaci", NOW(), NOW()),
            (24, "Baltati","Filiasi", NOW(), NOW()),
            (24, "Baltati","Madarjesti", NOW(), NOW()),
            (24, "Baltati","Podisu", NOW(), NOW()),
            (24, "Baltati","Sarca", NOW(), NOW()),
            (24, "Baltati","Valea Oilor", NOW(), NOW()),
            (24, "Barnova","Cercu", NOW(), NOW()),
            (24, "Barnova","Pietraria", NOW(), NOW()),
            (24, "Barnova","Paun", NOW(), NOW()),
            (24, "Barnova","Todirel", NOW(), NOW()),
            (24, "Barnova","Visan", NOW(), NOW()),
            (24, "Belcesti","Liteni", NOW(), NOW()),
            (24, "Belcesti","Munteni", NOW(), NOW()),
            (24, "Belcesti","Satu Nou", NOW(), NOW()),
            (24, "Belcesti","Tansa", NOW(), NOW()),
            (24, "Belcesti","Ulmi", NOW(), NOW()),
            (24, "Bivolari","Buruienesti", NOW(), NOW()),
            (24, "Bivolari","Solonet", NOW(), NOW()),
            (24, "Bivolari","Tabara", NOW(), NOW()),
            (24, "Bivolari","Traian", NOW(), NOW()),
            (24, "Braesti","Albesti", NOW(), NOW()),
            (24, "Braesti","Buda", NOW(), NOW()),
            (24, "Braesti","Cristesti", NOW(), NOW()),
            (24, "Braesti","Rediu", NOW(), NOW()),
            (24, "Butea","Miclauseni", NOW(), NOW()),
            (24, "Ceplenita","Buhalnita", NOW(), NOW()),
            (24, "Ceplenita","Poiana Marului", NOW(), NOW()),
            (24, "Ceplenita","Zlodica", NOW(), NOW()),
            (24, "Ciortesti","Coropceni", NOW(), NOW()),
            (24, "Ciortesti","Deleni", NOW(), NOW()),
            (24, "Ciortesti","Rotaria", NOW(), NOW()),
            (24, "Ciortesti","Serbesti", NOW(), NOW()),
            (24, "Ciurea","Curaturi", NOW(), NOW()),
            (24, "Ciurea","Dumbrava", NOW(), NOW()),
            (24, "Ciurea","Hlincea", NOW(), NOW()),
            (24, "Ciurea","Lunca Cetatuii", NOW(), NOW()),
            (24, "Ciurea","Picioru Lupului", NOW(), NOW()),
            (24, "Ciurea","Slobozia", NOW(), NOW()),
            (24, "Coarnele Caprei","Arama", NOW(), NOW()),
            (24, "Coarnele Caprei","Petrosica", NOW(), NOW()),
            (24, "Comarna","Curagau", NOW(), NOW()),
            (24, "Comarna","Osoi", NOW(), NOW()),
            (24, "Comarna","Stanca", NOW(), NOW()),
            (24, "Costuleni","Covasna", NOW(), NOW()),
            (24, "Costuleni","Cozia", NOW(), NOW()),
            (24, "Costuleni","Hilita", NOW(), NOW()),
            (24, "Cotnari","Bahluiu", NOW(), NOW()),
            (24, "Cotnari","Cireseni", NOW(), NOW()),
            (24, "Cotnari","Carjoaia", NOW(), NOW()),
            (24, "Cotnari","Fagat", NOW(), NOW()),
            (24, "Cotnari","Hodora", NOW(), NOW()),
            (24, "Cotnari","Horodistea", NOW(), NOW()),
            (24, "Cotnari","Iosupeni", NOW(), NOW()),
            (24, "Cotnari","Luparia", NOW(), NOW()),
            (24, "Cotnari","Valea Racului", NOW(), NOW()),
            (24, "Cotnari","Zbereni", NOW(), NOW()),
            (24, "Cozmesti","Podolenii de Jos", NOW(), NOW()),
            (24, "Cozmesti","Podolenii de Sus", NOW(), NOW()),
            (24, "Cristesti","Homita", NOW(), NOW()),
            (24, "Cucuteni","Baiceni", NOW(), NOW()),
            (24, "Cucuteni","Barbatesti", NOW(), NOW()),
            (24, "Cucuteni","Sacaresti", NOW(), NOW()),
            (24, "Dagata","Boatca", NOW(), NOW()),
            (24, "Dagata","Buzdug", NOW(), NOW()),
            (24, "Dagata","Balusesti", NOW(), NOW()),
            (24, "Dagata","Manastirea", NOW(), NOW()),
            (24, "Dagata","Piscu Rusului", NOW(), NOW()),
            (24, "Dagata","Poienile", NOW(), NOW()),
            (24, "Dagata","Tarnita", NOW(), NOW()),
            (24, "Dagata","Zece Prajini", NOW(), NOW()),
            (24, "Deleni","Feredeni", NOW(), NOW()),
            (24, "Deleni","Leahu-Nacu", NOW(), NOW()),
            (24, "Deleni","Maxut", NOW(), NOW()),
            (24, "Deleni","Poiana", NOW(), NOW()),
            (24, "Deleni","Slobozia", NOW(), NOW()),
            (24, "Dolhesti","Bradicesti", NOW(), NOW()),
            (24, "Dolhesti","Pietris", NOW(), NOW()),
            (24, "Dumesti","Banu", NOW(), NOW()),
            (24, "Dumesti","Chilisoaia", NOW(), NOW()),
            (24, "Dumesti","Hoisesti", NOW(), NOW()),
            (24, "Dumesti","Pausesti", NOW(), NOW()),
            (24, "Erbiceni","Barlesti", NOW(), NOW()),
            (24, "Erbiceni","Spinoasa", NOW(), NOW()),
            (24, "Erbiceni","Spranceana", NOW(), NOW()),
            (24, "Erbiceni","Totoesti", NOW(), NOW()),
            (24, "Fintinele","Fantanele", NOW(), NOW()),
            (24, "Golaiesti","Bran", NOW(), NOW()),
            (24, "Golaiesti","Cilibiu", NOW(), NOW()),
            (24, "Golaiesti","Cotu lui Ivan", NOW(), NOW()),
            (24, "Golaiesti","Gradinari", NOW(), NOW()),
            (24, "Golaiesti","Medeleni", NOW(), NOW()),
            (24, "Golaiesti","Petresti", NOW(), NOW()),
            (24, "Golaiesti","Podu Jijiei", NOW(), NOW()),
            (24, "Gorban","Gura Bohotin", NOW(), NOW()),
            (24, "Gorban","Podu Hagiului", NOW(), NOW()),
            (24, "Gorban","Scoposeni", NOW(), NOW()),
            (24, "Gorban","Zberoaia", NOW(), NOW()),
            (24, "Grajduri","Corcodel", NOW(), NOW()),
            (24, "Grajduri","Carbunari", NOW(), NOW()),
            (24, "Grajduri","Lunca", NOW(), NOW()),
            (24, "Grajduri","Poiana cu Cetate", NOW(), NOW()),
            (24, "Grajduri","Padureni", NOW(), NOW()),
            (24, "Grajduri","Valea Satului", NOW(), NOW()),
            (24, "Gropnita","Bulbucani", NOW(), NOW()),
            (24, "Gropnita","Forasti", NOW(), NOW()),
            (24, "Gropnita","Malaesti", NOW(), NOW()),
            (24, "Gropnita","Sangeri", NOW(), NOW()),
            (24, "Gropnita","Saveni", NOW(), NOW()),
            (24, "Grozesti","Coltu Cornii", NOW(), NOW()),
            (24, "Grozesti","Salageni", NOW(), NOW()),
            (24, "Halaucesti","Luncasi", NOW(), NOW()),
            (24, "Harlau","Parcovaci", NOW(), NOW()),
            (24, "Helesteni","Harmaneasa", NOW(), NOW()),
            (24, "Helesteni","Movileni", NOW(), NOW()),
            (24, "Helesteni","Oboroceni", NOW(), NOW()),
            (24, "Holboca","Cristesti", NOW(), NOW()),
            (24, "Holboca","Dancu", NOW(), NOW()),
            (24, "Holboca","Orzeni", NOW(), NOW()),
            (24, "Holboca","Rusenii Noi", NOW(), NOW()),
            (24, "Holboca","Rusenii Vechi", NOW(), NOW()),
            (24, "Holboca","Valea Lunga", NOW(), NOW()),
            (24, "Horlesti","Bogdanesti", NOW(), NOW()),
            (24, "Horlesti","Scoposeni", NOW(), NOW()),
            (24, "Ion Neculce","Buznea", NOW(), NOW()),
            (24, "Ion Neculce","Prigoreni", NOW(), NOW()),
            (24, "Ion Neculce","Razboieni", NOW(), NOW()),
            (24, "Ipatele","Alexesti", NOW(), NOW()),
            (24, "Ipatele","Bacu", NOW(), NOW()),
            (24, "Ipatele","Cuza Voda", NOW(), NOW()),
            (24, "Lespezi","Buda", NOW(), NOW()),
            (24, "Lespezi","Bursuc-Deal", NOW(), NOW()),
            (24, "Lespezi","Bursuc-Vale", NOW(), NOW()),
            (24, "Lespezi","Dumbrava", NOW(), NOW()),
            (24, "Lespezi","Heci", NOW(), NOW()),
            (24, "Letcani","Bogonos", NOW(), NOW()),
            (24, "Letcani","Cogeasca", NOW(), NOW()),
            (24, "Letcani","Cucuteni", NOW(), NOW()),
            (24, "Lungani","Crucea", NOW(), NOW()),
            (24, "Lungani","Goesti", NOW(), NOW()),
            (24, "Lungani","Zmeu", NOW(), NOW()),
            (24, "Madarjac","Bojila", NOW(), NOW()),
            (24, "Madarjac","Frumusica", NOW(), NOW()),
            (24, "Mircesti","Iugani", NOW(), NOW()),
            (24, "Mircesti","Ursaresti", NOW(), NOW()),
            (24, "Mironeasa","Schitu Hadambului", NOW(), NOW()),
            (24, "Mironeasa","Ursita", NOW(), NOW()),
            (24, "Miroslava","Balciu", NOW(), NOW()),
            (24, "Miroslava","Bratuleni", NOW(), NOW()),
            (24, "Miroslava","Ciurbesti", NOW(), NOW()),
            (24, "Miroslava","Cornesti", NOW(), NOW()),
            (24, "Miroslava","Dancas", NOW(), NOW()),
            (24, "Miroslava","Gaureni", NOW(), NOW()),
            (24, "Miroslava","Horpaz", NOW(), NOW()),
            (24, "Miroslava","Proselnici", NOW(), NOW()),
            (24, "Miroslava","Uricani", NOW(), NOW()),
            (24, "Miroslava","Valea Adanca", NOW(), NOW()),
            (24, "Miroslava","Valea Ursului", NOW(), NOW()),
            (24, "Miroslava","Vorovesti", NOW(), NOW()),
            (24, "Miroslovesti","Ciohorani", NOW(), NOW()),
            (24, "Miroslovesti","Mitesti", NOW(), NOW()),
            (24, "Miroslovesti","Soci", NOW(), NOW()),
            (24, "Miroslovesti","Verseni", NOW(), NOW()),
            (24, "Mogosesti","Budesti", NOW(), NOW()),
            (24, "Mogosesti","Hadambu", NOW(), NOW()),
            (24, "Mogosesti","Manjesti", NOW(), NOW()),
            (24, "Mogosesti-Siret","Muncelu de Sus", NOW(), NOW()),
            (24, "Mogosesti-Siret","Tudor Vladimirescu", NOW(), NOW()),
            (24, "Motca","Boureni", NOW(), NOW()),
            (24, "Movileni","Iepureni", NOW(), NOW()),
            (24, "Movileni","Larga-Jijia", NOW(), NOW()),
            (24, "Movileni","Potangeni", NOW(), NOW()),
            (24, "Oteleni","Handresti", NOW(), NOW()),
            (24, "Pascani","Blagesti", NOW(), NOW()),
            (24, "Pascani","Bosteni", NOW(), NOW()),
            (24, "Pascani","Gastesti", NOW(), NOW()),
            (24, "Pascani","Lunca", NOW(), NOW()),
            (24, "Pascani","Sodomeni", NOW(), NOW()),
            (24, "Plugari","Borosoaia", NOW(), NOW()),
            (24, "Plugari","Onesti", NOW(), NOW()),
            (24, "Podu Iloaiei","Budai", NOW(), NOW()),
            (24, "Podu Iloaiei","Cositeni", NOW(), NOW()),
            (24, "Podu Iloaiei","Holm", NOW(), NOW()),
            (24, "Podu Iloaiei","Scobalteni", NOW(), NOW()),
            (24, "Popesti","Doroscani", NOW(), NOW()),
            (24, "Popesti","Harpasesti", NOW(), NOW()),
            (24, "Popesti","Obrijeni", NOW(), NOW()),
            (24, "Popesti","Padureni", NOW(), NOW()),
            (24, "Popesti","Vama", NOW(), NOW()),
            (24, "Popricani","Cotu Morii", NOW(), NOW()),
            (24, "Popricani","Cuza Voda", NOW(), NOW()),
            (24, "Popricani","Carlig", NOW(), NOW()),
            (24, "Popricani","Moimesti", NOW(), NOW()),
            (24, "Popricani","Rediu Mitropoliei", NOW(), NOW()),
            (24, "Popricani","Vulturi", NOW(), NOW()),
            (24, "Popricani","Vanatori", NOW(), NOW()),
            (24, "Popricani","Tipilesti", NOW(), NOW()),
            (24, "Prisacani","Moreni", NOW(), NOW()),
            (24, "Prisacani","Macaresti", NOW(), NOW()),
            (24, "Probota","Balteni", NOW(), NOW()),
            (24, "Probota","Perieni", NOW(), NOW()),
            (24, "Rachiteni","Izvoarele", NOW(), NOW()),
            (24, "Raducaneni","Bohotin", NOW(), NOW()),
            (24, "Raducaneni","Isaiia", NOW(), NOW()),
            (24, "Raducaneni","Rosu", NOW(), NOW()),
            (24, "Rediu","Breazu", NOW(), NOW()),
            (24, "Rediu","Horlesti", NOW(), NOW()),
            (24, "Rediu","Tautesti", NOW(), NOW()),
            (24, "Romanesti","Avantu", NOW(), NOW()),
            (24, "Romanesti","Ursoaia", NOW(), NOW()),
            (24, "Roscani","Radeni", NOW(), NOW()),
            (24, "Ruginoasa","Dumbravita", NOW(), NOW()),
            (24, "Ruginoasa","Rediu", NOW(), NOW()),
            (24, "Ruginoasa","Vascani", NOW(), NOW()),
            (24, "Scanteia","Bodesti", NOW(), NOW()),
            (24, "Scanteia","Borosesti", NOW(), NOW()),
            (24, "Scanteia","Ciocarlesti", NOW(), NOW()),
            (24, "Scanteia","Lunca Rates", NOW(), NOW()),
            (24, "Scanteia","Rediu", NOW(), NOW()),
            (24, "Scanteia","Tufestii de Sus", NOW(), NOW()),
            (24, "Scheia","Cioca-Boca", NOW(), NOW()),
            (24, "Scheia","Cauesti", NOW(), NOW()),
            (24, "Scheia","Frenciugi", NOW(), NOW()),
            (24, "Scheia","Poiana Scheii", NOW(), NOW()),
            (24, "Scheia","Satu Nou", NOW(), NOW()),
            (24, "Schitu Duca","Blaga", NOW(), NOW()),
            (24, "Schitu Duca","Dumitrestii Galatii", NOW(), NOW()),
            (24, "Schitu Duca","Pocreaca", NOW(), NOW()),
            (24, "Schitu Duca","Poiana", NOW(), NOW()),
            (24, "Schitu Duca","Poieni", NOW(), NOW()),
            (24, "Schitu Duca","Satu Nou", NOW(), NOW()),
            (24, "Schitu Duca","Slobozia", NOW(), NOW()),
            (24, "Scobinti","Badeni", NOW(), NOW()),
            (24, "Scobinti","Fetesti", NOW(), NOW()),
            (24, "Scobinti","Sticlaria", NOW(), NOW()),
            (24, "Scobinti","Zagavia", NOW(), NOW()),
            (24, "Sinesti","Bocnita", NOW(), NOW()),
            (24, "Sinesti","Osoi", NOW(), NOW()),
            (24, "Sinesti","Stornesti", NOW(), NOW()),
            (24, "Sipote","Chiscareni", NOW(), NOW()),
            (24, "Sipote","Halceni", NOW(), NOW()),
            (24, "Sipote","Iazu Nou", NOW(), NOW()),
            (24, "Sipote","Iazu Vechi", NOW(), NOW()),
            (24, "Sipote","Mitoc", NOW(), NOW()),
            (24, "Siretel","Berezlogi", NOW(), NOW()),
            (24, "Siretel","Humosu", NOW(), NOW()),
            (24, "Siretel","Satu Nou", NOW(), NOW()),
            (24, "Siretel","Slobozia", NOW(), NOW()),
            (24, "Stolniceni-Prajescu","Bratesti", NOW(), NOW()),
            (24, "Stolniceni-Prajescu","Cozmesti", NOW(), NOW()),
            (24, "Strunga","Bratulesti", NOW(), NOW()),
            (24, "Strunga","Crivesti", NOW(), NOW()),
            (24, "Strunga","Cucova", NOW(), NOW()),
            (24, "Strunga","Fedeleseni", NOW(), NOW()),
            (24, "Strunga","Farcaseni", NOW(), NOW()),
            (24, "Strunga","Gura Vaii", NOW(), NOW()),
            (24, "Strunga","Habasesti", NOW(), NOW()),
            (24, "Tansa","Suhulet", NOW(), NOW()),
            (24, "Targu Frumos","Coasta Magurii", NOW(), NOW()),
            (24, "Targu Frumos","Dadesti", NOW(), NOW()),
            (24, "Targu Frumos","Giurgesti", NOW(), NOW()),
            (24, "Targu Frumos","Ganesti", NOW(), NOW()),
            (24, "Targu Frumos","Ion Neculce", NOW(), NOW()),
            (24, "Tatarusi","Iorcani", NOW(), NOW()),
            (24, "Tatarusi","Pietrosu", NOW(), NOW()),
            (24, "Tatarusi","Uda", NOW(), NOW()),
            (24, "Tatarusi","Valcica", NOW(), NOW()),
            (24, "Tibana","Alexeni", NOW(), NOW()),
            (24, "Tibana","Domnita", NOW(), NOW()),
            (24, "Tibana","Garbesti", NOW(), NOW()),
            (24, "Tibana","Moara Ciornei", NOW(), NOW()),
            (24, "Tibana","Oproaia", NOW(), NOW()),
            (24, "Tibana","Poiana Manastirii", NOW(), NOW()),
            (24, "Tibana","Poiana de Sus", NOW(), NOW()),
            (24, "Tibana","Runcu", NOW(), NOW()),
            (24, "Tibana","Vadu Vejei", NOW(), NOW()),
            (24, "Tibanesti","Glodenii Gandului", NOW(), NOW()),
            (24, "Tibanesti","Griesti", NOW(), NOW()),
            (24, "Tibanesti","Jigoreni", NOW(), NOW()),
            (24, "Tibanesti","Recea", NOW(), NOW()),
            (24, "Tibanesti","Rasboieni", NOW(), NOW()),
            (24, "Tibanesti","Tungujei", NOW(), NOW()),
            (24, "Tibanesti","Valenii", NOW(), NOW()),
            (24, "Tiganasi","Carniceni", NOW(), NOW()),
            (24, "Tiganasi","Mihail Kogalniceanu", NOW(), NOW()),
            (24, "Tiganasi","Stejarii", NOW(), NOW()),
            (24, "Todiresti","Boldesti", NOW(), NOW()),
            (24, "Todiresti","Baiceni", NOW(), NOW()),
            (24, "Todiresti","Harmanestii Noi", NOW(), NOW()),
            (24, "Todiresti","Harmanestii Vechi", NOW(), NOW()),
            (24, "Todiresti","Stroesti", NOW(), NOW()),
            (24, "Tomesti","Chicerea", NOW(), NOW()),
            (24, "Tomesti","Goruni", NOW(), NOW()),
            (24, "Tomesti","Vladiceni", NOW(), NOW()),
            (24, "Trifesti","Hermeziu", NOW(), NOW()),
            (24, "Trifesti","Roscani", NOW(), NOW()),
            (24, "Trifesti","Vladomira", NOW(), NOW()),
            (24, "Trifesti","Zaboloteni", NOW(), NOW()),
            (24, "Tutora","Chiperesti", NOW(), NOW()),
            (24, "Tutora","Opriseni", NOW(), NOW()),
            (24, "Ungheni","Bosia", NOW(), NOW()),
            (24, "Ungheni","Coada Stancii", NOW(), NOW()),
            (24, "Ungheni","Manzatesti", NOW(), NOW()),
            (24, "Valea Seaca","Contesti", NOW(), NOW()),
            (24, "Valea Seaca","Topile", NOW(), NOW()),
            (24, "Vanatori","Crivesti", NOW(), NOW()),
            (24, "Vanatori","Gura Badilitei", NOW(), NOW()),
            (24, "Vanatori","Hartoape", NOW(), NOW()),
            (24, "Vanatori","Vladnicut", NOW(), NOW()),
            (24, "Victoria","Frasuleni", NOW(), NOW()),
            (24, "Victoria","Icuseni", NOW(), NOW()),
            (24, "Victoria","Luceni", NOW(), NOW()),
            (24, "Victoria","Sculeni", NOW(), NOW()),
            (24, "Victoria","Stanca", NOW(), NOW()),
            (24, "Victoria","Sendreni", NOW(), NOW()),
            (24, "Vladeni","Alexandru cel Bun", NOW(), NOW()),
            (24, "Vladeni","Borsa", NOW(), NOW()),
            (24, "Vladeni","Brosteni", NOW(), NOW()),
            (24, "Vladeni","Iacobeni", NOW(), NOW()),
            (24, "Vladeni","Valcelele", NOW(), NOW()),
            (24, "Voinesti","Lungani", NOW(), NOW()),
            (24, "Voinesti","Schitu Stavnic", NOW(), NOW()),
            (24, "Voinesti","Slobozia", NOW(), NOW()),
            (24, "Voinesti","Vocotesti", NOW(), NOW())
        ;';
        if (config('app.env') !== 'testing') {
            DB::connection()->getPdo()->exec($sql);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=24;';
        DB::connection()->getPdo()->exec($sql);
    }
}
