<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllLocalitiesForGJ extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $sql = 'INSERT INTO localities (county_id, township, name, created_at, updated_at) VALUES
            (19, "","Albeni", NOW(), NOW()),
            (19, "","Alimpesti", NOW(), NOW()),
            (19, "","Aninoasa", NOW(), NOW()),
            (19, "","Arcani", NOW(), NOW()),
            (19, "","Baia de Fier", NOW(), NOW()),
            (19, "","Berlesti", NOW(), NOW()),
            (19, "","Bolbosi", NOW(), NOW()),
            (19, "","Borascu", NOW(), NOW()),
            (19, "","Branesti", NOW(), NOW()),
            (19, "","Bumbesti-Jiu", NOW(), NOW()),
            (19, "","Bumbesti-Pitic", NOW(), NOW()),
            (19, "","Bustuchin", NOW(), NOW()),
            (19, "","Balteni", NOW(), NOW()),
            (19, "","Balesti", NOW(), NOW()),
            (19, "","Balanesti", NOW(), NOW()),
            (19, "","Barbatesti", NOW(), NOW()),
            (19, "","Ciuperceni", NOW(), NOW()),
            (19, "","Crasna", NOW(), NOW()),
            (19, "","Cruset", NOW(), NOW()),
            (19, "","Calnic", NOW(), NOW()),
            (19, "","Capreni", NOW(), NOW()),
            (19, "","Catunele", NOW(), NOW()),
            (19, "","Dragotesti", NOW(), NOW()),
            (19, "","Dragutesti", NOW(), NOW()),
            (19, "","Danciulesti", NOW(), NOW()),
            (19, "","Danesti", NOW(), NOW()),
            (19, "","Farcasesti", NOW(), NOW()),
            (19, "","Glogova", NOW(), NOW()),
            (19, "","Godinesti", NOW(), NOW()),
            (19, "","Hurezani", NOW(), NOW()),
            (19, "","Ionesti", NOW(), NOW()),
            (19, "","Jupanesti", NOW(), NOW()),
            (19, "","Lelesti", NOW(), NOW()),
            (19, "","Licurici", NOW(), NOW()),
            (19, "","Motru", NOW(), NOW()),
            (19, "","Musetesti", NOW(), NOW()),
            (19, "","Matasari", NOW(), NOW()),
            (19, "","Negomir", NOW(), NOW()),
            (19, "","Novaci", NOW(), NOW()),
            (19, "","Pades", NOW(), NOW()),
            (19, "","Pestisani", NOW(), NOW()),
            (19, "","Plopsoru", NOW(), NOW()),
            (19, "","Polovragi", NOW(), NOW()),
            (19, "","Prigoria", NOW(), NOW()),
            (19, "","Rovinari", NOW(), NOW()),
            (19, "","Rosia de Amaradia", NOW(), NOW()),
            (19, "","Runcu", NOW(), NOW()),
            (19, "","Samarinesti", NOW(), NOW()),
            (19, "","Schela", NOW(), NOW()),
            (19, "","Scoarta", NOW(), NOW()),
            (19, "","Slivilesti", NOW(), NOW()),
            (19, "","Stejari", NOW(), NOW()),
            (19, "","Stoina", NOW(), NOW()),
            (19, "","Stanesti", NOW(), NOW()),
            (19, "","Sacelu", NOW(), NOW()),
            (19, "","Saulesti", NOW(), NOW()),
            (19, "","Telesti", NOW(), NOW()),
            (19, "","Tismana", NOW(), NOW()),
            (19, "","Turburea", NOW(), NOW()),
            (19, "","Turceni", NOW(), NOW()),
            (19, "","Turcinesti", NOW(), NOW()),
            (19, "","Targu Jiu", NOW(), NOW()),
            (19, "","Urdari", NOW(), NOW()),
            (19, "","Vladimir", NOW(), NOW()),
            (19, "","Vagiulesti", NOW(), NOW()),
            (19, "","Ticleni", NOW(), NOW()),
            (19, "","Tantareni", NOW(), NOW()),
            (19, "Albeni","Bolbocesti", NOW(), NOW()),
            (19, "Albeni","Barzeiu de Gilort", NOW(), NOW()),
            (19, "Albeni","Doseni", NOW(), NOW()),
            (19, "Albeni","Mirosloveni", NOW(), NOW()),
            (19, "Albeni","Prunesti", NOW(), NOW()),
            (19, "Alimpesti","Ciupercenii de Oltet", NOW(), NOW()),
            (19, "Alimpesti","Corsoru", NOW(), NOW()),
            (19, "Alimpesti","Nistoresti", NOW(), NOW()),
            (19, "Alimpesti","Sarbesti", NOW(), NOW()),
            (19, "Aninoasa","Bobaia", NOW(), NOW()),
            (19, "Aninoasa","Costesti", NOW(), NOW()),
            (19, "Aninoasa","Groserea", NOW(), NOW()),
            (19, "Aninoasa","Sterpoaia", NOW(), NOW()),
            (19, "Arcani","Campofeni", NOW(), NOW()),
            (19, "Arcani","Stroiesti", NOW(), NOW()),
            (19, "Arcani","Sanatesti", NOW(), NOW()),
            (19, "Baia De Fier","Cernadia", NOW(), NOW()),
            (19, "Balanesti","Blidari", NOW(), NOW()),
            (19, "Balanesti","Canepesti", NOW(), NOW()),
            (19, "Balanesti","Glodeni", NOW(), NOW()),
            (19, "Balanesti","Ohaba", NOW(), NOW()),
            (19, "Balanesti","Voitestii de Vale", NOW(), NOW()),
            (19, "Balanesti","Voitestii din Deal", NOW(), NOW()),
            (19, "Balesti","Ceauru", NOW(), NOW()),
            (19, "Balesti","Cornesti", NOW(), NOW()),
            (19, "Balesti","Gavanesti", NOW(), NOW()),
            (19, "Balesti","Rasova", NOW(), NOW()),
            (19, "Balesti","Stolojani", NOW(), NOW()),
            (19, "Balesti","Talpasesti", NOW(), NOW()),
            (19, "Balesti","Tamasesti", NOW(), NOW()),
            (19, "Balesti","Voinigesti", NOW(), NOW()),
            (19, "Balteni","Cocoreni", NOW(), NOW()),
            (19, "Balteni","Moi", NOW(), NOW()),
            (19, "Balteni","Pesteana Jiu", NOW(), NOW()),
            (19, "Balteni","Vladuleni", NOW(), NOW()),
            (19, "Barbatesti","Musculesti", NOW(), NOW()),
            (19, "Barbatesti","Petresti", NOW(), NOW()),
            (19, "Barbatesti","Socu", NOW(), NOW()),
            (19, "Bengesti-Ciocadia","Bengesti", NOW(), NOW()),
            (19, "Bengesti-Ciocadia","Bircii", NOW(), NOW()),
            (19, "Bengesti-Ciocadia","Balcesti", NOW(), NOW()),
            (19, "Bengesti-Ciocadia","Ciocadia", NOW(), NOW()),
            (19, "Berlesti","Barzeiu", NOW(), NOW()),
            (19, "Berlesti","Galcesti", NOW(), NOW()),
            (19, "Berlesti","Lihulesti", NOW(), NOW()),
            (19, "Berlesti","Parau Viu", NOW(), NOW()),
            (19, "Berlesti","Scrada", NOW(), NOW()),
            (19, "Berlesti","Scurtu", NOW(), NOW()),
            (19, "Bolbosi","Bolboasa", NOW(), NOW()),
            (19, "Bolbosi","Balacesti", NOW(), NOW()),
            (19, "Bolbosi","Igirosu", NOW(), NOW()),
            (19, "Bolbosi","Miclosu", NOW(), NOW()),
            (19, "Bolbosi","Ohaba Jiu", NOW(), NOW()),
            (19, "Bolbosi","Valea", NOW(), NOW()),
            (19, "Borascu","Baniu", NOW(), NOW()),
            (19, "Borascu","Calaparu", NOW(), NOW()),
            (19, "Borascu","Gura Menti", NOW(), NOW()),
            (19, "Borascu","Mentii din Dos", NOW(), NOW()),
            (19, "Borascu","Miluta", NOW(), NOW()),
            (19, "Borascu","Scorusu", NOW(), NOW()),
            (19, "Branesti","Brebenei", NOW(), NOW()),
            (19, "Branesti","Badesti", NOW(), NOW()),
            (19, "Branesti","Capu Dealului", NOW(), NOW()),
            (19, "Branesti","Gilortu", NOW(), NOW()),
            (19, "Branesti","Parau", NOW(), NOW()),
            (19, "Bumbesti-Jiu","Curtisoara", NOW(), NOW()),
            (19, "Bumbesti-Jiu","Lazaresti", NOW(), NOW()),
            (19, "Bumbesti-Jiu","Plesa", NOW(), NOW()),
            (19, "Bumbesti-Jiu","Tetila", NOW(), NOW()),
            (19, "Bumbesti-Pitic","Carligei", NOW(), NOW()),
            (19, "Bumbesti-Pitic","Poienari", NOW(), NOW()),
            (19, "Bustuchin","Cionti", NOW(), NOW()),
            (19, "Bustuchin","Motorgi", NOW(), NOW()),
            (19, "Bustuchin","Namete", NOW(), NOW()),
            (19, "Bustuchin","Poiana Seciuri", NOW(), NOW()),
            (19, "Bustuchin","Poienita", NOW(), NOW()),
            (19, "Bustuchin","Pojaru", NOW(), NOW()),
            (19, "Bustuchin","Valea Pojarului", NOW(), NOW()),
            (19, "Calnic","Calnicu de Sus", NOW(), NOW()),
            (19, "Calnic","Didilesti", NOW(), NOW()),
            (19, "Calnic","Galesoaia", NOW(), NOW()),
            (19, "Calnic","Hodoreasca", NOW(), NOW()),
            (19, "Calnic","Pieptani", NOW(), NOW()),
            (19, "Calnic","Pinoasa", NOW(), NOW()),
            (19, "Calnic","Stejerei", NOW(), NOW()),
            (19, "Calnic","Valceaua", NOW(), NOW()),
            (19, "Capreni","Alunis", NOW(), NOW()),
            (19, "Capreni","Bratesti", NOW(), NOW()),
            (19, "Capreni","Bulbuceni", NOW(), NOW()),
            (19, "Capreni","Cetatea", NOW(), NOW()),
            (19, "Capreni","Cornetu", NOW(), NOW()),
            (19, "Capreni","Dealu Spirei", NOW(), NOW()),
            (19, "Capreni","Satu Nou", NOW(), NOW()),
            (19, "Catunele","Dealu Viilor", NOW(), NOW()),
            (19, "Catunele","Lupoaia", NOW(), NOW()),
            (19, "Catunele","Steic", NOW(), NOW()),
            (19, "Catunele","Valea Manastirii", NOW(), NOW()),
            (19, "Catunele","Valea Perilor", NOW(), NOW()),
            (19, "Ciuperceni","Boboiesti", NOW(), NOW()),
            (19, "Ciuperceni","Pesteana Vulcan", NOW(), NOW()),
            (19, "Ciuperceni","Priporu", NOW(), NOW()),
            (19, "Ciuperceni","Stramba Vulcan", NOW(), NOW()),
            (19, "Ciuperceni","Vartopu", NOW(), NOW()),
            (19, "Ciuperceni","Zorzila", NOW(), NOW()),
            (19, "Crasna","Aninisu din Deal", NOW(), NOW()),
            (19, "Crasna","Aninisu din Vale", NOW(), NOW()),
            (19, "Crasna","Buzesti", NOW(), NOW()),
            (19, "Crasna","Crasna din Deal", NOW(), NOW()),
            (19, "Crasna","Carpinis", NOW(), NOW()),
            (19, "Crasna","Dragoiesti", NOW(), NOW()),
            (19, "Crasna","Dumbraveni", NOW(), NOW()),
            (19, "Crasna","Radosi", NOW(), NOW()),
            (19, "Cruset","Bojinu", NOW(), NOW()),
            (19, "Cruset","Marinesti", NOW(), NOW()),
            (19, "Cruset","Mierea", NOW(), NOW()),
            (19, "Cruset","Miericeaua", NOW(), NOW()),
            (19, "Cruset","Maiag", NOW(), NOW()),
            (19, "Cruset","Slamnesti", NOW(), NOW()),
            (19, "Cruset","Slavuta", NOW(), NOW()),
            (19, "Cruset","Urda de Jos", NOW(), NOW()),
            (19, "Cruset","Valuta", NOW(), NOW()),
            (19, "Danciulesti","Bibulesti", NOW(), NOW()),
            (19, "Danciulesti","Halangesti", NOW(), NOW()),
            (19, "Danciulesti","Obarsia", NOW(), NOW()),
            (19, "Danciulesti","Petrachei", NOW(), NOW()),
            (19, "Danciulesti","Radinesti", NOW(), NOW()),
            (19, "Danciulesti","Zaicoiu", NOW(), NOW()),
            (19, "Danesti","Barza", NOW(), NOW()),
            (19, "Danesti","Botorogi", NOW(), NOW()),
            (19, "Danesti","Bratuia", NOW(), NOW()),
            (19, "Danesti","Bucureasa", NOW(), NOW()),
            (19, "Danesti","Merfulesti", NOW(), NOW()),
            (19, "Danesti","Trocani", NOW(), NOW()),
            (19, "Danesti","Ungureni", NOW(), NOW()),
            (19, "Danesti","Vacarea", NOW(), NOW()),
            (19, "Danesti","Sasa", NOW(), NOW()),
            (19, "Danesti","Tarculesti", NOW(), NOW()),
            (19, "Dragotesti","Corobai", NOW(), NOW()),
            (19, "Dragotesti","Trestioara", NOW(), NOW()),
            (19, "Dragutesti","Carbesti", NOW(), NOW()),
            (19, "Dragutesti","Dambova", NOW(), NOW()),
            (19, "Dragutesti","Iasi-Gorj", NOW(), NOW()),
            (19, "Dragutesti","Talvesti", NOW(), NOW()),
            (19, "Dragutesti","Urechesti", NOW(), NOW()),
            (19, "Farcasesti","Farcasesti Mosneni", NOW(), NOW()),
            (19, "Farcasesti","Pesteana de Jos", NOW(), NOW()),
            (19, "Farcasesti","Rogojel", NOW(), NOW()),
            (19, "Farcasesti","Rosia Jiu", NOW(), NOW()),
            (19, "Farcasesti","Timiseni", NOW(), NOW()),
            (19, "Farcasesti","Valea cu Apa", NOW(), NOW()),
            (19, "Glogova","Clesnesti", NOW(), NOW()),
            (19, "Glogova","Camuiesti", NOW(), NOW()),
            (19, "Glogova","Iormanesti", NOW(), NOW()),
            (19, "Glogova","Olteanu", NOW(), NOW()),
            (19, "Godinesti","Arjoci", NOW(), NOW()),
            (19, "Godinesti","Chiliu", NOW(), NOW()),
            (19, "Godinesti","Calcesti", NOW(), NOW()),
            (19, "Godinesti","Parau de Pripor", NOW(), NOW()),
            (19, "Godinesti","Parau de Vale", NOW(), NOW()),
            (19, "Godinesti","Ratez", NOW(), NOW()),
            (19, "Hurezani","Busuioci", NOW(), NOW()),
            (19, "Hurezani","Pegeni", NOW(), NOW()),
            (19, "Hurezani","Plopu", NOW(), NOW()),
            (19, "Hurezani","Totea de Hurezani", NOW(), NOW()),
            (19, "Ionesti","Gura Susitei", NOW(), NOW()),
            (19, "Ionesti","Iliesti", NOW(), NOW()),
            (19, "Ionesti","Picu", NOW(), NOW()),
            (19, "Jupanesti","Boia", NOW(), NOW()),
            (19, "Jupanesti","Parau Boia", NOW(), NOW()),
            (19, "Jupanesti","Vidin", NOW(), NOW()),
            (19, "Jupanesti","Viersani", NOW(), NOW()),
            (19, "Lelesti","Fratesti", NOW(), NOW()),
            (19, "Lelesti","Rasovita", NOW(), NOW()),
            (19, "Licurici","Frumusei", NOW(), NOW()),
            (19, "Licurici","Negreni", NOW(), NOW()),
            (19, "Licurici","Totea", NOW(), NOW()),
            (19, "Logresti","Coltesti", NOW(), NOW()),
            (19, "Logresti","Frunza", NOW(), NOW()),
            (19, "Logresti","Logresti Mosteni", NOW(), NOW()),
            (19, "Logresti","Maru", NOW(), NOW()),
            (19, "Logresti","Popesti", NOW(), NOW()),
            (19, "Logresti","Seaca", NOW(), NOW()),
            (19, "Logresti","Targu Logresti", NOW(), NOW()),
            (19, "Matasari","Bradet", NOW(), NOW()),
            (19, "Matasari","Bradetel", NOW(), NOW()),
            (19, "Matasari","Croici", NOW(), NOW()),
            (19, "Matasari","Runcurel", NOW(), NOW()),
            (19, "Motru","Dealu Pomilor", NOW(), NOW()),
            (19, "Motru","Horasti", NOW(), NOW()),
            (19, "Motru","Leurda", NOW(), NOW()),
            (19, "Motru","Lupoita", NOW(), NOW()),
            (19, "Motru","Plostina", NOW(), NOW()),
            (19, "Motru","Rosiuta", NOW(), NOW()),
            (19, "Motru","Rapa", NOW(), NOW()),
            (19, "Motru","Insuratei", NOW(), NOW()),
            (19, "Musetesti","Arseni", NOW(), NOW()),
            (19, "Musetesti","Barcaciu", NOW(), NOW()),
            (19, "Musetesti","Grui", NOW(), NOW()),
            (19, "Musetesti","Gamani", NOW(), NOW()),
            (19, "Musetesti","Stancesti", NOW(), NOW()),
            (19, "Musetesti","Stancesti Larga", NOW(), NOW()),
            (19, "Negomir","Artanu", NOW(), NOW()),
            (19, "Negomir","Bohorel", NOW(), NOW()),
            (19, "Negomir","Condeiesti", NOW(), NOW()),
            (19, "Negomir","Nucetu", NOW(), NOW()),
            (19, "Negomir","Orzu", NOW(), NOW()),
            (19, "Negomir","Paltinu", NOW(), NOW()),
            (19, "Negomir","Raci", NOW(), NOW()),
            (19, "Negomir","Ursoaia", NOW(), NOW()),
            (19, "Negomir","Valea Racilor", NOW(), NOW()),
            (19, "Novaci","Bercesti", NOW(), NOW()),
            (19, "Novaci","Hirisesti", NOW(), NOW()),
            (19, "Novaci","Pociovalistea", NOW(), NOW()),
            (19, "Novaci","Sitesti", NOW(), NOW()),
            (19, "Pades","Apa Neagra", NOW(), NOW()),
            (19, "Pades","Cerna-Sat", NOW(), NOW()),
            (19, "Pades","Closani", NOW(), NOW()),
            (19, "Pades","Calugareni", NOW(), NOW()),
            (19, "Pades","Motru Sec", NOW(), NOW()),
            (19, "Pades","Orzesti", NOW(), NOW()),
            (19, "Pades","Vaieni", NOW(), NOW()),
            (19, "Pestisani","Borosteni", NOW(), NOW()),
            (19, "Pestisani","Bradiceni", NOW(), NOW()),
            (19, "Pestisani","Francesti", NOW(), NOW()),
            (19, "Pestisani","Gureni", NOW(), NOW()),
            (19, "Pestisani","Hobita", NOW(), NOW()),
            (19, "Pestisani","Seuca", NOW(), NOW()),
            (19, "Plopsoru","Brosteni", NOW(), NOW()),
            (19, "Plopsoru","Brostenii de Sus", NOW(), NOW()),
            (19, "Plopsoru","Ceplea", NOW(), NOW()),
            (19, "Plopsoru","Cursaru", NOW(), NOW()),
            (19, "Plopsoru","Deleni", NOW(), NOW()),
            (19, "Plopsoru","Izvoarele", NOW(), NOW()),
            (19, "Plopsoru","Olari", NOW(), NOW()),
            (19, "Plopsoru","Piscuri", NOW(), NOW()),
            (19, "Plopsoru","Sardanesti", NOW(), NOW()),
            (19, "Plopsoru","Valeni", NOW(), NOW()),
            (19, "Polovragi","Racovita", NOW(), NOW()),
            (19, "Prigoria","Bucsana", NOW(), NOW()),
            (19, "Prigoria","Burlani", NOW(), NOW()),
            (19, "Prigoria","Calugareasa", NOW(), NOW()),
            (19, "Prigoria","Dobrana", NOW(), NOW()),
            (19, "Prigoria","Negoiesti", NOW(), NOW()),
            (19, "Prigoria","Zorlesti", NOW(), NOW()),
            (19, "Rosia De Amaradia","Becheni", NOW(), NOW()),
            (19, "Rosia De Amaradia","Dealu Viei", NOW(), NOW()),
            (19, "Rosia De Amaradia","Ruget", NOW(), NOW()),
            (19, "Rosia De Amaradia","Seciurile", NOW(), NOW()),
            (19, "Rosia De Amaradia","Stejaru", NOW(), NOW()),
            (19, "Rosia De Amaradia","Sitoaia", NOW(), NOW()),
            (19, "Rovinari","Vart", NOW(), NOW()),
            (19, "Runcu","Balta", NOW(), NOW()),
            (19, "Runcu","Baltisoara", NOW(), NOW()),
            (19, "Runcu","Dobrita", NOW(), NOW()),
            (19, "Runcu","Rachiti", NOW(), NOW()),
            (19, "Runcu","Suseni", NOW(), NOW()),
            (19, "Runcu","Valea Mare", NOW(), NOW()),
            (19, "Sacelu","Blahnita de Sus", NOW(), NOW()),
            (19, "Sacelu","Haiesti", NOW(), NOW()),
            (19, "Sacelu","Jeristea", NOW(), NOW()),
            (19, "Sacelu","Magheresti", NOW(), NOW()),
            (19, "Samarinesti","Boca", NOW(), NOW()),
            (19, "Samarinesti","Bazavani", NOW(), NOW()),
            (19, "Samarinesti","Duculesti", NOW(), NOW()),
            (19, "Samarinesti","Larga", NOW(), NOW()),
            (19, "Samarinesti","Valea Bisericii", NOW(), NOW()),
            (19, "Samarinesti","Valea Mica", NOW(), NOW()),
            (19, "Samarinesti","Valea Poienii", NOW(), NOW()),
            (19, "Samarinesti","Tirioi", NOW(), NOW()),
            (19, "Saulesti","Bibesti", NOW(), NOW()),
            (19, "Saulesti","Dolcesti", NOW(), NOW()),
            (19, "Saulesti","Purcaru", NOW(), NOW()),
            (19, "Schela","Arsuri", NOW(), NOW()),
            (19, "Schela","Gornacel", NOW(), NOW()),
            (19, "Schela","Pajistele", NOW(), NOW()),
            (19, "Schela","Sambotin", NOW(), NOW()),
            (19, "Scoarta","Bobu", NOW(), NOW()),
            (19, "Scoarta","Budieni", NOW(), NOW()),
            (19, "Scoarta","Ceratu de Copacioasa", NOW(), NOW()),
            (19, "Scoarta","Colibasi", NOW(), NOW()),
            (19, "Scoarta","Copacioasa", NOW(), NOW()),
            (19, "Scoarta","Campu Mare", NOW(), NOW()),
            (19, "Scoarta","Lazuri", NOW(), NOW()),
            (19, "Scoarta","Lintea", NOW(), NOW()),
            (19, "Scoarta","Mogosani", NOW(), NOW()),
            (19, "Scoarta","Pistestii din Deal", NOW(), NOW()),
            (19, "Slivilesti","Cojmanesti", NOW(), NOW()),
            (19, "Slivilesti","Miculesti", NOW(), NOW()),
            (19, "Slivilesti","Stramtu", NOW(), NOW()),
            (19, "Slivilesti","Sura", NOW(), NOW()),
            (19, "Slivilesti","Tehomir", NOW(), NOW()),
            (19, "Slivilesti","Siacu", NOW(), NOW()),
            (19, "Slivilesti","Stiucani", NOW(), NOW()),
            (19, "Stanesti","Alexeni", NOW(), NOW()),
            (19, "Stanesti","Balani", NOW(), NOW()),
            (19, "Stanesti","Curpen", NOW(), NOW()),
            (19, "Stanesti","Calesti", NOW(), NOW()),
            (19, "Stanesti","Mazaroi", NOW(), NOW()),
            (19, "Stanesti","Obreja", NOW(), NOW()),
            (19, "Stanesti","Parvulesti", NOW(), NOW()),
            (19, "Stanesti","Vaidei", NOW(), NOW()),
            (19, "Stanesti","Valari", NOW(), NOW()),
            (19, "Stejari","Balosani", NOW(), NOW()),
            (19, "Stejari","Bacesti", NOW(), NOW()),
            (19, "Stejari","Dealu Leului", NOW(), NOW()),
            (19, "Stejari","Piscoiu", NOW(), NOW()),
            (19, "Stejari","Popesti Stejari", NOW(), NOW()),
            (19, "Stoina","Ciorari", NOW(), NOW()),
            (19, "Stoina","Mielusei", NOW(), NOW()),
            (19, "Stoina","Paisani", NOW(), NOW()),
            (19, "Stoina","Toiaga", NOW(), NOW()),
            (19, "Stoina","Ulmet", NOW(), NOW()),
            (19, "Stoina","Urda de Sus", NOW(), NOW()),
            (19, "Tantareni","Arpadia", NOW(), NOW()),
            (19, "Tantareni","Chiciora", NOW(), NOW()),
            (19, "Tantareni","Floresti", NOW(), NOW()),
            (19, "Targu Jiu","Barsesti", NOW(), NOW()),
            (19, "Targu Jiu","Dragoeni", NOW(), NOW()),
            (19, "Targu Jiu","Iezureni", NOW(), NOW()),
            (19, "Targu Jiu","Polata", NOW(), NOW()),
            (19, "Targu Jiu","Preajba Mare", NOW(), NOW()),
            (19, "Targu Jiu","Romanesti", NOW(), NOW()),
            (19, "Targu Jiu","Slobozia", NOW(), NOW()),
            (19, "Targu Jiu","Ursati", NOW(), NOW()),
            (19, "Telesti","Buduhala", NOW(), NOW()),
            (19, "Telesti","Somanesti", NOW(), NOW()),
            (19, "Tirgu Carbunesti","Blahnita de Jos", NOW(), NOW()),
            (19, "Tirgu Carbunesti","Cojani", NOW(), NOW()),
            (19, "Tirgu Carbunesti","Cretesti", NOW(), NOW()),
            (19, "Tirgu Carbunesti","Curteana", NOW(), NOW()),
            (19, "Tirgu Carbunesti","Carbunesti-Sat", NOW(), NOW()),
            (19, "Tirgu Carbunesti","Floresteni", NOW(), NOW()),
            (19, "Tirgu Carbunesti","Macesu", NOW(), NOW()),
            (19, "Tirgu Carbunesti","Pojogeni", NOW(), NOW()),
            (19, "Tirgu Carbunesti","Rogojeni", NOW(), NOW()),
            (19, "Tirgu Carbunesti","Targu Carbunesti", NOW(), NOW()),
            (19, "Tirgu Carbunesti","Stefanesti", NOW(), NOW()),
            (19, "Tismana","Celei", NOW(), NOW()),
            (19, "Tismana","Costeni", NOW(), NOW()),
            (19, "Tismana","Gornovita", NOW(), NOW()),
            (19, "Tismana","Isvarna", NOW(), NOW()),
            (19, "Tismana","Pocruia", NOW(), NOW()),
            (19, "Tismana","Racoti", NOW(), NOW()),
            (19, "Tismana","Sohodol", NOW(), NOW()),
            (19, "Tismana","Topesti", NOW(), NOW()),
            (19, "Tismana","Valcele", NOW(), NOW()),
            (19, "Tismana","Vanata", NOW(), NOW()),
            (19, "Turburea","Cocorova", NOW(), NOW()),
            (19, "Turburea","Poiana", NOW(), NOW()),
            (19, "Turburea","Spahii", NOW(), NOW()),
            (19, "Turburea","Sipotu", NOW(), NOW()),
            (19, "Turceni","Garbovu", NOW(), NOW()),
            (19, "Turceni","Jiltu", NOW(), NOW()),
            (19, "Turceni","Murgesti", NOW(), NOW()),
            (19, "Turceni","Stramba Jiu", NOW(), NOW()),
            (19, "Turceni","Valea Viei", NOW(), NOW()),
            (19, "Turcinesti","Cartiu", NOW(), NOW()),
            (19, "Turcinesti","Horezu", NOW(), NOW()),
            (19, "Turcinesti","Rugi", NOW(), NOW()),
            (19, "Urdari","Fantanele", NOW(), NOW()),
            (19, "Urdari","Hotaroasa", NOW(), NOW()),
            (19, "Vagiulesti","Covrigi", NOW(), NOW()),
            (19, "Vagiulesti","Carciu", NOW(), NOW()),
            (19, "Vagiulesti","Murgilesti", NOW(), NOW()),
            (19, "Vagiulesti","Valea Motrului", NOW(), NOW()),
            (19, "Vladimir","Andreesti", NOW(), NOW()),
            (19, "Vladimir","Frasin", NOW(), NOW()),
            (19, "Vladimir","Valea Desului", NOW(), NOW())
        ;';
        DB::connection()->getPdo()->exec($sql);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $sql = 'DELETE FROM localities WHERE county_id=19;';
        DB::connection()->getPdo()->exec($sql);
    }
}
